### ISSUE TITLE
[Suggestion] Rank Slides in the Bertel's CO/XO bunks

### ISSUE THREAD

**Issue by Joe44445** [HaloSpaceStation/HaloSpaceStation13#1000]
I suggest we add Rank slides into the CO or XO's office on the Bertels.

they could be placed in their office, allowing for a safe place where no one could get to them without breaking in.

The rank slides would be mainly LCPL and CPL, with a few PFC ranks in there to help ease the gap between marines. The PFC and LCPL ranks would generally be useless however, and could probably be left out.

this would help out commanders in getting an actual chain of command set up, allowing for a seamless transition in command if the one PL leader goes down, leading to less panic and disorganization within the marine ranks.

considering SOME of the feedback I got about the canon event, it seemed to be a lack of leadership for a bit of it that led to the UNSC performing how it did, I hope this suggestion would help solve that problem and allow for an actual chain to be set up without big gaps in ranks (i.e from gunny to PVT)

**Comment by CdrRiley** [comment]
1+

**Comment by CdrRiley** [comment]
mappers please do it

**Comment by Max-023** [comment]
Dewit

**Comment by Nanu308** [comment]
So uh, Bertels gone, Close plze
