### ISSUE TITLE
[Suggestion] Buff the Anti-Material Sniper

### ISSUE THREAD

**Issue by Cynliax** [HaloSpaceStation/HaloSpaceStation13#1003]
The Anti-Material Sniper, currently most commonly employed by the URF Commandos, is absolute rubbish. It is meant to be the counterpart ( which implies it should be equal or at least close to the level the SRS has ) of the SRS. But at this point you're better off with a magnum.

One of the main issues is the finicky reload, now this isn't much of an issue as it is annoying to deal with.
The main issue is the penetration, it has essentially none at all compared to the SRS counterpart. It's an Anti-Material Sniper, it should bloody well act the part, but in the instances I've utilised it, it has done no damage to even marines when they are hit. 

The clearest buff would be to it's penetration, making it equal to the SRS penetration wise ( or higher ) which would be balanced out by the fact you have to take a good 2-3 seconds at fastest to load the thing with a round, since it can only take a single round, before firing again.

**Comment by caelaislinn** [comment]
#1023
