### ISSUE TITLE
STAIRS!!!!!!!

### ISSUE THREAD

**Issue by daPotato** [HaloSpaceStation/HaloSpaceStation13#1004]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

stairs dont work for like everything except the bertels

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by caelaislinn** [comment]
512 slightly changed the way the movement procs are handled, I believe this is the issue - not a mapping issue as we previously believed. I've been testing this today and I'm getting close to a fix. I'm aware how urgent the problem is but it's not an easy fix as I can see
