### ISSUE TITLE
Suggestion: Add Brutes to First Contact

### ISSUE THREAD

**Issue by mcalexev** [HaloSpaceStation/HaloSpaceStation13#1007]
Now we've got brutes in the new Doisac gamemode, I was hoping they might be added as jobs/a useable species on First Contact aboard the Covenant vessel. It'd only require new jobs/loadouts for said jobs and an additional barracks/brute armoury aboard the covenant ship.

**Comment by mcalexev** [comment]
An additional note. If stats are a concern, brutes could always be nerfed a bit to be onpar with elites, though without shields.

**Comment by ghost** [comment]
Yeah, I'd support getting brutes added to FC.

**Comment by Plaguewalker** [comment]
Make it happen. They can already be selected in the lobby all that'd be needed is a role addition and some edits to maps item spawn

**Comment by caelaislinn** [comment]
The current plan is to split FC into 3 separate versions - a sangheili corvette, a kigyar pirate ship and a brute raider. This will be done during the overmap arc

**Comment by PantasTheDank** [comment]
I know our voice doesn't matter in this but, Im pretty sure covenant players won't like being limited to 1 species because someone voted for it roundstart.

**Comment by caelaislinn** [comment]
Your voices absolutely do matter. But First Contact is a low pop gamemode and there's been a lot of power creep for all the factions already. There are also fairly strong lore concerns with having Sangheili and Brutes on the same ship. 

We don't have any immediate plans to add a gamemode like this, but it will be high on the dev priority list once population starts increasing.

**Comment by PantasTheDank** [comment]
Yep, the population thing is understandable,  I forgot the lore aspect about having brutes and elites on the same ship.
Thank you for your swift response. :)

**Comment by Stingray540** [comment]
Our current gamemode lineup has brutes implemented in our "main" gamemodes. Closing this.
