### ISSUE TITLE
Hunters are immortal

### ISSUE THREAD

**Issue by Nick123q23** [HaloSpaceStation/HaloSpaceStation13#1017]
#### Description of issue
Covenant Hunters / Mgalekgolo don't die.

#### Difference between expected and actual behavior

Hunters should be able to die when they reach 0% health.

Hunters do not die when they reach 0% health.

#### Steps to reproduce 

Find a hunter, shoot it until it hits 0% health. Notice that it is still running around shooting at you, most likely pissed off.

#### Specific information for locating
simple mob mgalekgolo

#### Length of time in which bug has been known to occur
Unknown, might have been since 512.

#### Client version, Server revision & Game ID
Client Version: 512
Server Revision: 3f5d9ce7936ddcbcf0728501e7b44588fbdffd4f - alpha - 2018-12-30
Game ID: bX7-a4Xs
Current map: Outer System #1445113

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by caelaislinn** [comment]
Had a quick look can't see the immediate issue. It will be due to the rewrite I did recently. I'll spend some more time on it over the next week

**Comment by caelaislinn** [comment]
What PR addressed this?

**Comment by BDpuffy420** [comment]
It think was one of your PRs, just I recently tested it and they are still immortal

**Comment by caelaislinn** [comment]
I introduced the bug with the hunter rewrite, this issue was made in response. I put up a fix but was waiting for player confirmation on live before closing... there were some reports the bug persisted

**Comment by X0-11** [comment]
#1157
