### ISSUE TITLE
ODST Helmet Internals 

### ISSUE THREAD

**Issue by Blackburn56** [HaloSpaceStation/HaloSpaceStation13#1020]
#### Description of issue
Myself and several other ODSTS have noticed whenever we switch on internals it does not feed any oxygen at all to our helmet. despite a message saying that our internals are indeed toggled. 

#### Difference between expected and actual behavior
unless this is working as intended I believe the helm should be able to feed oxygen to people, right now while the oxygen tank valve is open it does not link up to the helmet.  

#### Steps to reproduce 
1. Grab Oxygen Tank 
2. Grab ODST helm (unknown if its the same case for the commandos)
3. Toggle internals.

#### Specific information for locating

(sadly I do not have access to the specific message outputs at this time)
But the objects commonly used in my experience are 
all ODST Helm variants 
and the Double Emergency Oxygen Tank

#### Length of time in which bug has been known to occur
it has only been happening over the last week to two weeks I'm not too sure exactly when 

#### Client version, Server revision & Game ID

(currently do not have access to this at the moment) 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by caelaislinn** [comment]
I recall looking at this ages ago. Is this still happening?

**Comment by sleepyretard** [comment]
yeh it still happens

**Comment by BDpuffy420** [comment]
bump
