### ISSUE TITLE
Throat slit fix

### ISSUE THREAD

**Issue by frontline03** [HaloSpaceStation/HaloSpaceStation13#1024]
Throat slitting currently is a death sentence, even when using biofoam
-Allow throat slitting to be cured by biofoam so it allows people who have had their throat slit to be fixed.

**Comment by X0-11** [comment]
this isn't a fix, it's a suggestion. throat-slit is an artery destroyer, which biofoam doesn't fix

**Comment by caelaislinn** [comment]
If this gets added I'll make biofoam fix broken bones

**Comment by X0-11** [comment]
Biofoam should fix both broken bones and slit arteries now. (#1234 )
