### ISSUE TITLE
!!!!!!!!!!!!!!!!!!!STAIRS 2: RETURN OF THE STAIRS!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by Nick123q23** [HaloSpaceStation/HaloSpaceStation13#1025]
by the rings the fucking insurrectionist asteroid stairs are BROKEN again.

send help

**Comment by BDpuffy420** [comment]
not really broken, someone just needs to remove the extra wall under them

**Comment by X0-11** [comment]
#1042
