### ISSUE TITLE
Suggestion: Covenant Personnal Storage

### ISSUE THREAD

**Issue by Nick123q23** [HaloSpaceStation/HaloSpaceStation13#1029]
As it turns out, a covenant warrior's carrying capacity is extremely low. To counteract this, I propose adding storage equipment for covenant species to wear.

Something similar to webbing that can be attached to undersuits of every species, this should allow for carrying important battlefield loot, trophies, weapon ammunition, individual alien engineering tools, and medicine for non-sangheili.

Combat harnesses themselves should also have a tiny storage section like CM's marine armor. This might be able to hold two grenades, or more weapon ammo.

A toolbelt that could hold the full toolset of the covenant tools from packwar.

For actual transport of equipment and items, maybe a psuedo-backpack that instead of being worn, must be carried, but has plenty of storage space for virtually anything.

Some people have addressed concerns that adding storage of any kind to the covenant would be abused to be filled with plasma grenades. I think that much like vanilia ss13 medical belts being unable to hold security items, covenant webbing shouldn't accept plasma grenades.

**Comment by caelaislinn** [comment]
Packwar has a covenant toolbelt in the storeroom already. I've played with unggoy suits a bit so they have storage space now, and I'd like to add in a small back for gear storage to complement a utility or weapons belt. Don't even need sprites, can just reuse the human ones. 

Humans already have space to carry multiple grenades if they desire, I don't see why Covenant players shouldn't be able to accessorise into grenades if they want.

**Comment by X0-11** [comment]
The covenant have been provided with ammo belts, with a restriction on placing grenades within. The lowered capacity for covenant troops is a part of their tradeoffs.
