### ISSUE TITLE
Esword swap hands bug

### ISSUE THREAD

**Issue by ghost** [HaloSpaceStation/HaloSpaceStation13#1031]
#### Description of issue

When swapped to a different hand, an energy sword will explode if its safety is active.

#### Difference between expected and actual behavior

Energy swords should only explode when dropped if the fail safe is active

#### Steps to reproduce 

1.Pick up an energy sword with an enabled failsafe
2. Swap to a different hand
3. Click on the esword, swapping it to that hand
Result: Failsafe activates

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players (Haven't checked)
- [X ] Issue could be reproduced in multiple rounds
- [X ] Issue happened in a recent (less than 7 days ago) round
- [X ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by X0-11** [comment]
This is due to swapping hands technically "dropping" the item, and then picking it straight back up.

**Comment by BDpuffy420** [comment]
This was fixed by having the safety on at start.
