### ISSUE TITLE
Beamy Death

### ISSUE THREAD

**Issue by ghost** [HaloSpaceStation/HaloSpaceStation13#1036]
Give the glassing beam a separate "Combat" mode

in effect this would:
Allow the glassing beam to fire on ships, BUT
Not be able to target planets
Possibly require an amount of time to swap to, so that it can't be done immediately when surprised
Fire what amounts to a wider pulse laser, 4-ish tiles, instead of a massive lava-making destructive glass-forming 999 damage explosion
Give the covenant a MAC equivalent for space superiority

**Comment by X0-11** [comment]
#1037
