### ISSUE TITLE
Missing items from the medical ship.

### ISSUE THREAD

**Issue by Tasald** [HaloSpaceStation/HaloSpaceStation13#1057]
#### Description of issue
The medical Ship is missing bottles of surgery cleaner, bags, chemical cartridges for the machines, and food that's not the liquid emergency rations. 

Could also use some kinda airlock camera for the front entrance.

#### Length of time in which bug has been known to occur

Just found out about all this today.

#### Client version, Server revision & Game ID
Server Revision: 096c462ead2c5e9b8ac2a537a07907885ba8450c - alpha - 2019-01-14
Game ID: bYj-cVHR
Current map: Outer System #1445113

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by caelaislinn** [comment]
The map is getting disabled soon. It will still be in the repo but unused

**Comment by caelaislinn** [comment]
Medical ship removed about a hundred PRs ago
