### ISSUE TITLE
Covenant needs something like inflatable walls to stop air leaks

### ISSUE THREAD

**Issue by PantasTheDank** [HaloSpaceStation/HaloSpaceStation13#1062]
#### Difference between expected and actual behavior
The only way to get air back is to get metal and nano sheets from the already destroyed rooms, wall the room back and haul an air canister and release the air, but the pressure is still low

#### Steps to reproduce 
none

#### Specific information for locating

Could be a holo wall that only blocks air and atmos

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by caelaislinn** [comment]
Make a variant of the portable energy blockade that stops airflow. It would need a different sprite that fills the turf to make it obvious that it is blocking airflow. To balance it vs the ones used in combat, it should have less health.
