### ISSUE TITLE
Provide players with a way to disable spawns on captured vessels / bases

### ISSUE THREAD

**Issue by X0-11** [HaloSpaceStation/HaloSpaceStation13#1070]
Personally, I think a system similar to the ship-capture/claiming system of the game Pulsar : Lost Colony (http://www.pulsarthegame.com/captain/) would be a good inspiration, replacing their specialised capture-screens with a tool or other way to hack the APCs of a ship.

**Comment by Maxattacker** [comment]
Iirc, Star Trek 13 had a capture zone mechanic similar to what you are describing.

**Comment by caelaislinn** [comment]
My idea was a single indestructible console in a command area (bridge, CIC etc) which you flip (hack) then have to guard for 5-10 mins. 

Doing it the pulsar way could be cool but require a bit of finagling for different types of capture loations (colony, innie base, different faction ships). It would also require balancing for different amounts of server population.

**Comment by X0-11** [comment]
True, but that also makes it that a single console becomes the only thing you need to care about within the ship to ensure control. The pulsar method could be combined with yours, with the speed being influenced by the amount of apcs hacked, or downright disallowing it if a certain amount are unhacked.

**Comment by caelaislinn** [comment]
The Planetside 2 method worked like that. 1-5 control consoles at strategic points around the base, and once you had >half the capture timer would start ticking down, doing at a faster rate with more consoles flipped. 

In PS2 low pop fights, having multiple consoles to flip makes most of them impossible to defend, resulting in a game of cat and mouse between the points. 

I want to avoid making it too immersion breaking though... the capture consoles should make sense from an in world perspective.

**Comment by X0-11** [comment]
In this case however, we would have a central point you could disable to ensure any of the progress they've made is null. This would make a defense need to spread out across the entire ship.

On the immersion front:
Well, a ship would need some way of transferring command over to different people.

**Comment by caelaislinn** [comment]
#1354 and #1343 

For now, capturable ships and bases isn't on the roadmap. It may be for a future gamemode though
