### ISSUE TITLE
Implement slipspace traversal devices for faster ship travel

### ISSUE THREAD

**Issue by X0-11** [HaloSpaceStation/HaloSpaceStation13#1074]
A slipspace device could create an ovefmap-portal-object with a short lifespan, allowing ships to travel long distances but also be followed by other vessels.

**Comment by caelaislinn** [comment]
I would like to add in system slipspace jumps for the Covenant ship at some point, but I don't know if we will ever have a gamemode with multiple star systems to jump between

**Comment by X0-11** [comment]
James mentioned a want to expand the overmap to it's maximum, using slipspace to traverse said larger map.

**Comment by ghost** [comment]
In system jumps could be reflected by human ships having a higher minimum range of travel, and/or a degree of RNG to where they actually end up travelling to.

**Comment by BDpuffy420** [comment]
Has been added
