### ISSUE TITLE
Covenant Ship's consoles are fucked.

### ISSUE THREAD

**Issue by AccointNaim** [HaloSpaceStation/HaloSpaceStation13#1081]
#### Description of issue
Consoles are fucked, can't view space or the consoles, Engine Control Console is not connected to ship, gun consoles give you the gun but you can't view spess. Helm and navigation ones don't show up.

#### Difference between expected and actual behavior
The consoles work, the consoles DONT work.

#### Steps to reproduce 
I don't know, just happened when the game started.

#### Specific information for locating

I, guess the helm consoles and stuff.

#### Length of time in which bug has been known to occur

Probably the duration of the server.

#### Client version, Server revision & Game ID

512, e04a6fb919399d2927e0938ada6e37c2e25c72d8 - alpha - 2019-01-19, bYo-bYTV

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [?] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [  ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by X0-11** [comment]
#1085
