### ISSUE TITLE
Fix the recurring lag issue stemming from constantly-crashing machinery process

### ISSUE THREAD

**Issue by X0-11** [HaloSpaceStation/HaloSpaceStation13#1087]
The machinery process seems to constantly crash and restart, acting as a constant source of lag.

**Comment by BDpuffy420** [comment]
test

**Comment by BDpuffy420** [comment]
test2

**Comment by caelaislinn** [comment]
This is potentially fixed by #1581 and the various zlevels that have been removed recently, but I want to leave it open for a while in case it recurs

**Comment by caelaislinn** [comment]
I added unit test logging for process controller hangs in #1656 and I optimised turf process controller startup in #1676 

It's been a fortnight and I haven't seen any process controller hangs/had any reported to me

**Comment by bloxgate** [comment]
I've had a few reports of occasional turf hangs during testing of a couple recent pull requests, though I don't know how merged the heads of those PRs were.

**Comment by caelaislinn** [comment]
Added process controller stat data to hangs debug logging in #1707

**Comment by caelaislinn** [comment]
This is probably still recurring, but we'll wait to see another instance of it before opening it
