### ISSUE TITLE
Dual Wielding Penalty 

### ISSUE THREAD

**Issue by Wehraboo** [HaloSpaceStation/HaloSpaceStation13#1096]
Apparently dual wielding in its current form has no penalty at all, which means you basically get twice the firepower without any kind of downside. 

Something on the lines of whacking accuracy down a notch or two would be great.

**Comment by X0-11** [comment]
Due to dual wielding being limited to a few species, the extra firepower provided is intended. The synergy dual wielding held with aim-mode has been identified and #1097 's resolution will also effect this. Re-open if this continues to be an issue.
