### ISSUE TITLE
Pelican health bar please and repair

### ISSUE THREAD

**Issue by CdrRiley** [HaloSpaceStation/HaloSpaceStation13#1112]
<!-- it would be nice to add a health bar to the pelican to see how many bullets you can suck up befroe having to fly way, and it would be nice to have a way to repair pelicans.

**Comment by daPotato** [comment]
Thank you for the wonderful description.

I feel like a good way to do health would be through sprite states of damage to the pelican, such as torn panels and jazz like.

**Comment by X0-11** [comment]
This could be accomplished by making vehicle-examines show a vague level of damage.
