### ISSUE TITLE
Add Gravity Thrones

### ISSUE THREAD

**Issue by ghost** [HaloSpaceStation/HaloSpaceStation13#1115]
Add gravity thrones for prophets

A gravity throne would, I believe:
Negate the Prophet's natural movement debuff 

Have an energy shield (?)

Have integrated weapons for self defense

**Comment by Stingray540** [comment]
If this can't get mounted by Spartans in order to give crisp punches to the face I don't see the point.

**Comment by caelaislinn** [comment]
We wanted this back in covenant arc but didn't get the sprites. Need someone to sprite it

**Comment by BDpuffy420** [comment]
We have sprites and this issue is almost done

**Comment by Stingray540** [comment]
These are implemented, though sadly no ability for spartans to hijack beat them to death.
