### ISSUE TITLE
Colony NPC's chill as you shoot/stab them

### ISSUE THREAD

**Issue by PantasTheDank** [HaloSpaceStation/HaloSpaceStation13#1120]
#### Description of issue
Colonist NPC don't react to harm in any way

#### Difference between expected and actual behavior
They should atleast atempt to run away from the danger and yell for help 

#### Steps to reproduce 

Be on colony, harm npc

#### Length of time in which bug has been known to occur
4ever

**Comment by caelaislinn** [comment]
#1780
