### ISSUE TITLE
Add a Hard-Sound Rifle as a URFC sniper

### ISSUE THREAD

**Issue by Cynliax** [HaloSpaceStation/HaloSpaceStation13#1122]
The Hard-Sound Rifle is a weapon typically used to assassinate enemies by ONI Operatives, it uses sound waves instead of a conventional bullet to kill and fucks people up by cerebral haemorrhage, which can translate in game as organ damage.

Obviously, it wouldn't be an instant kill as that would be unfair, however could do medium organ damage or major organ damage to completely unarmoured people (which the sound waves won't be lessened by solid armour).

URFC will only come equipped with one and since URFC have very little advantages, I'd say it'd be fair. 

It would work like a covvie weapon that would recharge, but it would only have one shot available and the recharge time is ten seconds (or more if too powerful), it would be wielded and have no tracer, except maybe a very light/transparent blue beam signifying the sound waves.

**Comment by Darkking1234** [comment]
Possibly some kind of radiation like effect. The longer it affects you the more it damages you. Organ damage kills somebody REALLY quickly and just straight out major organ would kill somebody in a few seconds

**Comment by Cynliax** [comment]
^ Agreed, maybe a fat amount of radiation damage or light damage to the lungs so you cough blood and shit, maybe black out but not enough to kill you outright or in seconds.

Or maybe make it cause Internal Bleeding as its primary or secondary effect.

**Comment by Wehraboo** [comment]
Yes, lets give the Innies top of the line ONI weapons because it makes perfect sense for them to get their hands on it for some strange reason. Considering this weapon has only ever been used once in lore, and that was only for promotional material - You can make the assumption that this piece of equipment is very much rare. 

Giving the Commandos something is okay, but not an ONI exclusive assassination tool.

**Comment by Cynliax** [comment]
There have been plenty of ONI defectors in the past, including researchers which can be assumed they know how to produce such a weapon or operatives that have utilised this weapon. Sure it'd be incredibly rare, and like I said there's only one rifle in the entire arsenal for URFC. 
And also consider that if the person wielding the weapon dies, its now in the hands of whoever killed them.

**Comment by Cynliax** [comment]
General agreement is that it won't be the Hard-Sound Rifle, but rather a variant of it developed by URF Researchers or something yada yada lore monkeying.

It will cause incredibly high halloss (for those who don't know, pure and utter pain) which can run the risk of a heart attack as you do when in insanity levels of pain, but isn't common, it will also deafen the target for a while since its a literally sound wave beam. 
Also, some ideas that it could possible blur the screen or inhibit vision (like when you have low blood and your screen goes white).

**Comment by daPotato** [comment]
could do screen shake like when you are drunk, but there is a bug with that screen shake that makes scopes unusable until it stops, ill make an issue about that later

**Comment by BDpuffy420** [comment]
#1126
