### ISSUE TITLE
Biofoam doesn't heal IB

### ISSUE THREAD

**Issue by Wehraboo** [HaloSpaceStation/HaloSpaceStation13#1125]
Pretty much the title.

**Comment by Cynliax** [comment]
That would make biofoam hella op, it already permanently heals organ damage fully.

**Comment by daPotato** [comment]
XO stated it is actually supposed to heal IB already

**Comment by Cynliax** [comment]
Biofoam really needs balancing though, if this goes through then it'll heal pretty much everything besides shrapnel, which duplicates for some reason.

**Comment by daPotato** [comment]
doesnt fix arterial bleeding, full bone breaks (to my knowledge), which are your biggest fuckovers already

**Comment by Cynliax** [comment]
It slows down artery bleeds iirc and full bone breaks are obvious, can't repair broken bones with just foam.

**Comment by daPotato** [comment]
As far as I know, arterial bleeding isn't affected by foam, I'll double check later though.

Biofoam is still extremely weak compared to the _**UNLIMITED POWER**_ of Bicaridine and whatever-the-fuck-its-called burn stuff chemical.

**Comment by Cynliax** [comment]
Dermaline.

also yea because bicardine is hella annoying to make init?

**Comment by daPotato** [comment]
Both are really easy to make, Dermaline just takes two steps.

**Comment by CdrRiley** [comment]
theres no IB only AB.
