### ISSUE TITLE
DMR ammunition can be loaded into MA5B ammo mags

### ISSUE THREAD

**Issue by X0-11** [HaloSpaceStation/HaloSpaceStation13#1134]
DMR ammo is statistically better than MA5B ammo, making this ability to load the ammo into different magazines a balance issue.

**Comment by Max-023** [comment]
But the MA5B is good with the DMR rounds.

**Comment by BDpuffy420** [comment]
But not intended

**Comment by Max-023** [comment]
But it literally makes the weapon better. Only the NPCs can make the AR good right now.

**Comment by X0-11** [comment]
This is a bug report not a discussion post, please only post if you have information pertaining to the bug or the replication of the bug.
