### ISSUE TITLE
Jamming Pack for URFC/URF

### ISSUE THREAD

**Issue by Cynliax** [HaloSpaceStation/HaloSpaceStation13#1138]
In essence, this will be a radio jammer that can fit on the back slot, in place of a secondary weapon or backpack.
As the name implies, it is a device that will block all communications within a radius of 20-30 tiles around the user, preventing anyone for hearing or speaking on their radios. This can be activated and deactivated whenever the operator needs to from the top left abilities thingy.

I believe this will fit the URFC and URF as they use hit and run tactics as well as more sneaky beaky shit, this will allow more room for stealth operations by easily taking out targets by activiating the jammer and eliminating them since they won't be able to alert. 

There is a downside, however, once activated not even the user or his allies will be able to use their radio and will have to wait until the operator deactivates the jammer or they get out of range from it.

**Comment by daPotato** [comment]
Only stays on for X amount of time before needing time to recharge?

X could be a minute to a minute and a half, recharge time would be X/2?

**Comment by Cynliax** [comment]
Yea, sounds good.

also smh this isn't maths class you can just say minute and a half and then 45 second recharge

**Comment by BDpuffy420** [comment]
Could possibly re-work the comm bags for this

**Comment by Cynliax** [comment]
Mental, whatever it takes for sweet, sweet Vigil/Mute gameplay.

**Comment by BDpuffy420** [comment]
@X0-11  the comm jammer should still be in the code right?

**Comment by BDpuffy420** [comment]
We added comm jammers  for all 3 factions
