### ISSUE TITLE
SDSR has no effect on armoured targets.

### ISSUE THREAD

**Issue by Cynliax** [HaloSpaceStation/HaloSpaceStation13#1142]
The SDSR, the Sound Rifle URFC has, currently has no effect on any targets wearing armour at all.

The intended effect is that it should bypass all armour ( not shields ) and provide a 2 second weaken, massive surpression effect and then a confused effect for a few seconds after, similar to when you are heavily drunk. 

The above effects do NOT work at all against armoured targets, but rather is deflected by the plating of armour, it seems to damage the plating but is absorbed fully by it, which is not what should happen.

**Comment by Cynliax** [comment]
^^ Continuing above, after testing on unarmoured targets the following effects are:
- It has the confusion effect for a few seconds.
and literally nothing else, which I assume is an issue, as it's suppose to have a surpression and weaken effect on top of that.

**Comment by X0-11** [comment]
#1151
