### ISSUE TITLE
Glassing beam is bugged,hits the covenant ship.

### ISSUE THREAD

**Issue by PantasTheDank** [HaloSpaceStation/HaloSpaceStation13#1143]
#### Description of issue

The glass hits the covenant ship even when its taken away from the planet,and each shot is fired 10 seconds after the last.

#### Difference between expected and actual behavior
It shouldn't blow the covenant ship like that.

#### Steps to reproduce 

Not sure,depends it seems

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x ] Issue could be reproduced at least once
- [x ] Issue could be reproduced by different players
- [x ] Issue could be reproduced in multiple rounds
- [ x] Issue happened in a recent (less than 7 days ago) round
- [ x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by BDpuffy420** [comment]
#1144
