### ISSUE TITLE
UNSC and URFS ship weapons buff (Mostly the MAC)(Mainly the MAC)

### ISSUE THREAD

**Issue by Chambers0** [HaloSpaceStation/HaloSpaceStation13#1145]
I believe that the ship weapon's damage used by UNSC and URFS needs a buff. (Unless it goes against lore)

This is my idea:
Gun Deck:
Ship Hull (For all factions)- Decent to low damage (But softens the hull's armor up)
Covenant ship's shield- Low to almost no damage (But reduces to putting the shield's recharge rate at a complete halt due to putting the shield under constant fire)

Missile Deck:
Ship Hull (For all factions)- Good to very good damage
Covenant ship's shield- Decent to good damage

MAC:
Ship Hull (For all factions)-RIPS right through them 
Covenant ship's shield- Takes away 1/3 to 2/3 of the ship's shield overall, in one shot

(Extra)
I also believe that the recharge rate of the MAC "PROBABLY" needs a speed buff

**Comment by Cynliax** [comment]
give thorn and avarice cloaked (like SDV) anti ship mines

**Comment by X0-11** [comment]
These suggestions for each weapon's role is exactly the case right now. MAC shots from the Bertels deplete essentially a third of the covenant ship's shields per shot.

**Comment by X0-11** [comment]
MAC rounds now scale more aggressively by number of capacitors, with the HA's MAC being able to one-shot the corvette's shields.

**Comment by caelaislinn** [comment]
Capacitors aren't buildable. I'm wondering if they should be so ship engineers can upgrade their MAC (with expensive supplies from researchers maybe?)
