### ISSUE TITLE
Open Mapping Request: Various Spaceships

### ISSUE THREAD

**Issue by X0-11** [HaloSpaceStation/HaloSpaceStation13#1155]
The NPC ship maps currently used for NPC ships are outdated and placeholder maps derived from player-ship-maps. NPC ships would ideally have a different overall structure than player ships due to their need to have the umbilicals fully secured and guarded by NPC guards.

New maps are needed for the Insurrectionist combat ship, UNSC combat ship, civilian cargo ship and general civilian ship.

A covenant combat NPC ship is also required.

These maps shouldn't contain too much general clutter due to the extra strain more items place on the ship-loading system.

**Comment by caelaislinn** [comment]
We can probably reuse the existing ship maps. I think they're ok. I'd rather we think up ways to have NPC ships not be boardable so we dont have to task entire zlevels over to them though

**Comment by caelaislinn** [comment]
NPC ships are disabled for now for performance reasons, but if we decide to bring them back there are a few we could use
