### ISSUE TITLE
Suppressor Sound Climbs

### ISSUE THREAD

**Issue by Desolane** [HaloSpaceStation/HaloSpaceStation13#1168]
#### Description of issue

Attaching a suppressor to an MA5B and firing nonstop will cause the sound to climb in level

#### Difference between expected and actual behavior

sound should stay stagnant or at least alternate in levels below normal firing sound

#### Steps to reproduce 

attach suppressor to MA5B and just keep clicking

#### Length of time in which bug has been known to occur

Just found it in testing locally.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 9a7fcce72841e5b7cacfac2d59735271c88d5ba8 - unsc-achlys - 
Game ID: bYx-cS7L

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by X0-11** [comment]
This will be due to the "vary" argument of the playsound() proc being set to 1
