### ISSUE TITLE
Plug the glasser hole

### ISSUE THREAD

**Issue by ghost** [HaloSpaceStation/HaloSpaceStation13#1171]
Fill the empty floor tile on the energy projector chamber, as it is very easy to break the glass and cause a potentially unrepairable (No huragoks) breach that eventually sucks all ait out of the Covenant corvette.

**Comment by BDpuffy420** [comment]
>cover hole
>glass ship



Is that what you want?

**Comment by ghost** [comment]
I don't think a floor tile actually means glassing the ship codewise, but if it's there for fluff, it needs to have something stronger than a one pane thick glass box preventing a breach.

**Comment by X0-11** [comment]
#1173 has added proj-resist windows, the same windows used near the umbilicals.
