### ISSUE TITLE
Add admin fax departments

### ISSUE THREAD

**Issue by Nick123q23** [HaloSpaceStation/HaloSpaceStation13#1174]
Like centcomm, the only admin fax departments available are for the UNSC. This leads to the covenant and URF sending faxes to the UNSC and pretending that they didn't just ask their enemy for permission to glass a colony.

Try Ministries for the covenant, such as Ministry of Resolution for general war command, Ministry of Tranquility for small artifacts, Ministry of Fervant Intercession for zealot matters and important relics, and so on.

Insurrectionists could have URF HIGHCOM and whatever commandos are supposed to be now.

**Comment by BDpuffy420** [comment]
#1584
