### ISSUE TITLE
[Suggestion] - Mission com links 

### ISSUE THREAD

**Issue by goodfun13** [HaloSpaceStation/HaloSpaceStation13#1185]
a place where you could go to use a com terminal to pick up jobs 
like a set list of random jobs e.g (hitman jobs, take a ship, find something, or steal something)

which will then spawn in a ship NPC or player Ship, an NPC player you got to kill or a hit on a person being civ, a UNSC member or a URF member

this could work for all factions as well as Civs

**Comment by Cynliax** [comment]
I think this would be best for mercs/pirates (URFC) as this is, in essence, what a mercenary is and hits and theft fits especially well with the theme of the URFC after its reformation.
Ideas for jobs could be:
NPC:
- Destroy X NPC Ship
- Steal X valuable object
- Destroy X target
- Kill X NPC
- Hijack X Ship and take to Y Coordinates

Player:
- Kill X Player
- Destroy X Structure/Object
- Steal X Object
- Kidnap X Player and take to Y Location.

Just a few I thought up on the spot.

**Comment by goodfun13** [comment]
that's pretty much the Idea really but what I mean for another faction. they could have a whole new set of jobs, which when one job is done they get a point which can go to
 (support, troops, guns or more NPC ships )

but i see the UNSC jobs being more protector kinda missons e.g
- protect a UNSC cargo ship
- protect a person X and get them to Y
- get more support from local areas
- hold place for X and then move to Y and hold for set time while waves of NPCs attack
- grab intel on a local URF cell in the area 
- man hunt
- find the URF troop thats working undercover

**Comment by caelaislinn** [comment]
#1486

**Comment by BDpuffy420** [comment]
#1783
