### ISSUE TITLE
Make orion organ implantation create orion species

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#1195]
Admins have been doing this ingame already for over a year, so we may as well make it happen in code.

**Comment by Stingray540** [comment]
I'd honestly disagree with this, as one of the people who regularly changes the species in ahelps. The other dicerolling aspect adds some fun to it, and if it were automated we may get issues popping up where jobs that wouldn't have the knowledge (ie civvies or basic marines) end up making Orions where they shouldn't. Just my thoughts.

**Comment by Aroliacue** [comment]
Added
