### ISSUE TITLE
T'vaoan buff?

### ISSUE THREAD

**Issue by mrturkeytoe** [HaloSpaceStation/HaloSpaceStation13#1202]
Balance suggestion.
Right now T'vaoan Kig-yar are a strict downgrade from Ruutian ones, they trade even more health reduction and farsight for a speed increase which is lost when they're even slightly wounded.

I suggest their durability be changed to be inline with regular kig-yar or greater.

**Comment by ghost** [comment]
They already have better durability. 100 health compared to 75.

Unless you mean you want to give them Ruutian shields, which coupled with their higher mobility and health would be a bit much.

**Comment by mrturkeytoe** [comment]
I don't mean the gauntlet shields, wouldn't be lore appropriate.

I didn't think they had more health than Ruutians. I thought they had less. Is their armor just really bad or something? Because they feel super super squishy.

**Comment by ghost** [comment]
No, it's that Ruutians have wrist gauntlet shields that have more health than any other shield below ship shields. Ever flank a ruutian successfully and you'll learn they go down like a sack of potatoes when slapped by a high speed bullet.

**Comment by mrturkeytoe** [comment]
Hm, I guess guns on here just do a fuckton of damage huh?

I suppose some of it is that due to the 2D nature of SS13 and that as of now most of the fighting happens in enclosed two tile wide corridors so the speed doesn't feel like a good trade.
How does their armor match up to others? And Would them getting a bit more speed be an option? Or maybe some time in the future be able to jump up/fall down multi-z holes in ceilings/floors without getting hurt?

**Comment by mrturkeytoe** [comment]
Looking at the code the ruutian and t'vaoan both 150 total health and both have a 1.1 brute mod? The only difference is the speed and t'vaoans have a .9 pain mod?

**Comment by X0-11** [comment]
A T'voan's upside is their speed. If they fail to use it correctly and get shot, they lose their upside.

**Comment by mrturkeytoe** [comment]
I mean. I wont argue and you're one of the ones in charge of how stuff goes, it just seems like to me, it's two negatives (durability of the shield gauntlet & focus sight) in exchange for one positive.

**Comment by X0-11** [comment]
An increase in their pain resist may help with them losing their speed advantage.

**Comment by mrturkeytoe** [comment]
That works, it would make it a lot less situational. Six of one, half dozen of the other type of deal with adding pain resist vs health, for short term sustainability at least.

**Comment by BDpuffy420** [comment]
#1516
