### ISSUE TITLE
Suggestion- Make ODSTs a little bit faster

### ISSUE THREAD

**Issue by PantasTheDank** [HaloSpaceStation/HaloSpaceStation13#1205]
ODSTs are slightly slower from their Marine counterpart, be it from their armor or magboots,I have not checked.
The main issue is that the ODSTs can't keep up with their targets,meaning elites can fall back and recharge their shields,or innies can go back and pop a biofoam and wait a bit to heal before heading back.
Just slightly lower the speed penality.

**Comment by X0-11** [comment]
This is likely due to active magboots. Inactive magboots shouldn't have this issue.
The speed of elites has been nerfed recently, which should assist in this.

**Comment by flinntowin** [comment]
It could also be due to multiple weapons, as having more then one gun can sometimes have an effect on speed, at least, it feels like it. It could also be due to backpack weight.

**Comment by PantasTheDank** [comment]
Agreed, the elite speed nerf was a good alternative to this
