### ISSUE TITLE
Beam Rifle PB

### ISSUE THREAD

**Issue by mrturkeytoe** [HaloSpaceStation/HaloSpaceStation13#1209]
#### Description of issue
It doesn't work for some reason.

#### Difference between expected and actual behavior
I expected the gun to fire at pointblank range but it don't

#### Steps to reproduce 
Get beam rifle, walk up to someone, set intent to harm, click.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Max-023** [comment]
The SAW also has this issue, except it isn't just point blank range. It sometimes just won't fire.

**Comment by caelaislinn** [comment]
This is likely a bug, but also beam rifle and SAW are both mid-long range weapons.
