### ISSUE TITLE
Covenant ship fluff suggestions

### ISSUE THREAD

**Issue by mrturkeytoe** [HaloSpaceStation/HaloSpaceStation13#1222]
Atmos piping.

Floor tiles.

Proper/more proper than it is now power generation.

Canteen?

Fluffing up the quarters a bit with 'purple' beds, maybe some fluffing mapping to them as well.

Give the armories a more official feel with how they're mapped, fluffed sprites for the weapon containers, maybe use 'purple' vending machines.

Make the medical room less of a maint chop shop by purplizing things and partitioning the pharmacy related stuff away from the operating tables, maybe add purpled surgical curtains.

Fluff the brig cells to have force field doors akin to the cells seen in Halo 2.

A bio printer in the medical section with a purple freezer of meat or something to ensure it's supplied to replace destroyed limbs/organs wouldn't go amiss either. Either on the corvette or on the station if one isn't present already.

Some liquid phoron or phoron sheets and a grinding machine.

Purplized Defibrillator.

**Comment by Maxattacker** [comment]
Just going to say right now, Atmos piping on ships is not a good idea.

**Comment by mrturkeytoe** [comment]
:eyes: 

It takes the strongest wills to make the largest sacrifices. Joking aside though some of the SS13 fun is suffering from atmos.

**Comment by BDpuffy420** [comment]
#1953  address most of this
