### ISSUE TITLE
Add permenant ship-destruction

### ISSUE THREAD

**Issue by X0-11** [HaloSpaceStation/HaloSpaceStation13#1223]
Original recollection of discussion on this feature:

"It involved some sort of invisible markers for "hull"
and would, on a process tick, ascertain the percentage of ship that was "damaged"
providing a warning to the crew to GTFO if it was too low"

**Comment by caelaislinn** [comment]
This is more of a feature than a bug. Now that we've redone the spawns we need to think about what players do once their ship is destroyed... the ship is the main form of player agency
