### ISSUE TITLE
ONI Security paradoxially spawn on the Covenant faction base instead of VT9

### ISSUE THREAD

**Issue by Nick123q23** [HaloSpaceStation/HaloSpaceStation13#1229]
#### Description of issue
ONI security spawn on the Covenant Faction base rather than VT9 where they normally spawn.

#### Difference between expected and actual behavior

See above

#### Steps to reproduce 

Join the game as an ONI security agent, find out that you're not in kansas anymore.

#### Specific information for locating
None.

#### Length of time in which bug has been known to occur
A few days ago at the least, probably since the base updates.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 98800b40304074d233040535f9b8d3014adfc0ff - alpha - 2019-02-03
Game ID: bYE-ckTA
Current map: 111 Tauri System, Human Colony "Elmsville"

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by X0-11** [comment]
#1232
