### ISSUE TITLE
Lesser Charity port-side umbilical behind wall when extended

### ISSUE THREAD

**Issue by ParadoxialVox** [HaloSpaceStation/HaloSpaceStation13#1230]
#### Description of issue

The port-side umbilical vanishes behind a wall of the station when extended. That is the left side of the station to anyone unsure. While it doesn't seem to cause any issues with boarding it, the other side does not reproduce this glitch from what I have seen.

#### Difference between expected and actual behavior

The umbilical vanishes beneath a wall, when it should be on the top layer, I do believe.

#### Steps to reproduce 

Just extend the left side umbilical to a ship

#### Length of time in which bug has been known to occur

I am more than sure it's been an issue since the base was first implimented, but I am certain.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 98800b40304074d233040535f9b8d3014adfc0ff - alpha - 2019-02-03
Game ID: bYE-ckTA
Current map: 111 Tauri System, Human Colony "Elmsville"

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this
![screenshot 2019-02-04 10 34 41](https://user-images.githubusercontent.com/47331155/52226199-ef236300-2871-11e9-8475-508356bba141.png)

**Comment by caelaislinn** [comment]
Can I get confirmation this is a visual bug and the umbilical is still accessible when it occurs?

**Comment by X0-11** [comment]
It's purely visual

**Comment by caelaislinn** [comment]
Covenant base removed #1646
