### ISSUE TITLE
Implement Halo's style of Neural Lace for use as an ID card

### ISSUE THREAD

**Issue by X0-11** [HaloSpaceStation/HaloSpaceStation13#1233]
UNSC personnel are stated to have neural laces. These could be used as replacements for ID cards.
Ship captains have neural laces specialised for ship command. This would assumedly report things like ship and subsystem status, as well as allowing an onboard ship AI to send data directly to the neural lace.

**Comment by X0-11** [comment]
As an addition to this, Neural Laces could act as an inbuild FoF ID, allowing the rule of disallowing the wearing of other faction armour to be removed.

**Comment by BDpuffy420** [comment]
bumping

**Comment by Nick123q23** [comment]
spartans actually have enhanced neural laces that do more stuff and can hold AIs

not sure if this would ever solve their lack of access problems though

**Comment by BDpuffy420** [comment]
#1857
