### ISSUE TITLE
Suggestion: Adjust the Mounted HMG stats.

### ISSUE THREAD

**Issue by RenGusta** [HaloSpaceStation/HaloSpaceStation13#1241]
#### Description of issue
The HMG sprays everywhere and is super inaccurate, if hard hitting. I feel like it should be a more effective and accurate suppression tool.
It also fires slowly.
It should fire faster.

Also nerf damage if you make it more accurate.

#### Difference between expected and actual behavior

It fires in a giant god-damn arc instead of where you try and aim.

#### Steps to reproduce 

Shoot the HMG at all.
Be disappointed at how it fires in a giant inaccurate arc.

**Comment by PantasTheDank** [comment]
I dunno, I feel like it SHOULD be innacure and fire in an arc because that means its covering a lot of ground meaning less space for your target.
As of now its great at supressing, not strait up assassinations.

**Comment by RenGusta** [comment]
I maintain the position that it should be an effective -directed supression- tool, not a low chance de-handing on the off chance it hits you twice.

besides, spoke to XO-11 about it with the intent of him handling it eventually. So, the end result is up to him.
