### ISSUE TITLE
Suggestion: Add Navy Ranks to ODST.

### ISSUE THREAD

**Issue by RenGusta** [HaloSpaceStation/HaloSpaceStation13#1242]
#### Description of issue
ODST don't have naval ranks other than Petty Officer Third Class.
This isn't fun for the ODST who don't just want to be Marines. Also allows for some more navy jokes.

#### Difference between expected and actual behavior
Expected: Ranks.
Reality: No Ranks.

#### Steps to reproduce 
Setup Character.
Be disappointed that you can't be a Chief Petty Officer or even just a normal Petty Officer First Class.
Try not to cry.
Cry a lot.

#### Specific information for locating
Probably job code.

**Comment by Max-023** [comment]
Since ODSTs now no longer use Navy ranks, mind if you close this?

**Comment by RenGusta** [comment]
It's like 9 months out of date, you don't gotta ask, lmao.
