### ISSUE TITLE
Huragok immediately die when going through ship umbilicals.

### ISSUE THREAD

**Issue by Elzenio** [HaloSpaceStation/HaloSpaceStation13#1253]
#### Description of issue
As the title says, Huragoks (Engineers) instantly gib into a mess of drone wires when transferring through ship umbilicals. However, this does not happen when going up or down normal stairs.

#### Difference between expected and actual behavior
Expected Behavior: Being able to go through umbilicals without the fear of dying from an unseen force.

Actual Behavior: Immediately being gibbed into wires when transferring through ship umbilicals.

#### Steps to reproduce 
1: Spawn as Huragok.
2: Go to a ship umbilical- any of them.
3: Attempt transferring through umbilical.
4: Watch as- when you finish transferring to the other side- you are auto-ghosted while your body is turned into a fray of drone wires.

#### Specific information for locating

Ship umbilicals.

#### Length of time in which bug has been known to occur

Ever since the Huragok code has been implemented.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [✓] Issue could be reproduced at least once
- [✓] Issue could be reproduced by different players
- [✓] Issue could be reproduced in multiple rounds
- [✓] Issue happened in a recent (less than 7 days ago) round
- [✓] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by PantasTheDank** [comment]
I think thats a legit feature, to prevent them from escaping the shit or something.

**Comment by Elzenio** [comment]
Devs have said that it's only occurring due to the original maintenance drone code that the Huragoks use- plus, Huragok are planned to be used as medical responders and essentially seemingly outfitted as FOB builders (as conversations both in and out of the embassy have suggested). It isn't an intended feature.

**Comment by X0-11** [comment]
It's literally just due to them being resprited maint drones, yes.
This issue should be closed when they are recoded.

**Comment by caelaislinn** [comment]
This is technically a bug, but it also qualifies as an unintended feature as it fits with the lore (explosive harnesses on huragok when they attempt to escape or betray the Covenant).
