### ISSUE TITLE
Covenant language bug 

### ISSUE THREAD

**Issue by BDpuffy420** [HaloSpaceStation/HaloSpaceStation13#1262]
Cael added a feature which made the elite language more hard to understand for non-covenant races by showing alien text like this 

![](https://i.gyazo.com/5acfa5f63a90629ddd1838bed1d83592.png)

But it’s currently showing null text like “.” Or “ ”

**Comment by caelaislinn** [comment]
Leave this open as a feature request for now.

**Comment by BDpuffy420** [comment]
.

**Comment by BDpuffy420** [comment]
rebump

**Comment by Aroliacue** [comment]
Stale, closing
