### ISSUE TITLE
Muzzle Flash

### ISSUE THREAD

**Issue by ghost** [HaloSpaceStation/HaloSpaceStation13#1264]
Firing a gun should light up darkness, for thematic purposes (And tinted for some weapons, like plasma if possible). It'd also give some opportunity to fight back if you're getting shot at from a dark area or are fighting enemies with night vision.

**Comment by caelaislinn** [comment]
This will add a lot of extra load to via lighting calculation updates. There is a similar performance issue with fast moving lights eg on vehicles. 

It's possible to do and I won't reject it if anyone does it. Just feel uncomfortable with the idea
