### ISSUE TITLE
Change Glassing

### ISSUE THREAD

**Issue by ghost** [HaloSpaceStation/HaloSpaceStation13#1271]
Make glassing a planet into a timed process, requiring ~three to six minutes to complete, and send out a systemwide message of "A large energy signature has been detected near -targeted planet-"

This means there's a window of opportunity to prevent a planet's glassing and it's known that it's going on, as glassing can currently be done instantly with no risk to the Covenant once artifacts are recovered from the planet.

However, with the timed glassing, it should also glass the entire surface Z-level, rather than only a portion that current glassing does. This means that anyone on the surface will die, and any stairs leading underground will be destroyed by the glassing, making it a real destruction to a planet rather than a, in the grand scheme of things, relatively minor inconvenience to the survivors.

**Comment by daPotato** [comment]
Instead of energy signatures, have it scream about fluctuating radiation levels as seen in Reach.

**Comment by caelaislinn** [comment]
This is intended as a Covenant objective for the FC gamemode overhaul. Although in the lore it was implied that people could survive in bunkers underground, it's easier if we just make the planet inaccessible and kill off everything on it.

**Comment by caelaislinn** [comment]
I was debating whether glassing should utterly destroy the planet making it inaccessible and killing any players in there... but then I realised it's more fun to transform the entire zlevel in lava and allowing dropships or fighters to skim over the ruined landscape searching for survivors

**Comment by X0-11** [comment]
How would you decide which tiles become lava and which tiles don't? Currently lava is immediately deadly and the surface becoming lava would just instantly everyone anyway.

**Comment by caelaislinn** [comment]
All outside turfs on the "ground" zlevel. Skip caves and impassable rock. The way to do it would just have a process tick slowly changing all the viable turfs to lava in a chain.

**Comment by ghost** [comment]
Bump, still an issue. Eight energy projector shots in a recent round resulted in a relatively small glassed area on KS7 that was more of a minor inconvenience than anything else.

**Comment by BDpuffy420** [comment]
Glassing has gone through some changes since this post and the damage dealt is devastating
