### ISSUE TITLE
Unggoy tanks can be taken off the back, and placed into suit storage.

### ISSUE THREAD

**Issue by Katiefuckinghellwhyisitalltaken** [HaloSpaceStation/HaloSpaceStation13#1281]
Title

Don't /think/ it's intended.

Unggoy using bags has been an issue, too.

**Comment by caelaislinn** [comment]
Although this is a bit counterintuitive I did this deliberately to give Unggoy a bit more loadout flexibility under our "gameplay over lore" policy.

**Comment by Katiefuckinghellwhyisitalltaken** [comment]
Hm. Would it be possible to restrict backpacks?

**Comment by bloxgate** [comment]
Perhaps we could make the back tanks work like the RIG’s parts and deploy to the slot in an irremovable way whenever they're wearing armor?

Sent from my Windows 10 device

**Comment by caelaislinn** [comment]
That's the way the Unggoy armour initially functioned. I removed the restriction after some discussion on Discord.
