### ISSUE TITLE
Duel wield duplication bug

### ISSUE THREAD

**Issue by JediCaster** [HaloSpaceStation/HaloSpaceStation13#1290]
#### Description of issue
Duel wielded weapons can be duplicated infinitely

#### Difference between expected and actual behavior
I believe the item in your hands are suppose to dissapear into the container, but instead unduel wield and remain as the result

#### Steps to reproduce 
1. Under abilities tab, duel wield weapons
2. Place duel wield combo into a container (Coffin, etc)
3. Boom dupe

#### Specific information for locating

idk

#### Length of time in which bug has been known to occur

i just found out today

#### Client version, Server revision & Game ID

Server Revision: 426eb5867448dbcfdef2fa8543bb726c5a390849 - alpha - 2019-02-19

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x ] Issue could be reproduced at least once
- [x ] Issue could be reproduced by different players
- [x ] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [x ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)
![g59veac](https://user-images.githubusercontent.com/47832314/53123009-13e03180-3526-11e9-905a-cd8ccf3d5d99.png)

**Comment by Real-MAGNUM** [comment]
When duping, the 'duped' weapons cannot fire, or be separated. Only the original.
