### ISSUE TITLE
Add RnD to Insurrectionist Base

### ISSUE THREAD

**Issue by Cynliax** [HaloSpaceStation/HaloSpaceStation13#1294]
Since the cells update is delayed, or hell might not even happen, what would of balanced URF to have somewhat a chance against other factions when they're competent (X-52) is now gone in the wind, and I don't believe the devs are working on anything URF related at all, so for the time being can we get some RnD machines mapped into our base so we have some chance to do cool shit? Or at least some gadgets such as Freedom implants or one or two traitor uplinks with TC so we can requisition some shit to help even the odds.

**Comment by caelaislinn** [comment]
It's still coming. Mapping in a research base would be the first step for X52, but it would need to be a separate base in another part of the colony. The reason for the delay is we may be switching colony maps soon so any mapwork done to an existing map may be lost.

**Comment by Stingray540** [comment]
X52 now have their own research areas and so this can be closed.
