### ISSUE TITLE
HA map and some job issues. 

### ISSUE THREAD

**Issue by Spessmun** [HaloSpaceStation/HaloSpaceStation13#1304]
The unlabeled marine role for what I assume is the HA has an ONI style ID card. On deck two of the HA there is two sets of stairs that run into each other, I think they lead to the same place. 
Edit: Normal marines and the old marines both have ONI cards, and the normal marine class doesn’t have access to the HA, but the old one does.
 Normal marine has access to some doors but doesn’t to others, one of the doors being the COs office. Will continue to update with any other bugs I find as I go on. 
Edit 2: Normal marines don’t have access to the weapon racks on deck 4, this is probably redundant at this point but don’t want anything to get overlooked.

**Comment by BDpuffy420** [comment]
To be fair that “oni id” is the standard unsc ID card, someone just hasn’t gotten around to giving it to all unsc roles

**Comment by caelaislinn** [comment]
This is most likely a job access issue in code. This is not a bug

**Comment by Stingray540** [comment]
Most of this has been fixed and I recommend this issue is removed.
