### ISSUE TITLE
Crew manifest is welp not showing correct

### ISSUE THREAD

**Issue by CdrRiley** [HaloSpaceStation/HaloSpaceStation13#1311]
![grafik](https://user-images.githubusercontent.com/25209341/54078833-f6ee8100-42cf-11e9-9cd8-e8a6e6e3b7c5.png)

**Comment by caelaislinn** [comment]
This is an ongoing issue from ages back. It's partially a game design problem we never addressed because it shows players and jobs from other factions which shouldn't be displayed. We need to think and decide who actually has access to it and who should be shown on it

**Comment by caelaislinn** [comment]
There needs to be a lobby display of active players per faction, and some other info to help steer players towards playing factions that need them. This will tie into the faction balancing stuff later this arc
