### ISSUE TITLE
Potato's Ultimate List of HA Feedback

### ISSUE THREAD

**Issue by daPotato** [HaloSpaceStation/HaloSpaceStation13#1312]
Big man potato noticed big thingoes with the medbay.

1. Big lack of boxes of pill bottles
2. There's only one defib
3. Another row of morgue trays could be fit in the morgue
4. If I say pretty please can we get more large beakers

- Might update this with more _observations,_ might not.

**Comment by daPotato** [comment]
Update

6. There are no Advanced Body Scanners within convenient distance of the surgery tables
5. The bloodbags should proooobably be in the bloodbag crates and not on a table in an open room

**Comment by daPotato** [comment]
Update 2: There's no limb printers boogaloo.

There aren't any organ printers either.

**Comment by daPotato** [comment]
Update 3
- Unless its in the brig, there are no straight jackets nor muzzles
- There are no sleepers in the medbay [Might be wrong, just going off of memory]

Now for something that isn't focused on the medbay : 
- Basically every single wall mounted button for blast doors and such are unable to be used by marines. This is known issue but I thought I would include it anyway.

~~Suggestion : Add a full lockdown button to the bridge to close down all of the blast doors within certain areas of the ship. This would probably require the other factions to have a boarding kit buff. I believe the AI can toggle the blast door buttons individually so it won't be as necessary if there is an AI.~~
- Suggestion has general distaste in the embassy, I want more boarding countermeasures for all factions but people aren't a fan of this so we can just put a pin in it and throw it into the ocean for the time being.

[Also made the issue thread's title more fitting.]

**Comment by Stingray540** [comment]
I'll begin ticking these off and will edit this post along with the progress.

EDIT 1: There are 3x Pill bottle boxes already in storage, and there are already 2x Large beakers in chemistry (don't lose them).

EDIT 2: Added additional defibs to medbay storage (even though you should just use tri-adrenaline...), an additional column of morgue trays have been added, Advanced body scanners have been added to surgery, Bloodbags have been put into their crate, Added limb and bioprinters to the surgery storage, Added sleepers to medbay, added 2x additional sets of straight jackets to the brig. This will be PR'd shortly.
