### ISSUE TITLE
Marines don't have access to HA Weapon Vendors

### ISSUE THREAD

**Issue by daPotato** [HaloSpaceStation/HaloSpaceStation13#1314]
oh my gosh literally unplayable 0/10

**Comment by CdrRiley** [comment]
HA weapons vendor should be acsaple via the one officer job , so taht marines all take LMGS RPGS and SRSs
some needs to play taht role othwise basic guns

**Comment by Stingray540** [comment]
Simple access issue from the old system, I'll add the new access to the new jobs

EDIT: Fixed. Will be up on my next PR.
