### ISSUE TITLE
HA EWS [Suggestion] 

### ISSUE THREAD

**Issue by CdrRiley** [HaloSpaceStation/HaloSpaceStation13#1319]
idea well it needs coding EWS gets a console and SMES which can be used to send  like an emp to an sletecd ship which requires  time to set up and power drain wich disable like 1 apc randomly on said ship for like the time of an ion storm, 2 is a heavy emp blast  requires longer time t setup and more power drain but disables more then 1 apc like 3-4 apcs for duration of ion storm , countermeasure like  against rockets
this is idea for EWS           

EDIT:i have 2 ways of the EWS working
1 less coding
you do the action and the action happens on the enemy said ship
option 2
more coding reuqierd as it would like an shipboard firewall to prevent like apcs overloards
Firewall looses x amount % of each EW Attack or action  but heals those x amound of % slowly up like a shild gen but slower
if firewall is breached you can go on like temp disable weapons
engines
power
Fire wall can be reobboted by a person but takes x amount of time
option 3 includes option 2
EW attacks can be fixed manually via counter EW (should be added in option 2)
takes energy and time
For signaler and sensor im gonna write taht up shortly
note EWS should have an attack range outside of ship viewing distance but no over the hole overmap !

**Comment by caelaislinn** [comment]
I'd like to see this as a researchable weapon for X52 or ONI scientists with variants for ship, fighter, vehicle and portable heavy weapon

**Comment by CdrRiley** [comment]
https://www.youtube.com/watch?v=fBLHZwEXKeA to get a more clear idea of waht EW is in IRL

**Comment by CdrRiley** [comment]
why this closed tho?

**Comment by caelaislinn** [comment]
Whoops I didn't mean to close this
