### ISSUE TITLE
T'vaoan spawn in the URF Station.

### ISSUE THREAD

**Issue by Elzenio** [HaloSpaceStation/HaloSpaceStation13#1330]
#### Description of issue
As the title states, the Covenant T'vaoan seem to spawn within the URF station's spawn.

#### Difference between expected and actual behavior
Expected: T'vaoan spawn in Covenant station/ship(s).

Actual: T'vaoan is stranded in URF station, either to be killed by horrified URF or try to sneak out and not die.

#### Steps to reproduce 
Spawn as (in my case) a T'vaoan Major.

#### Length of time in which bug has been known to occur
Not sure when this began. Prior to a few updates- maybe like last week- T'vaoan just didn't spawn at all.

#### Client version, Server revision & Game ID
Client Version: 512
Server Revision: 37cf087b7884fea05e5102fd326a7c5190388178 - alpha - 2019-03-14
Game ID: bZh-cJGy

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [(Unchecked)] Issue could be reproduced by different players
- [(Unchecked)] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by caelaislinn** [comment]
#1360
