### ISSUE TITLE
More HA quality checks [Potato Edition]

### ISSUE THREAD

**Issue by daPotato** [HaloSpaceStation/HaloSpaceStation13#1331]
Here we go again!

There is a wall-based nanomed inside of this laptop
![image](https://user-images.githubusercontent.com/37031441/54479177-af488780-47f0-11e9-8cc0-994d35f5d958.png)
- That laptop also can not be picked up, unsure if this was intentional but it is something to note.
- Theres also the wall-mounted intercomm right beside the laptop

For the few of us insane enough to do paperwork, there are no paper copiers as far as I have found.

None of the main canteens have ovens, stoves, grills, deep fryers, or soda machines. 

![image](https://user-images.githubusercontent.com/37031441/54479818-968fa000-47f7-11e9-9643-a7583487429c.png)
Officer dining quarters are reportedly not for dining.

There are no maintenance doors for the Deck 2, Starboard reactors, unlike the Deck 2 Port reactor.s

Crescent Base reportedly doesn't have any medical records consoles.

**And can someone turn down the frequency for the fucking ion storms, we _never_ have lights.**

**Comment by daPotato** [comment]
Update

Why the hell is there no chairs in the break room

**Comment by CdrRiley** [comment]
medical break room and chief corpsmen office where?

**Comment by caelaislinn** [comment]
Ion storms might be the only random event enabled. That should be in a separate issue report though

**Comment by CdrRiley** [comment]
can we replaice the sugery tools in the sugery room with the Sugery kit?

**Comment by Maxattacker** [comment]
So there are photo copiers in the crew chief offices. The thing with the officer dining quarters was fixed.
