### ISSUE TITLE
Are T'vaoan spawns just randomized?!

### ISSUE THREAD

**Issue by Elzenio** [HaloSpaceStation/HaloSpaceStation13#1333]
#### Description of issue
So, spawning as a T'vaoan Major.. I end up spawning on VT9. In the ONI barracks.

#### Difference between expected and actual behavior
Expected: Spawn inside of Covvie ship/base/station.

Actual: Spawn inside of ONI facility.

#### Steps to reproduce 
1: Spawn as T'vaoan Major (in my case).
2: Scream as you realize you are stuck in the ONI base.

#### Specific information for locating
No idea.

#### Length of time in which bug has been known to occur
No idea!

#### Client version, Server revision & Game ID
Client Version: 512
Server Revision: 37cf087b7884fea05e5102fd326a7c5190388178 - alpha - 2019-03-14
Game ID: bZi-deWP

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by caelaislinn** [comment]
Duplicate #1330 but leave it open as there is useful info in both

**Comment by caelaislinn** [comment]
#1360
