### ISSUE TITLE
HA small first aid room threwout the decks

### ISSUE THREAD

**Issue by CdrRiley** [HaloSpaceStation/HaloSpaceStation13#1337]
so suggestion a milltäry ship should have smaller first aid station on all decks maybe incase like medbay gets hit or the wound are really serve to get them to the first aid station on the said deck to stablzien then and move them later to deck 3 it was to medbay

**Comment by daPotato** [comment]
![image](https://user-images.githubusercontent.com/37031441/54483288-184af200-4827-11e9-821d-0d4495348b7c.png)

**Comment by Maxattacker** [comment]
With there being first aid kit lockers literally everywhere, I don't feel that this is necessary.
