### ISSUE TITLE
Shipmaster Bugged Spawn

### ISSUE THREAD

**Issue by ghost** [HaloSpaceStation/HaloSpaceStation13#1350]
#### Description of issue
Shipmasters spawn on KS7 

#### Difference between expected and actual behavior
They should be spawning on the covenant base

#### Steps to reproduce 
1. Spawn as shipmaster, either readied up or latejoin
2. observe

#### Length of time in which bug has been known to occur
Past week or so

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by caelaislinn** [comment]
Damn we need a "spawn bug" label

**Comment by caelaislinn** [comment]
#1360
