### ISSUE TITLE
Local ODPs blow up UNSC base

### ISSUE THREAD

**Issue by daPotato** [HaloSpaceStation/HaloSpaceStation13#1355]
UNSC ODPs decide to fire upon the UNSC Base at random points in the round, has happened for the past 3 or 4 rounds.

**Comment by daPotato** [comment]
This needs further examination, apparently Topey activated the nuke on two or so of the 3 rounds that the ODPs fired on the base.

**Comment by caelaislinn** [comment]
I'm not sure the nuke activation is connected, unless it destroys the nav computer on the base,

**Comment by G0nTar** [comment]
they also attacked my "Heavens Above" Cruicer when we went to the coordinates since there was a "SPAM" of "ODPs under fire" they were shooting at each other, and when we came to help, they started shooting at us for no reason

**Comment by X0-11** [comment]
Has this been confirmed yet? Explosions can and will often delete the nav chip within the nav computer.

**Comment by X0-11** [comment]
Bases are quite literay immune to outside ship v ship gunfire, this was probably someone activating the nuke
