### ISSUE TITLE
Grabbing mobs makes you go Enderman 

### ISSUE THREAD

**Issue by PantasTheDank** [HaloSpaceStation/HaloSpaceStation13#1356]
When you use grab intent on one mob, then switch hands and grab another, your movement makes you blink 2 tiles away every tick.
*teleports 2 tiles behind you*
heh, sorry code monkeys, nothin' personel

**Comment by caelaislinn** [comment]
http://www.scp-wiki.net/scp-173

**Comment by Maxattacker** [comment]
As far as I have experienced, this happens with older bay codebases as well. I don't think this is an issue just we have.
