### ISSUE TITLE
Covenant Slipspace interferes with Restart Vote

### ISSUE THREAD

**Issue by daPotato** [HaloSpaceStation/HaloSpaceStation13#1359]
Figured it out, the restart vote's restart can not properly initiate until the Covenant enter a slipspace jump.

Delicious interference.

**Comment by caelaislinn** [comment]
There is no connection between the Covenant slipspace engine and the restart vote. What is not working about the restart vote?

**Comment by caelaislinn** [comment]
Rewrote the auto restart vote in #1360
