### ISSUE TITLE
Nanolaminate plating

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#1364]
Requesting a sprite for this

**Comment by ghost** [comment]
Will be done this evening.

**Comment by ghost** [comment]
#1374 did this

**Comment by caelaislinn** [comment]
Leaving this open for now because the icon_state still needs to be set in the code

**Comment by BDpuffy420** [comment]
I think this was done

**Comment by Nanu308** [comment]
bruhg, close no?
