### ISSUE TITLE
Heaven's Above checks : Elevator Edition

### ISSUE THREAD

**Issue by daPotato** [HaloSpaceStation/HaloSpaceStation13#1379]
Due to Cael's Z-level rewrite, Elevators on the HA say they are ascending when they are descending, and vice versa.

MAC ELEVATOR : 
![image](https://user-images.githubusercontent.com/37031441/55283562-2d9a4300-5334-11e9-91ad-f28a26fd1136.png)

What the fuck is this shit?

**Comment by caelaislinn** [comment]
Closed HA currently unused
