### ISSUE TITLE
Multiple issues.

### ISSUE THREAD

**Issue by kaseywolf878** [HaloSpaceStation/HaloSpaceStation13#1391]
#### Description of issue
File organization so it's easier to find and edit files within our current build. Admin logs have an issue that need to be fixed, console lag due to the server needing to go all over the place to find the things it needs to find. There's issues with some of the doors I'd sec credentials. There is an issue with shutters even after they have been destroyed on ha. There's a problem with lighting on the shuttle and any other instance of dynamic lighting needing work cause it just glitches out. There is a problem of the cameras on guns not working all the time. A glitch with pAI not being able to open doors in it's chassis form.

To my knowledge these either where not brought up as an issue or the issue was forgotten about after some time for some reason.

#### Difference between expected and actual behavior
Files should be organized for both game play optimization and ease of modification.
admin logs don't show who sets off nukes and anti matter, this was supposed to be a git issue but i guess it got ignored or didn't happen.
Consoles lag i believe due to the unorganized file placement. causing controls to not respond when firing guns and such while moving the ship. it should not lag.
on the HA one of the doors i believe the top left reactor door with like oxygen tanks in it doesn't have proper ID credentials. Ask potato for the specific location as i don't know which one it is right now. ID should be required as part of HA engis to open these doors as they lead to one of the reactors directly
Security shutters like to re spawn when destroyed or suddenly activate without prompt from the control button. Example is the shutters around the slip-space drive for the HA. shutters should be prompted to close as to not trap ODST or MARINES in the room indefinitely without outside help.
Shuttle needs the dynamic lighting fixed. should be able to see on shuttles for the UNSC at least.
Shot cameras don't work properly on the MAC and possibly glitch out on other weapons. should be working.
pAI cant open doors when spawned it shows "it wont budge" and cant hotkey it open. can only 100% confirm this on the ONI research base. pAI also do not have sight in the dark. should be able to open doors of where the pAI and who the pAI spawns for as if also an ID card for the person they spawn with when prompted. Its also a robot it should at least get mason vision.

#### Steps to reproduce 
Most of these are visual, ID check just step up to door, console lag you have to shoot the HA mac and gunswhile trying to move the ship for it to cause some lag, unsure how much. security shutters usually seem to react to atmosphere, they respawn when reacting to atmosphere. everything is pretty self explanitory.

#### Length of time in which bug has been known to occur

about a day. a little less for some stuff.

#### Client version, Server revision & Game ID

unknown did not check. was same revision as 3/30/2019 at 11PM to 3/31/2019 2AM

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by X0-11** [comment]
Please create seperate issues for each, for the sake of readability.

**Comment by BDpuffy420** [comment]
Firstly the admin log issue was fixed if you read the GitHub and do what XO stated
