### ISSUE TITLE
MP Thematic Boogaloo [suggestion]

### ISSUE THREAD

**Issue by Insanegame27** [HaloSpaceStation/HaloSpaceStation13#1394]
#### Military Police/Master At Arms/Naval Security expanded 

Currently, Military Police personnel lack access to a range of thematically appropriate weaponry. At this point in time with respect to non/lessthan lethals, they have access to MA5 Training rounds, M7 rubbers, the taser, humbler, flash and pepperspray. If you’re exceptionally lucky you can convince someone to vend you an M90 and acquire beanbags from a lathe. 

Give Naval Security officers access to their current equipment, plus the custom .45s with flash/rubbers and code some LTL ammo for the M6D (expanding joint-lock foam, RvB style?). The Naval Security Officer’s arsenal should look like taser + flash/humbler/spray + M6D/.45 + M7/MA5. Lethal rounds on request to Master At Arms or Commanding Officer. 

The Master At Arms really deserves a shotgun in their locker with a box of beanbags and a box of buckshot. Because nothing says “Last chance to surrender, criminal” like racking a shotgun. 

They also currently lack any form of equipment whatsoever on the Defiance.

Finally, change the name from “Naval Security” to “Naval Police Coxswain” for the grunts but let the Master At Arms retain that title

**Comment by caelaislinn** [comment]
Good suggestions. LTL ammo would probably be recomended for fighting innies.

**Comment by Insanegame27** [comment]
Could give MP and MAA alt titles too. Make the default “Military Police” with “Naval Security” and “Naval Police” as alt titles. Make MAA a “Military Police Officer” with alt titles of “Master-at-arms” and “Naval Police Coxswain”

**Comment by BDpuffy420** [comment]
Will address soon

**Comment by caelaislinn** [comment]
MP have been removed for now due to low pop, but may return in future
