### ISSUE TITLE
Feature: supply drop pods (sprites needed)

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#1397]
A supply pod should be craftable, meaning you can keep sending them as long as you have resources. Unlike drop pods which are once per round (and there probably shouldn't be so many). Crew members can load whatever supplies they like onto the pods then send them down to coordinates provided by someone on a planet. 

This will need Covenant and UNSC variants. UNSC reference: https://vignette4.wikia.nocookie.net/halo/images/3/3f/Resupply_Capsules.jpg/revision/latest?cb=20071116040101 Covenant didn't use them in any games, so we could probably do something similar.

**Comment by ghost** [comment]
#1408 placeholders are in place, holding.

**Comment by BDpuffy420** [comment]
sprites have been added

**Comment by BDpuffy420** [comment]
#2091
