### ISSUE TITLE
Suggestion- URF drones

### ISSUE THREAD

**Issue by PantasTheDank** [HaloSpaceStation/HaloSpaceStation13#1402]
This was suggested on the forums
The jist is to give URF remote controlled drones to keep themselfs anonimous 
Bolter made a flying drone sprite and eluxor said he might made threaded one.

**Comment by caelaislinn** [comment]
The code for these won't be too complex. We might be able to reuse the bot system.

**Comment by BDpuffy420** [comment]
Sprites are in the code for it I believe

**Comment by BDpuffy420** [comment]
They were added, just not used by many
