### ISSUE TITLE
Can't close umbiricals in Camp New Hope OR URF Thorn

### ISSUE THREAD

**Issue by PantasTheDank** [HaloSpaceStation/HaloSpaceStation13#1407]
The bug occured when I tried to close the umbiricals from the Camp New Hope while they were connected to URF Thorn, I am not sure if the thorn or innies base umbiricals are bugged

**Comment by PantasTheDank** [comment]
It seems the bug occured during the overmap bug, it might be connected to it

**Comment by caelaislinn** [comment]
These are both removed, so I'm going to close this
