### ISSUE TITLE
Missing code for sprited gear.

### ISSUE THREAD

**Issue by bloc97** [HaloSpaceStation/HaloSpaceStation13#141]

**Comment by caelaislinn** [comment]
Emergency tank dispensers, flashlights, inhand sprites for marine gear (uniforms, helmet etc), outdated UNSC armour plus shemagh and jumpsuit (for innies), new fusion reactor (not slipspace reactor, that sprite is for something else), oxygen and emergency oxygen tanks, new tool sprites, new wall sprites.

**Comment by caelaislinn** [comment]
Most of the smaller stuff sorted in the other PR.

**Comment by caelaislinn** [comment]
Still Todo: slipspace engine, advanced reactor sprites, thruster sprites, new wall sprites, new tool sprites, Innie armour and suit.

**Comment by BDpuffy420** [comment]
Other items such as the ODST and Spartan  gear.

**Comment by caelaislinn** [comment]
These items have either been added by now or won't be needed for the public alpha.
