### ISSUE TITLE
Matt's horrid suggestions - E-dagger throat slitting

### ISSUE THREAD

**Issue by Sgtwok** [HaloSpaceStation/HaloSpaceStation13#1414]
As it turns out, the human Combat knives and Covenant's energy daggers do the same difference. However, the Energy daggers, lacking the 'edge' and or 'sharp' variable do not posses the ability to perform throat-cutting. At the very least, it should serve as a surefire 'finisher' against opponents instead of having to spam the dagger onto a hostile's head until it explodes.

While, yes, it is a very powerful ability (i'm not sure if even biofoam can fix it), it is easily balanced by the time it takes to perform as well as the effort of knocking down an opponent

**Comment by X0-11** [comment]
Please confirm this is still impossible, it was supposed to be fixed a while back in #1024

**Comment by BDpuffy420** [comment]
no update
