### ISSUE TITLE
[Suggestion] Vehicle lights

### ISSUE THREAD

**Issue by Joe44445** [HaloSpaceStation/HaloSpaceStation13#1429]
Suggestion made on request of XO

Add lights to appropriate vehicles(Mongoose, Scorpion, Warthog etc) to help with navigation in dark areas. This should hopefully mitigate the bug of lights not working whilst in a vehicle.

**Comment by BDpuffy420** [comment]
Yes we need this

**Comment by X0-11** [comment]
has been done #1518
