### ISSUE TITLE
Forward unto dawn

### ISSUE THREAD

**Issue by Kmc2000** [HaloSpaceStation/HaloSpaceStation13#143]
I've done the base of the map, what it needs

Atmos

Power that isnt just a godcell, and that reaches all Z levels

Maybe some tweaking needed, but meh

Boop

**Comment by BDpuffy420** [comment]
We also need the areas marked with spawn points.

**Comment by Kmc2000** [comment]
I did that though, i added spawns


Did i not PR it...?

**Comment by BDpuffy420** [comment]
For all the jobs?

**Comment by Kmc2000** [comment]
Yeah all included jobs and latejoins etc. Etc.

**Comment by BDpuffy420** [comment]
Map isn't in use.
