### ISSUE TITLE
Fragmentation Grenade Time

### ISSUE THREAD

**Issue by Chambers0** [HaloSpaceStation/HaloSpaceStation13#1437]
I believe we should reduce the time it takes of a primed frag grenade to go off from 5 seconds to 3 second.
Leaving targets enough time to run away but not too much time.
Any arguments?

**Comment by SuckMySocks** [comment]
Ever hear the story of the boy that knew how to cook grenades?

**Comment by Chambers0** [comment]
Hey you know the load ass beeping noise of when you prime the grenade.
Yeah that not the grenade going off, the grenade telling everyone HEY THIS JACKASS IS CHUCKING A GRENADE, TAKE COVER!!!
It's after the beeping is done, that's when the timer goes off.

**Comment by ghost** [comment]
Does that somehow make it impossible to cook the grenade?

**Comment by PantasTheDank** [comment]
The grenade could use a buff,there was talk about buffing other nades so that the covenant plasma nade isnt better than frag ones

**Comment by ghost** [comment]
I'd say adding an explosion or making the shrapnel more 'accurate', IE less likely to narrowly miss someone, would be a lot better for buffing the frag grenade than reducing the timer. Cook your grenades.

**Comment by Chambers0** [comment]
Listen, after cooking the grenade, in other word wait for the beeping to end, it takes it five seconds to go off, I'm saying it should take 3 seconds to go off after being cooked.

**Comment by ghost** [comment]
Cooking the grenade isn't 'waiting for the beeping to end'. Cooking a grenade is using your wits and waiting until you think the grenade is about to explode before throwing it, so that the enemy has less time to react. If you do it right, it explodes immediately on contact with the enemy. If you do it wrong, it either explodes in a second or two, or you've just been hit point blank by your own grenade's explosion and are probably bleeding out on the floor.

**Comment by Chambers0** [comment]
Ok, when I see a group of enemies, I don't think, let me hog this grenade for dear life and hope they show up.
I think, group-->grenade-->Throw

**Comment by G0nTar** [comment]
> The grenade could use a buff,there was talk about buffing other nades so that the covenant plasma nade isnt better than frag ones

but, coviee plasma nade is better than frag since Halo: CE

And lowering the timer, in some cases would lead to some un-wanted lag suicide frags that may not be intented by players who could be having a bad connection from time to time (4 example, everyone cause BYOND)

**Comment by X0-11** [comment]
Can't you adjust grenade timers, picking between 2, 3 and 5 seconds by using a screwdriver on it?
