### ISSUE TITLE
BR55 is chambered in 7.62

### ISSUE THREAD

**Issue by daPotato** [HaloSpaceStation/HaloSpaceStation13#1439]
Who the fuck did this?

![image](https://user-images.githubusercontent.com/37031441/56433866-6fb60500-62a0-11e9-9d20-260097e446b2.png)

**Comment by CdrRiley** [comment]
Travis did it.

**Comment by Desolane** [comment]
The BR55 has it's own specific magazine, though this is still a bug

**Comment by daPotato** [comment]
I _did_ check in-game, the BR85 mags are indeed also filled with 7.62mm cartridges. This is absolute fucking heresy.

**Comment by Desolane** [comment]
The desc says it's 7.62 but mechanically it's 9.5
