### ISSUE TITLE
Frag grenades cause gravity to disappear

### ISSUE THREAD

**Issue by frontline03** [HaloSpaceStation/HaloSpaceStation13#1441]
Throwing frag grenades in the heavens above cause gravity to disappear in the area it hit. It should not be doing that

#### Steps to reproduce 
Throw grenades in the Heavens above and wlak on them afterwards

#### Specific information for locating
Hallways before the Armoury on Heavens above

**Comment by BDpuffy420** [comment]
Hasn't came up as of late
