### ISSUE TITLE
Make elites 2x as long to climb ladders and enter vehicles

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#1442]
They have backward jointed knees lol

**Comment by ghost** [comment]
remove all stairs from the HA for maximum delay of boarding parties.

"Sir, the humans have blocked all stairs! Only way up is ladders!"
"FUCK"

**Comment by CdrRiley** [comment]
good idea but please dont, how will you get wounded a ladder up or down?

**Comment by frontline03** [comment]
They dont

**Comment by Joe44445** [comment]
https://gyazo.com/a076e29f320e4c36487da4100f161fe9

it works, although 2x might be too much. maybe 1.5? 1.25? if those are possible.

**Comment by X0-11** [comment]
Cael pls
