### ISSUE TITLE
Civilian NPC Additional Dialog

### ISSUE THREAD

**Issue by SuckMySocks** [HaloSpaceStation/HaloSpaceStation13#1447]
“Hey did you hear that rumour of those big green walking tanks?”

“Bleh, this sucks, why does nothing interesting ever happen to Emsville?”

“Been seeing a lot more traffic in these parts, I wonder why?”

“I use to be a soldier (like you), then I took a landmine to the knee.”

“Use to live on Far Isle, still don’t know what happened to that place.. wiped from existence.”

“Have you seen those uh.. Helljumpers? In that sleek black armor?.. man I wanna be one of them some day.”

“Hey, did you hear they reopened recruitment for the Hellbringers? I wonder what that’s all about.”

“Feels good to live on a free planet!”

“Went hunting last week, found me one of those ice-boar things, they may smell terrible but they taste pretty good!”

“Have you ever been to Space? Sometimes I long for my chance.”

“I eat crayons.”

“I heard Earth it quite beautiful this time of year. Maybe I’ll visit it one day.”

“Tried my hand at the *International War Photography Prize* last year, came in last place..”

**Comment by SuckMySocks** [comment]
Made at request of Cael

**Comment by frontline03** [comment]
"Do the unsc Really care about us? I haven't  see any unsc in years"

"Did you hear the urf are managing to steal unsc ships easily, they have already stolen two so far"
