### ISSUE TITLE
[Sugg] New colony

### ISSUE THREAD

**Issue by frontline03** [HaloSpaceStation/HaloSpaceStation13#1459]
Ks7 is not a good colony at the moment, we. Have some ideas how to improve it

•	Medium map
•	Underground oni base
•	Desert biome location of a colony(currently Named emsville)
1.	Security
2.	Bunks
3.	Perimeter fence
4.	Gate
5.	Landing pads
6.	Medical
7.	Garage(Contains warthogs)

•	Snowy Mountainous range 
1.	Secret insurrection outpost, 
2.	Outpost Only accessible by pelican
3.	Just a small valley, one or two people wide

•	“Badlands”
1.	Ruined city
2.	Crashed land and air vehicles
3.	Abandoned buildings(Mining, Arsenals)
4.	Hostile fauna
5.	Abandoned vehicles
6.	Weapons scattered
7.	Abandoned fortifications

**Comment by G0nTar** [comment]
are these extra biomes intented to be part of the same ks7 level (updates of the level), or as a new planet itself? 

Cause a desert biome on an ice planet would be kind of weird to begin with

**Comment by BDpuffy420** [comment]
We need a new colony altogether

**Comment by frontline03** [comment]
Xo and I made it as ideas for a new colony, that can include other planets to be honest

**Comment by X0-11** [comment]
The idea was to for each subsection to be a part of the same planet, whilst residing on their own map. They'd be linked by pelican travel and/or a groundbased tram system.

**Comment by X0-11** [comment]
The idea was to for each subsection to be a part of the same planet, whilst residing on their own map. They'd be linked by pelican travel and/or a groundbased tram system.
It'd be an entirely new planet, 'cause KS7's been glassed.

1st map would be the colony itself, with walls sealing it off from the outside.
2nd is Innie Forward Base, which isn't needed but may be a good idea to place on the same planet as the colony. Do this last if you plan on working on the colony.
3rd map is an area that is "outside" of the protective walls of the colony, acting as a PVE opportunity where colonists and innies alike can scavenge the ruins of innie-unsc conflicts, with the wildlife acting as an obstacle and deterrent.

**Comment by caelaislinn** [comment]
These are great ideas but it's become redundant now that we've switched to Geminus. Keep these ideas on the backburner and someone can always map up a new colony later if they like.
