### ISSUE TITLE
[SUGGESTION] Add Flares/Chemlights to the UNSC/URF/COV Factions

### ISSUE THREAD

**Issue by Blackburn56** [HaloSpaceStation/HaloSpaceStation13#1475]
Add alternative light sources to faction arsenals. currently factions use flashlights located on their person to navigate through dark terrain. Suggesting we add more options of lighting up a dark area other than tossing our flashlights out.

**Comment by BDpuffy420** [comment]
There already stuff in the code for this, it just needs to be mapped in
