### ISSUE TITLE
[Suggestion] Add Elite EVA Suit to Armory

### ISSUE THREAD

**Issue by Allakai** [HaloSpaceStation/HaloSpaceStation13#1483]
I'd like to begin with the firm statement: This is not requesting a new elite slot at all. This is in-fact requesting a _armor set_ as a tool to use for the Sangheili aboard their ship in the instance of breaches.

One of the major weakness (with good reason and a good balance) to elites is being spaced and losing oxygen; however, it seems entirely annoying the elites have no way to effectively fight in low-atmos environments.

This suggestion requests that, much like how the kig-yar have in their own armories, the elites get ONE Ranger set for the use of repairs or even fighting in low atmosphere enviroments. For balance I would suggest that this armor is about the same as a minor shielding as this suit would be more oriented for EVA use, not combat.

**Comment by BDpuffy420** [comment]
Denied, all rites combat suits come with a EVA mode

**Comment by BDpuffy420** [comment]
Denied, all elite combat suits come with a built-in EVA mode.
