### ISSUE TITLE
[SUGGESTION]Add Quest Mechanics to NPCs

### ISSUE THREAD

**Issue by Desolane** [HaloSpaceStation/HaloSpaceStation13#1486]
Add baseline conversations to NPCs in the form of dialogue and add the ability to receive rewards for meeting criteria(optional) as well as map loading overmap objects for getting information from them.

Stranded could be added as a dungeon to the overmap by either overhearing an NPC mention the coordinates, randomly generated each round, or getting a dialogue option that would put in a shuttle somewhere on their planet akin to vanilla centcomm shuttles, which then takes people to the Stranded site, crashes, and forces the survivors to live through some smaller waves than the actual gamemode. The survivors then get the option to continue the quest line into the Achlys dungeon by being inducted into the crew of the Dante, a Mariner class ship scouting for the Achlys in a debris field, which would spawn on the overmap after successful completion of the Stranded dungeon.

This is a single example of the branching paths Quest integration could bring into the game. Covenant could also get quests from a prophet NPC, which rewards them for finding artifacts, which could also be sold to Kigyar NPCs, which could give quests to steal things or kill someone.

**Comment by BDpuffy420** [comment]
#1653

**Comment by caelaislinn** [comment]
#1783
