### ISSUE TITLE
UNSC Ship Hull

### ISSUE THREAD

**Issue by Chambers0** [HaloSpaceStation/HaloSpaceStation13#1493]
After wondering to myself I always wondered, why are we using steel as a hull for UNSC ships rather than Titanium-A as they did in lore.
https://www.halopedia.org/Titanium-A_armor
Although Titanium isn't as good to disperse heat its way better than using steel, not only that, they put in a layer of tungsten along the armor plating because the melting point of tungsten is 3,400 Celsius making more effective at dispersing heat and protecting the ship from plasma weaponry since plasma torpedoes burns at about 3,000 Celsius.

**Comment by X0-11** [comment]
It's pretty simple as to why we used steel: making a new wall type would require a new material define and in the end would have 0 effect because weapons are currently being balanced against steel. All it would do is nerf the abilities of steel.
