### ISSUE TITLE
/turf/simulated/floor/open not updating underlays properly

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#15]
What's supposed to be happening is a shaded underlay of the turf on the level below is applied, but instead the open turf just has a pitch black overlay. This appears to be an issue with lighting (note possible fix in https://github.com/HaloSpaceStation/HaloSpaceStation13/pull/16).

**Comment by caelaislinn** [comment]
Do we really need this for alpha? :/

**Comment by bloxgate** [comment]
I'd expect it to be quite confusing for someone to walk onto a black turf not realizing what it was and falling down 5 z levels or something.

**Comment by BDpuffy420** [comment]
Bay update fixes this issue
