### ISSUE TITLE
Covenant Consoles are industructable

### ISSUE THREAD

**Issue by Chambers0** [HaloSpaceStation/HaloSpaceStation13#1500]
After shooting the glassing console a couple and then later placing then detonating C12 on it, the Console took no effects.

**Comment by Stingray540** [comment]
I believe this is a bug, however I also believe it's currently codedly impossible to create those consoles too via in-game methods. They shouldn't be so easy to cripple as a single c12, and neither should the critical consoles on other ships.

**Comment by X0-11** [comment]
No, this is wholly intended. Severing power to the area will stop the consoles from functioning.
