### ISSUE TITLE
Give ONI a pelican/shuttle/something

### ISSUE THREAD

**Issue by Leudoberct1** [HaloSpaceStation/HaloSpaceStation13#1505]
Currently, there's no way for the ONI security team or research staff to leave VT9 without the assistance of the Bertels. I'd like to propose that a shuttle or somesort be added to allow them to leave VT9 without the assistance of the Bertels. This would allow the ONI folks to do some shady clandestine business, like secretly going to KS7 to kidnap a colonist for experimentation or augmenting them. I think this would be a pretty cool thing to add.

**Comment by Max-023** [comment]
Except the CO specifically gets orders in the form of papers to do that. Aside from Orions, which are supposed to be put on the Bertels and used, VT9 is primarily a research station, not a ONI FOB

**Comment by Max-023** [comment]
Giving them a shuttle just removes the need to use the Bertels

**Comment by Leudoberct1** [comment]
And what if they're trying to be clandestine and don't want the entirety of the Bertels knowing they're doing something?

**Comment by Max-023** [comment]
Then it is their fault for going to the planet the Marines are already at and getting shot at by Marines because the ONI wanted to be snowflakes.

**Comment by Max-023** [comment]
The Bertels is already going to KS7 and VT9 has no offensive units available. Just tell the CO what you need done over fleetcom and he will conduct the operation out because the Marines don't need to know why they need a few civs

**Comment by BDpuffy420** [comment]
ONI isn’t meant to leave VT9
