### ISSUE TITLE
Glassing still seems to not work

### ISSUE THREAD

**Issue by Leudoberct1** [HaloSpaceStation/HaloSpaceStation13#1506]
I shot KS7 ten times with the energy projector and heard people screaming that the planet was being glassed. However, after looking at it, the planet appears perfectly fine and the colony is completely intact. Not sure if it damaged people on the surface at the time or not, but it doesn't seem to actually be destructive,

**Comment by Boltersam** [comment]
There's already an issue open about this. When there's already an issue open about the same topic, you should post in its comment section so that it gets looked at sooner, rather than open a new one. It prevents people from bloating the issue section.

**Comment by Leudoberct1** [comment]
Please link this issue? This issue is not related to the objective not being completed.

**Comment by X0-11** [comment]
Does this mean that glassing does not produce the circles of lava/scorched earth

**Comment by Leudoberct1** [comment]
Yes.

**Comment by X0-11** [comment]
Was the colony counted as glassed by the game at endround?

**Comment by Leudoberct1** [comment]
Yes.

**Comment by X0-11** [comment]
#1507
