### ISSUE TITLE
KS7 kitchen sometimes spawns without some tiles,leading to z level bellow it.

### ISSUE THREAD

**Issue by PantasTheDank** [HaloSpaceStation/HaloSpaceStation13#1509]
This same thing happened a while back but I ignored it thinking it was just a one time thing,I dunno whats causing it
https://ibb.co/87Mnnpf

**Comment by caelaislinn** [comment]
Was this still happening or can it be closed?

**Comment by caelaislinn** [comment]
KS7 is no longer being maintained
