### ISSUE TITLE
Better Huragok code

### ISSUE THREAD

**Issue by Delnth** [HaloSpaceStation/HaloSpaceStation13#1513]
Until we can an entirely unique code for it with fancy features, we could:

- Allow it to pick up items (Currently, huragok use the maintenance drone code, which sucks) /vg/ has a synthetic (MoMMI) that is capable of that
- Give it an ability to deconstruct/destroy any item/structure to salvage the resources that were used to build them (all of the resources, rather than half like in the case of walls)
- Unlimited power (To avoid shutting down due to the lack of power and recharge stations)
- Give the huragoks all the tools and items they are expected/supposed to use. (Most materials, surgery and healing stuff. That might be too much to fit on a screen though, thus comes the idea of starting off from scrap and having huragok run standard cyborg code, with the possibility to pick only one out of two modules, engineer and healer or whatever it is called)

That is more of a list for me to look at if I start working on these features myself, rather than a suggestion. However discussing it is okay I guess. It's not like anyone care about Huragoks anyway, right?

**Comment by BDpuffy420** [comment]
#2026
