### ISSUE TITLE
Covenant don't get syringes.

### ISSUE THREAD

**Issue by UntoldTactics** [HaloSpaceStation/HaloSpaceStation13#1522]
#### Description of issue
Covenant do not get syringes, they get syringe cases for syringe guns that need syringes.

#### Difference between expected and actual behavior
We should have syringe boxes.

#### Steps to reproduce 
1. Spawn in
2. Go to faction base medical/corvette medical.
3. Cry in pain.

#### Specific information for locating

Look at the medbays of the corvette and the faction base, you'll see theres no syringes at all.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by ghost** [comment]
We also need plasma charges, plasma drills, and atmos barricades/shields put on the ship

and all the emergency lockers need to be changed to the covenant wall locker sprite, and all the contents need to have their covenant sprite equivalent (I.E., change oxy tanks to their covenant version)

**Comment by UntoldTactics** [comment]
Another addition: Cyro pods need to be replaced with covvie variant
