### ISSUE TITLE
Projectiles Spawn Inside The DAV

### ISSUE THREAD

**Issue by ghost** [HaloSpaceStation/HaloSpaceStation13#1525]
https://gyazo.com/135ef2160cce083aa708d591e555d73b
https://gyazo.com/e65c6f90c6e7526abc6199ad9e984a1a

Difference Between Actual And Expected Behaviour:

Projectiles should be hitting the outside of the ship/the shields instead of spawning inside the hull.

**Comment by X0-11** [comment]
Recently fixed.
