### ISSUE TITLE
VT9 Glassing bug

### ISSUE THREAD

**Issue by daPotato** [HaloSpaceStation/HaloSpaceStation13#1530]
Noticed this a couple of days ago but forgot to say fuck all about it.

When the covenant glasses VT9, due to the top Z being glassed, it just glasses the rooftops of the facility.

Quite a major oversight, probably should have noticed this sooner but who the fuck goes on the rooftops anyway?

**Comment by X0-11** [comment]
![image](https://user-images.githubusercontent.com/17511708/58049537-00545f00-7b45-11e9-8101-44bd543f7af5.png)

Per above image, the code should already be handling these issues.
