### ISSUE TITLE
Suggestion: Covenant Galactic Common re-distribution

### ISSUE THREAD

**Issue by Nick123q23** [HaloSpaceStation/HaloSpaceStation13#1538]
#### Description of issue
Some covenant roles should be able to speak English, and others probably shouldn't
Also, instead of a paper, it would be easier if covenant species could select Galactic Common as part of their languages in character creation.

https://www.halopedia.org/English#English

Unggoy are known for their ability to speak english, all unggoy roles should have the option to understand english

Kig-yar speech isn't translated for the audience until Halo 5, but the jackals do have the ability to speak english, if sounding a little rough. They're also known to be the most neutral species during the Human - Covenant war, 
I'd restrict english to majors, shipmistresses, and skirmisher champions, just so it isn't too common.
Right now it seems like every kig-yar role is given a translation paper.

Sangheili at this point in the war have an intense, religious hatred for humanity, and are unlikely to know or desire to know english beyond interrogation purposes. However, some elites may prefer to interrogate prisoners personally instead of having a grunt translate.
For them, I'd personally restrict the option of understanding english to officers like the major, ultra and shipmaster.

Jiralhanae would probably be the same as elites, but they're not on Invasion yet so I can't say for sure.

Hunters and Lekgolo can barely speak Sangheili as it is, so they shouldn't really need to know english.

Prophets, on the other hand, aren't a military role at all, intended solely for leadership and spiritual ruling. Although they might hate humanity for their own reasons, all of their power is done through speech and manipulation. They also serve as the most powerful Covenant role in terms of authority. Yet they can't even understand the machinations of their foes.

If nothing else, I'd definitely give prophets the ability to understand and speak english.

**Comment by UntoldTactics** [comment]
I agree on all of these points. Doesn't make sense that the officers of the  covenant (sangheili major, Shipmasters etc) can't speak it, even more so with prophet boi

**Comment by caelaislinn** [comment]
I'm removing all English language from Covenant mobs in #1646 as there is no reason for the two factions to be interacting, including taking prisoners. 

When kigyar pirates get re-added as a trading partner for innies, they'll get English language. If later on we add an objective for Cov to take human prisoners, Sangheili officers will get English
