### ISSUE TITLE
Increase Insurrection Spawns to infinite

### ISSUE THREAD

**Issue by Sgtwok** [HaloSpaceStation/HaloSpaceStation13#1555]
#### Description of issue
As it stands the URF only has 6 grunts spawns, a commander spawn, eight URFC spawns, and a URFC officer, this is in sharp contrast to.. Well.... Infinite spawns for the marines.

#### Difference between expected and actual behavior
The marines have infinite spawns, and there are staff members who still believe URF spawns are infinite.

#### Steps to reproduce 
Have Six insurrectionist grunts in game
Attempt to play as one
Realize the role is no longer on the roster.

#### Specific information for locating
Just try and join as an insurrectionist grunt when there's six of them.

#### Client version, Server revision & Game ID
16438ad1f0e8a653ca7ef740cf539b04568be925 - alpha - 2019-05-24

#### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by BDpuffy420** [comment]
#1608
