### ISSUE TITLE
E-Barricade Boogaloo (Blocking the back)

### ISSUE THREAD

**Issue by DronzTheWolf** [HaloSpaceStation/HaloSpaceStation13#1565]
#### Description of issue
Energy barricades seem to be a bit broken at the moment, if you stand behind it/on the tile it's on and destroy it, it will still block your path.

#### Difference between expected and actual behavior
When destroyed, it should no longer block your path.

#### Steps to reproduce 
Stand behind an energy barrier, destroy it, try to move past.

#### Specific information for locating

Energy Barricade

#### Length of time in which bug has been known to occur
Multiple, and as different species.

#### Client version, Server revision & Game ID

Most recently tested the bug in:
Client Version: 512
Server Revision: aed2e7cef5ae6283067ee315dda4498b45307813 - alpha - 2019-05-26

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this]

**Comment by caelaislinn** [comment]
Fixed #1646
