### ISSUE TITLE
NPC trade hub maps

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#157]
These can be filled with placeholdery type rooms and content. All they need are a few rooms with magic lighting, infinite power and basic NPCs so that other NPCs can fly up and dock to 'pretend' to trade, or hang around in the bar "chatting."

**Comment by Flaksim** [comment]
@caelaislinn Is this still needed? the asteroid colony I mapped out can perfectly fill this purpose if the right NPC's are placed on it.

**Comment by caelaislinn** [comment]
We could use that or the Geminus. The idea back then was just to stimulate some ideas for mapping
