### ISSUE TITLE
Spawning as UEG AI on Geminus spawns as a real person

### ISSUE THREAD

**Issue by Allakai** [HaloSpaceStation/HaloSpaceStation13#1570]
#### Description of issue
When spawning as the UEG AI it causes the player to spawn as a living carbon being.

#### Difference between expected and actual behavior
Not sure how to answer, expecting to spawn as AI in the actual core, spawns as an actual character.

#### Steps to reproduce 
Pick UEG AI, even set to max, choose spawn as AI, spawn on Geminus city bus as an actual carbon being

#### Length of time in which bug has been known to occur

Unknown, only recently discovered by myself.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 672b4735df371374a92279331cd3a346c8bbfc3b - alpha - 2019-05-30
Game ID: b1v-aki6
Current map: Geminus City

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by bloxgate** [comment]
I'll note that their assigned role is set to UEG AI and they seem to have their AI name selected as their name.

**Comment by BDpuffy420** [comment]
I believe this has been sorted since the addition of @X0-11  AI
