### ISSUE TITLE
[BUG] colonist doctors do not have access to hospital

### ISSUE THREAD

**Issue by CdrRiley** [HaloSpaceStation/HaloSpaceStation13#1575]
when you spwan in as colonist /ive chosen clonist doctor, you cant enter any of the medical rooms like sugery or any other room wich requiers medical acces, the normal colony ID doenst comes with it please fix otherwise for teh futrure rounds are gonna be proplems

**Comment by BDpuffy420** [comment]
Not a bug, go to city hall to get access from the mayor
