### ISSUE TITLE
Covenant ODPs fire on their shuttles

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#1577]
See title. Might be a mapping issue with navchips, or an overmap issue with the IFF not spawning in before the shuttles are detected as a threat

**Comment by bloxgate** [comment]
Perhaps this is related to the helm crashes?

I've noticed that they seem more likely to occur if a shuttle has recently spawned in.

**Comment by caelaislinn** [comment]
Fixed #1646 Covenant base was removed
