### ISSUE TITLE
[SUGG] making stais bag have more then 1 use 

### ISSUE THREAD

**Issue by CdrRiley** [HaloSpaceStation/HaloSpaceStation13#1585]
basicly makes the stais bags have unlimted uses 

was discuse in embadssy and got an okey from the majory of diplomats
placeholder here

**Comment by bloxgate** [comment]
After further discussion and a small poll in embassy, we're going to be porting rescue bags from Bay and allowing those to be re-used.

**Comment by CdrRiley** [comment]
just to make sure those works excatly same as a statis bags only they are atmos proof?

**Comment by bloxgate** [comment]
No. Please refer to the discussions in embassy and unsc_barracks. We're going to end up with something very similar to how the rescue bags currently work on Baystation.

**Comment by CdrRiley** [comment]
your gonna have to define teh exacts specs on the resuce bags csue i havnet been on bay and never seen resuce bags so please write down the difrentc betwen those those

**Comment by CdrRiley** [comment]
but why closed ?
