### ISSUE TITLE
[bug] cant put peole into ONI cryo pods

### ISSUE THREAD

**Issue by CdrRiley** [HaloSpaceStation/HaloSpaceStation13#1589]
<!

cant put sombady into ONI cryo pod into base,  not via drag and drop or grab intent

**Comment by bloxgate** [comment]
Hi, could you please put in all the required information from the template that comes up when you create issues?

**Comment by CdrRiley** [comment]
hi all the info is there provided

**Comment by BDpuffy420** [comment]
Re-make this issue and follow the template to the letter
