### ISSUE TITLE
3 in  1 github

### ISSUE THREAD

**Issue by CdrRiley** [HaloSpaceStation/HaloSpaceStation13#1613]
1 First point mapping. add a light to deck 2 starboard medbay cryo area thank you

2 make it so taht passengers insde a pelican cant drop the tanks or hogs from it 

3 move embadys to github

**Comment by X0-11** [comment]
For the sake of issue tracking, please use the default template and make each issue seperate.

**Comment by bloxgate** [comment]
Also, number 3 is infeasible. GitHub is not designed for the types of discussion embassy is used for.

**Comment by CdrRiley** [comment]
number 3 was meant as ajoke

and no templte im gonna use
fuck the system

**Comment by CdrRiley** [comment]
also how is the templete gonna help ?
