### ISSUE TITLE
Geminus Mining Sectors

### ISSUE THREAD

**Issue by DronzTheWolf** [HaloSpaceStation/HaloSpaceStation13#1619]
#### Description of issue
Geminus underground, surface, and roof levels start vented, and when you break a rock by mining, it produces an atmosphere-free tile.

#### Difference between expected and actual behavior
Being a planet, one would expect atmosphere, this seems more of a mapping issue than an actual bug.

#### Steps to reproduce 
Literally just go mining

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by caelaislinn** [comment]
Fucks sake

**Comment by caelaislinn** [comment]
#1657
