### ISSUE TITLE
Desynched Console

### ISSUE THREAD

**Issue by Max-023** [HaloSpaceStation/HaloSpaceStation13#1620]
#### Description of issue
Squad console 3 on the Bertels bridge does not work. It gives you the camera tool, but the interface doesn't change and you cannot view the squad.

#### Difference between expected and actual behavior
Consoles 1 and 2 behave regularly and allow you to see the squad members through the tachuds.

#### Steps to reproduce 
Link a member to the squad.
Try to view them
No success

#### Specific information for locating

It is a squad manager console.

#### Length of time in which bug has been known to occur

I cannot say, but I found it recently today.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by X0-11** [comment]
Is the correct squad linked to the squad console and does the squad manager actually have anyone assigned?

**Comment by Max-023** [comment]
It is, indeed. I checked the manager's members and I cannot view those who are linked. Both the tachud and person were linked.

**Comment by X0-11** [comment]
The console itself was also linked to the manager?

**Comment by Max-023** [comment]
Yep. I tried to link it twice after it wouldn't work.

**Comment by X0-11** [comment]
Hm. Alright. If this happens again, please note on this issue.

**Comment by caelaislinn** [comment]
This sounds like it could be a mapping issue?
