### ISSUE TITLE
Rat-Based URF Equipment

### ISSUE THREAD

**Issue by Caelum464** [HaloSpaceStation/HaloSpaceStation13#1631]
New science has reached the URF. In a desperate plea to defeat the oncoming threat of walking tanks and covenant shields, they have developed a weapon in secret.

Synthesizing together Rats with Monkeycubes, the URF has created a weapon more dangerous then anything seen before. Tools of war. Destructive machines who only know how to do one thing- Go for the eyes.

Ratcube - A cube like a monkeycube, spawns a simplemob Rat when water is applied. Can be stuck in landmines, perhaps, for a dangerous surprise?

Ratbombers- A cage that can be held in the hand. When primed, you have 5 seconds before it releases a rat with a bomb strapped to it, which will run towards the nearest mob using Simplemob AI and explode violently. 

Other Rat Projects? Maybe... Rat Genomes? EMP Rats that constantly emit an EMP around them, causing shields and radios to break? Controllable Rats with Cameras on their heads?

The possibilities are endless. This is a dead serious suggestion. Rats could improve the fun and enjoyment for the URF and bring the hell that is this dangerous creature to the surface world.

**Comment by DexterDude** [comment]
what the fuck

**Comment by CdrRiley** [comment]
chotto matte    i know the urf is desparte and shit but taht is kinda welp

**Comment by bloxgate** [comment]
Alright, I have to ask regardless of your closing sentences there. Is this a meme?

**Comment by caelaislinn** [comment]
Probably not as goofy as some of those ideas, but the Geminus innies need a way to safely traverse the underground with the giant rats. Some ideas we discussed were rat musk which make them friendly to you when you are sprayed with them

**Comment by Caelum464** [comment]
That sounds... Disgusting.

But it works.

Also no, it's not a meme. Though I would not be offended if you took it as one!
