### ISSUE TITLE
Spartan armor incorrect

### ISSUE THREAD

**Issue by Max-023** [HaloSpaceStation/HaloSpaceStation13#1638]
#### Description of issue
In OPRF and whenever admins spawn Spartans, female Spartans get the male set, creating some covering issues. Because of this, from the front the hips are visible, and from the sides the boots are visible.

#### Difference between expected and actual behavior
The female sets created by Ollie cover the female sprites accurately, as shown when he first showcased the armor sets. They do not expose the hips and boobs and are much more SFW than the male sets.

#### Steps to reproduce 
-Spawn as a Spartan in OPRF
-Try to keep it in your pants when you turn

Or

-Watch admin spawn Spartan
-Try to keep it in your pants when they turn

#### Specific information for locating

This is likely because whoever implemented the Spartan armors did not create female sets, for both the suit and undersuit. Cloning and making the female sets should fix the issue.

#### Length of time in which bug has been known to occur

Ever since implementation. I have brought the issue up before in gitbus when the armor first debuted, James even reacting to it, but it has sense been unchanged. Now I am posting the issue here to ensure it is better documented.

#### Client version, Server revision & Game ID

Current

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by caelaislinn** [comment]
This is me taking shortcuts and not wanting to complicate Spartans when I added them. It would take a partial rewrite of the item overlay and appearance code to allow separate sprite sets by gender which I didn't have the time for
