### ISSUE TITLE
Ultra spawns on Geminus Arrivals Shuttle

### ISSUE THREAD

**Issue by PantasTheDank** [HaloSpaceStation/HaloSpaceStation13#1639]
#### Description of issue

Sangheilli Ultra spawns on Geminus Arrivals Shuttle during Invasion and Revolution

#### Difference between expected and actual behavior

Ultra shouldn't be spawning on Geminus to begin with 

#### Steps to reproduce 
Be whitelisted for the Covenant,attempt to spawn as Ultra, be spawned on Geminus

#### Specific information for locating

None

#### Length of time in which bug has been known to occur

Apperently since Ultra was enabled

#### Client version, Server revision & Game ID

512
2974dce72031fee5d8da37c933b4875844fb59c7 - alpha 
b1N-c8v4
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Max-023** [comment]
Wait.....how did you test ultra in revolution?

**Comment by PantasTheDank** [comment]
> Wait.....how did you test ultra in revolution?

someone was able to spawn as one

**Comment by Max-023** [comment]
Well the ultra shouldn't even be spawning, so that isn't necessarily an issue for the ultra as it is for the revolution gm.

**Comment by PantasTheDank** [comment]
> Well the ultra shouldn't even be spawning, so that isn't necessarily an issue for the ultra as it is for the revolution gm.

Whatever it is, it should be fixed
