### ISSUE TITLE
Update Byond Hub and roundstart info to be generic Halostation blurb

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#164]
We don't want copycats to be confused with us for the official HS13 server, and also we want to make sure we're distinctive from the default Bay12 blurb.

**Comment by bloxgate** [comment]
I'll assign myself to this since I seem to be doing some of this sort of stuff as part of [Cicero's](https://gitlab.com/bloxgate/cicero-bot) integraton.

**Comment by BDpuffy420** [comment]
I'm guessing this was taken care of?

**Comment by bloxgate** [comment]
I believe so. I'll need to remote in and double check. But I'm assuming since Cicero shows the right name its good.

If we want to go live on the hub though, there is a small define change we'd need to make in code.dm

**Comment by BDpuffy420** [comment]
Alright cool.
