### ISSUE TITLE
Mechs don't go down

### ISSUE THREAD

**Issue by TYoung86** [HaloSpaceStation/HaloSpaceStation13#1644]
#### Description of issue

Mechs appear to be able to traverse stairs up, but not down.

They also do not appear to fall when walking over any z-level transition (ledges of roofs for example).

#### Difference between expected and actual behavior

Expecting mech to traverse stairs down, or fall.

#### Steps to reproduce 

Spawn Hrunting. Walk up stairs, attempt to walk down. Continue walking to roof, attempt to walk off.

#### Specific information for locating

ONI site on Geminus

#### Length of time in which bug has been known to occur

? ? ?

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 2974dce72031fee5d8da37c933b4875844fb59c7 - alpha - 
Game ID: b1Q-a7p0
Current map: Geminus City

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by BDpuffy420** [comment]
#1805
