### ISSUE TITLE
Suggestion: Set a version of Slayer on one of the Geminus Overmap locations.

### ISSUE THREAD

**Issue by Nightspark43** [HaloSpaceStation/HaloSpaceStation13#1662]
I recently had an idea of having Slayer set in a map on the Geminus Overmap, perhaps either Geminus itself or the new UNSC station, flavored potentially as either a Simulation for the Spartan Program, or an invasion by a band of Sangeili, or even a combination of both depending on team setups.

That way, if the population is too low for Invasion or Revolution, we could either force, or vote, for the mode instead of having to switch maps, which seems to kill the population each time it happens, possibly helping to alleviate some of the population and gamemode issues that have been cropping up.

**Comment by BDpuffy420** [comment]
This wouldn’t change anything, people who don’t like playing slayer won’t stay because it’s on Geminus. Map switching takes less than 30 seconds

**Comment by caelaislinn** [comment]
I requested this, it wouldn't be a hard change and allow a little extra gameplay variation that could be fun
