### ISSUE TITLE
Kig'Yar Commando spawns on geminus, Murmillos spawn on Geminus too

### ISSUE THREAD

**Issue by PantasTheDank** [HaloSpaceStation/HaloSpaceStation13#1666]
#### Description of issue
Title

#### Difference between expected and actual behavior
Commando should spawn on the Covenant's Ship, Mumilos were disabled if I am correct

#### Steps to reproduce 

make a kigyar character, try to spawn as kigyar commando or murmilo

#### Length of time in which bug has been known to occur
N/A

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Nightspark43** [comment]
Actually, T'vaoan Minors and Majors were disabled to leave Murmillos and Commandos if I recall.
