### ISSUE TITLE
Add new fusion reactor using the custom sprites

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#168]
We have an existing reactor, but the mechanics don't fit with the sprites so we may as well tweak the functionality to make a slightly different one. It will be interesting to have a couple of different methods of power generation. The one for this issue will probably be independant of a much larger multitile central reactor I'm planning to add later.

**Comment by DoctorOctopusTheOctopi** [comment]
Issue is almost two years old and I'm pretty sure we already updated the fusion reactors at least twice over.
