### ISSUE TITLE
Quality Analysis pass on ship destruction mechanics

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#1701]
Ship destruction mechanics are unintuitive and unpredictable. The main problem is that there is a variable amount of damage which needs to be applied before the ship is destroyed, as ship hull segments are typically unevenly spaced around the ships - but even if they were evenly spaced when overmap projectiles enter the zlevel they are randomly spread around. 

Direct targetting isn't the solution as that will reduce the chance of destroying enough hull segments. 

I think the solution is to track the damage of overmap projectiles that collide with the ship sprite, and have them subtract from ship health directly. There can also be damage applied to turfs in the ship directly, but that wouldn't affect ship destruction. It's a lot simpler and more reliable.

**Comment by X0-11** [comment]
I feel like the threshold is just too high. Making it rely on the overmap projectile's damage will unbalance things due to the overmap projectile's damage currently being used for player-to-npc ship combat, with NPCs being much, much easier to kill than a normal ship.

**Comment by BDpuffy420** [comment]
This has since been addressed !
