### ISSUE TITLE
Boots Are Too Loud

### ISSUE THREAD

**Issue by Max-023** [HaloSpaceStation/HaloSpaceStation13#1717]
#### Description of issue
Marines were given boots that produce a sound whenever they move around, a balls to the wall tactic of making the enemy well aware that they are there and they are wanting blood, but for the more careful Marines, this is just a boon.

Suppressors become pointless as now it is impossible to be stealthy. Everyone can hear you coming before you are even on screen, even if your intent is to be quiet.

Making it so walking mutes the sound completely and maybe toning down the range of its sound should help as now it is easier to move around without scouts having to not risk anything and still get troop movements.

#### Difference between expected and actual behavior
>Marines stomp around to incur fear as they march through the enemy
>Instead Marines are heard way out and enemies prepare an ambush
>Marines stomp right in to the ambush
>Enemies chase down the survivors because they are still stomping as they run away

#### Steps to reproduce 
The sounds are tied to the VGZ7 so wearing them causes this.

#### Specific information for locating

See above.

#### Length of time in which bug has been known to occur

Ever since it was merged.

#### Client version, Server revision & Game ID

Current

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Max-023** [comment]
Oh and Sec guards don't have the same sound for walking, so they are still silent even though they use reinforced Marine gear.

**Comment by bloxgate** [comment]
Closed by #1729
