### ISSUE TITLE
Spirit Doesn't Have A Gunner Seat

### ISSUE THREAD

**Issue by ghost** [HaloSpaceStation/HaloSpaceStation13#1718]
#### Description of issue
Title. No gunner seat for the Spirt, therefore making it unarmed as the pilot can't use it.

#### Difference between expected and actual behavior
There should be a gunner seat for the spirit cannon

#### Steps to reproduce 
Get in a spirit
Attempt to enter gunner seat
Fail
Enter pilot seat to see if it gets a weapon instead
Observe that weapon is not given

#### Length of time in which bug has been known to occur
Indeterminate, several weeks at least

#### Issue bingo
- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this]

**Comment by bloxgate** [comment]
Just for clarification, is it giving you an option to try and enter the gunner seat? Or is there not one?

**Comment by ghost** [comment]
The gunner seat has been used successfully in a few rounds now, and the issue hasn't been reproduced since it was reported. Gonna close this for now seeing as the bug can no longer be reproduced.
