### ISSUE TITLE
Loadout is broken.

### ISSUE THREAD

**Issue by DronzTheWolf** [HaloSpaceStation/HaloSpaceStation13#1721]
#### Description of issue
The loadout for innie, and UNSC aren't working.
Since there's nothing in the Changelog about this, I assume it is not intended.

#### Difference between expected and actual behavior
You should spawn with loadout gear.

#### Steps to reproduce 
Spawn

#### Specific information for locating

Loadouts.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by frontline03** [comment]
This happens for Sons of Eridanus too

**Comment by Max-023** [comment]
This happens to CO and XO too.

**Comment by caelaislinn** [comment]
Colonists appear to have working loadouts
