### ISSUE TITLE
NPCs Don't Shoot Each Other

### ISSUE THREAD

**Issue by Max-023** [HaloSpaceStation/HaloSpaceStation13#1727]
#### Description of issue
The NPCs do not make any attempt to shoot down ships of other factions. URF, UNSC, and Covenant vessels all just fly by each other without doing anything. The civie ships aren't being war crimed, so it is helping in some aspects.

#### Difference between expected and actual behavior
The actual behavior should involve the NPCs blasting each other. Aside from the civies, the only time the NPCs seem to fire is in retaliation. But without aggroing the ships, they refuse to fight the war that I supposedly raging on.

#### Steps to reproduce 
Just sit in an overmap console and watch them.

#### Specific information for locating

They don't say anything until they are shot.

#### Length of time in which bug has been known to occur

It has happened since last night after energy sword Sunday.

#### Client version, Server revision & Game ID

Current.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by bloxgate** [comment]
Closed by #1726

**Comment by caelaislinn** [comment]
Needs more testing

**Comment by BDpuffy420** [comment]
Confirmed they still don’t

**Comment by BDpuffy420** [comment]
was fixed
