### ISSUE TITLE
Geminus Lighting Purge

### ISSUE THREAD

**Issue by bloxgate** [HaloSpaceStation/HaloSpaceStation13#1732]
It appears we have somewhere between 2 and 3 thousand lights on Geminus.

This is extremely problematic, as it causes our CI builds to hang and often crash when attempting to process the map. It may also be related to the occasional controller crashes we've been seeing on the server.

The following have been proposed as possible solutions:
1. Remove dynamic lighting from Geminus
2. Decrease light count, but raise background light to compensate
3. Remove some Z-levels from Geminus entirely

**Comment by Max-023** [comment]
It would probably be good to make some places use god light. Removing lighting entirely hurts the stealth aspect of the game.

Perhaps decreasing the amount of street lamps could help. Make it so lamps are only on the edges of each other's light range. That could help. Making some parts of the slums have not enough lights to light up the entire thing could help too.

**Comment by bloxgate** [comment]
Should be closed by #1738
