### ISSUE TITLE
[SUGG] ONI Analyzer

### ISSUE THREAD

**Issue by Delnth** [HaloSpaceStation/HaloSpaceStation13#1740]
My idea is basically:

A big machine (64x64, 64x96 or 96x128) similar to the R&D console in many aspects, however how it functions will vary. [This is a vague idea of the design that I have in mind.](https://i.imgur.com/iddjUeV.png)

Or otherwise, two "pylon-like" thing or whatever it is called, on each side. The machine should have a few options, such as: **analyze** (teaches how to use a machine/item but DOES NOT give insight on the components and thus, the knowledge to produce a copy), **deconstruct** (teaches how to use the machine, and learns the components, thus allowing the produce every parts), **refit** (refit the object/machine to be human-friendly and compatible with human technology while still retaining all of its properties/pros, at the cost of it no longer yielding any tech upon deconstruction/analyze)

It's 10:49am by the time I write this so I'm really tired. I hope it makes sense. Can't find the words to properly describe the whole idea. It's too tech savy for me.

**Comment by caelaislinn** [comment]
#2604
