### ISSUE TITLE
Ready-up Bug

### ISSUE THREAD

**Issue by Zergrushh** [HaloSpaceStation/HaloSpaceStation13#1742]
#### Description of issue
Readying up sometimes not spawning you as chosen job.

#### Difference between expected and actual behavior
When readying up as a spartan on Redflag, it can sometimes simply do nothing after round start. Normally, you could just click unready and join, but since Spartans (among other things with  timers) cannot be joined as after round start, 

#### Steps to reproduce 
Ready up. Occasionally, it works, but sometimes it breaks. Not sure what causes it. Redflag is generally effected worse by the issue. 

#### Length of time in which bug has been known to occur

The past week or two, it's been most noticable. 

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: ebeeb179f846a7b508b547d91455e0058cc1c0a9 - alpha - 2019-07-25
Game ID: b2p-dCp2
Current map: Damaged "CCS Templar Of Light"

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by bloxgate** [comment]
Potential regression of #594?

**Comment by Zergrushh** [comment]
Seems like a different issue. I've not noticed slots being taken up randomly from it, but that's mainly due to the fact that the jobs I ready up for are only available at round start. I'll have to test and see if it takes the slot when it occurs

**Comment by caelaislinn** [comment]
This is probably the biggest issue making OPR unplayable right now, changed to critical priority
