### ISSUE TITLE
[SUGG] Weapons parts manufacture machine

### ISSUE THREAD

**Issue by Delnth** [HaloSpaceStation/HaloSpaceStation13#1751]
As the name suggest, the idea is to have machine function roughly like the exosuit fabricator. It needs R&D levels to unlock more stuff.

Levels would unlock weapon parts. Weapon parts would be used to construct a (modular¹) weapon. Components would affect many variably, such as the burst_fire (existing and toggleable or stuck on burst by default), range, possible attachments, caliber and much more.

Definitely not a feature we need right now, but I figured it'd be an interesting idea to share with the rest of the community.

¹ * Modular refers to fully customizable weaponss/armors, as seen in some codebases (armor with additional protection, etc)

**Comment by X0-11** [comment]
jesus christ no please, this is a balance hell

**Comment by Delnth** [comment]
Balance is only a matter of time. It's something that gets discussed and planned. Beside, it's just an idea and the devs can do whatever they want with it. I am merely proposing something that may or may not be fun to use, for the players. Of course, this is not warhammer, therefore sticking a brick to a pipe doesn't make it a shotgun.

Naturally there'd be some recipes that are simply not going to work.

**Comment by caelaislinn** [comment]
Partial #2604

**Comment by Aroliacue** [comment]
Stale, closing
