### ISSUE TITLE
[SUGG] Elite Jetpack sprite

### ISSUE THREAD

**Issue by Delnth** [HaloSpaceStation/HaloSpaceStation13#1774]
Title.

The jetpacks in the code have two sprites (normal and active). Normal would serve as an oxygen supply during operation in zero-g. The second sprite (active) is when the jetpack is activated and works as an actual jetpack.

As for the actual mechanic of the jetpack, I am not sure yet what would be the most convenient to be used for it. It uses anti-gravity technology but I assume too much of a hassle to code so I doubt anyone would mind if it was made an actual variant of pre-existing jetpacks.

Pictures: [1](https://vignette.wikia.nocookie.net/halo/images/9/9e/Antigrav_pack.png/revision/latest?cb=20110927182614) - [2](https://steamuserimages-a.akamaihd.net/ugc/916911015703365731/92815EB2C24DE3A12DAC40916B35C3EBAAF9F3D6/?imw=637&imh=358&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=true) - [3](https://steamuserimages-a.akamaihd.net/ugc/916911015703366159/F16ED69DFE51FC907FDF1CDF1D1B7A1BBADB50BE/?imw=637&imh=358&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=true)

**Comment by caelaislinn** [comment]
#2607
