### ISSUE TITLE
Movement Bug

### ISSUE THREAD

**Issue by Max-023** [HaloSpaceStation/HaloSpaceStation13#1802]
#### Description of issue
During a round, I was disabled halfway in the match and could not move at all, resulting in my death as the room I was stuck in was without oxygen and the pressure was crushing. After being ahealed and teleported to a different room, I still could not move, even while standing up and full health. Additionally, I could not grab others.

I could interact with my inventory, use my hotkeys to speak and use items, and spin myself my clicking on tiles, but movement itself was not working. I tried the arrow keys and WASD, toggling hotkeys multiple times, and got nothing.

All the while, when I was trying to grab a Marine next to me, I kept getting the message "You already grabbed the grab" and could not grab the Marine. This would happen even on help intent.

#### Difference between expected and actual behavior
Obviously the arrow keys and WASD should move you unless you manually change your macros.

#### Steps to reproduce 
Open a room with no oxygen while you stand in a room with oxygen and be holding a Marine while you do it.

#### Specific information for locating

N/A

#### Length of time in which bug has been known to occur

N/A

#### Client version, Server revision & Game ID

Current

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by caelaislinn** [comment]
Have you been able to reproduce this?
