### ISSUE TITLE
New map: Asteroid Mining Hauler (1 Deck)

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#181]
Just a simple map 1 zlevel map with a few placeholder rooms and small hangars. The idea is that this one acts as a sort of mobile base by flying out to asteroid fields with shuttles and EVA pods so that miners can harvest minerals and drop them off back here. Then when it's full or a shift ends, the hauler flies back to a trade station to sell or drop off the minerals.

**Comment by DoctorOctopusTheOctopi** [comment]
With the recent NPC addition we are in dire need of some NPC ships. Should anyone wish to test there hand this would be a great project to do so.

**Comment by Flaksim** [comment]
@caelaislinn Is this still needed/wanted given the current ship designs?

**Comment by caelaislinn** [comment]
More NPC ship designs are needed. I've heard a couple of players mention its very easy to metagame the innie ship because its obvious

**Comment by BDpuffy420** [comment]
We have this somewhere.
