### ISSUE TITLE
[SUGG] making r&d great again

### ISSUE THREAD

**Issue by enkidienne** [HaloSpaceStation/HaloSpaceStation13#1810]
First of all, i am not a coder, dev, spriter or anything even close.

I am a heavy player of r&d and i wish for it to be actually useful. Here is just a few suggestions to try to improve it:

1. R&D exclusive weapons: weapons that are only obtainable using r&d. Those weapons could be prototypes, new versions or even completely new weapons. Exemple, an h5g railgun.
2. Upgradable vehicle: possibilities to change certains part or even build from the ground up a vehicle. Exemple: changing the cargo of a mangoose to make it able to transport heavier loads, an mini-electromagnetic canon that can replace the turret of a scorpion.
3. Modular armor: armor that can be personalized with different upgrades. Maybe something like the mechs work, using ports and energy. Exemple: an armor with retractable blade in the arm-guard.
4. Ancient technology experimentation: experimenting on forerunner artifacts, getting techs out of  it. Exemple: using a forerunner cristal to boost a slipspace drive.
5. More buildings: additions of more constructible using boards and such. Exemple: an high-tech turret that is not a confetti maker.

That is all for the moment, feel free to correct me or to discuss about balance and other related stuff. Im hopping for suggestions so i can improve my ideas further.

-Enki

**Comment by Delnth** [comment]
I could try to code in the H5G railgun. We already have some remnants of railguns in the code, which functions weirdly. There is an ammo and capacitor factor. Ammo is a single "bullet" (metal rod, just like crossbows from what I've seen) or a magazine, while the capacitor is what provides the railgun its required punch to propel the ammo. 

I could use this code, but briefly looking over the ARC-920 description, it described as follow:

> Despite the ARC-920's lighter weight over previous models, it is still too heavy and cumbersome for general use by non-augmented personnel. [...] The rifle requires a brief charging period before firing high-explosive rounds accelerated to an incredible speed.

So. It would essentially be a spartan laser, except with less ammo (one slug), but ridiculously OP damages.

Also:

Advantage
> The railgun is extremely powerful and can kill Spartans and all but the highest-ranking Promethean Knights and Elites with one shot. It is also very accurate at short and medium distances. 

Disadvantage
> The railgun must be charged before firing, which is a disadvantage on the battlefield. It can only fire one slug before reloading and is weak against vehicles. Its lack of scope coupled with its narrow blast radius make it difficult to aim, limiting mostly to firing at stationary targets. 

Naturally, the fact that it'd be locked behind a research level and given its disadvantage, it might provide a decent balance, but this advantage will also make it unreliable on the battlefield.

**Comment by enkidienne** [comment]
That would be wonderfull, but balance is to keep in mind. I think giving it a shorter range than an actual sniper would do the balancing job?

**Comment by caelaislinn** [comment]
#2604
