### ISSUE TITLE
New map: Navy Patrol Clipper (1 deck)

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#182]
Just a small NPC crewed ship which patrols around the sector checking for smugglers or pirates. Only needs 1 zlevel as well as some placeholder rooms.

**Comment by DoctorOctopusTheOctopi** [comment]
With the recent NPC addition we are in dire need of some NPC ships. Should anyone wish to test there hand this would be a great project to do so.

**Comment by Flaksim** [comment]
I made a patrol clipper basicly, the mapfile I first did and sent to Octopus is perfect for it (small, but contains the necessary areas.)

**Comment by DoctorOctopusTheOctopi** [comment]
Good work @Flaksim #528
