### ISSUE TITLE
Merge base destruction system with ship destruction

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#1824]
This would cut down on code duplication, streamlining both systems.

**Comment by X0-11** [comment]
Is the innie base now a seperate overmap object? If so, ship destruction system would work fine without changes instead of the base destruction system

**Comment by caelaislinn** [comment]
No, it only works by zlevels. I left that part of your demolition system the same. 

The whole point of this is merging the two systems to reduce code duplication. The two systems should behave the same.
