### ISSUE TITLE
A way for vehicles to enter or exit the Insurrection base

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#1825]
Two options (why not both?): 
- Cargo elevator up to a secret factory or warehouse in Geminus
- Overland fast travel into the valley with shuttle berths.

**Comment by Flaksim** [comment]
Sounds good, I think the cargo elevator style would be best, but Elevators really need to work properly before that could be implemented, they are 50/50 reliable at best currently.
