### ISSUE TITLE
[SUGGESTION] Species-locking the Covenant Glassing Console

### ISSUE THREAD

**Issue by Stingray540** [HaloSpaceStation/HaloSpaceStation13#1831]
After discussion in the super-secret admin channel, XO asked me to post this:

Essentially what this would do is species-lock the covenant glassing console to elites and prophets. Maybe brutes as well.

The reason for this is that the covenant have an extremely unique ability to annihilate entire Z-levels with extremely minimal risk (Especially in low-pop situations), and a lot of new players do not seem to understand that it is not OK to glass certain planets without fulfilling certain factors.

The console would be able to be unlocked by those species, meaning that if an elite wants a grunt to glass a planet or shoot a ship with it, that works, but the elite would still have to take responsibility for the console by unlocking it.

**Comment by ghost** [comment]
Sounds good, enforces elite/brute/prophet oversight so randos don't glass fellow covenant, or an artifact, or something. At least not without someone authorising it first.

**Comment by loafe** [comment]
Don't forget to allow Spartans as well.
