### ISSUE TITLE
Unused Covenant Things

### ISSUE THREAD

**Issue by ghost** [HaloSpaceStation/HaloSpaceStation13#1839]
A compiled list of covenant sprites that need implementation

(Covenant/medical.dmi)
- [x] Rollerbed
- [ ] IV
- [ ] Syringe
- [ ] Beaker
- [ ] Bottle
- [x] Chemmaster (cov_mixer1)
- [x] Bodybag
- [x] Splints
- [x] Sleeper
- [x] Body scanner

(Covenant/tools.dmi)
- [X] Covenant welding mask 

(Covenant/cov_weld_worn and /cov_weld_worn_elite)
- [x] Covenant welding mask worn sprites for normal races and elites

(Covenant/internals.dmi)
- [x] Large oxygen tank
- [x] Large anesthetic tank
- [x] Large tank indicators

(Weapons/icons/Weapon_Inhands_left_elite.dmi and Weapon_Inhands_right_elite.dmi)
- [ ] elite-fitted inhands for all covenant weapons

(Icons/Covenant Weapons,dmi)

- [X] "type 12" covenant humbler for the brig 

ref: (all locations within brackets are within /halo)

**Comment by Stingray540** [comment]
As per my PR #1953 I have ticked off multiple items from this list.

**Comment by Nanu308** [comment]
Is this smth that needs to be done through mapping?

**Comment by BDpuffy420** [comment]
coding the items so they can be used for mapping

**Comment by caelaislinn** [comment]
Splints and welding mask added #2424
