### ISSUE TITLE
Plasma grenades effect bypasses walls

### ISSUE THREAD

**Issue by Delnth** [HaloSpaceStation/HaloSpaceStation13#1859]
Likely a bug. A plasma grenade "heatwave" will bypass the walls and severely injure anyone that's too close. I'd imagine a wall being capable of soaking up the damages, but that doesn't seem like the case. I know it's supposed to be OP, but not to the point of going through a rather thick and heavy wall.

The same could be said about any other grenades really, some seem to have effects that go through walls, such as frag grenades.

**Comment by X0-11** [comment]
that'll be because the damage radius of explosions use range() instead of view()

**Comment by Stingray540** [comment]
As the range of the plasma grenade has been lowered as of this comment, this issue is effectively fixed.
