### ISSUE TITLE
Change EMP effectiveness on Airlocks and Blast doors.

### ISSUE THREAD

**Issue by Flaksim** [HaloSpaceStation/HaloSpaceStation13#1864]
#### Description of issue

Currently EMP is a dice roll on taking out the locks on blast doors and airlocks.
When successful it enables anyone to open the airlock as if they had an ID.
One would expect doors in military facilities to be hardened against EMP, especially on anything featuring a MAC gun as that weapon system generates a significant EM field on its own.

If the door is not hardened however, it should disable the entire airlock, not just the lock. This would require the attacker to crowbar it the airlock open at the very least.
It currently gives a significant advantage to the side with EMP weapons (in this case covenant), as they do not need to carry other breaching supplies with them.

#### Difference between expected and actual behavior

EMP weapons currently easily open locks.

EMP weapons should either disable the entire airlock (including motors) or the airlocks should be hardened against this.

#### Steps to reproduce 

This is currently an intended feature in the game.

#### Specific information for locating
Any weapon with an EMP effect in combination with any locked airlock.

#### Length of time in which bug has been known to occur
Not applicable.

#### Client version, Server revision & Game ID
Not applicable

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by BDpuffy420** [comment]
#1868
