### ISSUE TITLE
[SUGG?] Cant Fly over NPCs 

### ISSUE THREAD

**Issue by Blackburn56** [HaloSpaceStation/HaloSpaceStation13#1876]
it would be nice if the Pelican (and in relation the spirit) would be able to fly over NPCs. instead you have to play try and squeeze your thick drop-ship around the 40 foot tall NPCs. this isn't exactly easy to do on maps like GC where your bird is usually taking up the entire street.

**Comment by CdrRiley** [comment]
fucking please fix taht

**Comment by BDpuffy420** [comment]
#1878
