### ISSUE TITLE
[SUGG] Covenant Wall deconstruction

### ISSUE THREAD

**Issue by Delnth** [HaloSpaceStation/HaloSpaceStation13#1900]
Make it more complex for a Covenant wall to be deconstructed, or better yet, make it both complex AND require covenant tools to be used.

Currently, it takes a single hit of a welding tool with harm intent to take down an otherwise stronger wall that what humanity has ever seen in the past. It doesn't make sense that it can be taken down so easily but manage to stop a volley of rockets without breaking down.

**Comment by Flaksim** [comment]
It shouldn't be that easy to take it down indeed, but it also shouldn't be made any more difficult than it is to take down human R_Walls.

It also shouldn't require covenant tools, unless the same is reciprocated for human r_walls.

**Comment by Delnth** [comment]
That's fair, I guess. Although people rarely use tools (especially the Covenant) some do know that all they need to break into the next room is one or two welding tools and a wrench. Which makes the C12 useless. And all factions have a limited of it to force a wise use of their stock.
