### ISSUE TITLE
Umbiclicals not disconnecting when away from the connected planet.

### ISSUE THREAD

**Issue by Dwarfwarrior417** [HaloSpaceStation/HaloSpaceStation13#1924]
#### Description of issue
Umbilicals can stay connected despite not being close to the planet it is connected to.

#### Difference between expected and actual behavior

I'd assume it'd auto-disconnect at a certain range. But it stays connected sometimes, if not all the time.

#### Steps to reproduce 
Do not disconnect Umbilical before you leave planet. Let it stay connected

#### Specific information for locating

Not quite sure where in the code it would be. But I'd assume wherever the code is for an umbilical's disconnect is the problem. 

#### Length of time in which bug has been known to occur

I have no idea how long it has been going on. But I know that it at least happened once today.

#### Client version, Server revision & Game ID

512 - b4a-aAHQ
81ac7c5ed1d7facacf0836e1b4d6acf30cdb84a6 - alpha -
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ x] Issue happened in a recent (less than 7 days ago) round
- [x ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by WitchKat** [comment]
Anyone know if this was implemented at any point? Regardless, working on.

**Comment by BDpuffy420** [comment]
Yeah the bug showed up after the pixel movement update, anyway good luck!

**Comment by WitchKat** [comment]
Does anyone know why lines 204 through 216 are commented out in code/modules/overmap/ships/ship.dm? ship/process() does not call break_umbilicals().

If most of that code is not needed, probably can include that conditional and break_umbilicals()?

Ya girl never used github before, will figure it out and do the thing in the next 48hrs.
