### ISSUE TITLE
Bridge does not use bullet proof glass

### ISSUE THREAD

**Issue by bloxgate** [HaloSpaceStation/HaloSpaceStation13#196]
The windows on the bridge should really be replaced by ALON windows so people can't one-shot them with a pistol.

**Comment by BDpuffy420** [comment]
This was meant for the PoA map which isn't in use ATM

**Comment by bloxgate** [comment]
No. I made this for the current map. The bridge is using reinforced windows which can still be 1-shot by the magnum.

**Comment by caelaislinn** [comment]
Map (out of date): unsc_frigate.dmm
