### ISSUE TITLE
UNSC drop pods can lock onto covenant beacons

### ISSUE THREAD

**Issue by BurnedSweetPotato** [HaloSpaceStation/HaloSpaceStation13#1974]
#### Description of issue
UNSC drop pods can lock onto covenant beacons, even when UNSC one beacons are active.

#### Difference between expected and actual behavior
UNSC drop pods shouldn't lock onto covenant drop beacons, and covenant drop pods shouldn't lock onto UNSC beacons.

#### Steps to reproduce 
Be covenant, put down your beacon and then try to deploy to the planet from a UNSC drop pod. The UNSC pod should then lock onto the covenant one, even when the UNSC beacon is active. The round it happened in some people managed to go to the UNSC beacons, while others went to the Covenant beacons.

http://prntscr.com/pybf50
#### Specific information for locating

Don't really know what to put here, UNSC drop pod, UNSC beacon, Covenant beacon...

#### Client version, Server revision & Game ID

d3028ad9223c7ae1b71b6b995b3d23ebd1adb0ce
b4h-adTV

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by X0-11** [comment]
Intended, drop pod beacons have limited timeframes
