### ISSUE TITLE
Donor Gear Spawning Issue

### ISSUE THREAD

**Issue by KKarmac** [HaloSpaceStation/HaloSpaceStation13#1977]
#### Description of issue

Joining the server as a standard UNSC Marine, which I have asked be spawned with Donor Gear, results in my donor uniform spawning on the ground beneath me, and not giving me any ID for said role.

#### Difference between expected and actual behavior

I am certain it is not intended to spawn without an ID.

#### Steps to reproduce 

Join server as a role you have listed as spawning with donor gear, notice lack of ID.

#### Specific information for locating

Check ID slot.

#### Length of time in which bug has been known to occur

First noticed 18/11/2019, encountered same issue the following day.

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: d3028ad9223c7ae1b71b6b995b3d23ebd1adb0ce - alpha - 
Game ID: b4h-dh4l

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by bloxgate** [comment]
We've recently introduced some changes to how donator spawning works. You're supposed to receive a box containing your donator equipment on spawn.

Can you confirm that there isn't a box spawning with the uniform?

**Comment by KKarmac** [comment]
No box spawns either in hand, or on the floor beneath me, it simply spawns me equipped with my donor equipment, asides my uniform, which spawns on the floor. This has happened at least twice.

**Comment by KKarmac** [comment]
https://imgur.com/a/aQCiZ9x

Third instance of this, images provided.

**Comment by bloxgate** [comment]
We've uploaded a fix for this. Could you let us know if the issue continues

**Comment by Ashvor** [comment]
Yeah, it was a simple load order error. Armor spawns and equips first, thus suit cannot be equipped after spawning. This leads to the ID not spawning because of no slot available. Has been fixed.

**Comment by bloxgate** [comment]
I'm going to go ahead and close this. Feel free to reopen if you're still having an issue
