### ISSUE TITLE
Spirit Repair Bugged

### ISSUE THREAD

**Issue by ghost** [HaloSpaceStation/HaloSpaceStation13#1995]
Destroyed spirits (possibly other covenant vehicles) can't be repaired, using nanolaminate and the tools doesn't update the repair list, meaning the vehicle never actually repairs.
- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds (not yet tested)
- [ ] Issue happened in a recent (less than 7 days ago) round (not yet tested)
- [X] [Couldn't find an existing issue about this]

**Comment by X0-11** [comment]
Should be fixed.
