### ISSUE TITLE
Malfunctioning APCs on the Light Brigade

### ISSUE THREAD

**Issue by Greg351** [HaloSpaceStation/HaloSpaceStation13#2009]
#### Description of issue
None of the functions (Cover lock, Main breaker, Reboot, etc.) on the LB APCs work.

#### Difference between expected and actual behavior
**Expected:** Using the buttons on the LB APCs does stuff.

**Actual:** Using the buttons on the LB APCs does nothing.

#### Steps to reproduce 
1. Find an APC inside the Light Brigade
2. Unlock it using a UNSC ID
3. Use one of the buttons

#### Specific information for locating

Any APC within the Light Brigade ship.

#### Length of time in which bug has been known to occur

Ever since the AI update.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 9648b1550252eb06d10449e1e8f798b510baeb15 - alpha - 
Game ID: b4s-cJ6q

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by X0-11** [comment]
#2023
