### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by WilliamWestmoreland** [HaloSpaceStation/HaloSpaceStation13#2020]
For the love of god add dark mode to the chat,tabs,and window my eyesight gets worse each round and i will eventually perish from not being able to see where my dick is 

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by BDpuffy420** [comment]
#3407 #3408 
has added this and Runechat
