### ISSUE TITLE
[Balance] LB doesn't need reactors at all - nerf SMESes

### ISSUE THREAD

**Issue by Terror4000rus** [HaloSpaceStation/HaloSpaceStation13#2037]
You may don't fuel up reactors and still have all systems nominal - just repair APCs and power cables to SMESes.

**Comment by CdrRiley** [comment]
you need reactors. unsc LB just got massive power backups but it still needs reatcors

**Comment by Terror4000rus** [comment]
> you need reactors. unsc LB just got massive power backups but it still needs reatcors

I saw 2 houred revolution round and lost 2 SMESes in aft engineering room in reclamation (still 1.5 hours or so). In both situations, we still had power. The game doesn't goes longer than 1.5/2 hours, so you don't need to fuel up reactors at all .

**Comment by CdrRiley** [comment]
still no reason to remove the reactors

**Comment by Terror4000rus** [comment]
> still no reason to remove the reactors

I'm not suggesting removal or reactors - remove some storage capability from SMESes. There is 3... 4... 5... +2 ... ;-;<r>
Many high capacity SMESes at the ship.
