### ISSUE TITLE
[Suggestion] Split up MAC room and both fore reactors rooms at LB

### ISSUE THREAD

**Issue by Terror4000rus** [HaloSpaceStation/HaloSpaceStation13#2038]
![image](https://user-images.githubusercontent.com/19491666/70832041-ad1a6480-1e26-11ea-9abf-c7e75cd9bf1c.png)<br>
If MAC section lose its power, the power at the whole fore section goes too.

**Comment by CdrRiley** [comment]
yeah tahts flaksims fult for adding 1 fucking apc to the hole section wich should be fixed cough cough

**Comment by Nanu308** [comment]
This can be closed with the Current reowrk on LB done
