### ISSUE TITLE
[Suggestion] Replace janitor room at LB with pumps storage or air generating machine

### ISSUE THREAD

**Issue by Terror4000rus** [HaloSpaceStation/HaloSpaceStation13#2039]
![image](https://user-images.githubusercontent.com/19491666/70832122-e5ba3e00-1e26-11ea-8b45-7d6cea13e10a.png)<br>
Engineers have to move pumps from fore side of the ship to others - it takes too much time.

**Comment by CdrRiley** [comment]
all honsty you might wanna just ping flaksim on mapper bus easyer then doing githubs for taht

**Comment by Terror4000rus** [comment]
> all honsty you might wanna just ping flaksim on mapper bus easyer then doing githubs for taht

I'm a developer myself and I know how difficult sometimes to remember suggestions and bug reports - so, I think here is more chances to get things done.

**Comment by X0-11** [comment]
A github issue is indeed preferred to pinging specific staff in channels

**Comment by Nanu308** [comment]
This can be closed with the New LB rework done
