### ISSUE TITLE
[Suggestion] Remove all effects from the artifact

### ISSUE THREAD

**Issue by Terror4000rus** [HaloSpaceStation/HaloSpaceStation13#2040]
![image](https://user-images.githubusercontent.com/19491666/70832222-287c1600-1e27-11ea-8f48-b7fe845fec39.png)<br>
3 covenants and 2-3 ONI were teleported to nowhere.<br>
I also saw one which generated phoron. The whole lower level was burned away.<br>
As long as the artifact has only objectively cost, such effects make its containment too unprofitable.

**Comment by X0-11** [comment]
The artifact is indeed meant to be dangerous to secure

**Comment by Terror4000rus** [comment]
> The artifact is indeed meant to be dangerous to secure

It shouldn't break your game at all - just because its too salty. Allow it emit radiation or so, but don't teleport characters around the system or generate phoron.

**Comment by X0-11** [comment]
I would recommend carefuly interacting with the artifact. After all, the job of ONI personnel is to secure and research it. It pulls from basic Xenoarch effects.

**Comment by Terror4000rus** [comment]
> It pulls from basic Xenoarch effects.

And I am suggesting to remove at least two the most griefest one.

**Comment by BDpuffy420** [comment]
Its intended and won't be removed
