### ISSUE TITLE
[Bug] LB MAC consumes power from its APC

### ISSUE THREAD

**Issue by Terror4000rus** [HaloSpaceStation/HaloSpaceStation13#2042]
![image](https://user-images.githubusercontent.com/19491666/70834316-9119c180-1e2c-11ea-827c-510caab0b81f.png)<br>
I think should consume directly from SMESes? The APC recharges very slow.<br>
_And sometimes doesn't recharges at all._

**Comment by X0-11** [comment]
It consumes it directly from the power grid. Them failing to recharge is due to machinery process controller crashes and is something we've been trying to pin down for a bit now.
