### ISSUE TITLE
[Balance] Yanme'e armor

### ISSUE THREAD

**Issue by Terror4000rus** [HaloSpaceStation/HaloSpaceStation13#2045]
![image](https://user-images.githubusercontent.com/19491666/70852848-c1b73500-1ed8-11ea-897c-360a73c0a68f.png)

Two marines had CQC with a yanme'e.
One of them had LMG, other one - assault rifle
They did... Oh, just see.
![image](https://user-images.githubusercontent.com/19491666/70852881-207cae80-1ed9-11ea-8d47-f2a21c599bc3.png)
![image](https://user-images.githubusercontent.com/19491666/70852886-2ffbf780-1ed9-11ea-8933-6c46403fe57f.png)

You cannot kill it with normal weapon.
They even didn't damaged it (has normal pulse, because no adrenalin from wounds or tramadol is in blood).

**Comment by X0-11** [comment]
You would do well to count the amount of hits. RNG is also something to consider.

**Comment by Terror4000rus** [comment]
> You would do well to count the amount of hits. RNG is also something to consider.

Not so much. It just breaks combat mechanic.
It was also hit by assault rifle, but I miss it

**Comment by X0-11** [comment]
I state that the amount of hits should be counted because the armor degredation system provides an amount of "grace shots", aka shots that are guaranteed to be blocked. As you take hits, your armor gets worse and worse. If the marines had taken damage previously, they would be at a disadvantage if the Yanme'e was at full armor thickness.

**Comment by Terror4000rus** [comment]
> I state that the amount of hits should be counted because the armor degredation system provides an amount of "grace shots", aka shots that are guaranteed to be blocked. As you take hits, your armor gets worse and worse. If the marines had taken damage previously, they would be at a disadvantage if the Yanme'e was at full armor thickness.

I don't have any "grace shots" as a marine. Alright, I can be low-tech grunt with assault rifle, but why I cannot shoot down an alien in group with outhers? Almost any alien.

**Comment by X0-11** [comment]
Variables are being adjusted due to this feedback, both in here and in discord.
