### ISSUE TITLE
[Suggestion] Add OD threshold to tricordrazine

### ISSUE THREAD

**Issue by Terror4000rus** [HaloSpaceStation/HaloSpaceStation13#2046]
LOOC  Intricate Adjustments: now everyone got 100 units of tricord

Very nice, covenant, but maybe not? :>

**Comment by X0-11** [comment]
This is likely referring to Huragok Lifeworkers. Their main and only role is to dispense medical care, and they do it without caring if it's UNSC, Insurrectionist or Covenant. Frankly, Tricord is (last I checked) easy to make. The amount doesn't really matter because the metabolisation speed is so low.

**Comment by Terror4000rus** [comment]
> This is likely referring to Huragok Lifeworkers. Their main and only role is to dispense medical care, and they do it without caring if it's UNSC, Insurrectionist or Covenant. Frankly, Tricord is (last I checked) easy to make. The amount doesn't really matter because the metabolisation speed is so low.

...Because of lags. I've played with deleting of all mobs but me - everything were fine.
And you really shouldn't fill up yourself with so much medicine, because if one will, others have to do so - less fun, more preparing and abusing.

**Comment by X0-11** [comment]
No the metabolism speed of tricord is low by default.
My point was: filling yourself up with medicine doesn't help you because all it means is it lasts longer, not heals more. A gunshot will still down you, even if one guy is on 20u of tricord and the other is on 20000.

**Comment by CdrRiley** [comment]
tricord is fine as it is no really reason to change it
