### ISSUE TITLE
[Suggestion] Vehicle lock

### ISSUE THREAD

**Issue by Terror4000rus** [HaloSpaceStation/HaloSpaceStation13#2049]
How it works:
You get in it.
You press a button.
No one can enter.

May be overriden with a screwdriver.

And maybe, add some cooldown before getting in? With visible message.

**Comment by WitchKat** [comment]
This kind of thing exists for mechs in most, if not all servers I've played on. Perhaps make an ID lock that's faction/access based, similar to APCs? Suggestion seems more concerned with keeping more people from getting in when someone's already in, I guess I care more about locking your vehicle so nobody can steal it or its contents.

**Comment by Yacobpo157** [comment]
From a gameplay standpoint, you’d be removing hijacking as a system.
Spartans could no longer hijack wraiths.
URF could no longer hijack Scorpions.
UNSC could no longer hijack Bulls.
GCPD could no longer eject a criminal from a Mongoose, thus preventing an arrest.

Maybe remove locking mechs to make things equal and fair?

**Comment by Delnth** [comment]
Hijacking a vehicle is unreliable anyway, unless you somehow manage to board the vehicle or if, by one mean or another, you manage to stand beside it for entire duration of the hijack.

**Comment by Yacobpo157** [comment]
Hijacking is quite effective in of itself, I’d actually suggest lowering the time to remove someone but keep it the same for tanks and APCs.

The easiest way is to board a vehicle in an empty seat, remove the other occupant, take the driver’s seat, and now you have a tank or whatever the vehicle may be.
