### ISSUE TITLE
Shooting a corpse in a tray does not damage or spend the bullet

### ISSUE THREAD

**Issue by jusa297** [HaloSpaceStation/HaloSpaceStation13#2050]
#### Description of issue
If you shoot a corpse with a M90 Tactical Shotgun (the player may or may not need to be SSD), and they are on a Crematorium tray the weapon fires but no damage is applied and the ammunition isn't spent.

#### Difference between expected and actual behavior
The leg should come off and the slug should be utilized, but none of these things happen.

#### Steps to reproduce 
Grab a corpse, preferably SSD and put them on a crematorium tray, then shoot them with an M90 Tactical Shotgun, slugs or shells both work.

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: 4f52bef754bf5faadf6398d3e4e1f1490cf2df08 - alpha - 
Game ID: b4I-aNBs

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Aroliacue** [comment]
Stale, closing
