### ISSUE TITLE
[Bug] MAC projectiles don't damage covenant shield

### ISSUE THREAD

**Issue by Terror4000rus** [HaloSpaceStation/HaloSpaceStation13#2051]
Everythink in topic. I mean, it doesn't damages it at all.
You cannot break the shield with anything but rockets. Even 40 hits from deck guns damage the shield to 3.2 points, but a barrage of missiles drop the shield to zero from 1 lucky hit with all rockets.
You cannot fight versus covenant at the end of round - the most of your missiles launchers and deck guns destroyed, so you cannot remove the shield and use MAC.

**Comment by X0-11** [comment]
The deck guns are intended to do little shield damage. Missles are somewhat more effective, then the MAC is the most effective.

**Comment by Terror4000rus** [comment]
> The deck guns are intended to do little shield damage. Missles are somewhat more effective, then the MAC is the most effective.

So, you are writing about "I've started local server and tested it - MAC does damage to shield and it is high"?
