### ISSUE TITLE
[Suggestion] Covenant objectives points rebalance

### ISSUE THREAD

**Issue by Terror4000rus** [HaloSpaceStation/HaloSpaceStation13#2054]
UNSC is much weaker than covenant - especially in ground/aboard combat.
Give covenant debuff for not glassing the colony and not securing the artifact - like, "UNSC reinforcement is about to arrive in this system - secure the artifact and finish heretics before it will happen (in round end)". It also would reduce delay.

**Comment by X0-11** [comment]
They lose points by not gaining the points they would if they were to do the action. Negative points are only applied in the case of defense objectives.

**Comment by Terror4000rus** [comment]
I didn't saw UNSC victory in rounds with covenant at all.
I don't like to argue - just notice that something wrong with covenant, because in 4 days I didn't saw at least minor UNSC victory (not in objectives and points - just in things like "kill the most of covies", "destroy covies ship", "don't let covies secure the artifact and evacuate it" - in each round there still many of them and the ship is intact and combat-ready even without shipyard).

**Comment by X0-11** [comment]
I'm afraid the inability to destroy the covenant ship may have been due to a bug that essentially made ship combat unwinnable for the UNSC due to covenant projectiles spawning within the hull.

**Comment by Terror4000rus** [comment]
> I'm afraid the inability to destroy the covenant ship may have been due to a bug that essentially made ship combat unwinnable for the UNSC due to covenant projectiles spawning within the hull.

I saw it only at Argentum and asteroid station
