### ISSUE TITLE
X52 seems strong - Mechs can tank multiple rockets

### ISSUE THREAD

**Issue by SovietCyanide** [HaloSpaceStation/HaloSpaceStation13#2055]
#### Description of issue
I recently saw a Durand tank a single rocket in the UNSC space elevator, I saw the tile underneath it explode, and when I examined it - It was only 'lightly damaged'. For something that can be mass produced, has an EXTREME rate of fire, and is pretty much impervious to bullets. A single mech being piloted by one person should not have the ability to tank multiple rockets. It encourages the UNSC to just rush the innie base because it's become a habit for x52 to just spam produce mechs and steamroll because their mechs are so tough. The entire game mode is unbalanced due to the fact people cannot 'rush' the x52 base, giving them a shit ton of time to produce mechs, but I've seen plenty of innies rush the MAC and use the two layered wall and hack/deconstruct in with no issues.

#### Difference between expected and actual behavior
5 random civilians shouldn't be able to hop into a mech and easily pilot it, especially since they're so tough and can tank multiple rockets. This is especially an issue on lower populations, since every single innie can be armed with a mech. On a one to one fight it is impossible to face them down, and their counter takes multiple rockets to destroy. 

#### Steps to reproduce 
Take a rocket, fire it at a reinforced mech, and see that it does minimal damage.

#### Length of time in which bug has been known to occur

Found today, just now.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Yacobpo157** [comment]
1.) An SRS is an easy and easily available counter to the mech. Last night one Marine with an SRS killed 3 mechs and their occupants. Or make flash powder. Or make an EMP grenade, which instantly disabled them and depending on how "new" HaloStation's baycode is, also ejects the occupant(s).

2.) The UNSC has four LAAG-armed Hogs, two Scoprions, two Pelicans with autocannons, and two Scoprions, along with multiple SRSes and M41s. You have a slew of counters to mechs.

3.) The issue with the rocket launcher is that it needs a buff itself, the mechs are balanced. Both the URF and UNSC rocket launcher are incredibly weak.

4.) The point of Rev and OC isn't to rush another base at 11 minutes. The URF works up to good equipment and gear and earns it over time, and then they act and achieve results. Or they don't and the Rev round ends in thirty minutes. Don't complain about them working up to a good point.


I don't see the purpose of nerfing mechs. Make mines, make tank traps, make EMP grenades, and get a Marine Scout Sniper or an ODST and you're set. Just because you have to do a little work to counter someone else's minimum of twenty minutes of grinding doesn't mean something is unbalanced or unfair.

In short: git gud.

**Comment by X0-11** [comment]
This is a large wall of text and a dig at a person's robustness just because they asked for anti armor weapons to do reasonable damage to vehicles

**Comment by SovietCyanide** [comment]
It's absolutely wonderful that you had to top off the end of these complaints with an insult directed towards players that amount to 'git gud'. You're acting extremely dismissive and I've noticed you seem to only demand more for URF, and avoid all nerfs and tweaks. It appears you don't seek balance but just more advantages for the faction. 

I also find it ironic you say 'rushing to the base is unfair and ends the round within 30 minutes' when I see SOE attach to the ODP 15-30 minutes into the round multiple times in an attempt to slipspace bomb the ODP and prevent all marines from spawning, or civvie innies hacking into the planetary MAC and bombing it immediately despite that not being your objective.

https://i.gyazo.com/2246fc4599d2a46c822b9334983117c7.png insurrection objectives here, showing that destroying the ODP is NOT an objective.

I don't find spamming mechs balanced at all, and it's become the new meta that should be fixed. Every rev round I play, I see people spawning as x52 and going completely silent, not 'rebelling' until  you guys are done grinding enough to have an overwhelming advantage. And I do find rockets need to do more against mechs or there should be a hard cap of mechs used, instead of building an army of them while doing nothing else.

**Comment by BDpuffy420** [comment]
> 1.) An SRS is an easy and easily available counter to the mech. Last night one Marine with an SRS killed 3 mechs and their occupants. Or make flash powder. Or make an EMP grenade, which instantly disabled them and depending on how "new" HaloStation's baycode is, also ejects the occupant(s).
> 
> 2.) The UNSC has four LAAG-armed Hogs, two Scoprions, two Pelicans with autocannons, and two Scoprions, along with multiple SRSes and M41s. You have a slew of counters to mechs.
> 
> 3.) The issue with the rocket launcher is that it needs a buff itself, the mechs are balanced. Both the URF and UNSC rocket launcher are incredibly weak.
> 
> 4.) The point of Rev and OC isn't to rush another base at 11 minutes. The URF works up to good equipment and gear and earns it over time, and then they act and achieve results. Or they don't and the Rev round ends in thirty minutes. Don't complain about them working up to a good point.
> 
> I don't see the purpose of nerfing mechs. Make mines, make tank traps, make EMP grenades, and get a Marine Scout Sniper or an ODST and you're set. Just because you have to do a little work to counter someone else's minimum of twenty minutes of grinding doesn't mean something is unbalanced or unfair.
> 
> In short: git gud.

This type of behavior won't be tolerated, this has been noted

**Comment by Yacobpo157** [comment]
> This is a large wall of text and a dig at a person's robustness just because they asked for anti armor weapons to do reasonable damage to vehicles

A large wall of text showing examples on how to defeat mechs, trying to discuss their issue, and then making a joke at the end. This was in no way a serious insult to the person making the report or anyone in general.

**Comment by SovietCyanide** [comment]
Yacob with your behavior it can be taken as an insult in many ways and i'm 100% sure you are aware of that.

**Comment by X0-11** [comment]
The Issue is titled "Mechs can tank multiple rockets" not "mechs are invincible".
Stick to topic, don't clog the issue with irrelevant walls of text

**Comment by Yacobpo157** [comment]
> It's absolutely wonderful that you had to top off the end of these complaints with an insult directed towards players that amount to 'git gud'. You're acting extremely dismissive and I've noticed you seem to only demand more for URF, and avoid all nerfs and tweaks. It appears you don't seek balance but just more advantages for the faction.
> 
> I also find it ironic you say 'rushing to the base is unfair and ends the round within 30 minutes' when I see SOE attach to the ODP 15-30 minutes into the round multiple times in an attempt to slipspace bomb the ODP and prevent all marines from spawning, or civvie innies hacking into the planetary MAC and bombing it immediately despite that not being your objective.
> 
> https://i.gyazo.com/2246fc4599d2a46c822b9334983117c7.png insurrection objectives here, showing that destroying the ODP is NOT an objective.
> 
> I don't find spamming mechs balanced at all, and it's become the new meta that should be fixed. Every rev round I play, I see people spawning as x52 and going completely silent, not 'rebelling' until you guys are done grinding enough to have an overwhelming advantage. And I do find rockets need to do more against mechs or there should be a hard cap of mechs used, instead of building an army of them while doing nothing else.

A hardcap on mechs for each side, as the Covenant have complained about ONI mechs in the past, is a good idea.

Rocket launchers in general should see a greater use if they're actually effective.

Durands and MK1s should still be tough, maybe have it like this in terms of armor and protection.
MK1 > Durand > Gygax > Odysseus 

Mechs themselves are holdover code and their armor values are tailored to old SS13 weapons and not to what current factions have at their disposal. A general nerf is a start but it should be specified. Maybe increase Gygax speed but decrease its armor? Slow the Durand and lower its max power by reducing a percentage of whatever power its cell can use?
And greatly reduce the armor of the Odysseus as people can just rush you can put you into a sleeper.

**Comment by Yacobpo157** [comment]
> Yacob with your behavior it can be taken as an insult in many ways and i'm 100% sure you are aware of that.

I'm sorry if I offended you, that genuinely wasn't the intent. You brought up a valid point about mechs, it's just my sense of humor.

**Comment by SovietCyanide** [comment]
> > It's absolutely wonderful that you had to top off the end of these complaints with an insult directed towards players that amount to 'git gud'. You're acting extremely dismissive and I've noticed you seem to only demand more for URF, and avoid all nerfs and tweaks. It appears you don't seek balance but just more advantages for the faction.
> > I also find it ironic you say 'rushing to the base is unfair and ends the round within 30 minutes' when I see SOE attach to the ODP 15-30 minutes into the round multiple times in an attempt to slipspace bomb the ODP and prevent all marines from spawning, or civvie innies hacking into the planetary MAC and bombing it immediately despite that not being your objective.
> > https://i.gyazo.com/2246fc4599d2a46c822b9334983117c7.png insurrection objectives here, showing that destroying the ODP is NOT an objective.
> > I don't find spamming mechs balanced at all, and it's become the new meta that should be fixed. Every rev round I play, I see people spawning as x52 and going completely silent, not 'rebelling' until you guys are done grinding enough to have an overwhelming advantage. And I do find rockets need to do more against mechs or there should be a hard cap of mechs used, instead of building an army of them while doing nothing else.
> 
> A hardcap on mechs for each side, as the Covenant have complained about ONI mechs in the past, is a good idea.
> 
> Rocket launchers in general should see a greater use if they're actually effective.
> 
> Durands and MK1s should still be tough, maybe have it like this in terms of armor and protection.
> MK1 > Durand > Gygax > Odysseus
> 
> Mechs themselves are holdover code and their armor values are tailored to old SS13 weapons and not to what current factions have at their disposal. A general nerf is a start but it should be specified. Maybe increase Gygax speed but decrease its armor? Slow the Durand and lower its max power by reducing a percentage of whatever power its cell can use?
> And greatly reduce the armor of the Odysseus as people can just rush you can put you into a sleeper.

I am open to those nerfs, like speed and armor. The only reason the initial opening was vague was just to note that the issue is present and a civil discussion can be opened. Also ONI only have/use the mechs in their vehicle bay I believe, so that is already hard capped. I've only seen one Yggdrasil used at a time, in my PERSONAL experience, this might be different for you though. From what I also saw, a rocket directly hit a durand and it was only left with light damage. A HEAT round designed to punch through tanks would mulch a single man plasteel mech, but that's getting into shockwaves and other ballistic science that doesn't translate into ss13.

**Comment by Yacobpo157** [comment]
If we apply realism, most of spacemans wouldn't be what it is.

Due to the URF needing to rely on staff to get say a Cobra or a Bison, mechs are effectively their "tanks." A 102mm HEAT round should definitely do more damage, but I'd like to test the values before we start going with real numbers for the nerf.

**Comment by enkidienne** [comment]
"lightly damaged" can range from 85% to 50%. 
A rocket will damage the circuitry of the mech.
2 rockets and a few bullets will easily take down the mech.
the UNSC have a batterie of weapons that they can use against armored units. (such as scorpion, pelican, SRS, rocket luncher, chemistry)
Mechs are hard to make, they require time, advancing r&d, mining. 
A pilot can be injuried inside of a mech.

**Comment by Terror4000rus** [comment]
1 durand can destroy the scorpion.
Scorpion need 5-6 hits to take it down. If don't miss. And the mech still can gun it down faster.
I was gunner and shoot it myself.
<details>

![image](https://user-images.githubusercontent.com/19491666/70870812-93198700-1fca-11ea-8c4c-9402f289ee3b.png)

</details>
