### ISSUE TITLE
[Balance] Covenant and UNSC, round 2

### ISSUE THREAD

**Issue by Terror4000rus** [HaloSpaceStation/HaloSpaceStation13#2064]
<details>
:^)
</details>

### Guns
Covenant:
<details>

![image](https://user-images.githubusercontent.com/19491666/70886337-d5b08300-200d-11ea-8b7f-7644485a9aff.png)
</details>

UNSC:

<details>

![image](https://user-images.githubusercontent.com/19491666/70886366-eeb93400-200d-11ea-9273-8e3876a0120f.png)
![image](https://user-images.githubusercontent.com/19491666/70886386-f678d880-200d-11ea-86c9-79ed0b594e7d.png)
Not the best example, but since I showed every gun but main...
![image](https://user-images.githubusercontent.com/19491666/70887143-b581c380-200f-11ea-80f2-2ef529c9405d.png)

</details>

`At my opinion`, covenant has much dispersed weaponry.
It means that they have less chance to get a lucky missile or MAC shot to get the whole battery destroyed. Per contra, UNSC has very compact deck guns and missiles placement - they may lost from 2 to 3 guns.

At 1:30, usually, UNSC has only 2 MACs, no missiles at all and from 2 to 4 shots from deck guns console. Without missiles, you cannot do significant damage to the shield.

### Pods

Covenant:

<details>

![image](https://user-images.githubusercontent.com/19491666/70887304-275a0d00-2010-11ea-9cf2-f6de1b2e7a30.png)
</details>

UNSC:

<details>

![image](https://user-images.githubusercontent.com/19491666/70887313-304ade80-2010-11ea-87a5-8d2bf7d95004.png)
</details>

`At my opinion`, covenant has illogical boarding pods placement.
They should be behind blastdoors with lack of 3, 4, 5 layers of hull in front of them.
~~_Remove at least some hull, please_~~

### Hangar

Covenant:

<details>

![image](https://user-images.githubusercontent.com/19491666/70887503-bcf59c80-2010-11ea-9646-e2ade4d85ddb.png)
</details>

UNSC:

<details>

![image](https://user-images.githubusercontent.com/19491666/70887513-c0892380-2010-11ea-878d-41d2b3cad321.png)
</details>

There is no way to get out or in for a shuttle at all for covenant.
Add some force fields which block air flows there?

I can ``"fix"`` it myself with PR, but I fear someone already working on both ships and we'll have conflicts.

**Comment by X0-11** [comment]
In many cases it's assumed the exit point for vehicles is through the roof.
Adding a physical exit is stylistic preference and is in no way required. 

The boarding pods are the same. 

The placement of weapons across the entire ship is a good point.

**Comment by Terror4000rus** [comment]
> The boarding pods are the same.

There is literally 1 layer of blastdoors at UNSC and from 3 to 5 layers of walls at covenant.

**Comment by Terror4000rus** [comment]
> In many cases it's assumed the exit point for vehicles is through the roof.

In mechanic it means 2 layers additional layers of armor. Do so to UNSC then? There is some floor strapes in hangar - there may be "underfloor airlock".

**Comment by X0-11** [comment]
Apologies, I meant the statement above that applied to boarding pods too

**Comment by Terror4000rus** [comment]
> Apologies, I meant the statement above that applied to boarding pods too

> Do so to UNSC then? There is some floor strapes in hangar - there may be "underfloor airlock".

**Comment by X0-11** [comment]
Airlocks are suprisingly resistant to hits and2 tiles of armor wouldn'd do anything due to the main ship weapons having 2 tiles of penetration

**Comment by Terror4000rus** [comment]
> Airlocks are suprisingly resistant to hits and2 tiles of armor wouldn'd do anything due to the main ship weapons having 2 tiles of penetration

Usually, MAC shoots faster than missiles reach the target and break its shields - and, due current mechanic, MAC doesn't damages shield (shots wasted). But MAC shooting cooldown takes more time (at server. At local I can run between MACs and fire them without any cooldown from lags) than reloading of one missiles pod.

I can understand why there drop pods within layers of hull - it would be stupid to place them as boarding pods, IMHO. But not shuttles or boarding pods.

**Comment by X0-11** [comment]
Suggestions are no longer relevant to new system
