### ISSUE TITLE
Yanme'e Balancing Tweaks

### ISSUE THREAD

**Issue by SifMunaDCSS** [HaloSpaceStation/HaloSpaceStation13#2066]
Drones have had a battery of changes, fixes and nerfs in the short time following their introduction. Most of these are entirely merited, such as disallowing movement through doors, windows and the like, along with reducing the transparency so they're easier to notice and subsequently hit. They've also had their armor and shields reduced, and already take more damage than a Kig-Yar. Combined with the slowdowns, it's lead to the situation where many Drone players have resorted to picking up a scoped weapon and sitting beyond visual range. They're too slow to risk fighting at closer ranges without instant death, and the flight makes them immune to return blindfire. It's a fairly cheesy strategy in my opinion, and I'd like to present some theoretical tweaks to improve drone gameplay and make for a more interesting fight.

1. Disallowing or otherwise limiting scoped weapons. Drones aren't known for being snipers, nor are they ever seen using any precision weapons in any of the games. I'd propose either locking the species out of such weapons, or simply disallowing use of scopes when in flight if possible. This would both encourage more hit and run tactics from drones, while introducing scoped weapons as a counter to their advances, forcing them to flank or otherwise get in range.

2. Second Change: Increasing Drone mobility or durability. Drones may be the flimsiest out of any race on the server, which would be fine if it weren't for the fact they're now slow enough that their one saving grace, flight, is mitigated as players learn they have to click on the sprite. The proposal here is to either restore their original speed so their mobility actually grants some chance of evasion, or tweak their armor/damage values so they can survive more than a couple of direct hits without getting squished. This, combined with the first changed proposed would allow them to risk direct confrontation and harassment instead of sitting back with a scoped rifle.

3. Flight tweaks. This is just noting that several items you'd think they'd be able to fly over, such as flipped tables, barbed wire and certain barricades, can somehow affect a drone in flight. All the silly things they shouldn't be able to fly over have been fixed, and it doesn't make sense that barbed wire can catch a flying bug.

**Comment by X0-11** [comment]
1: This would involve snowflake code I'd rather not add
2: Sure, sounds good. Their mobility nerf was to see how much the species relied on it. Evidently, it was a large amount.
3. Provide a list of objects, I'll have to apply CanPass() modifications.

**Comment by SifMunaDCSS** [comment]
I'm at work and this is an incomplete list, but still:
Flipped tables
Energy barricades
Barbed Wire causes cuts still
Maybe normal barricades? I'll have to check when I'm home

I'll add to this as I test more and find more things.

**Comment by BDpuffy420** [comment]
There were balance changes done for them.
