### ISSUE TITLE
All doors have universal access

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#207]
Related to #192 as the new job datums are aren't fully implemented. Currently there are no job access defines and all doors on the innie base and unsc frigate have universal access. Generally we'd expect restricted access in both maps thus making hacking or other methods of forced door opening significant mechanics. 

Ideally I'd like to see access universal or near universal across both factions. In the Halo games UNSC installations were generally quite open except when in actual combat when they would be manually or remotely locked down.

**Comment by BDpuffy420** [comment]
Was tested out, caused more pain than anything
