### ISSUE TITLE
[Suggestion] ODST/Covenant Balance Changes

### ISSUE THREAD

**Issue by Caelum464** [HaloSpaceStation/HaloSpaceStation13#2073]
This was discussed heavily today in general and has become a bit of a talking point, and was generally agreed upon, even by the covenant officers and FL.

Currently, the 'power roles' (ODST and Elites/Brutes) is a bit skewed to one side at the moment. There are more Brute/Elite slots then the ODST, it's generally harder to get an ODST whitelist and the toolkits you're given as an ODST vs Elites and Brutes is skewed at best. Ya just can't beat those shields/dank health.

Some suggestions were made to balance things out and generally make things a bit better for everyone, including but not limited  too-

1. Reducing the amount of Elites/Brutes allowed at once. Poplocking the covenant races seems like a harsh step, but would reduce rounds where there's 6-8 marines, a pair of ODST, fighting 3 elites, a brute, and whatever other minor races are running around.

2. Increasing the armor value of ODST gear. This would allow them to be able to be more beefy and stack up against Elite/Brute Minors (The role that we all proposed ODST should be equivalent too). Unsure of the values on this, but needless to say, it's an interest proposal

3. The most controversial suggestion from what I've seen to developers, is an invisible shield bar for ODST. This would be 'Reflexes', which would reflect the 'shields' that ODST had in Halo: ODST. They would be an unseeable shield for ODST (As in, you couldn't see your own percentage, but would tell you when they are recharged), equivalent or lesser then an elites shielding. This is agreed by covenant and UNSC alike that it'd make ODST more of a power role, more interesting to fight, and more gratifying to kill then they currently are- And give an actual counter to the current Elites that roam the rounds slaughtering left and right!

These are just some suggestions. If you have any counter suggestions or ideas, feel free to say. Thank you.

**Comment by X0-11** [comment]
3: hard no,
2: led to elitism last time we tried it, horrible idea to try that again
1: wasn't an issue until apparently recently the unsc has had horrible population deficiencies compared to the surge in covenant population. Combined with the lack of any consistent command leaves the unsc in a bad spot

**Comment by Caelum464** [comment]
3. Any reason on the hard no here?

2. What do you mean by elitism? Couldn't the same be said by a lot of things?

1. I don't really see how this changes the suggestion. It would fix the problem. If there's enough pop to allow the amount of elites needed, then there it is, but as it stands, it's just stacks of power roles against roles that can't really level up against them.

**Comment by X0-11** [comment]
Shields are a unique feature restricted to highly advanced technology, adding "reflexes" as shields is just silly.

Whilst it can be said about a lot of things this specifically has already been tried and only served to emphasise the odst elitism issue we encountered

It doesn't change the suggestion, that one stays valid

**Comment by Caelum464** [comment]
It's highly advanced technology, yes, but from a gameplay perspective it gives that sense of 'strength' that an ODST should have. Currently, ODSTs are just marines with EVA gear, access to guns, and if you're lucky, tactics. The general idea of both of those suggestions is to make them a power role akin to the Elites, rather then just Marine+.

**Comment by X0-11** [comment]
I do believe their intent was marine +

**Comment by X0-11** [comment]
perhaps another armor value pass is needed?
For all armors, I'd say.

**Comment by Caelum464** [comment]
It's an idea. As I put in the first post, just giving a general work out to make things a bit more fun and lasting then they currently are would help, be it invisible shields, armor upgrades, or whatever needs to be done.
