### ISSUE TITLE
[Suggestion] Add Roundstart URF AI

### ISSUE THREAD

**Issue by c3329p3** [HaloSpaceStation/HaloSpaceStation13#2074]
The title, some of the main reasons for this is that:

1. The recipes of AI circuit board and AI core frame have been removed.

2. Due the first, it is impossible to make an AI.

3. Even with Admin help, aka spawning the board and frame, it simply don't works.

**Comment by Delnth** [comment]
Did you try to build it properly? If I recall correctly, once you have the core, it goes as follow:

Wires
AI Board (may come first before the wires, unsure)
MMI/Posibrain
Reinforced Glass
Screwdriver

**Comment by c3329p3** [comment]
Yes, I did.
