### ISSUE TITLE
[Bug] The artifact doesn't counts as secured as ODP

### ISSUE THREAD

**Issue by Terror4000rus** [HaloSpaceStation/HaloSpaceStation13#2075]
![image](https://user-images.githubusercontent.com/19491666/71060427-015f7480-2198-11ea-8d97-290d2faeb790.png)
~~No one reported about it because it's the first UNSC major with secured artifact I think~~

**Comment by BDpuffy420** [comment]
Normally it's due to people placing the artifact into a closed locker
