### ISSUE TITLE
[SUG] Marine Utility Caps

### ISSUE THREAD

**Issue by SuckMySocks** [HaloSpaceStation/HaloSpaceStation13#2084]
Lately there have been a few complaints about how it’s to hard to tell a regular marine from a Platoon sergeant/leader.
With the issue of lack of proper leadership cropping it’s head up once again, I suggest a very minor change.

 Utility Caps.

This may seem like a pointless change, but personally I believe that it could help with an all to common issue for the UNSC; visually being able to point out your superiors while in the heat of combat. 

Adding the Utility Cover will make NCO’s more noticeable, help with command and of course the obvious, looking like a badass green mean killing machine.

Stat wise, I suggest they get the same/similar to the regular marine helmet. (So they just don’t outright die when getting smoked in the head. These heretics put Titanium-A in their caps!) 

If this gets approved then I’ll probably try to sprite up a utility cap.

**Comment by BDpuffy420** [comment]
#3220
