### ISSUE TITLE
[BUG] UNSC Defenders attacking ONI Researchers and Orions

### ISSUE THREAD

**Issue by Yacobpo157** [HaloSpaceStation/HaloSpaceStation13#2088]
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by X0-11** [comment]
This is an issue with job settings correctly defining a job as "unsc"

**Comment by Yacobpo157** [comment]
Gotcha, just wanted to make sure the dev team was aware. Thanks.
