### ISSUE TITLE
[SUG] Allow for SOE, URF, and ODST armor to have two storage slots like Marine armor.

### ISSUE THREAD

**Issue by Yacobpo157** [HaloSpaceStation/HaloSpaceStation13#2089]
#### What do you guys think?

**Comment by X0-11** [comment]
ODST and SOE armor is already buffed, this feature is relegated to marine armor due to the upsides already present on the other armors.

**Comment by 5crownik007** [comment]
Also URF Tactical armour has _four_ slots of storage

**Comment by Nanu308** [comment]
isnt the buff between marine and ODST armor neglieble at best? Its a WL role so why not just hand it over as a QOL, Its also gonne help against insta taking off armor and reequiping a new set

**Comment by X0-11** [comment]
I'd only accept this as a full cross faction buff

**Comment by Nanu308** [comment]
Go Ahead gamer, I think it will be a QoL change overall

**Comment by Aroliacue** [comment]
Added
