### ISSUE TITLE
[BUG] On Rev rounds, the Asteroid Listening Post doesn't spawn on the overmap.

### ISSUE THREAD

**Issue by Yacobpo157** [HaloSpaceStation/HaloSpaceStation13#2090]
#### Upon the round start, while the Asteroid Listening Post would normally spawn near the SOE ship, however during a Revolution round I presume it isn't enabled. I'm not sure if it's intentionally disabled or that it just wasn't added to the gamemode.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by X0-11** [comment]
Intended
