### ISSUE TITLE
[BUG] URF Capital Ships Mapping Errors

### ISSUE THREAD

**Issue by Yacobpo157** [HaloSpaceStation/HaloSpaceStation13#2096]
#### Before I start, the ship itself is fantastic. Looks great, super practical, just a couple issues and then a recommendation.
1.) There is no ship requisition console. There's a _shuttle_ requisition console which spawns the old Innie.Ship transport prior to this update, but the URF currently lack any way to spawn the new ships.

2.) There's a significant power issue aboard the ship, specifically an unknown 250kw drain that we couldn't identify during the first round. Because of this, we constantly lost both comms and power. And eventually the ship suffered a complete power failure.

3.) In the armory, there's 3 SOE vendors except none of them are weapon vendors, just clothing vendors. Maybe replace these with racks with basic URF armor and clothing?

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Delnth** [comment]
Have you tried disabling one of the two SMES? Shouldn't be a problem when you have two fusion reactors but still, might be worth a try.

**Comment by X0-11** [comment]
Sorry for placing the wrong console, I've done that twice now. Didn't catch this one in testing.
