### ISSUE TITLE
[BUG] URF Objectives Errors

### ISSUE THREAD

**Issue by Yacobpo157** [HaloSpaceStation/HaloSpaceStation13#2098]
#### At round end, the "Protect the Rabbit Hole base" objective counts as failed, even though the capital ship remains safe. The URF objectives could do with an update anyways, there was an effort to do this with the HISC update but that never came.
1.) Update the broken objective to account for the URF Liberator and not the non-existent base.

2.) Add some objectives like ending the round with (X) money or capturing Marines or having a certain faction rep score or even taking the artifact or something.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by X0-11** [comment]
The broken objective should be fixed now.
