### ISSUE TITLE
[SUG] Covenant species language colors

### ISSUE THREAD

**Issue by Sgtwok** [HaloSpaceStation/HaloSpaceStation13#2104]
Server Revision: c304438e3d7291a5ded6f6cf899b8805d95db059 - alpha - 

After getting told to by XO, I'm suggesting that other species, while speaking a language other than sangheili, have a different color for their language, so that other members of their species know they are speaking it instead of sangheili.

**Comment by caelaislinn** [comment]
Which colours would you suggest?

**Comment by Sgtwok** [comment]
Blue for unggoy, dark orange for Ruuhtian's Ruuht, red for T'vaoans, dark grey for JIralhanae, the yanme'e need no color thanks to their language speech being a listed hivemind.

**Comment by BDpuffy420** [comment]
#2255
