### ISSUE TITLE
[Suggestion] Make rocket launcher reloading less clunky

### ISSUE THREAD

**Issue by Joe44445** [HaloSpaceStation/HaloSpaceStation13#2136]
re do Rocket Launcher reloading so that the spent Rocket Tube is ejected upon opening up the clasp without having to click on the rocket launcher again to remove it. 

This should hopefully make reloading the rocket launcher much less clunky, without severly affecting the balance of the weapon.

**Comment by Desolane** [comment]
When I redid the rocket launcher to have an actual clasp and cycle for reloading it was done in the sake of balance in the same way one would restrict the SRS to 4 shots and a slow fire rate. Power weapons will always require some amount of clunk to keep them from being OP. I'd suggest closing this unless a better idea than autoeject is given as I'm sure there could be work on power weapons, though making them smoother to use on other players isn't the answer.
