### ISSUE TITLE
[SUG] Space Hazards

### ISSUE THREAD

**Issue by UwUPlusUwU** [HaloSpaceStation/HaloSpaceStation13#2138]
![image](https://user-images.githubusercontent.com/47270986/73075020-85222480-3eed-11ea-866e-cefa06d37431.png)

AKA Space Hazards

Dust Cloud
-Adds a chance for shots to miss.
Nebula
-Adds a high chance for shots to miss.
Asteroid Field
-Damages the ship on it.
Unexploded Ordnance
-REALLY damages the ship on it.
Gravity Well
-Disables Slipspacing on it.
Ship Graveyard
-Adds a chance for shots to miss, as well as damaging the ship on it.

XO bless.

**Comment by caelaislinn** [comment]
#not sure when, sometime earlier this year
