### ISSUE TITLE
T'vaoan language consistency

### ISSUE THREAD

**Issue by ghost** [HaloSpaceStation/HaloSpaceStation13#2150]
Made on behalf of roushguy because his git account is megarino fucked

- T'vaoan commandos have humanspeak, murmillos do not. It seems to be an oversight since they're similar in status and limited in slots.

**Comment by Zergrushh** [comment]
Gonna check in with devs and see if it's fine to change. Hopefully, I won't fuck it up.

**Comment by BDpuffy420** [comment]
This was intended, only high ranks should have common
