### ISSUE TITLE
Flood QoL & Achlys Updates for XO

### ISSUE THREAD

**Issue by Desolane** [HaloSpaceStation/HaloSpaceStation13#2174]
1. Flood don't react to being shot if they can't see what shot them, this would be changed to them running towards the direction a projectile came from to find a target.
2. Flood don't react to being bumped in darkness nor do they attack with darksight, this would be changed to either shoving someone away or actually attacking when bumped into. Optimally the first one to stop friendly fire.
3. Combat form slash should inject the target with flood toxins to lead to an infection from festering wounds without needing an infection form around to complete the job.
4. Comms cut in event doesn't occur and should occur at least once per round at random timeframes starting after 15 minutes with a total open time for communication of 1-2.5 minutes max with a minimal time of 10 minutes between them.
5. Round doesn't end upon destruction of nav consoles nor marine deaths, if no marine is left alive on the Achlys with no marines left on the Dante for reinforcement, the round would end in a failure, if both nav consoles are destroyed an event would play citing instability of the slipspace drive from a lack of safety protocols to keep it in check, giving a ten minute timer before the round ends and the ship is destroyed.
6. Give the CO the ability to use the MAC to end the round via bombardment after a 30 minute lead up from the round start, again causing explosions across the Achlys and causing a round end.

**Comment by X0-11** [comment]
1: Hook into overmind processing?
2:this might need some changes for findtarget to factor in darkvis
3: easily done, OD is 27, how much per slash?
4:Will do.
5: Might be a tricky one
6: Once again, might be a tricky one.

**Comment by Desolane** [comment]
> 1: Hook into overmind processing?
> 2:this might need some changes for findtarget to factor in darkvis
> 3: easily done, OD is 27, how much per slash?
> 4:Will do.
> 5: Might be a tricky one
> 6: Once again, might be a tricky one.

1. No difference. If you attack flood from darkness or with a sniper outside 7 tiles they'll take the beating like a redheaded stepchild.
3. Hook in 1/3rd of brute damage from a type so that larger forms inject more toxin. Getting hit would cause pain effects and death eventually regardless so an early infection would be optimal.
4,5,6. If anything needs to be done with dmm fuckery do let me know and I'll be able to work through it.

**Comment by X0-11** [comment]
5: Was this tested with also retrieving the documents? The code indicates both need to be done for roundend to happen

**Comment by Desolane** [comment]
> 5: Was this tested with also retrieving the documents? The code indicates both need to be done for roundend to happen

Yes I tested all factors. The documents can be removed however as marines seem too incompetent to actually retrieve anything.

**Comment by X0-11** [comment]
The round ending worked when I tested it. Did you ensure that all relevant items were marked with the proper tag, including the delivery spot for documents?

**Comment by Desolane** [comment]
Tag: "destroythis"?

**Comment by X0-11** [comment]
I believe that was the default yes. An object needs to be marked as the object to be delivered to such as a locker or bin nearby.
