### ISSUE TITLE
[Suggestion] Require the SRS and beam rifle to be scoped in to be able to fire and add (maybe?) a small delay to scoping

### ISSUE THREAD

**Issue by BurnedSweetPotato** [HaloSpaceStation/HaloSpaceStation13#2180]
Sniper rifles have been a bit of a saltfest for both sides lately, and I believe a way to negate some of that salt would be to have it so the sniper rifles require you to be scoped in to fire. They are SNIPER rifles, not regular rifles. The SRS and beam rifles are massive anti-material rifles and it wouldn't make sense to just shoot them from the shoulder at a guy 4 meters in front of you. This fix would allow for more time to escape from the instant death trap that is the beam rifle, (and SRS for unshielded covenant) while still allowing them to put out continuous sustained fire if in a proper position. The delay is there so you cant just instantly quickscope someone repeatedly.

From my experience playing both covenant and UNSC, beam rifles are really only used against Spartans and ODSTs in close quarters, with some few exceptions down hallways on ships or at Northwind. I haven't personally seen the SRS used much other than by ONI guards on Northwind, and it is great at killing brutes, grunts, and sometimes a cocky jackal or t'voan. The CQC SRS spam has gone away in the current meta due to the accuracy thing, which is good, but since the beam rifle has 10 shots and can fire out multiple shots quickly the accuracy debuff doesn't do much and they are still able to strip a spartan's shields or drop an ODST within seconds while only standing a few tiles away and usually get the kill by swiftly switching to dual plasma rifles.

I think making the snipers have a clear and defined long range role would benefit BOTH Covenant and UNSC and encourage more teamwork by having to strip shields using a sniper and then requiring your more CQC focused people to run up, or you could really do it yourself if you wished, but it would still be risky. This is all just a suggestion and would like to hear feedback from people.

**Comment by Delnth** [comment]
If you put a delay on a weapon, not to mention that you're suggesting them to not be allowed from firing unless scoped; everyone will ditch them unless the delay and the risk are worth it. Which is rarely the case.

Snipers are already extremely inaccurate in CQC, add to that the irregular pathing of an enemy and your proximity with them, this leaves you little response time to coordinate a shot. Sometimes it lands, thanks to the RNG, but in most cases it really doesn't.

The beam rifle has a good delay between each shot (compared to the SRS) which prevent its user from spamming the 10 charges into a single enemy with little to no effort.
The SRS has less delay, but it has a smaller magazine and its avantage compared to the beam rifle is that you can reload it anytime, even on the field.

In my opinion, they are good as is. But that doesn't mean they are perfect. I'd just rather we do not make them worse or just completely useless.

**Comment by WilliamWestmoreland** [comment]
Adding a delay would not make the beam rifle completely useless it would just stop retards from using it like a bumrush spam and run away weapon.

**Comment by X0-11** [comment]
I disagree with this idea and am unconvinced that it is a better option over using more tradiitonal balancing methods

**Comment by ghost** [comment]
I feel like this is more an issue of the map than anything else.

**Comment by BDpuffy420** [comment]
Closing this as it no longer relevant
