### ISSUE TITLE
NPC ore depot/refinery

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#220]
This can be filled with placeholdery type rooms and content. All it needs are a bunch of empty storerooms, somewhere for mining transports to come in and offload and maybe a lobby or something.

**Comment by DoctorOctopusTheOctopi** [comment]
With the recent NPC addition we are in dire need of some NPC ships. Should anyone wish to test there hand this would be a great project to do so.

**Comment by BDpuffy420** [comment]
Basically this has been done on KS7
