### ISSUE TITLE
[SUG] Magboots, gripping feet.

### ISSUE THREAD

**Issue by Sgtwok** [HaloSpaceStation/HaloSpaceStation13#2202]
Seeing as to how UNSC has magboots aplenty, it's only feesible that covenant get their own, I propose sangheili ranger boots get a magboot function, and that jiralhanae get some kind of equivalent.

I also propose that, since they cannot take their natural armor off (which at the moment does literally nothing except take up a slot and protect from shards), the yanme'e, Unggoy, T'vaoans, and Ruuhtians get some kind of gripping foot function, to balance ship based boarding combat, assuming it happens.

Server Revision: af0a446c9e2df5aeac81eadffd8103646fa1065d - alpha -

**Comment by caelaislinn** [comment]
#2551
