### ISSUE TITLE
[SUG] Triwielding Fix: Or how I held an energy sword and two plasma rifles at once. How?

### ISSUE THREAD

**Issue by Sgtwok** [HaloSpaceStation/HaloSpaceStation13#2207]
Server Revision: af0a446c9e2df5aeac81eadffd8103646fa1065d - alpha -

Sangheili, Spartans, Jiralhanae, and Orions, can hold duel wielded items, and another item in their other hand since duel wielded items count as one item.

This is of course, pretty unfair, perhaps a solution could be put in place in which the other hand has to be free to fire.

**Comment by X0-11** [comment]
You require the other hand to be free when firing dual wielded weapons already.
