### ISSUE TITLE
[BUG] Unyielding Transgression comms range issue

### ISSUE THREAD

**Issue by FGRSentinel** [HaloSpaceStation/HaloSpaceStation13#2213]
#### Description of issue
For some unknown reason, the Unyielding Transgression's comms don't transmit to other objects on the system map. This means that the Covenant flagship is effectively mute.

#### Difference between expected and actual behavior
Flagships are, at present, supposed to have long-range comms outranging any other comms source. Instead, the Transgression's comms appear to have a comms range of two or less.

#### Steps to reproduce 
1. Get two Covvies and spawn in a ship.
2. Have one board the smaller ship and move to a range of 5-7 away from the Transgression.
3. Once in position, the player on the smaller ship informs the player on the Transgression.
4. The player on the Transgression says a short message over comms (ie, "hello")
5. The player on the smaller ship should either confirm they heard the response or, if they didn't move one closer to the flagship five seconds after giving the "ready" message.
6. If comms aren't heard, repeat from step 3 until comms are heard or the small ship is directly under the Transgression

#### Length of time in which bug has been known to occur
Unknown. First noticed in a round around 8-10PM EST on February 9th.

#### Client version, Server revision & Game ID
Server revision:  c4b4cfa73d6aa6a20378d2c996e669aa20597c22

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Real-MAGNUM** [comment]
Resolved in #2214
