### ISSUE TITLE
[SUG] Pinpointer Target Switch

### ISSUE THREAD

**Issue by ghost** [HaloSpaceStation/HaloSpaceStation13#2215]
Allow the artifact pinpointer to switch between artifacts, due to the introduction of multiple artifacts.

Being unable to locate the other artifact has lead to some issues in gameplay, namely accidental glassing without knowledge of the artifact's presence. The second artifact has no relevance in terms of objectives but still conflicts with rules on not glassing while it's present.

**Comment by kacyroush** [comment]
It not having relevance in terms of objectives is wrong, actually. One round, a Covenant force nicked the main artifact and skedaddled, and at round's end, ONI still got +450 points for 'securing' an artifact that the Covenant just didn't know was there. It wasn't even in the ONI base, just in the underground area of VT9.
