### ISSUE TITLE
[SUG] Spiker Improvement

### ISSUE THREAD

**Issue by ghost** [HaloSpaceStation/HaloSpaceStation13#2219]
Suggestion made on behalf of roushguy, since his GitHub doesn't work.

"The Spiker would be okay if it could embed even through armor"

While this is a rather extreme proposal in my opinion, I think it would be worth looking into whether or not spiker projectiles should have some amount of AP due to their rather low damage.

Discuss below

**Comment by kacyroush** [comment]
Finally managed to fix my github issue thanks to some googling and some finagling.

So, I think if we gave the spiker carbine either damage buff (bad idea) or an addition of AP (middle-road plan), or, in my opinion, a rare chance to embed even through armor, it would greatly improve the viability of the Spiker as a good Brute weapon.

**Comment by c3329p3** [comment]
Another problem that it haves its that you can put it on Back slot, only Belt and Armor storage. The same with the Mauler.

**Comment by X0-11** [comment]
Once armour is passsed, the spiker has a 100% chance of embedding, and the 20 damage it does do hits the cap for armour degredation anyway, so it's no less effective at degrading armour than other weapons.
