### ISSUE TITLE
[SUG]Bring back the ability to place the SAW on the back slot

### ISSUE THREAD

**Issue by Plaguewalker** [HaloSpaceStation/HaloSpaceStation13#2221]
This has been a common thing as of quite a long time to my knowledge. Back then before the original VT-9's removal you could tote the SAW LMG on your back to compensate carrying it at the cost of a backpack. Fast forward to now to my knowledge you can only carry the SRS, slung over your back as with the SpNKR (I think).  This is more of an oversight that fell to the wayside more than anything,

**Comment by X0-11** [comment]
This is intended. LMGs are intended to be unwieldy to carry due to some of the unique features they were supposed to (and now do) have

**Comment by kacyroush** [comment]
That said, if this is intended, perhaps the ability for sangheili to armor-slot the Type-51 Plasma Repeater should be removed, @X0-11, because as it stands, it's a tad imbalanced in favor of the Covenant.

**Comment by X0-11** [comment]
They cannot be placed into suit storage unless they are sangheili or spartans
