### ISSUE TITLE
Sentinel HP

### ISSUE THREAD

**Issue by CommodoSix** [HaloSpaceStation/HaloSpaceStation13#2223]
While the recent changes and additions to sentinels has turned them from laughably easy into a proper challenge,  it seems like either their HP or resistance may have been buffed too much.

A single sentinel was capable of tanking 60 sniper rifle shots, 24 pistol shots and two whole carbine magazines and was still alive afterwards. Future encounters with more sentinels resulted in similar amounts of ammo being used up if not more to finally destroy them. 

If sentinels were much more rare and didn't have the means to respawn, that could be considered balanced. But given the fact that there can be over fourty sentinels at a given time and that there are also spawners in place to produce more, it feels as though having them be both very tanky and numerous makes for rather tedious encounters.

As such I am requesting for their HP to be looked at and adjusted.

**Comment by X0-11** [comment]
Their HP is 150, with their per-hit resistance being 15 (will be lowered to 10). They regenerate 1hp per life tick (2 byond seconds iirc)

**Comment by CommodoSix** [comment]
Then there might be something wrong with how certain weapons interact with sentinels. Because it used to be 8 or 9 shots from a sniper rifle to take down a sentinel, now they seem to be able to shrug off 60 shots and still be fine.
