### ISSUE TITLE
Covenant Land Point doesn't work on VT9

### ISSUE THREAD

**Issue by kacyroush** [HaloSpaceStation/HaloSpaceStation13#2224]
Pretty much cut-and-dry. Once you fly a Spirit down to VT9, it's there to stay, you can't fly it back to the transport ship. (Might be able to fly to cruiser?)

Covenant Land Point takes you out near the waterfall west of the chasm.

**Comment by X0-11** [comment]
This is likely due to a map issue. I'll take a look.
