### ISSUE TITLE
[SUGG] Decrease player Sentinel passive healing and fire delay/damage

### ISSUE THREAD

**Issue by Delnth** [HaloSpaceStation/HaloSpaceStation13#2227]
I got the opportunity to test a player sentinel and came to realize that their passive healing is a bit too strong for the amount of DPS they can inflict to a single target. I could outheal the damages received by two sources (both with beam rifle and plasma pistols) while still being capable of retaliation (both auto and manual)

It might be a good idea to nerf the passive healing, fire delay and maybe even the damage if the fire delay is fine as is.

**Comment by X0-11** [comment]
Player sentinel passive healing is the same as normal sentinels. Unlike normal sentinels, player sentinels have an ammo cap on their weapon. The weapon also fires slightly longer bursts.
