### ISSUE TITLE
Toolbelt change

### ISSUE THREAD

**Issue by kacyroush** [HaloSpaceStation/HaloSpaceStation13#2229]
As it stands, both the toolbelt for humans *and* Covenant are near useless. Most of the tools that are needed can be carried in a bandolier, pocket, or armor pouch.

What I suggest is changing the way toolbelts handle items, from a flat seven items to a size-based approach like medkits and backpacks.

Ideally, carrying a full set of tools and, I suggest, a stack and a half to two full stacks of materials (unsure how size works for sheets, but ~75-100 sheets in total is my suggested 'size')  would be a good balance. This allows engineers to bring material for rapid FOB construction or vehicle repair, gunboat reinforcement, or the like. 

In addition, this'll make an underused item something useful again, which is always something I like to see.

**Comment by BDpuffy420** [comment]
This has been looked into!
