### ISSUE TITLE
[BUG] Human colony faction is NOT enabled.

### ISSUE THREAD

**Issue by DronzTheWolf** [HaloSpaceStation/HaloSpaceStation13#2231]
#### Description of issue

On the Changelog, it reads "enables the human colony faction on all gamemodes making the  destruction of geminus a major objective" however the human colony faction isn't actually enabled and none of the colony job spawns are opened.

--

#### Difference between expected and actual behavior

The colony jobs/factions should be available, and are not.

#### Steps to reproduce 

Try to join as Mayor/Colonist/GCPD. You cannot.

#### Length of time in which bug has been known to occur
From Wednesday, Feb 12

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: 66778ceb3b4f320290d4dca68b730f3562dc8d4c - alpha - 
Game ID: b5G-aRuz
Current map: Geminus City

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by X0-11** [comment]
Enabling the faction does not enable the jobs, nor was it supposed to. It made glassing or nuking geminus a major objective capable of ending the round.
