### ISSUE TITLE
Spartan Poplock doesn't seem to work

### ISSUE THREAD

**Issue by loafe** [HaloSpaceStation/HaloSpaceStation13#2235]
#### Description of issue
The new Spartan poplock system doesn't seem to be functional.

#### Difference between expected and actual behavior
With 7 living Covies and 4 living UNSC, there was no open Spartan spot when there should have been.

#### Steps to reproduce 

Get 7 Covies, and 4 UNSC, and witness the lack of Spartan slot

#### Length of time in which bug has been known to occur
Since the implementation of the new poplock system about a week ago, 0 Spartan spots have naturally opened.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x ] Issue could be reproduced by different players
- [x ] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [x ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by X0-11** [comment]
I'll get this fixed asap, sorry for this.
