### ISSUE TITLE
Yanme'e flight fix

### ISSUE THREAD

**Issue by kacyroush** [HaloSpaceStation/HaloSpaceStation13#2253]
As it stands, yanme'e flight doesn't ignore turf effects. This means you can see something bizarre, like a flying drone getting tangled up in barbed wire, or falling through open space.

I suggest that flying drones ignore the following turf's effects -

Wet floors (if they don't already)

Open Space

Barbed Wire

Sandbags and energy barricades

REMOVE ability for drones to ignore windows one-directionally.

**Comment by X0-11** [comment]
this would also apply to vehicles that are flying

**Comment by kacyroush** [comment]
That would be the intent, yes. I'd also suggest removing their ability to trip infrared sensors and proximity-based explosives, at least until directly over the latter.
