### ISSUE TITLE
Mobile Respawn Point Loadout Suggestions

### ISSUE THREAD

**Issue by X0-11** [HaloSpaceStation/HaloSpaceStation13#2257]
Format:

Soldier Type (Marine, ODST, Unggoy)

Soldier Loadout,
slot - item in slot

**Comment by Joe44445** [comment]
UNSC:

Marine(Weapon)
-----------------------------------------------------------
Head- marine helmet
Armour-Marine armour
Undersuit-Marine jumpsuit
armour slot-Weapons of choice (MA5B, DMR, BR, Shotgun)
Belt-Ammo belt with ammo (for gun chosen)
Back- Marine backpack (1/2 medkits)
pockets: 2 grenades (1 frag, 1 smoke)
^
this could be split into different options per gun if needed

Marine Engineer
-----------------------------------------------------------
Head- marine helmet
Armour-Marine armour
Undersuit-Marine jumpsuit
armour slot-Weapons of choice (MA5B, DMR, BR, Shotgun)
Belt-Tool belt (with tools)
Back- Marine backpack (1/2 stacks of metal, ammo for weapon of choice <-- very few magazines)
pockets: 2 grenades (1 frag, 1 smoke)
^ the weapons of choice could be swapped out for something less impactful i.e an SMG or a magnum

Marine Medic
-----------------------------------------------------------
Head- Marine Medic Helmet
Armour- Marine Medic Armour
undersuit- Marine jumpsuit
Armour slot- SMG
Belt- Medical belt with medkits
Back- Marine Medic backpack with 1 field trauma kit + 1 combat medical kit and SMG ammo
Pockets- 2 smoke grenades

UNSC Janitor 
-----------------------------------------------------------
head- grey cap(optional)
undersuit- Janitor jumpsuit
Back- mop
pocket- space cleaner

also a janitorial cart spawned on the ground near him, if possible.
(please don't hurt me for this one mr XO the players demand it)

**Comment by CommodoSix** [comment]
Covenant:

**Unggoy Minor**

Head - Unggoy Rebreather Mask
Armor - Unggoy Combat Harness (Minor)
Undersuit - Unggoy Internal Jumpsuit
Hands - Natural Armor
Feet - Natural Armor 
Eyes - Tactical Hud
Weapon - Type-25 Directed Energy Pistol

**Unggoy Major**

Head - Unggoy Rebreather Mask
Armor - Unggoy Combat Harness (Major)
Undersuit - Unggoy Internal Jumpsuit
Hands - Natural Armor
Feet - Natural Armor 
Eyes - Tactical Hud
Weapon - Type-25 Directed Energy Pistol, Type-1 Antipersonnel Grenade

**Suicide Unggoy**

Head - Unggoy Rebreather Mask
Armor - Unggoy Combat Harness (Minor)
Undersuit - Unggoy Internal Jumpsuit
Hands - Natural Armor
Feet - Natural Armor 
Eyes - Tactical Hud
Weapon - Type-1 Antipersonnel Grenade x2

**Comment by X0-11** [comment]
AS a note: Loadouts cost nothing besides not getting what's in the other loadout types, so they should be somwhat on-par with eachother.

**Comment by BDpuffy420** [comment]
#2264

**Comment by BDpuffy420** [comment]
#2264
