### ISSUE TITLE
Dying while in a fighter (or if the fighter is destroyed) does not reset your view range

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#226]
As title.

**Comment by eeetem** [comment]
i do not have much expireance with byond, but i can try to fix this, so the main dev team can work on more complicated stuff

**Comment by BDpuffy420** [comment]
Any help will be gladly taken!

**Comment by eeetem** [comment]
i tried, i could not. i don't get byond. it's meant to be easy ,but i can't code anything, while i easily code stuff on c#.

**Comment by bloc97** [comment]
@etet2 same here, the global and local variables are all mixed up and I can't just get a sense of it. Formal OOP languages are clearer.
