### ISSUE TITLE
[BUG] URF ship lag

### ISSUE THREAD

**Issue by Joe44445** [HaloSpaceStation/HaloSpaceStation13#2261]
The URF ships, atleast the troop transport, upon spawning, are generating infinite amount of lag and are making rounds unplayable.

**Comment by X0-11** [comment]
Does this also happen to UNSC ships of similar types?

**Comment by Joe44445** [comment]
it does not, only the URF ships were affected by this. The round was OC, if that helps.

**Comment by X0-11** [comment]
Are the urf getting the normal ship options? (all types of gunboat, etc)

**Comment by Joe44445** [comment]
Unknown, I believe the first ship they called in was the Troop Transport which caused the lag.

**Comment by X0-11** [comment]
Both times?

**Comment by Joe44445** [comment]
Yeah, both times.
