### ISSUE TITLE
change TACCOM color back to the original blue

### ISSUE THREAD

**Issue by Darkking1234** [HaloSpaceStation/HaloSpaceStation13#2263]
#### Description of issue

exactly what the title says, change the ODST TACCOM color back to the original blue/grey as it currently shares the same color as SQUADCOM and sometimes gets a tad bit confusing when both are being used at the same time.
![bde20b329c145f60b7d69a7f1667a3f3](https://user-images.githubusercontent.com/45013185/75116234-6f2b8f00-5666-11ea-9624-cf39c6f54161.png)

**Comment by caelaislinn** [comment]
Addressed #2374 

SQUADCOM is now a nice dark blue, and ONI on TEAM3 is brown
