### ISSUE TITLE
[Sprite] Orion Defector's Gear

### ISSUE THREAD

**Issue by Johnson4589** [HaloSpaceStation/HaloSpaceStation13#2266]
When wearing the Orion Defector's Chest rig, it will cause boots, undersuits, and gloves to dissapear along with itself. The Orion's helmet is invisible and removes the character's hairstyle once equipped.

**Comment by BDpuffy420** [comment]
I’m well aware of this bug, I’ve been trying to fix it. Like the helmet and suit are bugged but everything else is fine

**Comment by BDpuffy420** [comment]
#2264
