### ISSUE TITLE
[BUG] Baseball bats not craftable

### ISSUE THREAD

**Issue by DronzTheWolf** [HaloSpaceStation/HaloSpaceStation13#2269]
#### Description of issue

You cannot craft baseball bats, and according the @X0-11 you should be able to.

#### Difference between expected and actual behavior

You should be able to open the craft menu from some material sheets and make a bat. You cannot.

#### Steps to reproduce 

Take material sheets, try to craft bat, realize there is no option.

#### Specific information for locating

Material sheets of all kinds.

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: 96423210c174601a10d64d303906730f6a8ac3b7 - alpha - 
Game ID: b5S-bBwf
Current map: Geminus City

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by caelaislinn** [comment]
I disabled it because we're not a HRP circlejerk server. Give me a reason why you want to make baseball bats that doesn't involve RP

**Comment by DronzTheWolf** [comment]
Beating someone to death because plasteel baseball bats are pretty robust.

**Comment by caelaislinn** [comment]
ok approved
