### ISSUE TITLE
Gun QA feedback

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#227]
- Shotgun beanbag rounds are very damaging (supposed to be the nonlethal round). 
- While zoomed in, you are able to swap weapon with middle click and fire with another gun. 
- Most guns are overpowered. 
- Sniper, magnum can destroy walls. 
- All guns can be used one handed when some shouldn't (sniper, LMG, rocket launcher, DMR, battle rifle, shotgun)

**Comment by bloxgate** [comment]
I will point out beanbag rounds are lethal if it gets a headshot irl. And can cause some pretty bad injuries with chest shots.

**Comment by Krautzy** [comment]
Most, if not all weapons, are normal-sized items and can be fit into containers (ie you can throw five assault rifles into a backpack).

**Comment by BDpuffy420** [comment]
most issues have been fixed
