### ISSUE TITLE
Unggoy balancing.

### ISSUE THREAD

**Issue by EpicFatGamer** [HaloSpaceStation/HaloSpaceStation13#2272]
WARNING: lengthy effortpost ahead

After a lengthy discussion in covenant hall involving multiple long-time community members, myself (not long-time but a deacon main), and XO, one of us was encouraged by XO to make a github request about unggoy balance. As it stands, I believe the intent is for unggoy to be slightly weaker then marines. As for execution, I do not believe this to be the case. 
**Unggoy Pros**
EVA capable with no hardsuit. 
Less slowdown from items (more about this later)
**Unggoy Cons**
0.25 negative speed slowdown compared to normal speed
Less dodge range
Significantly less weapon variety
Always have a slot taken up by their methane tank
Slightly worse armor overall, and NO head armor unless they kill a marine.
No backpack, making it harder to carry both ammo and meds. (Only a problem with needler/fuel rod, but those are 2/3 grunt weapons
No suit storage.
**Marine Pros**
Faster by 0.25
Can dodge roll an extra square
Significantly higher weapon variety and range.
The ability to carry a backpack
More storage overall, between boots, armor, etc.
Better armor overall 
**Marine Cons**
Not EVA capable by default (but they do have EVA armor right? Unsure).

This may seem like a whine post, but I genuinely do not believe most of these things need changing. Grunts relative weakness is balanced by other covenant species variety. However, as discussed last night, I believe the relative weakness of grunts is significantly lower then it should be, making currently playing grunts effectively suicide.

**Change to fix most issues I believe should be made before mobile spawns**
Honestly, the best thing I can see happening to grunts to slightly balance the imbalance is a movement speed change. A buff to normal grunt speed would make playing grunt significantly less tedious at times, and bring them back more towards the baseline. 
 Let me explain my reasoning. While a 0.25 movement speed difference may seem minor, it has significant effects on combat and gameplay in general.
-Cannot disengage from fights
-Cannot chase unless marine is heavily injured, and you arent at all
-Harder to get away from grenades, especially with the 1 square dodge roll.
-Round in general is slower, and honestly I believe this has a large impact on the "fun factor" making less new players want to covenant, and therefore apply for whitelist.
-**Most importantly**, injury slowdown. Being hit once as an unggoy slows your already slow movement speed down to a crawl, turning you into a sitting duck in combat, unable to dodge, and an easy target practice for marines. 
I fear that as it stands, once mobile spawns are added, covenant will have a large disadvantage due to the reasons I just listed. I believe the movement speed change is a simple value change that should be made before mobile spawns are added, as unggoy already are at a massive disadvantage as is and mobile spawns will only make this more noticable (and it already very much is for covvie players)

**Changes I believe could be looked at after mobile spawns**
Weird storage stuff, like needler being unable to fit on back, making it impossible to take a belt slot if you want to store your weapon.
Armor buffs depending on rank
I could be misreading the code, but natural armor seems to do nothing, and the jumpsuit covers the hands and feet instead. Unggoy could possibly get very slightly higher values on hand and foot armor then marines, and have the protection removed from jumpsuit.
Not enough to make them monsters in melee, but people seem to want a melee buff. I'm neutral on this.

Thanks for coming to my ted talk! 
-Ab-Duk

**Comment by SpanishMan227** [comment]
+1

**Comment by Sgtwok** [comment]
+1 to compensate for the huge nerf Covenant got.

**Comment by EpicFatGamer** [comment]
update: I've buffed speed up to baseline, XO has buffed armor, and I currently have a pull that *should* pass that adds needler to back slot along with a natural armor buff. Grunts feeling much better now.
