### ISSUE TITLE
Brutes cant pry open doors

### ISSUE THREAD

**Issue by MrNebbercracker** [HaloSpaceStation/HaloSpaceStation13#2281]
#### Description of issue
Just like the title, clicking on a door with grab intent as a brute does not start prying it open like it should

#### Difference between expected and actual behavior
normally elites and brutes can click on doors with grab intent to force them open provided they aren't bolted, and now clicking on doors with grab intent does nothing.

#### Steps to reproduce 
just walk up to any door and try to pry it open as a brute. I discovered this issue on the 1 tile doors in vt9 so there may be some doors you can still pry open

#### Length of time in which bug has been known to occur

at the very least its been happening on the day this issue was posted, and since the server has been down for a quite a while to do updates it is probably an issue with the latest changes

#### Client version, Server revision & Game ID

client version: 513
server revision: 68102d44b75d73353260716c9d4cd9d3048be52f
game ID: b54-auiQ

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by CommanderXor** [comment]
Confirming that the same issue affects Sangheili as well. Seems the door-forcing feature broke for both species.
