### ISSUE TITLE
[BUG] Comms Broken 

### ISSUE THREAD

**Issue by SuckMySocks** [HaloSpaceStation/HaloSpaceStation13#2283]
#### Description of issue
Comms are completely busted.
All of them.

#### Difference between expected and actual behavior
Comms should work but don’t 

#### Steps to reproduce 
Try to use comms, see that they don’t work

#### Specific information for locating

Press ; then type something out then press enter

#### Length of time in which bug has been known to occur
Server startup

#### Client version, Server revision & Game ID
Updated

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by bloxgate** [comment]
We need a bit more information on this. The length of time section is supposed to be how long the bug has been occurring, not how long it takes to occur in game.

It would also be helpful if you could give use the actual server revision and game ID rather than just `Updated`.
