### ISSUE TITLE
[Suggestion] Adjust Mongoose speed and remove the ability to throw grenades from the driver seat

### ISSUE THREAD

**Issue by CommodoSix** [HaloSpaceStation/HaloSpaceStation13#2288]
A mongoose driver is currently able to surpass T'vaoan level of speed by only equipping a machete. Coupled with the ability to deploy grenades from the drivers seat, enables the driver to dish out large amounts of damage (especially if its a custom grenade.) in exchange for very little risk to their own well being, since many of the slower races can not properly counter them.

As such I would like to suggest having another look at the vehicle speed and possibly disabling the ability to use grenades/weapons from the driver seat.

**Comment by Charger-jpeg** [comment]
I dont really have a problem with the nade thing. But i think the speed should be left alone. Its a vehicle powered by an engine. It should be faster than a bird...

Also i think two handed weapons are already disabled on a mongoose. Meaning you can only use the pistol. Which is prob weaker than a ghost.

**Comment by mrturkeytoe** [comment]
Driver shouldn't be able to use weapons period imo, and in actual halo I believe mongooses are only a little faster than birds.
