### ISSUE TITLE
[Suggestion] Beam Rifle stinky bad

### ISSUE THREAD

**Issue by mrturkeytoe** [HaloSpaceStation/HaloSpaceStation13#2291]
#### Description of issue
Beam rifle is objectively worse than the SRS in every way

#### Difference between expected and actual behavior
For the beam rifle and SRS to compete on an even ground with some differences

#### Steps to reproduce 
Look at code for beam rifle and SRS

#### Length of time in which bug has been known to occur
A long time

**Comment by X0-11** [comment]
Zoom levels equalised in #2286
