### ISSUE TITLE
[Bug] Trauma kit sprite is invisible

### ISSUE THREAD

**Issue by CommodoSix** [HaloSpaceStation/HaloSpaceStation13#2292]
#### Description of issue

The sprite for the field trauma kit is invisible.

#### Difference between expected and actual behavior

Expect to see the sprite, but unfortunately I can not.

#### Steps to reproduce 

Dispense field trauma kit from medical vendor, realise it is not visible.

#### Specific information for locating

Happens with the covenant med vendor at the medbay and the kits inside the crates at the auxiliary medbay too.

#### Length of time in which bug has been known to occur

For at least four days by now.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Sgtwok** [comment]
M8 I made the exact same issue two days before you did.

**Comment by caelaislinn** [comment]
Duplicate #2289
