### ISSUE TITLE
[Suggestion] Remove the ability to use weapons from the mongoose driver seat

### ISSUE THREAD

**Issue by CommodoSix** [HaloSpaceStation/HaloSpaceStation13#2296]
Pretty straight forward. A mongoose driver should not be able to use any kind of weapon, especially not melee weapons. The speed of the mongoose, coupled with the knockdown effect from hitting someone with a melee weapon, makes it a very cheesy tactic to use against the enemy to secure kills at very little risk to the driver themself.

**Comment by X0-11** [comment]
I had intended to remove this in the recently merged pr but had forgotten
