### ISSUE TITLE
[Suggestion] Remove URF access to VT9 coordinates

### ISSUE THREAD

**Issue by All-I-Do-Is-Nguyen** [HaloSpaceStation/HaloSpaceStation13#2302]
This wasn't an really issue before the OC threshold was reduced to 6 readied up. The URF have coordinates to Vt9 allowing them to immediately go to the planet and "find" the ONI facility. In reality, they're just going to raid the base. This allows them to meta the artifacts to steal/destroy them and just kill everybody by breaking in the base.

They have no reason to go to the planet as their primary objective is the liberation of Geminus Colony. Hell, this is the prompt you get in chat when you spawn as an innie 
![image](https://user-images.githubusercontent.com/31935474/77207612-114c6480-6ab7-11ea-81a1-31452f7b215d.png)

None of the objectives mention or hint anything about VT9 at all
![image](https://user-images.githubusercontent.com/31935474/77207665-3214ba00-6ab7-11ea-99be-af41b9945fbb.png)

Solution: Give innies a different set of nav data chips (probably the exact same as UNSC but with red accents) that only have the coordinates to GC. If the URF so please, they can steal UNSC/Covenant nav data chips and find the location of VT9 and its base, rather than immediately rushing it because they have metaknowledge that the UNSC/Covenant will be there and catch either of the factions off guard.

**Comment by X0-11** [comment]
Liberation of a colony would also include eliminating any strongholds of hostile forces in the area. It's not an objective but if the URF weren't provided the co-ords, they'd have no way to chip into the VT9 fight.

**Comment by All-I-Do-Is-Nguyen** [comment]
> Liberation of a colony would also include eliminating any strongholds of hostile forces in the area. It's not an objective but if the URF weren't provided the co-ords, they'd have no way to chip into the VT9 fight.

Then maybe add another objective to the already existing ones. Something along the lines of "Steal UNSC nav data to find a UNSC stronghold in this sector"

**Comment by X0-11** [comment]
Which would be completely impossible to actually perform seeing as the entire UNSC force will be focusing around VT9 in the first stage of the game?

**Comment by mrturkeytoe** [comment]
Maybe make it so covenant are directed first to Geminus as well to get nav data to the SECRET ONI base then they have to get the artifact?

**Comment by All-I-Do-Is-Nguyen** [comment]
> Which would be completely impossible to actually perform seeing as the entire UNSC force will be focusing around VT9 in the first stage of the game?

And the URF will be focusing on completing missions in the first stage of the game so they can get reliable gear and then move to GC. Once they start capturing the control points there is bound to be some UNSC heading their way to GC. Or, alternatively, UNSC secure the artifacts and then leave ONI to their own device (very unlikely as they would be expecting covenant anyways).

**Comment by X0-11** [comment]
ONI base is the first stage of the round, with GC being the second. The only thing removing VT9's co-ords would do is make the URF forced to fortify GC and would essentially make their round flow even more stale than it  currently is.
