### ISSUE TITLE
[Suggestion/Bitch] VT9 Underground sub-level mapping sucks

### ISSUE THREAD

**Issue by mrturkeytoe** [HaloSpaceStation/HaloSpaceStation13#2303]
Lots of long narrow two to three tile corridors with few or no alcoves or side rooms and lots of doors, all or almost all of which are access locked makes fighting there without overwhelming force in your favor against ONI, especially as the covenant, extremely unfun and hellishly punishing because ONI gets research toys, a respectable compliment of high power weapons like the SRS and shotgun and total control over positioning because you have to expose yourself hacking through each airlock individually giving them countless windows to fire on you then retreat behind another or ambush you.

Perhaps the tunnels could have some of the doors/some of the doors' access restrictions removed and some alcoves with desks/vending machines and some side rooms like closets added?
And maybe some bends in some places to the general shape of the tunnels could be added as well?

**Comment by mrturkeytoe** [comment]
Also none of the tiles have simulated lighting, totally removing the tactical option of smashing lights to sneak around.

**Comment by caelaislinn** [comment]
VT9 was removed in #2411 so we're not supporting it any more
