### ISSUE TITLE
Potential Needle Rework 

### ISSUE THREAD

**Issue by loafe** [HaloSpaceStation/HaloSpaceStation13#2305]
So it turns out that needles bypass shields (or at least have a chance to), which seems pretty strange. XO and I had a conversation around this, and we proposed that instead of bypassing shields, needles instead do a small amount of damage when they first hit, and then a couple seconds later do a large amount of damage. They will still have a chance to impale unshielded opponents as well. I think the numbers we agreed on were 5 damage when it first hits, then 20 when it detonates, compared to the flat 20 it was before.

In terms of balance, I think this will accomplish a few goals. First, it will get rid of the power difference of each faction versus shielded opponents, leveling the playing field between Spartans vs. Covenant. Secondly, it will replace the instant impale with a buff in damage, allowing it to still be a very good weapon vs unarmored opponents. Lore wise, this makes sense, as in the games, you see the needles first impale, and then pop after a second or two where it does additional damage. 

I don't know the numbers on supercombine, but I don't think there would be any change on it.

**Comment by X0-11** [comment]
This has been done. It does 20 on impact, doing 5 armour-bypassing and shield bypassing damage when the shard explodes, which happens after 10 seconds.
