### ISSUE TITLE
[Suggestion] T'vaoan Commando Armor is straight up worse than Murmillo

### ISSUE THREAD

**Issue by mrturkeytoe** [HaloSpaceStation/HaloSpaceStation13#2307]
Currently playing commando as a bird gives you objectively worse survivability than murmillos due to not have the shield with (I assume) the same number of armor grace shots.

Maybe add more grace shots to their armor to compensate?
Maybe make their armor give a increase to speed like URF light armor?

**Comment by caelaislinn** [comment]
This is intended. Players who know how the different tvoans play should be able to make a conscious choice for different strengths and abilities.
