### ISSUE TITLE
[Mapping issue] Covenant ships

### ISSUE THREAD

**Issue by mrturkeytoe** [HaloSpaceStation/HaloSpaceStation13#2311]
I think I already made one covering some of these issues in the past but am uncertain and will reiterate those issues alongside new ones I found

Dual glassing beam ship lights don't work
Scouting ship as well as others I believe have a very awkward issue where the the middle side rooms' (where it has medical supplies and the glasser has the projectors) entrances at the aft end of the rooms have obstructed tiles.

**Comment by caelaislinn** [comment]
This is hard to understand. Do you mean the doors have a machine blocking them?

**Comment by mrturkeytoe** [comment]
Apologies, no. It isn't the airlock tile directly, it's one tile north and one west of the airlock tile, for the north side of the ships I believe. I am fairly certain it has something to do with the light tile, or entity rather.

**Comment by caelaislinn** [comment]
Is this for CRS Unyielding Transgression, the current Covenant ship map? I can't find where you are talking about

**Comment by caelaislinn** [comment]
I did some testing on the subships and couldn't figure out the issue, so I fixed a few other things instead on #2482 Reopen or repost here if they are still occurring
