### ISSUE TITLE
Increase Spartan Population Requirement on Outer Colonies

### ISSUE THREAD

**Issue by Sgtwok** [HaloSpaceStation/HaloSpaceStation13#2317]
With the way current Spartan spawns work, I believe, for the Outer Colonies game mode, there must be an increased requirement before Spartans are permitted to spawn, instead of every five non-UNSC spawns equaling one Spartan.

This can lead to the extremely common situation of there being 5 UNSC members (as well as two or three Spartans), 7 URF members, and three Covenant members.

URF and UNSC can and often do team up, which not only augments Human numbers, but also, thanks to URF allowing extra Spartan respawns since they are not UNSC, this results in a team of three Covenant fighting:
3 Spartans
An Orion
6 URF members
and Five Marines

What's worse, this could include only unggoy or ruuthian kig-yar, vastly incapable of handling one, let alone three spartans as well as two entire teams against them unless they are legitimate gods or get extremely lucky.

Such numbers could instead be upped to 7, or 8 non-UNSC members, ultimately it's up to negotiations.

And for those who aren't 100% sure how it works, for every 5 non-UNSC members that spawn, which includes URF (I'm not 100% sure on Civillians or GCPD) a Spartan spawn is granted.

**Comment by X0-11** [comment]
The only other method to fix this issue would be to utilise the conversion tools that are in-game to force the player faction switches when team-ups like this are performed. Such an issue exists when there are no teamups too, due to a large covenant population allowing a small urf population to get stomped by spartans and other unsc personnel

**Comment by loafe** [comment]
I don't think a further nerf to the pop lock would be good in this case, because in reality, there are usually many more Covies than URF, and generally fights at VT9 are Covenant vs. UNSC. If the pop lock is 8 or 9, there could easily be 5 elites, 2 T'voans, and a couple grunts vs 1 Spartan and a handful of marines and ODST, which would be an absolute steamroll in favor of the Covenant. 

In term of power roles, a proposed nerf would be pretty unbalanced, especially since the Covenant have very powerful ways of dispatching Spartans. While you can argue all you like that marines propose a serious threat, in reality, they are most often cannon fodder unless they are very robust. ODST aren't much more powerful than them, either. 

The current system seems fine to me. 2 Spartans are what I generally see on highpop rounds, usually against 4-5 elites, a T'voan or two, and some other minor infantry. Alternatively, if you really want Spartans to go away, we should nerf the pop lock for power roles for the Covenant as well, so as to prevent a stomp at VT. 

In terms of the URF and UNSC teaming up, that is the kind of thing that doesn't happen too much, and can be avoided with some tactics. If you wait for the URF to start capturing GC, or for the URF to engage the UNSC, you can let the two sides gradually kill each other, and then swoop in to kill the survivors. It's a three way war, it's meant to be messy.

**Comment by Sgtwok** [comment]
This is exclusive to Outer_Colonies.

https://puu.sh/FnJfV/9e33a5c202.jpg

That is three Spartans in one picture.

**Comment by Joe44445** [comment]
^^ 

being in that round, there was also an assload of covie players playing. the 3 spartans and 2 marines shown in the picture were the only UNSC players.

I don't mind suggesting this if you think the poplock is unfair, but please don't post out of context pictures to try and back it up.

**Comment by Sgtwok** [comment]
Actually Joe, there were only three Covenant in the match, the player who took the picture was a sangheili minor, the other was a kig-yar, and the third? I do not know.


Correction: It was a video, and during the video, more than five UNSC members pass by.

**Comment by Joe44445** [comment]
that's a lie man, I know exactly what that round was and we killed covenant and even had their weapons. The same elite was killed by a needle rifle we stole from a dead covenant player we killed much earlier in the round.

Literally just asked Dondale (one of the 3 spartans in the picture bar me and Kozi) and he even confirmed it. There was way more than 3 covenant players, we distinctly remember killing them.

**Comment by Sgtwok** [comment]
Please don't lie to me.

https://www.youtube.com/watch?v=wqvUZTarvIc&feature=youtu.be

https://cdn.discordapp.com/attachments/383995124004159489/691433069722206299/unknown.png

**Comment by X0-11** [comment]
"more than 3 covenant players" and "more than 3 covenant enemies, split across multiple engagments" are two different things. Remember that respawns exist, mobile and otherwise.

**Comment by Joe44445** [comment]
this was after we'd already taken out covies, man. Should I get both Dondale and Kozi's accounts too? 

hell, in this same round I was ordered by dondale to use a captured covenant sniper from a corpse to false flag shoot some insurrectionists becuase we knew they'd try betray us.

reading back, I realised I did actually write it a bit wrong. Those 3 spartans and 2 marines were our force for a majority of the round. Completely forgot about the few ODSTs who showed up after the main bit of fighting was over.

I find it funny how you're using this round was an example, becuase I remember looking at the lobby before joining and noticing the total lack of marines and how outnumbered the UNSC was compared to the other 2 factions.

**Comment by X0-11** [comment]
Anecdotal evidence aside, the logical point of "there are more hostiles capable of filling a quota, therefore raise the quota to keep general ratio the same" is not the least agreeable idea available.

**Comment by Sgtwok** [comment]
Like I said XO, this does not also take into account what the numbers actually consist *OF*, both Covenant and URF side.

EDIT: Of course that's another problem, one which balancing is hard to take into account.

**Comment by Kozi32** [comment]
Actually this is only Covenant salt.. 3 Spartans in a round is Rarest thing ever, this was my first round to have 3 spartans, usually its 1 or 2 max... There wasnt 3 covenants but more, And usually covenant won the rounds, ODST isnt equal to Elite, its more equal to Kigyar, 2-3 elites plus brutes Isnt OP?...

**Comment by Kozi32** [comment]
Walaski actually is the person who killed alot of covenant ships.. if there wont be cobbies..why alot of their ships were on Geminus?

**Comment by X0-11** [comment]
You're failing to address the underlying point here. The fact of the matter is that in a high-pop gamemode with more slots, it is more likely for a side to be underpowered in terms of population, be it covenant or URF.

**Comment by Joe44445** [comment]
and there is also a chance the UNSC has a situation like that. The system is set up, as far as I can tell, so UNSC pop _also_ affects the poplock, its not like the UNSC is getting 20 marines and also 3 spartans. Other spartan players can attest, it is generally only 1 spartan, 2 at a push. I feel like this isn't a big of a problem as people make it seem, The round shown is the only time in the last month or two I can remember there being 3 spartans, and even then we were severly, serverly outnumbered by the URF and, as far as we could tell, the covenant (of which, actually killed us in the end via an endless wave of suicide grunts that was clearly more than 3 people at once).

**Comment by Sgtwok** [comment]
Many of your arguments include 'Ifs', argue as though the numbers are equal across all three factions, or argue that nobody is playing, in this event.

With that in mind, the only factor then that would not be equal would be humanity vs the Covenant, the only 'if' factor in my presented scenario, would be IF URF and UNSC ally, which, they have little, if any reason, to not do.

**Comment by Sgtwok** [comment]
Not only just the Covenant, but URF as well, of whom, are supported only by Orions and SoE, with their main force not having weapons at all until they prepare correctly.

**Comment by loafe** [comment]
>little, if any reason, to not do

I think a genocidal alien invasion is a good reason. See: Reach

**Comment by Sgtwok** [comment]
So you agree with my point then regarding the extreme power difference regarding manpower?

That statement only supports the underlying issue, the increased population demands a lock increase.

**Comment by Joe44445** [comment]
if you want equal numbers, we'll assume 5 across the board. That's 1 spartan player. 1 Spartan and 5 ODSTs/marines who are now forced to fight on 2 seperate planets.

**Comment by Sgtwok** [comment]
Then UNSC and URF allign with one another and now you have two spartans and ten humans including an Orion or two fighting five covenant players who could, for all you know, be three unggoy and two ruuthians.

**Comment by loafe** [comment]
No, the rather than assuming UNSC and URF will always team up, wait for them to kill each other. UNSC and URF are natural enemies until Covies invade GC, even then, they still kill each other pretty often.

**Comment by Sgtwok** [comment]
You are thinking about only Covenant in this instance instead of also taking URF into account.

**Comment by Joe44445** [comment]
what? no you don't, you still only have the 1 bloody spartan they spawned with, becuase the pop is still 5 across the board. Why would teaming with the URF get them another spartan?

**Comment by Sgtwok** [comment]
...Joe, you know URF count towards the Spartan population, yes?

**Comment by Joe44445** [comment]
yes okay, but if there's 5 UNSC then the poplock changes. I said in my first statement it was 5 across the board, so for all 3 factions.

**Comment by Sgtwok** [comment]
No, Joe, that's two spartans, one or two orions, as well as ten base humans vs five covenant members.

**Comment by loafe** [comment]
you are again assuming UNSC and URF will team up, which isn't a given. It's RP, I could very well see a Covenant negotiating a truce with the URF.

**Comment by Joe44445** [comment]
no it isn't man. The Spartan poplock is also affected by UNSC numbers. Is this another situation where you're trying to tell me how something you don't even have access to works...

**Comment by Sgtwok** [comment]
Why wouldn't they, Loafe?

Citation needed, Joe.

**Comment by loafe** [comment]
If I remember correctly, 5 UNSC/ONI add one person requirement onto Spartan poplock. That is what XO explained when it was initially changed

**Comment by Sgtwok** [comment]
Not to mention that with my proposed change, you'd still get one spartan, even if that were true.

**Comment by loafe** [comment]
I think you are severely overrating the strength of Spartans in relation to other power units in the game. Spartans should be pretty easy for Covies to kill given their tools, and the URF has some special tools as well.

**Comment by Sgtwok** [comment]
You are also expecting for covenant to have sangheili or jiralhanae, whom are actually suited to take on Spartans on their own, again, those five covenant members could be five unggoy.

**Comment by X0-11** [comment]
the poplock functions off of the population of non-aligned-faction members. For spartans, it tallies the non-unsc population, not the unsc population. If the unsc population outnumbers the combined non-unsc population, a multiplier is applied, however, it only really matters on low population counts.

**Comment by Sgtwok** [comment]
Hey here's a fun fact, this is already the most commented on issue we have, thus far the only people commenting have been me, XO, and two Spartan players.

**Comment by Kozi32** [comment]
i want to admit i died more times to Unggoy with sticky nade than Elites... Spartans arent OP as fuck since one grenade insta kills them

**Comment by Sgtwok** [comment]
This whole issue is about population balance, not spartan balance.
