### ISSUE TITLE
Custom player set objectives

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#232]
This would tie into the scanner waypointing system and players with an appropriate HUD (either fighter pilots or players with an actual wearable HUD ie marines) could set custom waypoints/objectives, and also have waypoints/objectives set remotely by a CiC or JTAC. 

This would better enable teamwork and communication, and allow faction gameplay to be more goal focussed.

**Comment by X0-11** [comment]
Currently working on a squad-wide personal waypoint system. Should fufill this issue.

**Comment by caelaislinn** [comment]
PR merged
