### ISSUE TITLE
[Suggestion] Covenant and UNSC Capture Points

### ISSUE THREAD

**Issue by CommanderXor** [HaloSpaceStation/HaloSpaceStation13#2325]
#### Description of issue
As the title suggests, this is well...a suggestion.

The basic concept is that at the end of the round, both the Covenant brig and ONI/LB's xenobiology/brig are scanned for alive mobs of their opposite factions.

From there, points would be assigned based on the role.

I.e ONI would mostly be looking for things like Ultra, Deacon, Sangheili of various ranks, T'vaoans, etc and would get points based on rank.

The Covenant would get points for having HVTs alive in the brig at round end. I.e XO, URF Officer, UNSC CO, ONI RD, ONI Researchers, Security Commander, etc.

This is both to give incentive to potentially capture, and a solution for the old system of how the UNSC captured that bugged out the point system.

Lower/common roles like ONI Guard, Unggoy, Marine etc should probably not give points, and if they do, very little.

**Comment by CommodoSix** [comment]
Great idea.

Though I would suggest further limiting the roles that grant points to avoid point bloat and ensure that the roles in question are rare and appropriately hard to acquire.

For the UNSC that would be: CO, XO and ONI RD.

For the Covenant it would be: SM, Sang Ultra and Deacon.

By limiting it to roles that only have one available slot, the targets become more valuable and it also makes more sense to only go for the top brass of both factions.

**Comment by caelaislinn** [comment]
This is already an objective for the UNSC to capture Insurrectionists, the system could easily be copied for UNSC and Covenant. Nice idea.

**Comment by X0-11** [comment]
The objective to capture innies is current disabled because iirc it was somewhat broken, allowing the unsc to obtain hundreds of points for a few innie kills.
