### ISSUE TITLE
UNSC Light Brigade Fax/Lighting Problem

### ISSUE THREAD

**Issue by Chambers0** [HaloSpaceStation/HaloSpaceStation13#2329]
Description of issue:
The UNSC Light Brigade lacks paper bin and pens to send in faxes.
Sometime if not all the time, when we spawn in ship, the ships themselves produces no lighting causing it to be dark for people who lacks night vision. Even the flashlight are ineffective to produces lighting in these environments due to the coding.

Difference between expected and actual behavior:
Expected: UNSC Light Brigade is spawned with a paper bin and pen at the Bridge.
Expected: Spawned Vessel produce lighting inside the ship.
Actual Behavior: UNSC Light Brigade lacks a paper bin and pen at the Bridge.
Actual Behavior: Spawn Vessel sometimes does not produce lighting inside the ship.

Steps to reproduce:
Code/Map the UNSC Light Brigade to spawn with a paper bin and pen at Bridge
Fix the lighting coding for spawnable vessels

Specific information for locating:
IDK

Length of time in which bug has been known to occur:
UNSC LB: All the time
Spawned Vessels: Random but with a high chance

Client version, Server revision & Game ID:
byond://ss13.projectunsc.org:2701

Issue bingo:

**Comment by caelaislinn** [comment]
Can you please make a separate issue for the lighting problem?
