### ISSUE TITLE
Colonial Governor Town Sim

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#233]
A player may be chosen at round start as the "Colonial Governor" and given a single zlevel worth of grid plots (24x24) to build on and expand their town. Manage utilities, housing, commerce, industry and defence while choosing what kind of town you want to make - utopian academia, gritty crime ridden slums, industrial powerhouse, center of trade or military strongpoint. 

Attract traders and different demographics of colonists depending on ordnances you enact or laws you enforce, and eventually choose whether to support the UNSC by clamping down on the Insurrection or secretly encouraging it and eventually declaring independance.

**Comment by ayyourboibilly** [comment]
24x24 is a lot smaller than you think

**Comment by caelaislinn** [comment]
Its larger than the standard viewport. For the "buildings" placed on the plots they can be tardised giving them much larger spaces on the inside.

**Comment by Flaksim** [comment]
Err, what is it you want exactly? Because if it is what it sounds like, (Small hub mapzone 24x24 linking to a shitload of prefab buildings on other Z's) Its way too much work for a gamemode that I dont believe will be popular.

**Comment by caelaislinn** [comment]
It's an expansion idea for the existing colony map/s where players can get PVE stuff happening, possibly with NPCs. Doesn't have to be its own gamemode, just something for players to do other than validhunt.

**Comment by Nanu308** [comment]
is this smth we still need at all? /added etc?
