### ISSUE TITLE
[SUGG] Various T'Vaoan Balance Ideas (And more, probably)

### ISSUE THREAD

**Issue by Delnth** [HaloSpaceStation/HaloSpaceStation13#2333]
Before the skirmisher mains jump at my throat and shred me to bits, I'd like to say that these ideas (some will be added over time) are not meant to make the role a living hell ; in fact, I will not suggest to things such removing their natural speed or their equipment (arm shields), because it's what makes them stand out from other Covenant classes and what makes them what they are; skirmishers. Everyone is free to add their ideas, just keep it civil.

**Special Application Rifle/SRS use** (may or may not be applicable for all species except spartan/elite/brute)
It's all cool and epic when you're the marksman shooting from miles away. Less so when you're the target. It's even worse when your opponent is a fast smirksher with arm shields that give it the ability to relocate safely. Not to mention the distance that separate it from other opponents, likely humans; their weaponry will often if not always miss at mid-long distance, be it to RNG or due to the spread. The lucky bullets will just hit the shield and the skirmisher will relocate a few tiles away to continue its work. I suggest adding a delay for all species (except those named above), which would require X seconds to take position and prepare yourself. Kneel down, aim down, hold your breath. Whatever. It is to make relocating a bit more tedious and finding the right spot more rewarding. Some structure  could even nullify or just lower the preparation time by half; such as tables, sandbags, ect.

**Stamina!**
Maybe give skirmishers normal human speed, but their current speed could be turned into a species-specific ability that can be used at any time. However doing so would put it on a cooldown. This is to favor a wiser use of the speed rather than being a tool that turns the skirmisher into an unstoppable killing machine. How long the speed effect will last has yet to be established, it'd have to be worth it, though.

(More ideas will probably be added later)

**Comment by X0-11** [comment]
There is no need to nerf skirmishers further. Whilst some players may find that in infantry combat they have issues eliminating a sole sniper-skirmisher in a 1-v-1, there is a wide array of vehicles and, additionally, chemicals, that would allow a person to easily equalise and surpass the hostile's ability to react.

Stamina isn't going to happen. It's evidently a reactonary measure based around a single species. Toggle walk mode for an entire round and ask yourself if you'd rather that be the default for everyone.

A delay on deploying sniper weapons sounds fine, however, it should be placed in a seperage git issue. All scopes would obtain this functionality. Please re-make the issue, specifically focusing on the scope delay.
