### ISSUE TITLE
[Issue/Suggestion] Huragok players too readily defect/convert (and are really really strong)

### ISSUE THREAD

**Issue by mrturkeytoe** [HaloSpaceStation/HaloSpaceStation13#2339]
"Vanilla" SS13 silicon culture of playing a AI or, especially borg just to have a powerful role and not have to RP seems to have carried over to HS13 and huragok players continue to take any and every opportunity to abandon their team to defect/convert, forgetting that they are still loyal to the covenant and that pacifist/universal medical attention =/= immediately defect/convert.

As well, due to the fact that standard SS13 code never accounted for large scale teambased PvP involving silicons, them having immediate access to any machine or door makes them ludicrously OP in this context. As an example, the syndicate borgs in standard SS13 are notoriously OP because they can access all the station's machinations just like the station AI/borgs can and can merely waltz right into the AI core chamber and kill it.

I propose as a solution to these two issues you cannibalize the borg self-destruct console code from base SS13 to implement the failsafe explosive huragok harness from H3:ODST to keep them in line and develop a system to differentiate doors/machines and silicons with a faction based tag perhaps and add a delay, and maybe later replace it with a hacking minigame if a silicon attempts to access a machine tagged as belonging to an opposing faction.

**Comment by X0-11** [comment]
Huragok aren't getting a self destruct console. These are covenant whitelisted players. Adminhelp if they act in ways that are against their whitelist. If you think borgs should obtain greater access controls, create a seperate git issue.
