### ISSUE TITLE
Increase UNSC Ship Size or Decrease Covenant Ship Size

### ISSUE THREAD

**Issue by Sgtwok** [HaloSpaceStation/HaloSpaceStation13#2341]
As it stands, UNSC have a much easier time in space combat with the covenant, thanks to the size of Covenant ships being much, much larger when in comparison to covenant ships

Exhibit A: http://puu.sh/FpLeN/b2b64950b5.jpg - Both of these ships are the same class, you cannot tell me this is fair.
There is also a ship so large, the biggest in the entire game mind you, which takes up 10% of the screen, which UNSC can very easily hide countless MAC ships beneath, with one marine manning a MAC gun to utterly decimate any passing covenant ship, and there is no need to worry about retaliation, since before that entire fleet can be even properly engaged, that large ship, acting as a shield, will offer 100% protection until it is destroyed.

Mind you, before any UNSC comment on here, only the flagship has shields.
**Side note for XO: The plasma torpedos are bugged and do not work.**
I propose either a reduction of Covenant ship sizes, or an increase in UNSC ship size, there ARE larger UNSC ship models, and there are smaller Covenant ship sizes, but as it stands, most of the time the Covenant will have a very large ship engaged with an extremely small, difficult to hit ship armed with a MAC gun.

Server Revision: ac715cdab770bce60ce2b13340ec152e14cb479f - alpha -

**Comment by Nanu308** [comment]
Local man can not click sprites, more at 11 B)

**Comment by Sgtwok** [comment]
Instead of addressing a legitimate concern you resort to mockery, the same issue happened to yanme'e and UNSC complained nonstop about it.

**Comment by Nanu308** [comment]
Its almost like the Yanme was an issue in a fast-paced environment while overmap combat is slow as fuck

**Comment by Sgtwok** [comment]
So you have no point and instead of addressing a legitimate concern, you still resort to mockery.

**Comment by X0-11** [comment]
An explanation of the issue being had with plasma torpedoes would be useful, otherwise, this issue can be solved when size appropriate sprites are supplied for the vessels.

**Comment by caelaislinn** [comment]
I actually agree, I think large ship sprites should be reserved for large ships - ie ships with multiple zlevels.
