### ISSUE TITLE
[suggestion] add landmines to the UNSC Light Brigade

### ISSUE THREAD

**Issue by Joe44445** [HaloSpaceStation/HaloSpaceStation13#2347]
Add a crate of landmines to the UNSC light brigade in order to give the UNSC more defensive options when deploying to defend a point.

github made after a discussion in UNSC barracks.

**Comment by X0-11** [comment]
wouldn't these be better suited for placement within ONI, requisitioned by the UNSC when they arrive to defend?

**Comment by Joe44445** [comment]
whilst that may be the case for defending the ONI base, the UNSC forces often find themselves also guarding Geminus Colony in which ONI's mines are not accessable without hauling them all the way from VT9.

**Comment by X0-11** [comment]
Which adds a level of prioritisation to the ONI research outpost, if only for it's resources?

**Comment by Joe44445** [comment]
I fail to see why the UNSC should have to rely on a completely different faction for something that should be standard issue, ONI already offers enough with its various research techs it can give the UNSC. Mines would be useful in situations where the ONI base has been completely wiped out and the UNSC have been pushed back to Geminus. Having already lost ONI base and all its research benefits, I don't see why they should also use a standard peice of defensive equipment with it when a ship such as the light brigade should be equipped with in its standard armoury. ONI does not need more prioritisation, as it is already home to the artifact and a nav chip, both of which are crucial Covenant objectives we need to defend.
