### ISSUE TITLE
[Donor] Request for Coding of Items

### ISSUE THREAD

**Issue by AttackHelicopter6784** [HaloSpaceStation/HaloSpaceStation13#2365]
Mistah XO told me to make a Git issue to ask for some equipment that was sprited for me to be implemented.

Role - Sangheili Ultra
Item - Energy Sword

https://cdn.discordapp.com/attachments/563947940675190794/694545619133661214/Bota_L-R_hand.dmi
https://cdn.discordapp.com/attachments/563947940675190794/694545620786217061/Bota_Swordd_1.dmi

**Comment by caelaislinn** [comment]
What is your ckey?

**Comment by AttackHelicopter6784** [comment]
> What is your ckey?

It's AttackHelicopter6784
