### ISSUE TITLE
Moray space mines currently use placeholder sprites

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#237]
As per https://projectunsc.org/showthread.php?tid=198

32x32 Moray Space Mines (animation states needed: inactive state, deploying state, active state, warning state, detonation imminent state)

**Comment by Kmc2000** [comment]
Working

**Comment by Kmc2000** [comment]
[https://cdn.discordapp.com/attachments/282688229784944641/282866604826558464/spacemine.dmi](url)

**Comment by BDpuffy420** [comment]
I have the sprite now
