### ISSUE TITLE
Cargo elevators for ships and stations

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#238]
This one shouldn't be a major project, but it will need to be carefully done with the turf changes making sure that proper safety checks are done. 

Specifications: define an editor placed effect marker, a platform turf, gearchain machinery and a console machine. When New() is called on the effect markers it will create the largest rectangle possible via adjacent marker of the same type then spawn the platform turf on every rectangle turf and delete all the effect markers. 

The platform can move up or down zlevels (at a delay) as long as there is space above or below and at least 1+ adjacent wall. Optional: have the gearchain machinery also required to be adjacent (?)

Some of this stuff is flexible according to whats achievable. The important thing is that there's an alternative to stairs, and also this is the only way to effectively move cargo between zlevels (ie using the cargo tug). 

There are also sprites floating around somewhere done by Krautzky, poke him or myself to get hold of them.

**Comment by BDpuffy420** [comment]
Included in new baycode
