### ISSUE TITLE
Job access to lockers and other items still broken

### ISSUE THREAD

**Issue by BDpuffy420** [HaloSpaceStation/HaloSpaceStation13#240]
The new jobs we have still can't interact with lockers to APC also the Nanomeds.

**Comment by caelaislinn** [comment]
@bloc97 you up to tackle this one?

**Comment by X0-11** [comment]
Tried this on a private server, looks like it works, could anyone provide a list of broken jobs and their needed access?

**Comment by caelaislinn** [comment]
Someone will need to go over all the jobs and check their access individually. You can find all the jobs in code\modules\halo\unsc_ship\

Most of the conflicts were in SS13 stuff being reused by the new jobs, so most should be working. Just check over the jobs list and make sure the relevant personnel have access to APCs, nanomed vendors and the gun lockers in the armoury.

**Comment by BDpuffy420** [comment]
this is still an issue with some of the nanomeds

**Comment by bloxgate** [comment]
Normally I'd say we should assign this to the mappers, but are we sure the right permissions exist for the antag groups?

**Comment by BDpuffy420** [comment]
not sure

**Comment by caelaislinn** [comment]
All the content that is relevant to this issue is out of date. It may crop up again but it was specific to content that isn't currently live

**Comment by bloxgate** [comment]
No, this is still happening with the innie medical bay. They're unable to use any of the medical vendors inside the medbay. Should be make a separate issue for that?

**Comment by caelaislinn** [comment]
Using the default SS13 gear will bring across the default SS13 access permissions which expect us to be using the default SS13 jobs. Hmm. I think we'll need to talk to the mappers about this.
