### ISSUE TITLE
Nav Chips from Spawned Ships Fragment When Taken Out

### ISSUE THREAD

**Issue by loafe** [HaloSpaceStation/HaloSpaceStation13#2406]
#### Description of issue
Before the LB and the ship calling feature, when shuttles still existed, it used to be that when you took the Nav Chip from a shuttle, it would fragment, and the Covies would need to collect 3 (4?) to get a full chip. Since the update, the spawnable ships are treated as disposable, so what happens is 
a new player calls a transport ship, flies to wherever the fuck, and leaves the chip in there, where the Covies go and yoink it for easy points.

Seeing as this makes winning as UNSC very hard since there are basically just free points sitting in orbit of VT all of the time, I propose that the nav chips should fragment when they are taken out, much like the shuttle, giving some point balance to objectives in terms of difficulty.

This can of course apply to Covenant Nav Chips as well, but they are pretty much worthless to the UNSC, so you could save yourself the coding if you are inclined.

(https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Delnth** [comment]
Could also make it so all navchips are encrypted by default and must be used on a console to decrypt it. It could take more complicated work such as require multiple navchips and stuff like, or just some time. 

CM-like, with codes and "mini-games", albeit on a smaller scale with less number-oriented requirement.
