### ISSUE TITLE
Mapping Feedback

### ISSUE THREAD

**Issue by ShadowCommander** [HaloSpaceStation/HaloSpaceStation13#241]
Currently it's hard to tell which rooms are dangerous and which aren't.
To fix that we need:
Emergency Doors
Air Alarms to trigger them
Fire Alarms to manually trigger the doors

Security Cameras are needed for security and command so that they can quickly check areas for intruders.

Space/Pressure suits are needed in the ship, preferably where anyone can grab one, but at least in engineering.

**Comment by caelaislinn** [comment]
Air alarms, fire alarms and emergency doors are easy enough, but mapping in vents and scrubbers will be a large job. There is space set aside (somewhere...) for atmospherics though.

**Comment by caelaislinn** [comment]
Map (out of date): unsc_frigate.dmm

**Comment by DoctorOctopusTheOctopi** [comment]
All of this has been addressed in #482
