### ISSUE TITLE
Enable 'WASD' control for fighters when the player is in hotkey mode

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#242]
As suggested by @tophatpenguin on discord.

**Comment by bloc97** [comment]
W/D should be thrust, and A/D for turning the ship, that would be most intuitive.

**Comment by caelaislinn** [comment]
Doesn't play nicely with the fixed perspective in 2D top down. The suggestion someone else gave was a control scheme where you automatically thrust to while turning towards the arrow key you press which I think is more intuitive.

**Comment by bloc97** [comment]
Or just WASD to thrust towards the direction, while also allowing diagonals movement.

**Comment by bloc97** [comment]
But I think both schemes are acceptable since the one I proposed is similar to the Asteroids game.

**Comment by caelaislinn** [comment]
Old code
