### ISSUE TITLE
Plasma pistol overcharge

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#2443]
- Does not reset after firing
- Sprite does seem to reset
- Can be spammed while in overcharge mode
- Should overheat after overcharging
- Needs a separate bullet sprite to show it's overcharged
- Needs to instantly drain target shields

**Comment by X0-11** [comment]
Instead of resetting after firing, couldn't it get a much lower overheat capacity when on overcharge so you can only really fire 1/2 shots before a long delay is incurred?

**Comment by caelaislinn** [comment]
#2546
