### ISSUE TITLE
[SUGG] Make the glassing beam an actual glassing beam

### ISSUE THREAD

**Issue by Delnth** [HaloSpaceStation/HaloSpaceStation13#2447]
As stated in the title, make the glassing beam an actual beam. Have it shoot a continuous beam down at the surface of a planet, obliterating everything in its wake whilst also spreading the 'glass', which would eventually reduce any lifeforms to dust, much like the bluespace tile, which spreads on its own at a slow rate. As it stands, the glassing projector is nothing than a glorified orbital bombardment device, except that it has a bigger radius than it's counterpart.

Along with such mechanic, there would be an incentive to stop the glassing progress, as each second would move the planet toward a point where it is no longer inhabitable for that time being. It would be a 'progressive event'.

I suggest a modest 0.5 progression per 1.5 seconds (90 seconds).
100 / 0.5 = 200
200 x 1.5 = 18.000
18.000 / 60 = 300

It would take five minutes to glass a world. Unless the tired idiot that I am can't do math anymore, that should be it. I personally believe it would be a -very- short frame to act upon, but after all, it shouldn't be too easy.

**Comment by X0-11** [comment]
the glassing beam isn't meant to actually be able to cover the entire game map in glass for the sake of player sanity, they can still escape, the planet is just marked as glassed

the orbital bombardment beam has a lower radius than the MAC bombardment device, and the usage as an orbital support weapon is intended

**Comment by Delnth** [comment]
The point of this suggestion is to make it an actual glassing beam, as stated previously. Because, again, right now it is nothing but a more powerful bombardment device. It also doesn't make sense for a planet to be recognized as "glassed" although there has been only occurrence of the projector beam actually hitting the ground. 

The radius is not even as big as Geminus' hospital. Also it wouldn't cover the map in a single hit. As I said, it would be a **progressive event**, where opponents must rush/hurry to stop the projector. It is not going to be overwhelming if they all work together to bring it down and, of course, if this feature is implemented correctly.

Having something of the sort would give players a better goal to achieve, rather than just hope they don't get hit by some random beam. There would still be a warning message sent to all players, like: 

> The sky is set ablaze by an bright, ominous purple storm.

This would be the warning notice to all players on the map that the glassing beam is charging and will start blastin' sooner than later. Again, as it stands, the glassing projector is just a better alternative to the bombardment option. And one single "hole" really doesn't make it feel like it's a projector meant for glassing.

**Comment by X0-11** [comment]
it's a solid idea, it's just that you're asking for a completely different item. the projector beam used for orbital bombardment and ship combat within the server is not meant to serve the role of a doom clock

**Comment by Delnth** [comment]
No. I don't think I am. Otherwise, why does the Covenant have a glassing objective? Unless the Covenant were glassing planets with an orbital bombardment device all along, I don't see that as being a completely different item. We have the mechanic for it already.

It's not a doom clock, it's just how glassing work in the lore. I just actually bothered about how to balance it so that opponents may have a window to act upon in order to counter it. As I keep saying, it'd likely be more interesting to fight against something like that rather than a simple explosion and calling it a glassing. 

Additionally, at map loading, each map would calculate the numbers of turfs they have and transform it into a percentage. Turfs covered by the spreading glassing effects would be removed from the percentage, reaching zero would make it properly glassed.

**Comment by X0-11** [comment]
it is functionally a doom clock, the weapon is literally not intended to cover the entire map with lava

it doesn't matter that it's "lore accurate", ships in lore didn't do this shit without multiple vessels, and it wasn't just the beam, all the weapons of the ship were usable for glassing.

indexing literally every turf just so we can track their destruction later on is incredibly inefficient and would add nothing to the experience as well as being much harder to tweak and control

currently glassing is 5 shots within orbital distance, which already provides an object wide message and is sufficent warning to groundside players to respond quickly lest they lose their objective and the associated points
