### ISSUE TITLE
Marine boots incorrect inhand sprite

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#2454]
Working:
/obj/item/clothing/shoes/marine/elmsville
/obj/item/clothing/shoes/marine/orion
/obj/item/clothing/shoes/marine
/obj/item/clothing/shoes/marine/crewman

Broken:
/obj/item/clothing/shoes/marine/brown
/obj/item/clothing/shoes/marine/winter
/obj/item/clothing/shoes/marine/riley
/obj/item/clothing/shoes/marine/karmac
/obj/item/clothing/shoes/marine/sleepy_retard

To fix: change var/item_state to "boots"

**Comment by CdrRiley** [comment]
whats wrong with the sprites?....
