### ISSUE TITLE
Two bugs found

### ISSUE THREAD

**Issue by billymom2** [HaloSpaceStation/HaloSpaceStation13#2455]
#### Description of issue
First bug is that the shadow vehicle transport main gun does not work it only goes click then please wait it not ready to fire, xo guess it mismatch ammo type, second bug the experiment projector ship is broken I loaded one it the device said I attempted to connect that worked then when I wanted to cross over it I could not then a minute later it disconnected and when I check the overmap it was gone not sure if it even spawned in 

#### Difference between expected and actual behavior

Experiment projector ship loading in properly

#### Steps to reproduce 

try loading experiment ship and firing shadow gun

#### Length of time in which bug has been known to occur
 About a day

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: ca75bf198cf8e17665e5d7357632b04c294df1c5 - alpha - 
Game ID: b7k-ap1t
Current map: Geminus City

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by caelaislinn** [comment]
Please make a second issue for the projector screen not loading in properly
