### ISSUE TITLE
T'vaoan helmet sprite is invisible

### ISSUE THREAD

**Issue by CommodoSix** [HaloSpaceStation/HaloSpaceStation13#2458]
#### Description of issue

Despite wearing the commando/murmillo helmet it does not show up on the t'vaoan sprite.

#### Difference between expected and actual behavior

Expected behavior: Helmet is visible.

Actual behavior: Helmet is invisible.

#### Steps to reproduce 

Join as either t'vaoan commando or murmillo.

#### Length of time in which bug has been known to occur

I've only been back for two days, so at least for the last two days.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by caelaislinn** [comment]
#2504 i think
