### ISSUE TITLE
Getting into a fighter makes a mob "float" in space and doesn't cancel it

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#247]
You can hear your heartbeat, and used to be able to see jetpack particles.

**Comment by bloc97** [comment]
The heartbeat part is handled in /mob/living/carbon/human/proc/handle_heartbeat(), should be pretty easy to disable the sound while in a vehicle.

As long as there is a turf and gravity beneath you, I think the code automatically counts it as not floating in space.

According to the handle_heartbeat, there is no real "floating" variable to check for the mob, though I can be mistaken. I think there should really be a boolean somewhere to check if a player is in space, and replace every other checks with a simple if(isInSpace) check.

**Comment by BDpuffy420** [comment]
Old issue
