### ISSUE TITLE
Extending Big Boom Timers

### ISSUE THREAD

**Issue by loafe** [HaloSpaceStation/HaloSpaceStation13#2471]
#### Description of issue
The vibe I currently get from the server is that nuke/AM bomb/Slipspace bombs has too short of a timer, and/or defusal takes too long. Currently, with a 60 second defuse time, the defenders have 180 seconds to get past whatever bolted doors, defenders, and other random bullshit may be in the way. If you are fighting tanky enemies like brutes, or Spartans if you are playing as the Covenant, this leaves little to no window to actually defuse the bomb, even if you kill all of the attackers. 

I understand why defusal takes so long, since you don't want someone to just run up and click it with 10 seconds left to defuse the bomb. But getting to the bomb with 59 seconds left, and knowing that you are just fucked is kinda a sour feeling, considering that is 25% of the bomb's timer. 
 
Considering the size of this event in a given round (being either the end of the first phase or the end of the round, depending on the faction), I think that the defenders should be given either more time to defuse the bomb, or have the bomb take less time to defuse. 

(https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by caelaislinn** [comment]
Yeah I'm not a fan of cov counter hacking doors to interfere with the UNSC on their own station. Having an AI isn't 100% guaranteed so it's an unpredictable challenge to overcome

**Comment by X0-11** [comment]
I don't see the problem with this at all. The ODP isn't meant to be eternally defended, and you're supposed to stop the thing from getting armed in the first place, the countdown timer is just a grace period of either disarming it if it was stealthily done, or fleeing

**Comment by X0-11** [comment]
addressed in #2470 by reducing disarm-time by half
