### ISSUE TITLE
Player hacking should be able to counter AI hacking

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#2472]
At the moment, the only way to counter a Covenant AI hacking into the ODP is a UNSC AI. We can't rely on an AI always being available to counter the Covenant AI, so there should be a way for a UNSC player/s to counterhack the ODP.

**Comment by loafe** [comment]
Also, there is no UNSC AI job slot, so there can't even be AI vs AI EWAR.

If covies manage to get an AI on board, the AI can do whatever the fuck it please with no resistance.

**Comment by caelaislinn** [comment]
#2475
