### ISSUE TITLE
Re-enable Reclamation Spartans & More than 1 ODST Officer Slot

### ISSUE THREAD

**Issue by loafe** [HaloSpaceStation/HaloSpaceStation13#2480]
#### Description of issue

Spartans are not currently enabled in Reclamation according to XO, and I dunno why, so perhaps they should be reenabled

Also, ODST Officers only have a single slot, meaning that only 1 person can spawn as ODST officer. Considering the activity of the officers, it might make sense to give 1 or 2 more slots.

**Comment by loafe** [comment]
I'm going to bump this and add an addendum. 

I know that Spartans are planned for phase 3, and I will wait until that comes out to make a full judgement. But in a standard 2 hour round, phase 2 either doesn't finish or barely finishes, with the majority of fighting being in that phase 2.

Likewise, with the recent changes to the loosening of the roles restricted to Covenant whitelist, there has been a significant amount of Covenant power roles that spawn in over the course of a round. The result of the power roles is marines getting stomped to no end, and frankly, losing every single round isn't that fun, especially when even an entire squad can't take a couple brutes or a couple of elites. 

I know Spartans were disabled for balance reasons, but there is already a Spartan poplock in place, which uses a formula which approximates to 6 Covies living per Spartan. Considering that two or three or three of those 6 will be a power role, it is not entirely unfeasible to think that a single power role for the UNSC might balance the scales a bit. 

The other thing as well is that Spartans are just not as strong as they used to be. They don't move as fast, dual wielding was removed, and their shields break relatively easily. Due to the changes to the Beam Rifle, the Spartan shield pops in 1 shot, and the Spartan takes a bit of damage along with it. Considering that ODSTs now have the same armor values for their armor as marines, the UNSC has no true power role, and as a result, is fairly weak in infantry combat compared to the Covenant. 

Once again, I am going to wait for Phase 3 to be released to make a full judgement, but perhaps a trial period where Spartans can participate in Phase 2 would help get an idea of how it affects the balance of a round. If the general consensus is that it throws a wrench into round balance, I would be perfectly happy letting them stay on Phase 3.

**Comment by X0-11** [comment]
i'm not sure where you heard the spartans-are-in-phase-3 thing from, but i don't recall that

**Comment by loafe** [comment]
Cael said it

**Comment by X0-11** [comment]
and now i know. thanks
