### ISSUE TITLE
UNSC and Covenant can enable each other's payload

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#2484]
This was a semi intentional oversight, but I'm not happy with how the gameplay is panning out - it makes things too easy for each team to destroy the other's stuff. I'd like to disable them triggering it, but keep in each team being able to disable the other team's payload.

**Comment by CommanderXor** [comment]
If this is passed through, how exactly is the Covenant meant to destroy the ODP and progress to Phase Two if they can't enable the self-destruct?

**Comment by caelaislinn** [comment]
Via their own antimatter bomb

**Comment by Sgtwok** [comment]
Going to have to disagree with this strongly. The end result would be the exact same except now they are towing an object behind you. There's no reason to remove the feature.

**Comment by X0-11** [comment]
Disagree due to reasons stated in discord ping
