### ISSUE TITLE
[Suggestion] Covenant EVA gear lacks MagBoots, we should give them some.

### ISSUE THREAD

**Issue by 24THBN** [HaloSpaceStation/HaloSpaceStation13#2489]
#### Description of issue
The Covenant lack any sort of Magboots, which is curious considering the UNSC do have, when they are not usually required on EVA as much as the Covenant do, considering they mostly land outside their Orbital Platform to destroy it, and when entering into a pressurized area, or an area with gravity, they get knocked down instantly and become really vulnerable.

#### Difference between expected and actual behavior
I expected that EVA gear would be prepared for shifting gravity as much as the EVA gear does with they big yellow magboots.

#### Steps to reproduce 
If you wish to reproduce this problem we currently have, look not further than just walking into an area with gravity from space wearing any gear from the Covenant Arsenal.

#### Client version, Server revision & Game ID

 73e7b2193bf525760d0d283e04f0126c04e40a5c - alpha - 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by caelaislinn** [comment]
#2551
