### ISSUE TITLE
[Map] ODP Cassius needs to have APCs, wiring and generators mapped

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#2499]
Currently it is powered by magic. Adding in proper power systems would make it feel more like a living, breathing space station.

**Comment by Flaksim** [comment]
This was mostly done because the covenant ship is powered by "magic" aswell, as we had no generator alternatives for them.

Having one side rely on power generation and easily losing it in a lucky hit, whilst the other side has no such constraint seems unbalanced?

**Comment by X0-11** [comment]
nobody's actually going to bother reparing it either
