### ISSUE TITLE
Me commands being double posted

### ISSUE THREAD

**Issue by BDpuffy420** [HaloSpaceStation/HaloSpaceStation13#250]
A bug I've noticed that has come up is whenever someone makes a me command  emote, for some reason that said command is posted twice in a row in-game.

**Comment by bloc97** [comment]
In /mob/proc/custom_emote, /atom/proc/visible_message and /atom/proc/audible_message were being duplicated as code.
Fix attempt in #253

**Comment by BDpuffy420** [comment]
Update on this?

**Comment by caelaislinn** [comment]
Fixed #253
