### ISSUE TITLE
Make a viewable map of the UNSC frigate

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#251]
A lot of people are confused by the layout, and although the department arrows help it's still difficult to find your way around. There used to be a script for this, but you could also easily just scroll around stitching together screencaps.

**Comment by X0-11** [comment]
![unsc_frigate-2 dmm 0](https://cloud.githubusercontent.com/assets/17511708/26763622/a590f2d4-494d-11e7-836f-1495631939b9.png)
![unsc_frigate-3 dmm 0](https://cloud.githubusercontent.com/assets/17511708/26763623/a597be2a-494d-11e7-8d56-5eea6b15b21d.png)
![unsc_frigate-4 dmm 0](https://cloud.githubusercontent.com/assets/17511708/26763624/a59e4b96-494d-11e7-9178-a268daf7ca9a.png)
![unsc_frigate-1 dmm 0](https://cloud.githubusercontent.com/assets/17511708/26763625/a5a40342-494d-11e7-9389-eacc176288e1.png)

**Comment by caelaislinn** [comment]
Can you put these into an imgur album then pin it in Discord and make a forum post? Ta. If you or someone can go over the images and put departmental labels on the different areas that would be great as well.

**Comment by X0-11** [comment]
http://imgur.com/a/1b5PR
