### ISSUE TITLE
ONI Complex Issues/Suggestions

### ISSUE THREAD

**Issue by CommanderXor** [HaloSpaceStation/HaloSpaceStation13#2510]
Made because Cael and XO asked me to compile issues.

1) The ONI Chemical Dispenser in the lab has no chemical cartridges.
2) There is a significant lack of materials. There's only two stacks of steel, one stack of plasteel, and two stacks of glass. There needs to be much, much more, and also gold/uranium/silver/diamond.
3) RnD can not print HRUNTING boards and thus they must be spawned in at roundstart/enable them to be printed.
4) There are no tool vendors. Thus no machines can be made. There needs to be more complex stuff like ROBCO tool dispensers, radiation suits, welding masks, etc.
5) There are no fuel/water tanks in the entire facility.
6) The medical vendor is a default SS13 one instead of the UNSC ones. Also, there's literally just one of them.
7) There are no sinks in the medical bay/OR to clean tools and items.
8) There are no sterile masks and gloves in the OR.
9) An anesthetic tank is a wall-mounted unit that can only be used next to it...and it's on the other side of the room of the surgery table.
10) Orion organ crates do not spawn.
11) There is no meat/biomass storage to fuel the bioprinter in medical.
12) Covenant can enter the base and kill everyone despite the 'bump teles are meant to be faction locked'
13) The medical bay only has small beakers, they need bluespace beakers, or at the very least large beakers.

**Comment by caelaislinn** [comment]
12 is still an issue but im closing this for now
