### ISSUE TITLE
Loaf Donor Armor Update/Fixes

### ISSUE THREAD

**Issue by loafe** [HaloSpaceStation/HaloSpaceStation13#2523]
#### Description of issue
My ODST donor armor doesn't spawn when I select anything other than Orbital Drop Shock Trooper on the job menu (this does not include subjobs like ODST Medic, ODST Sharpshooter, etc.). It also does not spawn when I spawn in as ODST Officer, with the same issue with subroles.

Also, I have new armor, so the sprites need to be updated.

#### Difference between expected and actual behavior

It should spawn in no matter what type of ODST I try to spawn as. 

#### Steps to reproduce 

>Log in with the Loafe CKEY
>Choose ODST job other than default
>Not have armor 
>what

#### Specific information for locating

It is the Loafe armor sets in the odst.dmi file. 

HaloSpaceStation13-alpha\code\modules\halo\clothing\odst.dmi

I think the actual title of the armor is loafe-armor-worn and loafe-helmet-worn.

#### Length of time in which bug has been known to occur
Since the Rec/Firefight Update

#### Other

Link to new armor download:
[https://cdn.discordapp.com/attachments/672175740426387456/719346408330887218/ODST_loaf_2.dmi](url)

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x ] Issue could be reproduced at least once
- [x ] Issue could be reproduced by different players
- [x ] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [x ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by caelaislinn** [comment]
What jobs does it spawn correctly as?

**Comment by loafe** [comment]
Orbital Drop Shock Trooper. Only for that class specifically will it spawn. If I select any subjob (like ODST Close Range, or ODST Sharpshooter) it doesn't work. It doesn't work for any ODST officer role.

**Comment by caelaislinn** [comment]
Can you send me the new donor sprites? I'm putting up a fix for donor gear spawning on alt titles. The officer is a separate job which makes it a hassle to deal with
