### ISSUE TITLE
New Bugs

### ISSUE THREAD

**Issue by loafe** [HaloSpaceStation/HaloSpaceStation13#2535]
#### Description of issue

3 Bugs:

1. Hyposprays no longer inject if you are wearing armor, instead bouncing off like it was an attack
2. The windows around the MAC inside the ODP have atmos shutters, which are still broken in terms of tiling.
3. When you have no oxygen anymore, there is no icon for an O2 alert, it just flashes NO ICON across your screen where the O2 warning would be.

#### Difference between expected and actual behavior

1. Hyposprays used to inject past armor no problem. 
2. Most of them have been fixed, but their sprite aligns within the window, but when they are deployed they block a portion of the hallway.
3. There should be an O2 icon when you have no air

#### Steps to reproduce 

1. Try to use a Hypospray while wearing ODST or Marine armor
2. Depressurize the SMAC room, and when the windows fall, try to walk on the wall close to them
3. Be in a depressurized room with no oxygen

#### Length of time in which bug has been known to occur

Since the last merge

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by caelaislinn** [comment]
Can you split these into 3 issues please?

**Comment by caelaislinn** [comment]
Can this be split into 3 issues please?
