### ISSUE TITLE
Turning while in cruise breaks the ship rotation.

### ISSUE THREAD

**Issue by bloc97** [HaloSpaceStation/HaloSpaceStation13#254]
If you rotate the ship using ctrl+arrowkey while in cruise, the rotation is updated in the overmap, but the real rotation of the ship does not change, and after exiting cruise, some angles can't be reached when rotating.

**Comment by DoctorOctopusTheOctopi** [comment]
Unable to replicate issue, issue is also a year old so it probably got fixed way back when.
