### ISSUE TITLE
Hyposprays do not inject past armor

### ISSUE THREAD

**Issue by loafe** [HaloSpaceStation/HaloSpaceStation13#2542]
#### Description of issue

Hyposprays don't inject past armor, instead bouncing off. 

#### Difference between expected and actual behavior

It used to inject through the armor, so it shouldn't bounce off.

#### Steps to reproduce 
Get a hypospray

Fill it with anything

Try to inject while wearing armor

Fail miserably

#### Length of time in which bug has been known to occur

3 days or so

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x ] Issue could be reproduced at least once
- [x ] Issue could be reproduced by different players
- [ x] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [ x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by X0-11** [comment]
#2545
