### ISSUE TITLE
ODP MAC Emergency Airlocks are Misplaced

### ISSUE THREAD

**Issue by loafe** [HaloSpaceStation/HaloSpaceStation13#2543]
#### Description of issue

The airlocks in the window surrounding the MAC on the ODP clip into the hall, when they should stay in the windows

#### Difference between expected and actual behavior
They should stay in the windows

#### Length of time in which bug has been known to occur

Since the ODP was readded

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ x] Issue could be reproduced at least once
- [x ] Issue could be reproduced by different players
- [x ] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [x ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by caelaislinn** [comment]
It's a directional thing. Easy to fix but painstaking to find in the map editor. One of the eshutters in the memorial garden have the same problem 
![318f08b310458c4d80fc6c0e68021eca](https://user-images.githubusercontent.com/1035969/84559261-5f9e9600-ad7c-11ea-9f94-fc7795bd6e18.png)

**Comment by caelaislinn** [comment]
#2553
