### ISSUE TITLE
Runtime in reader.dm, line 223: Cannot create objects of type null.

### ISSUE THREAD

**Issue by X0-11** [HaloSpaceStation/HaloSpaceStation13#2558]
proc name: instance atom (/dmm_suite/proc/instance_atom)
usr: Yanme'e 347 "Servitor" (/mob/living/carbon/human) ([0x30000b3]) (Nanolaminate Flooring) (77,80,7) (/turf/simulated/floor/covenant) (ondrej008)
usr.loc: Nanolaminate Flooring (/turf/simulated/floor/covenant) ([0x1064303]) (77,80,7) (/area/covenant_light_cruiser/bridge)
src: /dmm_suite (/dmm_suite)
call stack:
/dmm_suite (/dmm_suite): instance atom(null, /list (/list), 46, 29, 14)
/dmm_suite (/dmm_suite): parse grid("/obj/machinery/door/airlock/co...", 46, 29, 14, 0)
/dmm_suite (/dmm_suite): load map('maps/npc_ships/req_console_shi...', 14, null, null, 0)
Ship (/obj/effect/overmap/ship/npc_ship/shuttlecraft/cov_trooptransport): load mapfile()
Ship (/obj/effect/overmap/ship/npc_ship/shuttlecraft/cov_trooptransport): make player controlled()
Long Range Requisition Console (/obj/machinery/shuttle_spawner/multi_choice/cov): spawn shuttlecraft()
Long Range Requisition Console (/obj/machinery/shuttle_spawner/multi_choice/cov): attack hand(Yanme\'e 347 \"Servitor\" (/mob/living/carbon/human))
Long Range Requisition Console (/obj/machinery/shuttle_spawner/multi_choice/cov): attack hand(Yanme\'e 347 \"Servitor\" (/mob/living/carbon/human))
Yanme\'e 347 \"Servitor\" (/mob/living/carbon/human): UnarmedAttack(Long Range Requisition Console (/obj/machinery/shuttle_spawner/multi_choice/cov), 1)
Yanme\'e 347 \"Servitor\" (/mob/living/carbon/human): ClickOn(Long Range Requisition Console (/obj/machinery/shuttle_spawner/multi_choice/cov), "icon-x=6;icon-y=13;left=1;scre...")
/datum/click_handler/default (/datum/click_handler/default): OnClick(Long Range Requisition Console (/obj/machinery/shuttle_spawner/multi_choice/cov), "icon-x=6;icon-y=13;left=1;scre...")
Long Range Requisition Console (/obj/machinery/shuttle_spawner/multi_choice/cov): Click(Nanolaminate Flooring (70,81,7) (/turf/simulated/floor/covenant), "mapwindow.map", "icon-x=6;icon-y=13;left=1;scre...")

I would assume this is due to typepaths of airlocks being changed without replacing them on these maps.

**Comment by caelaislinn** [comment]
Hmm, I didn't touch any Covenant airlocks. It was only UNSC ones plus multitile blast doors.

**Comment by caelaislinn** [comment]
Is this still happening?

**Comment by X0-11** [comment]
No, it was fixed by reincluding the file containing the required airlock subtypes
