### ISSUE TITLE
Needle Rifle Does NOT Show On Your Person When Held in the Right Hand

### ISSUE THREAD

**Issue by Tupinambis** [HaloSpaceStation/HaloSpaceStation13#2568]
#### Description of issue

If you hold the needle rifle in your right hand, it will appear as though you hold nothing.

#### Difference between expected and actual behavior

I'd expect it to be mirrored to the appearance of holding the needle rifle in your left hand. Or to appear on your person at all.

#### Steps to reproduce 

Put a needle rifle in your right hand.

#### Length of time in which bug has been known to occur

Unknown

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: 75780b5

#### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this]

**Comment by X0-11** [comment]
Which species encounter this issue?

**Comment by Tupinambis** [comment]
> Which species encounter this issue?

From brief testing I've found both Kig'yar and T'vaoans encounter this issue. Unsure about others.

**Comment by caelaislinn** [comment]
Same problem #2564
