### ISSUE TITLE
Lessen the Radioactive/Blood Deletion effect of the Beam Rifle

### ISSUE THREAD

**Issue by loafe** [HaloSpaceStation/HaloSpaceStation13#2569]
#### Description of issue

Currently, the UNSC and Covenant weapons have some gimmicks. UNSC weapons do brute damage and give shrapnel, while Covenant weapons do burn damage, delete blood, and (some) give rads. 

Recently, Cael made it so shrapnel is not as dangerous as it once was. While I agree with this change, I think there should be some counter nerf to Covenant weapons, especially the beam rifle. 

Currently, if a UNSC and Covenant Sniper are duking it out, the Covenant sniper will win about 90% of the time. The reason for this is: if the UNSC sniper hits the Covenant sniper twice, the sniper takes a FUCK ton of damage, but is overall not that damage, and can heal pretty easily. Even if they start bleeding from the aorta, they won't lose that much blood if they just inject some biofoam. 

On the contrary, if a Covenant sniper hits the UNSC sniper twice, the UNSC sniper loses about 15% of their blood, which can only be fixed if that person takes iron pills, which for ODSTs and Spartans takes a pretty significant amount of time. Likewise, the UNSC sniper takes the massive burn damage, and also gets rads, which after about 10 seconds causes the person to throw up and be stunned for about 10 seconds. While I understand that the damage is the same, Covenant snipers are massively more effective than UNSC snipers simply for the extra effects that come with Covenant weapons. And considering certain classes within the Covenant already have an advantage when it comes to sniping (namely T'vaoans), a single Covenant sniper can pretty much wipe the entire UNSC by just shooting and running away over and over again. Even if the UNSC packs a sniper, that sniper will almost certainly get beat in a sniper duel. 

Because of this, I propose that either one of these effects (radiation or blood deletion) gets nixed entirely, or that both be reduced significantly. Being entirely frank, it isn't fun to pass out from blood loss after taking 3 beam rifle shots when you just hit the opposing sniper 3 times yourself, and they walked away fine.

**Comment by X0-11** [comment]
The blood-loss effect can be countered with the same chemical as unsc weapons can. Radiation will be looked into.

**Comment by loafe** [comment]
Iron? Iron can only be effective if ingested in pill form, which for ODSTs requires you to stop, take off your helmet, and take the pill. If you are bleeding from the aorta, you inject 5u of biofoam with a hypospray and are vibin
