### ISSUE TITLE
T’vaoan Spelled Wrong

### ISSUE THREAD

**Issue by SuckMySocks** [HaloSpaceStation/HaloSpaceStation13#2574]
T’vaoan roles are spelled wrong.
in game they are spelled “T’voan”. 
pretty sure this is for all T’vaoan roles. 
should be spelled “T’vaoan”
Pls fix

**Comment by caelaislinn** [comment]
This is related to reserved character issues. It's a tricky one to set right and has the potential to break the game depending on how tell tested the "fix" is

**Comment by 5crownik007** [comment]
Except it's spelled that way on Halopedia and Halo Alpha https://www.halopedia.org/T%27vaoan
