### ISSUE TITLE
AI access node routing being very finnicky and bugging out with freshly hacked nodes that are apart of a different system than the ship/station the AI initially spawned in.

### ISSUE THREAD

**Issue by Cursedcookie** [HaloSpaceStation/HaloSpaceStation13#2577]
#### Description of issue 
I was covvie AI and got slotted into the ODP. I hacked multiple nodes to access 4, but repeatedly i'd get a 'you need level 3 access' when trying to interface with doors. Now, i could easily air siphon, bolt and electrify doors ALA level 4 access. But the level 3 things would sometimes work on one level 4 node, then not work on another level 4 node.

#### Difference between expected and actual behavior
I should have access to the whole slew of level 1, 2, 3 and 4 abilities from nodes. Instead it gives me a very finnicky smattering of level 1, 2 and 4 abilities.

#### Steps to reproduce 
Slot an AI into a fresh access node terminal in an area it has no node access. Start hacking nodes and try and use the full slew of level 1-4 access and watch it bork out with trying to open or close doors/disable safeties/overide timing.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by caelaislinn** [comment]
This sounds like it could be a mapping issue, but I'm not familiar enough with the AI (it's a port from Bay12). When I remapped the ODP recently I just tried to copy what XO was mapping as much as possible.

**Comment by X0-11** [comment]
there's likely just some dodgy area-defs or lack of access nodes in places

**Comment by ghost** [comment]
Suffered the same issues myself.
