### ISSUE TITLE
Detonating the AM Bomb does not cause the CRS superstructure to fail

### ISSUE THREAD

**Issue by loafe** [HaloSpaceStation/HaloSpaceStation13#2584]
#### Description of issue
When the AM bomb on the Covenant flagship is detonated, it doesn't cause the superstructure to fail. It blows up the entire ship, but the superstructure failure sequence does not begin

#### Difference between expected and actual behavior

The superstructure should fail after the AM bomb explodes.

#### Steps to reproduce 

1) Arm the AM bomb
2) Let it it detonate, leaving the ship before it detonates
3) Go back 5 minutes later to see the ship still sitting there

#### Length of time in which bug has been known to occur

I don't really know, I last nuked the ship successfully about a week ago, so at some point after that

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [x ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by X0-11** [comment]
The CRS either does not have hull segements placed, or you did not eliminate enough hull segments
