### ISSUE TITLE
Spirit turret does not work, acts like it has no ammo even after using a repair/rearm station.

### ISSUE THREAD

**Issue by Alholidays** [HaloSpaceStation/HaloSpaceStation13#2585]
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by X0-11** [comment]
#2571
