### ISSUE TITLE
Snipers penetration doesn't break windows

### ISSUE THREAD

**Issue by Delnth** [HaloSpaceStation/HaloSpaceStation13#2586]
Be it the SRS or the beamrifle, on the ODP they never break the windows, which are projectile resistant. If they truly are, they should completely stop the shot, instead the bullet/beam penetrate the window and does its usual job. I've witnessed countless fights on the ODP where an ODST/Marine would engage covies during their EVA trip and shoot them through the window without even causing a breach. The windows are really tough, if all you have is a c12/plasma charge and no luck, it'll take three to blow the windows. All the while the marines can magdump their opponent safely.

Make it so projresist windows can stop sniper bullets/beam or break when hit.

**Comment by X0-11** [comment]
Stopping projectiles with projresist windows is easily doable
