### ISSUE TITLE
The General Donor Armour Thread

### ISSUE THREAD

**Issue by ghost** [HaloSpaceStation/HaloSpaceStation13#2589]
this is a reminder for the big dumb smelly nerd XO to put my donor armour into an autospawn box when he has time away from his 22 hour long coding sessions with cael.

I also need the files added for my super special reskinned gravhammer that would only spawn if I played a chieftain, which has been DMed to big dumb smelly nerd on discord

https://cdn.discordapp.com/attachments/568714596244914176/724730242778005605/bolter_hammer.dmi

https://cdn.discordapp.com/attachments/568714596244914176/724730213962874960/bolterhammer_obj.dmi

**Comment by loafe** [comment]
i will likewise hijack this issue to say that my donor box doesn't spawn on me when I spawn as ODST or CO, only when i spawn as sportan
