### ISSUE TITLE
Needler Supercomb Puts Holes in Floors

### ISSUE THREAD

**Issue by loafe** [HaloSpaceStation/HaloSpaceStation13#2591]
#### Description of issue
See title. Not sure if its intended, but it leads to quite a bit accidental venting and falling through floors. 

#### Difference between expected and actual behavior
I would expect it to explode, but not to the point where it puts a hole in the ground

#### Steps to reproduce 
Shoot needles at something until Supercomb on a ship or station
Witness hole
Get sucked into space

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x ] Issue could be reproduced at least once
- [x ] Issue could be reproduced by different players
- [x ] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [ x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by X0-11** [comment]
#2561

**Comment by caelaislinn** [comment]
Closing as other issue has more info
