### ISSUE TITLE
[BUG] NPC Grenades

### ISSUE THREAD

**Issue by Delnth** [HaloSpaceStation/HaloSpaceStation13#2593]
#### Description of issue
NPC do not **throw** grenades. They **spawn** at a given location. As long as they have vision on an enemy, they will spawn them. That means that they can even spawn grenades toward an enemy despite said enemy being behind a broken door. (Somehow, broken doors lose their opacity variable upon destruction)

#### Difference between expected and actual behavior
The grenade should obviously be stopped by whatever structure is present in its trajectory.

#### Steps to reproduce 
Have an NPC try to attack enemies behind a broken door.

#### Specific information for locating
Base SS13 doors seem to allow vision upon destruction. And I see no reason for all (halo) NPCs not to reproduce this behavior when the conditions are met.

#### Length of time in which bug has been known to occur
Just noticed it now.

#### Client version, Server revision & Game ID
Client Version: 513
Server Revision: 9fbc0fc8b315d016daad2f6a1c970b19e9a17210 - alpha - 
Game ID: b7O-b4nx
Current map: 111 Tauri - KS7 New Pompeii

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Sgtwok** [comment]
They do throw grenades, they've successfully been blocked by grinders.

Then it got them killed.

**Comment by Delnth** [comment]
This issue involves doors, not grinders.

**Comment by X0-11** [comment]
They still throw them. This is a door bug, not a grenade bug.
