### ISSUE TITLE
Large Waistpack Slowdown

### ISSUE THREAD

**Issue by BladeburstNINJA** [HaloSpaceStation/HaloSpaceStation13#2602]
#### Description of issue
When worn on your belt, the large waist pack causes greater slowdown than a backpack.

#### Difference between expected and actual behavior
A smaller, waistpack holding less stuff should not slow you down more than an actual backpack.

#### Steps to reproduce 
Take an empty large waist pack, equip it to your belt, walk around.

#### Length of time in which bug has been known to occur

Forever.

#### Client version, Server revision & Game ID

47794abd94e79acce403c54ca4a48e12435cd084
b7U-cJEG

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by X0-11** [comment]
This has been tweaked.
