### ISSUE TITLE
[bug] Spartans are unable to fit on autodocs

### ISSUE THREAD

**Issue by Joe44445** [HaloSpaceStation/HaloSpaceStation13#2608]
#### Description of issue

Spartans are unable to fit on the UNSC Autodocs to get healed. The same may also apply to Orions, but it certainly occurs with spartans.

#### Difference between expected and actual behavior
A spartan should be able to use a UNSC autodoc.

#### Steps to reproduce 
1.join as spartan
2.get hurt and need medical aid (i.e injured organs)
3.try to get on autodoc
4.cry when you turn out to be too dummy thick to fit on the autodoc

#### Specific information for locating

the autodoc needs spartans as an accepted species, i'd assume

#### Length of time in which bug has been known to occur

this has been a thing since spartans were added, before the Prowler they used to be stationed on was changed in order to fit spartans (or at the very least, varedited by staff when needed). Given the fact the Spartans are now deployed with mainline forces, it'd be nice if they could also use the autodocs.

#### Client version, Server revision & Game ID

N/A as it happens every round

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by caelaislinn** [comment]
#2612
