### ISSUE TITLE
[Suggestion] HRUNTING Balancing

### ISSUE THREAD

**Issue by 24THBN** [HaloSpaceStation/HaloSpaceStation13#2609]
#### Description of issue
Recent events have given me light of a certain issue when going against the HRUNTING Mech, I will give a list of what I have seen from them to give an idea of how overwhelming can they be, **but first I want to leave clear that none of these are the singular reason I feel they are Overwhelming or Overpowered, but its the combination that Mechs are capable of all of them at the same time**:

-**Manufactured**: First of all the Mechs are not ''_One of a kind_'', it doesn't matter if you already have one or yours got destroyed, you can always fabricate another Mech to add to the arsenal, leading to sometimes having to fight two or more Mechs at the same time. They are not also difficult to do so, as many players had show they are competent enough to produce them very quickly (As in, having two Mechs before being ready to attack the ODP.).

-**Speed**: The Mechs are capable to become so fast that they can outrun anyone on foot, making it impossible to keep distance with it and its overwhelming weaponry.

-**Weaponry**: The Mechs can easly deal with even the tankiest Covenants with a few clicks of its Machine Gun, leaving nobody chance to do anything against it but to try to helplessly run await from it for a slight chance at survival.

-**Slowdown**: The Mechs are **not** slowed down by how damaged they are, a fully intact Mech performs exactly as a heavily damaged one, with only some sparks spewing from time to time.

-**Knockdown**: The Mechs ability to punch and hit knocks down and makes characters helpless in the ground for a short period of time also dropping anything they have in their hands, this can easily be done multiple times given the Mech has the space to launch you, leading to you getting stunlocked and unable to do anything.

-**Single Manned**: The Mechs are able to be driven and gunned by a single person, that being in contrast with the rest of the UNSC vehicles, that require two persons to be fully manned, this point is confusing because one would thought that vehicles like the Scorpion require a different seat for the driver and the gunner for balancing reasons, but despite that, the Mechs firepower could be consider equal and their mobility greater than some vehicles, since **they do not drift like vehicles**.

-**No Consequence When Destroyed**: When a vehicle is destroyed, it stops and explodes, causing confusion and some damage to anyone that was inside, **This is not the case with the Mechs**, after its finally destroyed, the pilot is fully capable for escape or combat, leaving no consequence to a Mech being destroyed on top of them.

-**Easly Repaired**: The Mechs, despite all their tankiness and firepower, are easily repaired with either automatic drones, or simply by welding them, this is, again, in contrast with vehicles that require: inspection, materials and multiple tools, and a lot of time, to be able to be repaired.

-**Size**: The Mechs are of a very small size, specifically they are 1x1 tiles big, this means that its fully capable to enter anywhere any character is able to fit, and even where some vehicles are not even able to, this also causes a lot of difficulty trying to shoot it with Anti-Armor weaponry, due to their inaccuracy and dispersion, making them even more difficult to deal with, this is in contrast with say, the Scorpion, the Wraith, Warthog etc, because they are bigger than a single tile, making up for the Anti-Armor weaponry dispersion, and making them obvious targets due to the danger they impose in a battlefield due to their firepower.

#### Conclusion

While I can see the reason to want to have a mobile platform that also can give fire support and cover in the battlefield against enemies that are tanky like the Elites or the Brutes, I feel that having all these traits leads to a very overwhelming enemy, that was only countered by AT Weaponry (That has difficulty hitting it, and standing up to the Mech's oppressive firepower and knockdowns.) and EMP Charged Plasma Shots (That have been constantly nerfed in recent times, by making the Mechs more resistant to it, and having the Plasma Pistols unusable after a single shot for a period of time.) , it seems to me that it is no longer fun to go against it and it in fact can feel outright unfair to deal with, due to reasons stated above.

I kindly invite everyone to give their thoughts and opinions in the comments in a civilized matter, leaving this open for further discussion.

#### Difference between expected and actual behavior

Well, for starters I would expect to have a fair chance against the Mech and just not be simply outclassed in all manners no matter how prepared one is, and having the counters (AT/EMP) feel underwhelming compared to say, how effective a Sniper Rifle is against Shielding.

#### Steps to reproduce 

Everything listed can be reproduced in any round, simply by constructing Mechs and experimenting with them.

#### Length of time in which bug has been known to occur

--> This whole week by me, probably more by others that have not stated the issue in this manner.

#### Client version, Server revision & Game ID

Server Revision: 33d9a3ddc2d4f9c0a307d0c102aaa36bb1b5b2a8 - alpha - 
Game ID: b7X-cEt1

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by X0-11** [comment]
Tweaks have been made to the HRUNTING. Re-Open this issue if it still encounters balance issues
