### ISSUE TITLE
Armory Lockers causing Lockup on Opening

### ISSUE THREAD

**Issue by bloxgate** [HaloSpaceStation/HaloSpaceStation13#261]
Opening certain lockers in the armory causes intense lag lasting ~5 minutes. So far the sniper locker seems to be the most common culprit. We might want to remove the lockers from the armory and just replace them with some racks until we get the gun vendors put in.

**Comment by BDpuffy420** [comment]
#264 deals with this issue

**Comment by caelaislinn** [comment]
We need to test it to confirm first, and merging that doesn't actually fix the issue with the lockers
