### ISSUE TITLE
[Bug] Yanme'e (and Jetpacks) Unable to Transverse Space

### ISSUE THREAD

**Issue by CommanderXor** [HaloSpaceStation/HaloSpaceStation13#2610]
#### Description of issue

I talked to XO about the upcoming jetpack and Yanme'e ability to transverse Z-levels and brought up the fact that Yanme'e slip off edges easily and can get flung into space even when flying. This turns out to be a bug(heh) and isn't intended.

#### Difference between expected and actual behavior
Yanme'e, and Jetpacks are meant to be able to fly around in the void of space. As of right now, stepping onto space will send you in a straight line until you reach the end of the map and get deleted. The intended behavior is that you are meant to be able to move freely on these space tiles as Yanme'e/with a jetpack. 

#### Steps to reproduce 
1) Pick Yanme'e
2) Go to the ODP
3) Hug a wall in space
4) Push off a wall
5) Float into Space and die.

#### Specific information for locating
N/A

#### Length of time in which bug has been known to occur
Since the implementation of Yanme'e/Jetpack flight

#### Client version, Server revision & Game ID
N/A, latest server build.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by caelaislinn** [comment]
Fix in #2607 comment here if the problem hasn't been fixed
