### ISSUE TITLE
[bug] X Hammer X Hammer

### ISSUE THREAD

**Issue by Joe44445** [HaloSpaceStation/HaloSpaceStation13#2615]
#### Description of issue

the depowered brute hammer does not have an inhand sprite and appears as a big X over the person using it

#### Difference between expected and actual behavior
the hammer does not look like an X

#### Steps to reproduce 

grab hammer
notice massive cyan X over big bad brute

#### Specific information for locating

the depowered brute hammer, wish I knew the actual name for it

#### Length of time in which bug has been known to occur

since they've been added, so like a day ish?

#### Client version, Server revision & Game ID

N/A happens every round

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by ondrej008** [comment]
I think this was fixed, this should get closed.
@X0-11
