### ISSUE TITLE
Being flung through space at extremely high speed

### ISSUE THREAD

**Issue by BladeburstNINJA** [HaloSpaceStation/HaloSpaceStation13#2616]
#### Description of issue
Whenever I stand in space and the area around is destroyed, I'll get flung at extremely high speeds for no apparent reason into empty space with no means of getting out of it.

#### Difference between expected and actual behavior
Shouldn't be flung for zero reason.

#### Steps to reproduce 
Be on a destroyed vessel or station with the superstructure about to fail. Get flung?

#### Length of time in which bug has been known to occur

The recent jetpack update.

#### Client version, Server revision & Game ID

 fb1002d447a7a12e52b6261c7e7ff296d597ecb6
b71-douK

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by X0-11** [comment]
For what reason is the area around you being destroyed?

**Comment by BladeburstNINJA** [comment]
ODP was blown up and superstructure was failing. and as I reached the umbilical and was going to cross I was immediately flung. ODP hadn't been disintegrated yet, because as I was flying I saw the ODP as I flew past.

**Comment by Dragonace16** [comment]
Same issue happens if a plasma grenade lands near or on you while your downed on the ground you just get sent flying even when planetside.

**Comment by X0-11** [comment]
this isn't a bug, it's due to explosive throwing that replaced the confusion effect
