### ISSUE TITLE
UNSC AI Spawns on Covenant Ship Sometimes

### ISSUE THREAD

**Issue by loafe** [HaloSpaceStation/HaloSpaceStation13#2617]
#### Description of issue

The UNSC AI spawns on the Covenant Ship in the Kig Yar quarters sometimes, especially after the ODP blows up, but before the superstructure ends.

#### Difference between expected and actual behavior

The UNSC AI shouldn't spawn on the Covenant Ship, or shouldn't be able to spawn if the ODP blows up.

#### Steps to reproduce 

The ODP blows up
Spawn as UNSC AI
Spawn on Covenant Ship
Die of Autism

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x ] Issue could be reproduced at least once
- [x ] Issue could be reproduced by different players
- [ x] Issue could be reproduced in multiple rounds
- [ x] Issue happened in a recent (less than 7 days ago) round
- [x ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by 24THBN** [comment]
I can confirm that they spawn at a randomized point, one time it spawned on the Elite Quarters, next time it happened it was on the Jackal Quarters.

**Comment by Sgtwok** [comment]
Kig-yar do be thieves.

**Comment by loafe** [comment]
cringe

**Comment by caelaislinn** [comment]
duplicate #2034
