### ISSUE TITLE
[Suggestion] ODP debris falling over Geminus City after the destruction.

### ISSUE THREAD

**Issue by 24THBN** [HaloSpaceStation/HaloSpaceStation13#2618]
#### Description

After the the ODP blows up, some of it debris should make its way into the city.

This would shaping the once peaceful city into an actual hardened combat zone, both giving cover to troops fighting on the ground and maybe also some supplies that they could be repurposed.

This would also give a true warzone ambience of a city getting invaded by a alien force and the horrors the UNSC troops witness while trying to recover and fight back, similar to what happened in New Mombasa in Halo 2/ODST.

I would say that the message of the ODP blowing up that goes into everyone's radio should also alert about the danger of debris and damage happening when it spawns. Or it could be another message altogether.

I am open to discussing this, and I would like to hear opinions if you think its a cool idea to implement.

**Comment by Aroliacue** [comment]
Sort of in now
