### ISSUE TITLE
[SUG] Re-enable eye surgery and check on imidazoline

### ISSUE THREAD

**Issue by Jaybirdyy** [HaloSpaceStation/HaloSpaceStation13#2619]
#### Description of issue
Eye surgery is currently disabled, it'd probably be a nice thing to re-enable if the autodoctor is not provided.  Also, it may be an isolated case for only blinding from uncovered eyes during a wield, but imidazoline (used to heal eye trauma) did not work.  It may be brain damage, I didn't get time to check as I was on a tight schedule.

#### Difference between expected and actual behavior
Eye surgery would be a thing, as well as imidazoline hopefully healing eye damage.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Sgtwok** [comment]
Eyes in baycode are an internal organ, which means you need to open up the skull.

Autistic, I know.

**Comment by caelaislinn** [comment]
> Eyes in baycode are an internal organ, which means you need to open up the skull.
> 
> Autistic, I know.

That's incorrect, internal organs can be set surface_accessible=1 which allows surgery without opening an incision. Eyes are the only organ with surface_accessible=1

**Comment by bloxgate** [comment]
Just to confirm, how exactly did you attempt this eye surgery? I'm aware of someone successfully performing it a couple months ago, and don't recall it being deliberately disabled.

**Comment by Jaybirdyy** [comment]
@bloxgate I actually didn't attempt any eye surgery, I was just told by Cael to include it in an issue so he can remember to re-enable it.  The imidazoline on the other hand, I attempted and it didn't work.

**Comment by caelaislinn** [comment]
I had quick look at eye surgery and I can't find the part where it's disabled any more. However I'm going to close this because 2700 made imidazoline fix the STATUS_BROKEN flag, and autosurgeons should also be able to fix broken eyes
