### ISSUE TITLE
Put ESCAPE pods on the ODP

### ISSUE THREAD

**Issue by Sgtwok** [HaloSpaceStation/HaloSpaceStation13#2620]
#### Description of issue
When the Covenant go through the umbilical, or, if they block it off, the marines, unless they get to the Pelican (which can easily be destroyed) they are, essentially, stranded. It doesn't make sense to not include at least two.

#### Difference between expected and actual behavior
Urist McMarine [squadcomm] says, "Get to the escape pods!"
Urist McCommandingOfficer [squadcomm] says, "It wasn't in the budget! We'll have to go down with the ODP!"

#### Steps to reproduce 
Covenant Activate the Nuke/Slipspace Core Meltdown
Look for escape pods
There aren't any.
Cry.
Die.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by loafe** [comment]
Great idea

**Comment by X0-11** [comment]
preferred locations?

**Comment by Sgtwok** [comment]
This is something that loafe and co should answer.

**Comment by loafe** [comment]
2 on the bottom left of the lower deck that is currently unused and 2 on the upper deck near the airlocks, or around the bridge
