### ISSUE TITLE
Jetpacks and you: MY LEG: Or how your limbs exploded from a riveting two foot drop.

### ISSUE THREAD

**Issue by Sgtwok** [HaloSpaceStation/HaloSpaceStation13#2621]
#### Description of issue

With the addition of jetpacks (and yanme'e flight) comes the issue of what happens when your time is up. For now, that is having your limbs outright explode.

Now, obviously, there should be some kind of consequence, since otherwise people will just consequence free fall and get a mild bruise.

Unfortunately though I also think it's too harsh, especially since jumping from a building is less of a pain than falling an astounding... Three feet, and the addition of the Covenant Concussion Rifle, which throws them and basically empties their jetpack. Which makes their limbs explode.
Exploding limbs, meanwhile, while obviously a consequence, is extremely costly to replace, especially since the rocketeers will die in transport unless a medic is ON SCENE the moment it happens. 

**"Alright Matt get to the fucking point."**
What I propose instead is that limbs break, instead of exploding, while also still doing a fair degree of damage, which, while it hurts, isn't overly crippling.

#### Client version, Server revision & Game ID
Server Revision:14934085102eae146bd93dc4bddabcaa8c43ee06- alpha - 
Game ID: b72-a9i2

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by X0-11** [comment]
It doesn't specifically break any limbs or gib them, it just applies a flat 65 damage hit.

**Comment by Sgtwok** [comment]
Yes, it does it at random. Which is worse.
https://puu.sh/G4q6S/9b00ae7602.png

Marines have complained about it too, upon getting shot by a concussion rifle while in flight, they exploded.

**Comment by X0-11** [comment]
Failing to track fuel is meant to be punishing. Is it too punishing?
The concussion rifle thing is due to being flung eating fuel due to jetpack keeping you upright

**Comment by Sgtwok** [comment]
Yes, I believe it is far, far too punishing. The chance to have a limb outright explode is far too harsh considering it can cause the heart to stop and how long it takes to actually fix. Again, I know it's meant to be punishing.

**Comment by Jaybirdyy** [comment]
I think punishment is certainly necessary, is there a way you could direct damage to the legs (to the point of breaking them, or something) and not flat damage?

**Comment by X0-11** [comment]
It's possible to make it break someone's legs directly instead of dealing damage, or directing damage soley at the legs, yes.

**Comment by Sgtwok** [comment]
I believe minor damage and a broken leg or two is far more fair, especially given the risk factor with the presence of concussion rifles.
