### ISSUE TITLE
Face Direction: "Alright soldier, look east. Now walk. Now you're facing west. Now you got shot in the back."

### ISSUE THREAD

**Issue by Sgtwok** [HaloSpaceStation/HaloSpaceStation13#2622]
#### Description of issue
The 'Face Direction' feature, which locks your character sprite into one direction, is extremely bugged.
If you were to say, use face direction to face east, but then walked north, every step of the way, your sprite would alternate between facing north, your direction, and east, the direction you want your sprite to face.

This is especially crippling for kig-yar, who basically *RELY* on this feature to actually survive, which means that while moving, they can be shot thanks to this glitch.

Equally strange though, if you are in-flight, it works as intended.

#### Steps to reproduce 
Be a kig-yar.
See an enemy
Activate your shield.
Lock your sprite into their direction.
Fight
Take one step backwards
Now your back is facing the marine
Die from buckshot.

#### Length of time in which bug has been known to occur

Since we had jetpacks.

#### Client version, Server revision & Game ID
Server Revision:14934085102eae146bd93dc4bddabcaa8c43ee06- alpha - 
Game ID: b72-a9i2

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Jaybirdyy** [comment]
I also noticed that ctrl + arrow keys didn't work either with kig yar, which is very useful if you are holding down a hallway, for example and not moving.  Trying to walk into position in the right direction is doable, but limited for obvious reasons.

**Comment by Sgtwok** [comment]
I should also specify, alt+arrow keys don't work, which are the 'face direction' hotkeys.
