### ISSUE TITLE
AI spawning in w/ armor on the core.  (Covenant tested)

### ISSUE THREAD

**Issue by Jaybirdyy** [HaloSpaceStation/HaloSpaceStation13#2624]
#### Description of issue
When spawning in with certain species selected, (I have tried yanme and unggoy) armor is spawned as well on top of the AI core.  With an Unggoy, it is only the natural armor.

As a note, this issue has been reported already, but specifically to the yanme.  #2034 

#### Difference between expected and actual behavior
Expected - You spawn in as a covenant AI (no matter the race selected) and do not have armor on the core.
Behavior - You spawn in as a covenant AI, but have armor sitting atop the core.

#### Steps to reproduce 
Select a species (the ones I have seen it with are unggoy and yanme
Do not select AI as one of your jobs
Join, and select Covenant AI (Untested with UNSC ai)

#### Specific information for locating

![image](https://user-images.githubusercontent.com/44487173/86864927-e9433a00-c082-11ea-8d99-9e7fd9f2672f.png)

#### Length of time in which bug has been known to occur

At least since the last mention of this bug was made.  December 13, 2019

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: e20aa388a84aa72d50ff08ea233f5de499b0f6d6 - alpha - 
Game ID: b73-aplN
Current map: Geminus City

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by caelaislinn** [comment]
duplicate #2034
