### ISSUE TITLE
UNSC AI does not have access to entire ODP

### ISSUE THREAD

**Issue by loafe** [HaloSpaceStation/HaloSpaceStation13#2625]
#### Description of issue
The UNSC AI does not have any access at all to the Medbay or SMAC controls. 

#### Difference between expected and actual behavior

The AI should have access to the entire station's controls, not just some. 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x ] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [x ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by X0-11** [comment]
Were the nodes in those areas accessed to the correct required levels?
