### ISSUE TITLE
[Issue] Getting ashed because a ship you were once blew up, despite not being on it during its explosion

### ISSUE THREAD

**Issue by 24THBN** [HaloSpaceStation/HaloSpaceStation13#2626]
#### Description of issue

While I was on the ODP, I got random messages of ETA:2 minutes before explosions, turns out the Troopcarrier I used to fuel up a Banshee was about to blow, and when it did blew up, I got instantly ASHED.

This has apparently only happened to me, but the ETA messages when outside said blowing ship/station have some time happening. I believe it needs further testing. It is quite urgent since it removes you from the round for no reason, rendering you unable to be revived.

#### Difference between expected and actual behavior

Not getting messages of a ship I am no longer in is going to blow, not getting ashed because said ship blew up.

We are still getting random mesagges of ships or the ODP ETA despite not being in it anymore, I got ashed because one ship blew up after a while.

#### Steps to reproduce 

1.Get in a Banshee 2.Go to the troopcarrier 3.Go to the ODP 4.someone makes the troopcarrier critical structure to fail and blow up 5.Get ashed after the two minute timer

#### Specific information for locating

Unknown.

#### Length of time in which bug has been known to occur

Today.

#### Client version, Server revision & Game ID

Server Revision: e20aa388a84aa72d50ff08ea233f5de499b0f6d6 - alpha - 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by ondrej008** [comment]
You see the SUPERSTRUCTURE FAILING message, despite not being on the thing whose superstructure is failing. Then after the thing explodes you get ashed. If you stop seeing the SUPERSTRUCTURE FAILING message, it means you're safe, if it keeps popping up, you're not safe. No idea how to reproduce, but could be something with vehicles.

**Comment by caelaislinn** [comment]
#2629
