### ISSUE TITLE
[Suggestion] ODP Floor is way too weak.

### ISSUE THREAD

**Issue by 24THBN** [HaloSpaceStation/HaloSpaceStation13#2627]
#### Description 

Current ODP floor is comically easly destroyed by explosions, it is currently known that it can be destroyed with the Rocket Launcer and the FRC as any other explosions of any kind, this can lead to issues as falling to the deck below, or getting stuck somewhere you shouldn't, to even be instantly gibbed if you fall with magboots on as once occurred.

I believe it makes absolute no sense that a ODP has such strong doors and walls, while the floor is comically destroyed by any explosion, even cutting off sections of the station, or making a deadly trap when it happens under a door.

Please make the floor of the ODP more resistant to explosions.

**Comment by caelaislinn** [comment]
Duplicate #2561
