### ISSUE TITLE
[BUG] Permafried Headsets

### ISSUE THREAD

**Issue by ghost** [HaloSpaceStation/HaloSpaceStation13#2633]
#### Description of issue
When a headset is affected by plasma pistol EMP (possibly all EMPs) the speaker (functionally, the part needed to speak using the radio) can never be reenabled, resulting in a radio that can only receive but never send.

#### Difference between expected and actual behavior
EMP is meant to be a temporary disruption of headset use, not permanent

#### Steps to reproduce 
wear headset
be within range of plasma pistol EMP
attempt to reenable speakers

#### Length of time in which bug has been known to occur
Several weeks

#### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players (not yet tried)
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by ondrej008** [comment]
Just like EMP on most other codebases, you need to re-enable the headset, which just means toggling every button on the headset, and then doing that again. This has always worked for me, though it is a bit unintuitive, as it doesn't show the button going from off to on.

**Comment by ghost** [comment]
Can confirm that I tried this without success, and previously it did work.

**Comment by caelaislinn** [comment]
Eventually I'd like to add a temporary "timeout" which makes the headset completely unusable for perhaps 10-20 secs, but that's an idea for the future
