### ISSUE TITLE
RND Spartan Laser is not a spartan laser

### ISSUE THREAD

**Issue by thog1** [HaloSpaceStation/HaloSpaceStation13#2634]
The spartan laser upon completion just produces a basic energy gun. 

https://gyazo.com/a771a109e20db73f859d2679196bdf4c - The "Spartan Laser"

**Comment by Sgtwok** [comment]
It might be getting reworked thanks to how ungodly overpowered the actual spartan laser is, that's up to staff to answer.

**Comment by caelaislinn** [comment]
#2630
