### ISSUE TITLE
[SUGG] Make the CRS Unyielding Transgression unreachable

### ISSUE THREAD

**Issue by ondrej008** [HaloSpaceStation/HaloSpaceStation13#2639]
Just like how the ONI Complex is unreachable to anyone but UNSC (except when you have a living UNSC in your vehicle and then you can get inside it), the CRS Unyielding Transgression should be unreachable to anyone but the Covenant with these exceptions:
 - UNSC Pelican flies to Level 1 - direction
 - UNSC board Covenant ship and use Covenant ship to get onboard

**Comment by X0-11** [comment]
this is already true

**Comment by ondrej008** [comment]
> 
> 
> this is already true

How so? I just saw the UNSC drive their ship to the CRS Unyielding Transgression and just use umbilicals to get on it.

**Comment by X0-11** [comment]
point number 2
they boarded the covenant ship

**Comment by 24THBN** [comment]
The same reasons the Geminus MAC and ONI base is unreachable should apply here, it distracted the troops and divided them between defending two points, and makes it a easy win for the enemy team to just go to an undefended base and destroy it. 

As of now we would have to both defend the flagship and attack Geminus, which makes no sense since it would just divide the Covenant forces, just like you don't want to divide UNSC's.

The Covenant flagship is not even supposed to go into umbilical range because its just asking for it to be boarded via umbilical, ironically something the Covenant cannot do anymore because people didn't like them doing that.

**Comment by ondrej008** [comment]
> 
> 
> point number 2
> they boarded the covenant ship

![obrazek](https://user-images.githubusercontent.com/8739855/87094694-9c589280-c23f-11ea-811a-7fe72f611258.png)

**Comment by X0-11** [comment]
sure, i'll give the cov flagship the odp treatment in terms of umbilical accessibility. don't complain when you can't get back

**Comment by loafe** [comment]
i mean ill just do what I did last time and steal a spirit to board the flag ship

**Comment by 24THBN** [comment]
And nothing stops them to just send a random ship with one soldier and a pelican spawner on Phase 1 or Phase 2 to go around in space to find the Flagship and board it while everyone else is doing their objectives.

**Comment by loafe** [comment]
what is wrong with splitting our forces

**Comment by X0-11** [comment]
besides the fact they can't spawn a ship once the ODP's down?

**Comment by 24THBN** [comment]
Besides the fact they can spawn it before the ODP is down, and send it away still, and even if the ODP is down they still have their ships?

**Comment by ondrej008** [comment]
> 
> 
> besides the fact they can't spawn a ship once the ODP's down?

Except, they can spawn a ship before the ODP falls, and it's very hard to destroy ships as covenant.
Our only option for ship to ship combat is to board the ship with a tool-belt and welding helmet, then deconstruct enough rwalls with the hull segments to make the superstructure critical.

**Comment by X0-11** [comment]
i think we call that tactics

**Comment by loafe** [comment]
ship weapons are far more effective than you think

**Comment by ondrej008** [comment]
> 
> 
> ship weapons are far more effective than you think

After spending 5 minutes spamming a single UNSC ship with an Energy projector, I really disagree, the integrity was still at 100% and when I went to it, it wasn't even breached.

**Comment by 24THBN** [comment]
So you are saying that they got their stuff to be unreachable so they don't split, but we cannot have our stuff unreachable for the same reason, and we should split?

**Comment by X0-11** [comment]
last i checked the odp wasn't unreachable

**Comment by loafe** [comment]
make a git issue if energy projectors aren't working

**Comment by 24THBN** [comment]
The ODP isnt the only spawns from them, and its destruction doesn't end the round with a Covenant victory either

**Comment by loafe** [comment]
its also not particularly hard to destroy

**Comment by X0-11** [comment]
that's because the round is asymmetrically balanced in different phases

**Comment by ondrej008** [comment]
> 
> 
> its also not particularly hard to destroy

The ODP or flagship? Both are the same difficulty to destroy, unless you forgot to take tools for either.

**Comment by loafe** [comment]
most covie races can open doors with their hands, the ODP is smaller, and much easier to vent

**Comment by X0-11** [comment]
incorrect, 2 out of 5 covvie races can open doors with their hands, 2 out of 6 if we include prophets, or 2 out of 7 if we also include mgalekgolo. 2 is not most

**Comment by loafe** [comment]
2/5 of the most commonly played is still quite a bit, esp with infinite brute/elite minors

**Comment by X0-11** [comment]
soon not applicable

**Comment by loafe** [comment]
idek why this issue is still open, XO already agreed to limit umbillical access and if a spartan steals a spirit to board your ship or uses a boarding pod you deserve to get boarded

**Comment by X0-11** [comment]
it will be closed when the relevant change is made final and merged

**Comment by ondrej008** [comment]
> 
> 
> most covie races can open doors with their hands, the ODP is smaller, and much easier to vent

2 races can open doors with their hands out of 5 (not counting T'vaoans). Venting allows you to push & sometimes damage if you're venting to an area with vacuum, people who don't have magboots on, which unggoy and yanme'e cannot get. Elites, brutes and kig'yar need to sacrifice armor for EVA, as so marines, so that seems fair.

**Comment by caelaislinn** [comment]
Partially addressed #2629 cov flagship umbilicals can only connect outwards... iirc dropships and fighters can still long distance travel to the waypoints
