### ISSUE TITLE
[bug] Plasma Grenade making people invincible

### ISSUE THREAD

**Issue by Joe44445** [HaloSpaceStation/HaloSpaceStation13#2641]
#### Description of issue

A plasma grenade, upon ashing someone's head, has a chance to make them invincible.

#### Difference between expected and actual behavior

uh, a grenade blowing off your head should probably kill you

#### Steps to reproduce 
have a funny plasma grenade blow up your head
become immortal

#### Specific information for locating

the plasma grenade, I'd assume

#### Length of time in which bug has been known to occur

it happened both today and yesterday, but i'd assume whenever plasma grenades were last changed

#### Client version, Server revision & Game ID

Server Revision: eb8f5932562831b2285b8ae665d243d6c4f5ec59 - alpha - 
Game ID: b74-dqrA

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by bloxgate** [comment]
Confirmed to be happening again as of 07/15

**Comment by 24THBN** [comment]
Happened again 07/15 13:38 local time at 01:38 round time.

https://streamable.com/k7k3q1
