### ISSUE TITLE
Kig-yar cannot mount 02 tanks- Anything except small hand weapons to ranger suits

### ISSUE THREAD

**Issue by Sgtwok** [HaloSpaceStation/HaloSpaceStation13#2643]
#### Description of issue

As it stands, this already offers a disadvantage to storage space, whereas sangheili in ranger suits, ODSTs, and Spartans, can mount large O2 tanks no problem. Which presents a problem in that ODSTs, sangheili, and SPartans can mount jetpacks on their back as well as large 02 tanks on their suits, and also pack a large weapon in their hands.

#### Difference between expected and actual behavior

I'd expect to be able to carry both, as that's kind of part of the appeal of jetpacks and rangers.

This is not possible.

#### Steps to reproduce 

Be a kig-yar
Put on a ranger suit
Decide you want to be a rocket trooper.
Cry when the only 02 tank you can mount is a small one that lasts 6 minutes and you have to choose between breathing ad jetpacking

#### Specific information for locating

HaloSpaceStation13/code/modules/halo/covenant/species/kigyar/kigyar_ranger.dm 

#### Length of time in which bug has been known to occur
Forever.

#### Client version, Server revision & Game ID
Server Revision:eb8f5932562831b2285b8ae665d243d6c4f5ec59- alpha - 
Game ID: b75-aanH

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by loafe** [comment]
I was actually wrong the large ones do not fit on the suit slot, only on the back

**Comment by Sgtwok** [comment]
Nevertheless, I know for a fact they can fit large weapons on their suit slot, kig-yar can only fit pistols there.

**Comment by Joe44445** [comment]
if by "Large weapons" you mean things such as rocket launchers and snipers, only a spartan can actually fit them on their suit slot. If you mean like rifles and stuff you can just ignore this

**Comment by Sgtwok** [comment]
We can only fit pistols though. ONLY pistols.
