### ISSUE TITLE
[Suggestion] Add plasma rifles and carbines to the Yanme'e armory

### ISSUE THREAD

**Issue by CommodoSeven** [HaloSpaceStation/HaloSpaceStation13#2653]
Currently the Yanme'e armory is fairly limited. The only available weapons being the plasma pistol and needler. I therefore suggest to add carbines and plasma rifles as available options to choose from. Plasma rifles specifically have seen use by Yanme'e in the Halo games, although rarely so. Carbines not so much, but the responses I received in the covenant hall indicated that people would like to have them added as well, since it would allow for a more varied playstyle as drone and add a decent medium range weapon to their arsenal.

Adding two of each to the armory would suffice and ensure they are still fairly limited. That way the needler and plasma pistol still remain relevant and a valid option to pick from. Though of course that is just my personal opinion and the number of available guns can still be tweaked according to what the developer feels might be a better fit.

**Comment by mcalexev** [comment]
Seconded.

**Comment by loafe** [comment]
I'd be okay with one plasma rifle (ideally for ultras, but fuck it). Carbines don't really make sense in the context of how Yanmemes roll, at that point they'd just be kiggies that can fly

**Comment by X0-11** [comment]
Whilst plasma rifle addition is fine and would provide a larger variation, the point that covenant species are meant to have to communicate and co-ordinate with superiors should be kept in mind. Carbines would not fit Yanme'e as a weapon provided without any co-ordination with other species.

**Comment by CommodoSeven** [comment]
Duly noted. The carbines were more so a suggestion I carried over from the covenant hall. My primary interest lies in at least adding a plasma rifle or two to their armory. One for the ultra could work, but two would be better since there's also the leader spot who could use one too.

**Comment by caelaislinn** [comment]
Yanmee weapon choice is deliberately limited, like tvoans in combat they are meant to be harassers and skirmishers. If you want to get more powerful guns go a frontline combat species like jiralhanae or sangheili
