### ISSUE TITLE
Grunts need more Needlers

### ISSUE THREAD

**Issue by loafe** [HaloSpaceStation/HaloSpaceStation13#2654]
#### Description of issue

Grunts only get 3 needlers and 30 needle ammo, they should probably get more needlers since majors in the games almost always have needlers. That along with the fact it is kinda the "main weapon" for the Covenant, they should probably get a few more in their vendors

**Comment by caelaislinn** [comment]
It's not the "main" weapon for the Covenant, it's weird alien space crystal magic. The main weapons are plaspistol and plasrifle. I'll add a couple more to the vends anyway, from 4 needlers/32 mags to 6 needlers/32 mags
