### ISSUE TITLE
Yanme'e does not have a flight bar

### ISSUE THREAD

**Issue by Delnth** [HaloSpaceStation/HaloSpaceStation13#2655]
Title. The Yanme'e do not have a progress bar decreasing when flying, making it hard to know when nearing exhaustion. There also seem to be a 2-3 delay when using the flight ability. Not sure if it's intended but the delay seem unusually long, at times.

**Comment by X0-11** [comment]
Yanme'e flight relies on the player tracking their flight through the status panel, mainly, due to it utilising no special flight item, only the integrated system for all living-type mobs. The variable delay will likely be the Stun everyone experiences.

**Comment by Delnth** [comment]
When a Sangheili tries to force a door open, there is a progress bar. Yet no item is being used. I don't see why the Yanme'e wouldn't have that. BYOND ticks are incredibly unreliable. One second can often be translated in slightly more than 1 second or even 2 seconds, depending on what is using the ticks. This makes the whole "tracking their flight time" inaccurate and a bit of a chore reserved to a veteran player that play the role often enough to know everything about it.

I'm not a fan of using the status panel to keep track of stuff like shield, flight time and all that. I'm sure you are aware of tabs randomly switching between each other for no reason, whenever you come into range with an NPC, perform an action or walk by a certain object/structure. I can't confirm any of those cases but they exist, the point still stands, it's hard to keep an eye on the status tab when it's almost constantly switching to another tab. Not particularly helpful amidst a fight, especially if the tab happen to switch to another.

**Comment by X0-11** [comment]
Progress bar on elites opening things is seperate system iirc. Still, yanme'e need one. Will look into it
