### ISSUE TITLE
Donor armor doesn't spawn on any character

### ISSUE THREAD

**Issue by loafe** [HaloSpaceStation/HaloSpaceStation13#2656]
#### Description of issue

My donor armor for CO, ODST, and Spartan don't spawn in a box upon me spawning

#### Difference between expected and actual behavior
I should have the armor

#### Specific information for locating

HaloSpaceStation13/code/modules/halo/clothing/odst.dmi/loafe-armor_worn (plus the jumpsuit and helmet & backpack)
HaloSpaceStation13/code/modules/halo/clothing/spartan_armor.dmi/loafe-shell-worn (plus the helmet)
HaloSpaceStation13/code/modules/halo/clothing/marine.dmi/loafe_co_uniform_s (plus the hood, armor, and boots)

#### Length of time in which bug has been known to occur

2 weeks

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x ] Issue could be reproduced at least once
- [x ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [x ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by caelaislinn** [comment]
Is this still happening?
