### ISSUE TITLE
[bug] Plasma Grenades are now instant killing people.

### ISSUE THREAD

**Issue by Joe44445** [HaloSpaceStation/HaloSpaceStation13#2658]
#### Description of issue

plasma grenades, upon sticking to someone, Instantly kill you. Tested with both an ODST and a Spartan, it killed both instantly. Straight to braindead with no chance of survival

#### Difference between expected and actual behavior

The Plasma nade shouldn't be an instant kill, this was changed

#### Steps to reproduce 
have funny covenant man stick you with a nade
have it blow up and instantly kill you

#### Specific information for locating

the plasma grenade code itself (possibly to do with what Blox changed about them) or it may be due to the nerf to brainmed(Done by Cael)

#### Length of time in which bug has been known to occur

1 day? I'd assume

#### Client version, Server revision & Game ID

Server Revision: 8f0c5215d7519d766659c9630f55c42a3c7b38c1 - alpha - 
Game ID: b75-doYS
Current map: Geminus City

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by X0-11** [comment]
Does this still happen?

**Comment by bloxgate** [comment]
If it is still happening, I wonder if the alt_explosion and the call to `ex_act` are both happening. I could see that double stacking the damage - 120 damage across the right set of internal organs could be instantly fatal.

**Comment by 24THBN** [comment]
It is quite rare but it sometimes happen that you are completely delimbed but still alive for a while too.

**Comment by bloxgate** [comment]
You do still die if that happens though?

**Comment by 24THBN** [comment]
Yes I died, I recorded the event as aswell.

**Comment by bloxgate** [comment]
In that case, I'm willing to say that that is intended behavior and probably not related to this bug. Assuming you have a competent medic (as if that ever happens), embedded plasma grenades should *rarely* be survivable.

If it's simply taking an unreasonable time to die on the other hand, I can see how that'd be frustrating - but that should probably be a separate issue.

**Comment by 24THBN** [comment]
What I experienced was not a embedded grenade, but a suicide rush.
https://streamable.com/k7k3q1
Here.

**Comment by bloxgate** [comment]
That seems to be the issue that was happening in #2641 / #2642.

I can take another look at that I guess. If you could take go ahead and mention the round ID and approximate time in round in the thread for #2641, that would be appreciated.

**Comment by 24THBN** [comment]
How do I know what the Round ID was that round?
