### ISSUE TITLE
[BUG] LR Slipspace not ending round

### ISSUE THREAD

**Issue by Jaybirdyy** [HaloSpaceStation/HaloSpaceStation13#2666]
#### Description of issue
Long range slipspace, when activated and charged, acts like a short range slipspace.  You are able to activate it and such, but the round indeed does not end.  Once it activates, you are able to go back into real space just like short range.

#### Difference between expected and actual behavior
Long range should end the round.

#### Steps to reproduce 
Something happens that requires you to activate long range
Activate long range
Wait to see that it does not actually end the round.

#### Specific information for locating

![image](https://user-images.githubusercontent.com/44487173/87238309-d186f100-c3b5-11ea-8269-a6583a7f3d26.png)
The standard text prompts and such, just no leaving.

#### Length of time in which bug has been known to occur

Unknown, but most likely recent.

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: b60cbd3e15f11e6567a76f3dab8d37ec08dff486 - alpha - 
Game ID: b77-az7P
Current map: Geminus City

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Delnth** [comment]
It worked fine for me when the artifact was onboard (in the nuke room). Did you have it too?

**Comment by Jaybirdyy** [comment]
> It worked fine for me when the artifact was onboard (in the nuke room). Did you have it too?

Ah yeah, that's the weird part.  It worked fine with a nuke as well, but without a nuke, it doesn't work.

**Comment by X0-11** [comment]
LR slipspace is only one of the objectives for round end. If another objective hasn't been completed the round will not end.

**Comment by Jaybirdyy** [comment]
I see.  I do recommend allowing long range slipspace without other objectives.  If there's a case like all of the ships have been deployed, the ODP is still up and you have no spirits (this happens more often recently) than restarting the round is just better for everyone.  Even if you do somehow destroy the ODP, you won't be able to retrieve an artifact very effectively without good coordination, and that coordination with people staying on the ship to link umbillicals, does not happen as often as it should.

**Comment by Delnth** [comment]
If all objectives aren't complicated, it results in a failure nonetheless. Whether the flagship survives or not, it won't change anything. I am pretty sure this was removed because malicious and confused players alike would activate it and thus, end the round before anything happened.

**Comment by Jaybirdyy** [comment]
Yeah, but then you have 2 hour rounds where the covenant can't do much,  thats the thing.  No covenant player wants to get on if the flagship has several holes in it.  Yeah its a failure nonetheless, but at least you won't have hours where nothing happens and everyone leaves.  Maybe implement the ability to do it if you have the whitelist or something, to block random people from abusing it.

**Comment by caelaislinn** [comment]
I originally intended for long range slipspace to immediately end the round and trigger objective scoring, as a way for Covenant to force a stalemate or end a round that is dragging on too long.

**Comment by Jaybirdyy** [comment]
Yeah, thats what makes sense to me.  Maybe a restriction on who can turn on the drive or something, I dont know.  I just think its pretty important when staff aren't around to restart/vote for restart.

**Comment by Delnth** [comment]
The long range slipspace drive could prompt the player with a **very clear** warning that it's gonna end the round if they click it. If there are still malicious players out there going for the long range slipspace, we could better crack down on this behavior and there'd be no excuse for them.

**Comment by Jaybirdyy** [comment]
There is actually already a prompt that says if you activate it, you won't be able to come back and its a one way trip.  Maybe that isn't enough?
