### ISSUE TITLE
Aircraft suggestions

### ISSUE THREAD

**Issue by PantasTheDank** [HaloSpaceStation/HaloSpaceStation13#2676]
#### Description of issue 
Some suggestions for tweaking the sparrowhawk/banshee

1- Reducing missles to 10, maybe 6.
2- 90° firing cone from the cockpit
3- Seems like blindness from missles lasts too long? 
4- add erp? :flushed:

**Comment by Archi-guy** [comment]
I would also like to add that CAS are able to fire missiles/FRC way too quickly for it to be adequate. They need a much higher delay between each shot, because currently they feels like better machine guns, which cause heavier damage, knockback and blindness.
