### ISSUE TITLE
[suggestion] Tank Turrets

### ISSUE THREAD

**Issue by Joe44445** [HaloSpaceStation/HaloSpaceStation13#2681]
Currently, the tank's turrets are combined into one, disallowing the use of the other when one is on cooldown

this leaves tanks rather vulnrable due to the rather long cooldown, which I believe is a big reason for the tanks (particuarly on the covenant side) being underutalised.

I can think of 2 ways to fix this issue, but am willing to accept any suggestions other may have

Split the main gun and the machine gun in the tanks between the gunner and the driver, to allow both to be use in once (we see in the games that the machine gun on each tank is actually a seperate slot on the tank crewed by someone else).

or

allow the switching between the main gun and the machine gun in the tank whilst one is on cooldown.

This should (hopefully) lead people to use the tanks more often, due to them being less vulnreable to outside threats. 

However, I could see how this could be rather OP, so to compensate I would suggest perhaps a longer cooldown on the machine gun turret in between bursts to compensate for this change.

Post was made at the request of Mr Bones in the UNSC barracks.

**Comment by X0-11** [comment]
This is unfortunately not really doable due to the way the weapon distribution system works. Allowing switching weapons whilst on cooldown would lead to the ability of quickly switching weapon modes to fire faster. The cooldown on firing the main turret may be too long in general, so that could be tweaked down if needed

**Comment by Joe44445** [comment]
that could work, the cooldown on the main turrets leaves tanks way to vulnreable to attacks for too long imo. Another thing, what if a timer was put on switching between the two weapons on the tank, one that would be longer to switch to the machine gun and back to the main turret, to stop the issue of people switching weapons to fire faster?

if that can't be done, i'd be happy for a reduction on the cooldown of the main turret.

**Comment by X0-11** [comment]
Variable delays are already present due to each gun having a different fire delay
