### ISSUE TITLE
Remove UNSC Janitor slot

### ISSUE THREAD

**Issue by loafe** [HaloSpaceStation/HaloSpaceStation13#2682]
#### Description of issue

UNSC Janitor is pretty worthless right now. It's always been worthless, but old UNSC mains used to use it to slip covies and beat them to death with a boot. Now they just take a pop balance slot and die.

**Comment by X0-11** [comment]
The mobilespawn role?

**Comment by loafe** [comment]
Both preferably, they just take up a pop slot and usually do nothing and sit around while the round goes on

**Comment by Joe44445** [comment]
have to agree here, people are using it to meme around and take up valuable UNSC slots. a single Janitor doing nothing for the UNSC and sitting at base could mean there are 2 extra grunts on the battlefield, or an elite. The role serves no purpose other than taking up pop.
