### ISSUE TITLE
Lowering the Gravity Stun Timer

### ISSUE THREAD

**Issue by loafe** [HaloSpaceStation/HaloSpaceStation13#2684]
#### Description of issue

If you are playing a race which does not have access to magboots (unggoy, for example), the stun that happens when you go from a non-gravity area to a gravity area is crippling. It's currently about 10 seconds from what I can tell, which is an eternity in SS13 time, while the enemy can just wail on you, making it a death sentence. For other people, if you go out of a window into space and then get pushed back into that window with your magboots off, you are instantly stunned. I suggest a decrease of this time to something a little more reasonable, or at the very least the ability to crawl.

**Comment by Sgtwok** [comment]
Only ten? I've been stunned for straight up two minutes before.

**Comment by loafe** [comment]
I dunno I think it depends on some things, but it is annoying nonetheless

**Comment by caelaislinn** [comment]
It used to be only running, but someone added the stun for walking as well

**Comment by X0-11** [comment]
currently up PR has a tweak to it iirc

**Comment by Sgtwok** [comment]
Hold up, someone made it apply to walking too? Why?

**Comment by ondrej008** [comment]
> 
> 
> Hold up, someone made it apply to walking too? Why?



> 
> 
> It used to be only running, but someone added the stun for walking as well

Unless this was changed 2 days ago, walking does not get you stunned. The stun timer is too long though, anyway.
