### ISSUE TITLE
Sprites for new Insurrection guns

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#269]
- Franchi Spas-12 (folded and unfolded stock)
- Molotov Cocktail (lit and unlit)
- PTRD-41
- RPG-22
- Skorpion SMG
- G22 Sniper rifle
- AKM
- UTS 15
- AAC Honey badger
- M-14 enhanced battle rifle

Just some new additions to the armoury.

**Comment by BDpuffy420** [comment]
These guns aren't really lore friendly, and plus they did have their own arms  http://prntscr.com/h9i9j3
