### ISSUE TITLE
Poplock seems broken

### ISSUE THREAD

**Issue by loafe** [HaloSpaceStation/HaloSpaceStation13#2690]
#### Description of issue
Poplock seems to be counting ghosted players as active. This throws a monkey wrench into poplock mechanics, as if a player decides to ghost and just watch the round, they are taking up a poplock slot. 

#### Difference between expected and actual behavior
Ghosted players shouldn't be counted. 

#### Steps to reproduce 
1. Die
2. Ghost
3. Watch as no one can spawn on a particular side because it has more epic funni ghosts

#### Length of time in which bug has been known to occur

4 days

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ x] Issue could be reproduced at least once
- [x ] Issue could be reproduced by different players
- [x ] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [x ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by caelaislinn** [comment]
Ghosts shouldn't be triggering it. PM me to get on next time you think its happening
