### ISSUE TITLE
Remove Weapon Drop from Explosions

### ISSUE THREAD

**Issue by loafe** [HaloSpaceStation/HaloSpaceStation13#2693]
#### Description of issue

When the embassy vote went up about explosions being changed, quite literally 0 people voted for weapon drop to be added along with it. 

This thread will feature stats from UNSC weapons because I haven't bothered to do research into the covenant weapons, but you can look for yourselves if you Ctrl + F 

`can_use_when_prone()
	return 1`

While the explosion itself doesn't actually knock the weapon out of your hand, 90% of weapons cannot be held while prone. The total list of UNSC weapons that can are:

MA5B
DMR
SRS

I think one handed weapons can also be held on the ground, but I am not sure about that. 

Two of those are very seldom used, and very hard to use at close range where you are even at threat of getting hit by an explosive. This means that if you are hit with an explosive, you are most of the time instantly separated from your gun, where you cannot even shoot back at the person shooting you with an explosive. With weapons like the concussion rifle, fuel rod, or M41, this makes it basically a first draw is the winner for explosives, which is really just not fun. 

Ideally make it so weapons don't get knocked out of your hands when you get hit with an explosive. It makes gameplay very stun based, which just isn't fun. 

Likewise, if the knockback range of explosives could be reduced, that'd be ideal. We voted for a /slight/ knockback, not being sent 4 blocks down the road.

**Comment by X0-11** [comment]
This can be only be achieved if replaced with another effect. Previously, confusion was used. The only replacement now is Stun.
Weapons also have a basic way to determine if they drop when prone, the weapons with a return 1 override are forced to be holdable by prone even if they don't fit the normal requirements.
