### ISSUE TITLE
ODP Hitting Itself and Being Hit By AI Ships When Enemy Ship Is Too Close

### ISSUE THREAD

**Issue by BladeburstNINJA** [HaloSpaceStation/HaloSpaceStation13#2696]
#### Description of issue
When an enemy ship is too close, when the ODP fires to shoot it, it actually hits itself. The ODP will also shield the enemy ship from AI ship fire.

#### Difference between expected and actual behavior
ODP should not be able to hit itself. AI shouldn't be targeting friendlies.

#### Steps to reproduce 
Fly the CRS right on top of the ODP.

#### Length of time in which bug has been known to occur

Very recent.

#### Client version, Server revision & Game ID

ea21ec16334e470ba7cc463f37b5ec0be7c08084
b8f-dCgt

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Sgtwok** [comment]
Can confirm this happens to Covenant as well, sometimes when no ships are around.
