### ISSUE TITLE
AP Need a Rework

### ISSUE THREAD

**Issue by loafe** [HaloSpaceStation/HaloSpaceStation13#2697]
#### Description of issue
After extensive testing, I have concluded that AP guns are a meme and that armor is too resistant to AP. Lee and I tested the DMR, Carbine, magnum, shotgun, and other AP weapons extensively to see if it made a difference at all. 

Results were as follows: 
plasma rifle (control): 7 shots before damage

DMR: 7 grace shots, normal amount
Carbine: 7 grace shots, normal amount (still did radiation damage)
magnum: 7 grace shots
shotgun (slugs): 5-6 grace shots
SRS: 4 shots 

Some of these guns have absolutely absurd AP values (SRS has 80) and yet it took an absurd number of shots for each weapon to break armor, almost defeating the point entirely, especially on a weapon like the DMR or carbine. where it trades magazine size and fire speed for armor piercing capability. This reinforces a meta of weapons that either shoot explosives (UBGL or rockets and shit) or shoot VERY quickly to break armor as fast as possible. This leaves a lot of weapons out to dry, which makes gameplay stale after a while because some guns are just not very usable due to the way armor works.

So how can we fix this? Instead of armor having a thickness and armor value, it could work as having "hitpoints," like a shield, where weapons with high AP will do extra damage to the health of the armor. This is the easiest solution in my head, but I don't know how hard it would be to code.

The much cheaper fix is to bump AP values on weapons listed above to make them actually effective. This is probably the easiest solution coding wise. 

I think a change like this will bring a lot of weapons back into the meta, and hopefully remove explosives out of it. Either way, AP weapons need some adjustment to make them actually feasible.

**Comment by Sgtwok** [comment]
I would honestly be in favor of a higher than shields, static number for armor that can be restored, though I imagine it would be absolute hell to code.

**Comment by X0-11** [comment]
Most weapons mentioned don't have an ap value. The DMR and srs are pretty much the only ones
