### ISSUE TITLE
geminus colonists seem to count as one pop for the unsc

### ISSUE THREAD

**Issue by X0-11** [HaloSpaceStation/HaloSpaceStation13#2705]
they probably shouldn't count towards the unsc population at one full unit

**Comment by loafe** [comment]
why should they count at all, it is a roleplay non combat role

**Comment by Delnth** [comment]
I've seen a civvie take arms against the covies on the ODP 1-2 rounds ago. Calling them a roleplay non-combat role is wrong. The marines did welcome the civvie's presence and likely gave them an m90 shotgun.

The role is a 50/50 chance of being an ally.

**Comment by loafe** [comment]
colonists aren't supposed to actively join the unsc in taking up arms, they may grab a pistol or shitty gun from GC and fight back but they really aren't supposed to be much of a combat threat, anecdotal evidence aside

**Comment by caelaislinn** [comment]
Colonists are intended to be a sandbox role with minimal responsibilities. They're free to defend the colony, start a militia, mine for resources or roleplay. As innies are not in reclamation it's expected they will not self antag towards the UNSC though.

**Comment by X0-11** [comment]
Update: colonists are listed as 0.5 popbalance value
