### ISSUE TITLE
[BUG] Trying to remove cargo while inside a vehicle deletes the cargo.

### ISSUE THREAD

**Issue by driecg36** [HaloSpaceStation/HaloSpaceStation13#2708]
#### Description of issue
Title. Cargo just disappears forever.

#### Difference between expected and actual behavior
Should be either impossible to remove from inside or just have it be ejected under the vehicle. 

#### Steps to reproduce 
Load something into a vehicle, attempt to remove it from inside, lose said something forever. 

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by caelaislinn** [comment]
Duplicate #2567 also fixed in #2725
