### ISSUE TITLE
[bug] Covenant Escape pods can land in ONI base on GC

### ISSUE THREAD

**Issue by Joe44445** [HaloSpaceStation/HaloSpaceStation13#2715]
#### Description of issue

covenant escape pods can land in the UNSC second spawn, which is meant to be inaccsessable to the covenant

#### Difference between expected and actual behavior

the covenant shouldn't be able to get into the base

#### Steps to reproduce 

get in a covenant escape pod
launch
get stuck inside the ONI base

#### Specific information for locating

the covenant escape pods

#### Length of time in which bug has been known to occur

I first encountered it in the canon round on 31/07/2020.

#### Client version, Server revision & Game ID

Server Revision: cfa87f5c761c6506eb09b5566f5b3144486a3f64 - alpha - 
I am unable to get the game ID as I am reporting after the round

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Aroliacue** [comment]
No longer occurs
