### ISSUE TITLE
Melee balancing

### ISSUE THREAD

**Issue by Archi-guy** [HaloSpaceStation/HaloSpaceStation13#2720]
It isn't a secret that ranged combat in general vastly overshadows melee. And for a very good reason.

When it comes to melee, it's just not worth it. Melee is used only for finishing people off, but other uses are next to non-existant. Combat usage of melee weapons pretty much gets thrown into a trash bin by the fact that guns deal just as much, and in vast majority of cases - more damage per hit. It's not helped by the fact that some ranged weapons can kill people in a few hits, while melee takes VERY long and underwhelming process to clicking on people up close, even with the strongest melee weapons in the game.

My suggestion is for devs to see the stats of melee weapons and make some tweaks in general to make melee an actual viable combat option, instead of a finishing off tool it is right now.

**Comment by X0-11** [comment]
I would theorise this is due to melee weapons having to still deal with armour even if you are able to land a hit. Perhaps an increase in AP will make melee weapons feel more viable.
