### ISSUE TITLE
Cargo not working

### ISSUE THREAD

**Issue by Anystar1** [HaloSpaceStation/HaloSpaceStation13#2723]
#### Description of issue
cargo shuttles can't leave in order to bring the orders stuck in a docking/undocking state

#### Difference between expected and actual behavior
it should be able to take off

#### Steps to reproduce 
order something
try to send it
cant send it

#### Length of time in which bug has been known to occur

ever since cargo was added to the ODP and ONI base

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by caelaislinn** [comment]
This is a known issue with KS7, it is working fine on Geminus. The reason is that the "out system" shuttle destinations havent been mapped in for KS7. This is something @X0-11 needs to address

**Comment by caelaislinn** [comment]
Fixed in #2733 and took me 20 mins to find because the PRs aren't descriptive
