### ISSUE TITLE
Team Shooter Gamemode

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#273]
Requirements: 
- A map with team spawns and areas to fight over (spawns should have never ending ammo and medical supplies). 
- Main objectives: kills, payload (deliver a bomb), collect macguffins
- Side objectives: airdrop spawns, airdrop resupply (ammo and medicine), access to new gear, automated gun drone.

**Comment by bloxgate** [comment]
@X0-11 has started on this based on some earlier Discord conversations. We'll need to get him as a developer on here and start assigning issues.

**Comment by BDpuffy420** [comment]
He is now added to the list.

**Comment by X0-11** [comment]
#281
