### ISSUE TITLE
Assault Pods are Indestructible

### ISSUE THREAD

**Issue by loafe** [HaloSpaceStation/HaloSpaceStation13#2730]
#### Description of issue
Assault pods are indestructible, and since they are a mobile spawn, shit gets kinda wack. 

#### Difference between expected and actual behavior

Assault pods should be destructible. 

#### Length of time in which bug has been known to occur

honestly forever, but cael said they are meant to be destructible, and since they are mobile spawns this probably has to change now

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x ] Issue could be reproduced at least once
- [x ] Issue could be reproduced by different players
- [x ] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [x ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by 24THBN** [comment]
I remember seeing it being destroyed but it took a lot of damage.

**Comment by X0-11** [comment]
they're indestructible

**Comment by loafe** [comment]
@24THBN Koen deleted them after C12 was placed on them a couple times because we ahelped about it

**Comment by ghost** [comment]
As an addon to this issue, mobilespawn for boarding pods that have launched, cannot be disabled. If you try, it gives you this message:
"You cannot do that while the Boarding Pod is flying!"

**Comment by caelaislinn** [comment]
Fixed #2755
