### ISSUE TITLE
Pelicans Can't Leave The ONI Base

### ISSUE THREAD

**Issue by ghost** [HaloSpaceStation/HaloSpaceStation13#2732]
## Description of issue
Pelicans can no longer use the long range flying to leave the ONI base, functionally meaning they're trapped

#### Difference between expected and actual behavior
Pelicans should be able to freely use long range waypoints to come and go from the ONI base

#### Steps to reproduce 
Use a pelican (recommended to test with both planets as the issue may be specific to geminus), take off, attempt to fly to a waypoint on the planet, observe that when you select the waypoint and the progress bar is filled, nothing happens.

#### Length of time in which bug has been known to occur
Approximately one day

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by ghost** [comment]
Update: It appears this affects all dropships. Not sure if this is a geminus-specific bug. Immediate fix is required considering how important dropships are for the gamemode

**Comment by caelaislinn** [comment]
Attempted fix in #2739 but superseded by #2744
