### ISSUE TITLE
[SUGGESTION] Add armor repair kit request papers to loadouts. 

### ISSUE THREAD

**Issue by driecg36** [HaloSpaceStation/HaloSpaceStation13#2736]
#### Description of issue
Armor repair kits are an absolutely crucial tool yet they are in short supply for the covenant who have separate vendors for each species and therefore a limited pool of kits. For example, brutes only get SIX total armor repair kits over the entire round despite having to rely entirely on armor. Adding armor repair kit request papers to loadouts would ensure enough kits to go around without creating a massive amount of them in a vendor that can be hoarded.

**Comment by Sgtwok** [comment]
Bump. They're extremely limited for the covenant.
