### ISSUE TITLE
[BUG} Flying to waypoint is still broken

### ISSUE THREAD

**Issue by driecg36** [HaloSpaceStation/HaloSpaceStation13#2744]
#### Description of issue 
Flying to waypoints is still broken. In this specific round, a spirit was flown down from the Transgression but could not be flown back up. Every time an attempt was made, the prompt appeared but when an option was selected nothing happened. This was tried by two different players to multiple locations. 

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by caelaislinn** [comment]
ze sound of progress
![1445b89bce3efef1](https://user-images.githubusercontent.com/1035969/89478698-0e3ae200-d7d4-11ea-9390-93db7e8d8c24.jpg)

**Comment by caelaislinn** [comment]
Duplicate #2751 (other one has more accurate info)
