### ISSUE TITLE
[BUG] Drop pods occasionally drop you into the volcano on KS7

### ISSUE THREAD

**Issue by driecg36** [HaloSpaceStation/HaloSpaceStation13#2745]
#### Description of issue
I selected the eastern umbilical drop point, and was dropped right into the volcano instead. No beacon or the like was present.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by BDpuffy420** [comment]
IC , as not all drops were safe
