### ISSUE TITLE
[SUGGESTION] Make medic more fun: Necrosis and solutions

### ISSUE THREAD

**Issue by Sgtwok** [HaloSpaceStation/HaloSpaceStation13#2746]
Currently, thanks to how medical, necrosis, and braindeath work, reviving people who have had their pulse stop is extremely unforgiving, most notably thanks to necrosis, which makes revival impossible thanks to how quickly it begins.
Braindeath for 200 HP (most species) carbon mobs happens within one minute, forty seconds, 250 (Spartans and sangheili) get 2 minutes. With how quickly necrosis begins, even if immediate organ replacement were possible, if more than one organ went necrotic, by the time the second organ were replaced, the first would have went necrotic once more.

And if two people have no pulse? There's no point. 

I currently have three solutions:

**Increase the time of braindeath by a minute, and necrosis along with it. (Mostly unpopular)**

**Tri-adrenaline syringes being converted into tri-adrenaline autoinjectors.**

**The time for necrosis setting in being increased to allow medics to actually do their jobs.**

Some combination of the above would also do wonders, and further suggestions to make medic feasible along with heart revival possible within an acceptable timeframe are welcome.

Server Revision: b95d7452c642ed962d04f80b8397ad9849b82f6a - alpha -

**Comment by CommanderXor** [comment]
Maybe make tri-adren or some other chemical actually bring back necrotic organs so you can get them back up? I.e make it so they go to heavy-damage state, so you can bio them back to a bruised state and all that.

**Comment by bloxgate** [comment]
We're re-prioritizing this a bit, as it seems necrosis is bugged a bit. It's happening about 2 times faster than it should.

**Comment by Sgtwok** [comment]
This was intended, and has been a problem at least a month before I made this post.

**Comment by CdrRiley** [comment]
oh i was always wondering why the hell necortic were killing you taht fast now i know

**Comment by bloxgate** [comment]
I know this has been stalled for a while, but I'm starting a discussion for proper solutions over at #2884 so that we don't spam #gitbus with any large conversations.

**Comment by Aroliacue** [comment]
Necrosis time has been increased from 2 minutes to 10 recently, and new brainmeds have been added to hopefully help delay braindeath. Can be closed
