### ISSUE TITLE
[SUGGESTION] Give Kig-Yar a *scree emote

### ISSUE THREAD

**Issue by DronzTheWolf** [HaloSpaceStation/HaloSpaceStation13#2748]
Elites have *wort, now it's time for birds to *scree
I suggest adding a *scree emote to Kig-Yar that plays an appropriate sound clip. Notably, an .ogg I found of a cliff racer screech which is.. Close enough to a rip of Halo Kig-Yar sounds. Not like they speak English in any of the games, anyway.

**Comment by Aroliacue** [comment]
You can use *painscream to get all of the Kig-Yar's screeching sounds. Can be closed
