### ISSUE TITLE
Antimatter bomb cannot be planted on the covenant flagship

### ISSUE THREAD

**Issue by ghost** [HaloSpaceStation/HaloSpaceStation13#2752]
#### Description of issue
Title 

#### Difference between expected and actual behavior
The antimatter bomb should probably be plantable, within its secure room beside the covenant bridge

#### Steps to reproduce 
try to find place to plant AM bomb on the covenant flagship
die

#### Length of time in which bug has been known to occur
probably since the AM bomb change that let it be planted in specific ODP locations

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by caelaislinn** [comment]
#2750
