### ISSUE TITLE
UNSC Ships Spawn With No Helm (and other consoles)

### ISSUE THREAD

**Issue by ghost** [HaloSpaceStation/HaloSpaceStation13#2753]
#### Description of issue
UNSC spawned ships have no helms, and seem to be missing several other consoles as well

#### Difference between expected and actual behavior
they should have at least the basic capability to move

#### Steps to reproduce 
spawn UNSC ship
walk to bridge
observe that all consoles are blank
attempt to use consoles
observe that they don't work for anything

#### Length of time in which bug has been known to occur
Unknown but I believe an extended period of time, I haven't seen UNSC spawned ships move in a while

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by ghost** [comment]
They spawn with consoles, but they're improperly mapped. The actual, usable consoles are hidden underneath the unusable props. Why aren't they the same object?

**Comment by caelaislinn** [comment]
Is this all the summonable ships?
