### ISSUE TITLE
Frigate armoury vendors are inaccessible

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#276]
I thought this was a mapping issue but now I'm not so sure. It looks like you can access the vendors from the front after going through the glass sliding doors but not from the sides even though there is nothing blocking them. 

https://gyazo.com/9e29f4c27ddf964aac9a6191000c3183

**Comment by X0-11** [comment]
Couldn't reproduce it on a private server.

**Comment by caelaislinn** [comment]
It's possible the issue was on my end as I was also having trouble interacting with airlock consoles on the test server, but another player reported these access issues on the test server.
