### ISSUE TITLE
Return of the blindness bug

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#277]
Multiple people have reported the issue, but I haven't been able to repro it. Making an issue so maybe we can get some more info about it.

**Comment by bloxgate** [comment]
Seems to be happening to me every time I join. Currently using latest 511 version (stable I think). Others are saying its 50/50. We may just need to merge some of the more recent Baycode fixes for vision.

As painful as it may be, we may need to have someone go through and update us to current baycode. It could take a while, but I have a feeling it'd be worth it.

**Comment by X0-11** [comment]
It has something to do with people's blinded var not being reset, to reproduce it, you can even use the sleep verb.

**Comment by caelaislinn** [comment]
Fixed in bay update
