### ISSUE TITLE
UNSC NPC Issues: grenades, airlocks

### ISSUE THREAD

**Issue by 5crownik007** [HaloSpaceStation/HaloSpaceStation13#2785]
NPCs are capable of throwing grenades through doors and walls, specifically if the door is transparent, because they will see their target, but not be able to reach them, assuming they don't have access or just didn't open it.
I believe this is because the grenade spawns on the tile adjacent to the NPC and then is thrown.

Also, I discovered UNSC NPCs attempting to "strain open the airlock fruitlessly". Is this them attempting to crowbar a door open with their bare hands? Why? Seems like unnecessary code.

**Comment by X0-11** [comment]
AIs were given the ability to attempt to pry open doors, mostly so flood AI wasn't able to get stuck behind door so easily, iirc
Grenades should be spawned on the AI's tile and utilise normal throwcode
