### ISSUE TITLE
M7 is broken and so is the M7 mag

### ISSUE THREAD

**Issue by Anystar1** [HaloSpaceStation/HaloSpaceStation13#2791]
#### Description of issue
in the vendors there is no M7 it is instead called Magazine and the M7 doesnt shoot

#### Difference between expected and actual behavior
there should be a M7 magazine and the M7 should actually shoot

#### Steps to reproduce 
1) get M7
try to fire
doesnt fire
2) go to vendor
look for M7 mag
no M7 mag and is instead replaced with Magazine

#### Length of time in which bug has been known to occur

im assuming when the M7 got changed 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by loafe** [comment]
I went through the files and tested it locally, the M7 fired for me on the latest alpha branch. The magazines were wrong though, so I fixed that.
