### ISSUE TITLE
Shield Generator Crate available in Cargo

### ISSUE THREAD

**Issue by 5crownik007** [HaloSpaceStation/HaloSpaceStation13#2794]
UNSC + URF can just buy a shield generator from cargo and assemble it in like 2 minutes
Been told by Cael that this should be a tech tree unlock, so crate should be removed and shield circuit should be in tech tree.

I'll deal with this real quick- if I don't have a PR up by 2020/09/10 send me a Discord message or something

**Comment by Aroliacue** [comment]
Cargo updated, can be closed
