### ISSUE TITLE
UNSC AI has comms issues

### ISSUE THREAD

**Issue by DiscordWizard** [HaloSpaceStation/HaloSpaceStation13#2797]
#### Description of issue

Everytime someone sends a message, the name appears blank when you play as the AI. Not even the AI's name appear, everyone's just a void as far as names are concerned

#### Difference between expected and actual behavior

Instead of seeing the speaker's name on the chat, the AI only sees the message but nothing where the name should be, everything's the same blank

#### Steps to reproduce 

Joining as AI and using comms

#### Client version, Server revision & Game ID

513.1532, couldn't find the rest. 16/09/2020 date

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by ondrej008** [comment]
issue could be reproduced by different players, also applies to covenant AI

**Comment by DiscordWizard** [comment]
Also to add to the whole AI problem, apparently they aren't connected to the node inside the main MAC firing chamber too so they can't really use it if the rest of the crew is gone or fighting, nor can they look into it to bolt or interact with anything if there's boarders

**Comment by ilikesaying** [comment]
necropost but yeah, same problem, modern halostation
![ai1](https://user-images.githubusercontent.com/65475697/128123315-b5273a61-3efb-49a9-984d-f60cc26dd337.PNG)
![ai](https://user-images.githubusercontent.com/65475697/128123318-9af36f4e-2333-4a75-b12f-773087f5d9a7.PNG)

**Comment by Stingray540** [comment]
This issue is still ongoing. I'm looking into it but AIcode is a complete mystery to me.

**Comment by Aroliacue** [comment]
Fixed
