### ISSUE TITLE
Spawn radio announcements don't say the name properly

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#280]
https://gyazo.com/ae0138bd3b9b5766848f64de7f13d6b9

**Comment by X0-11** [comment]
Is this still currently applicable? Or is this being kept open pending re-implementation of signal-strength based comms?

**Comment by caelaislinn** [comment]
This was specifically for the telecomms changes I did in 0.2, which is out of date
