### ISSUE TITLE
Infinite phoron in beakers.

### ISSUE THREAD

**Issue by PantasTheDank** [HaloSpaceStation/HaloSpaceStation13#2803]
#### Description of issue
Phoron in beakers is infinite even if you grind just one sheet of it

#### Difference between expected and actual behavior
It shouldn't be infinite

#### Steps to reproduce 
Grind ONE sheet of phoron(remove one sheet from the 1000 stack in medbay)

#### Specific information for locating
ODP/Moonbase

#### Length of time in which bug has been known to occur
I dunno
-->

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by X0-11** [comment]
is this literally infinite, or an exaggeration?

**Comment by PantasTheDank** [comment]
As far as I can tell, its infinite, I didnt see the Phoron units drop down
