### ISSUE TITLE
Suggestion - Hunters as reinforcements.

### ISSUE THREAD

**Issue by SharkLordSatan** [HaloSpaceStation/HaloSpaceStation13#2809]
Like with how Brute Captains, Elite Zealots, and Skirmisher Champions can be deployed after the ODP is destroyed, there should be a chance to be able to spawn in as a Hunter during such acquisition of reinforcements.

Of course, any more than one Hunter being in a round/game should remain tied to admin discretion/events.

**Comment by Sgtwok** [comment]
I'd also be in favor of removing the jiralhanae Captain from the reinforcement roster, as there is already a Jiralhanae Captain that has little difference compared to even a jiralhanae minor.
