### ISSUE TITLE
Armor kits and you: Apparently the Covenant's underfunded

### ISSUE THREAD

**Issue by Sgtwok** [HaloSpaceStation/HaloSpaceStation13#2815]
The UNSC currently get 600 normal repair kits, and 400 miniature repair kits on the ODP
As well as a further 600 normal repair kits and 400 miniature repair kits in the KS7 base
The URF have 400 of each (not counting the extra included in the SoE armory thanks to their limited membership numbers)

The sangheili posses
30 regular repair kits
24 miniature repair kits
The jiralhanae posses
20 regular repair kits
16 miniature repair kits
The unggoy posses 
24 normal repair kits
32 miniature repair kits
The yanme'e posses
16 normal repair kits
20 miniature repair kits (especially notable as they cannot remove their armor to repair)
The kig-yar posses
36 armor repair kits only.

This equals 126 regular repair kits
92 miniature repair kits

This is quite imbalanced, as UNSC and even URF posses several times more repair kits than the covenant, which is even worse when one considers that the repair kit are locked by race, instead of the massive pool of repair kits that everyone gets access too.
(Especially worse when you consider UNSC have far more repair kits than Covenant and URF combined)
Server Revision: 78153a58b7dad251b8ec3738453d2bd1210f19d5 - alpha -

**Comment by SharkLordSatan** [comment]
oh hey i was planning on pushing this issue! (though you did it in a far better way than how i would've written it lmao)

yeah generally i find it very..unusual.. that the covies get so few armor repair kits compared to the unsc/unf vendors. im not sure if the human vendors are actually SUPPOSED to have 100 repair kits per vendor but either way the covenant sorely needs a boost in the number of kits (and maybe some other gear but im not sure what.)
