### ISSUE TITLE
Covenant ship map

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#282]
This isn't necessarily for any specific gamemode, but blocking out a Covenant ship to have on standby for when we start focussing more on Covenant features will be useful. Characteristics: 

- Around 3 zlevels to comfortably hold 20 players (current tests have ~40 players as of 1/1/18)
- Layout inspired by Covenant ship levels in the Halo games
- Require broadly similar areas to be designed to the ones UNSC ships have (bridge, hangars, fighter/shuttle berths, barracks, mess hall, armoury, engine rooms, reactor rooms, gunnery bays, ops bays etc).

**Comment by bloxgate** [comment]
Please don't use the same area definitions as on the UNSC ship though. Make them a /covenant type of the originals or something.

**Comment by Maxattacker** [comment]
I'll start work on this today

**Comment by DoctorOctopusTheOctopi** [comment]
Maxattacker is no longer working on this due to personal issues. As such this request is still open.

**Comment by DoctorOctopusTheOctopi** [comment]
@Flaksim wishes to take this project, as such it is now his.

**Comment by caelaislinn** [comment]
Actually completed ages ago
