### ISSUE TITLE
Suggestion: ODST officer ammo drop should call in ODST ammo variants instead of normal ones.

### ISSUE THREAD

**Issue by BladeburstNINJA** [HaloSpaceStation/HaloSpaceStation13#2829]
#### Description of issue
The mass ammo drop for ODST officers calls in M6D and M7 ammo mags. It should call in M6S and M7S magazines.

#### Difference between expected and actual behavior
ODST officers tend to be in ODST squads so it makes more sense for them to call in ammo for ODST weapons. M6D and M7 magazines would be useless for an ODST squad since none of their weapons could use those magazines.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Aroliacue** [comment]
New ammo variants for supply drops added. Can be closed
