### ISSUE TITLE
Additional Sangheili armour sprites: Zealot, Ranger, Specops, High Councillor, Honour Guard

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#283]
Krautzky appears to be our main Covenant specialist at the moment and will be able to offer more info on the sprite specs. At the moment we have minor (blue) major (red) ultra (white) but could probably use a few more of the elite ranks in there: zealot (gold), ranger (green) and specops (silver/dark grey). 

High Councillors and Honour Guard would both use ultra armour (or a similar variant) but with elaborate headdresses and the Honour Guard get matching pads and badass pike weapons. Rangers are the EVA specialists so they would have jetpacks built into their armour, while specops elites obviously get stealth units in their armour.

**Comment by BDpuffy420** [comment]
#377
