### ISSUE TITLE
[SUGG] Make hellbringers actual flamethrower operators

### ISSUE THREAD

**Issue by Delnth** [HaloSpaceStation/HaloSpaceStation13#2832]
Personally not satisfied with the current hellbringers for various reasons. First, it's meant to be an area denial role with damage over time. Currently, they have too much mobility and projectile is honestly gay.

Here's what I suggest to make them (probably) great:

- Give the hellbringers a backpack fuelpack (just like the one you can see in pretty much all pictures involving an hellbringer) which will be used to either refuel the flamethrower is simply fuel the gun for every shots. This also prevents hellbringers from being a stupidly strong harasser when they get a jetpack. Please, none of that.
- Remove. Fire. Projectile. Have the flamethrower actually project fire that will stay on the ground for a given duration and lit any hit entity on fire as well as those who step on the fire. Hellbringers shouldn't be very mobile, but they should compensate with the ability to completely block their enemy, should they try to push (or retreat).
- Getting shot in the back should have a chance to detonate the fuelpack. Low chance, but still present to encourage flanking hellbringers and also to give them a con that ought to force them not to let their guard down. This is also to compensate with the huge amount of suppressive capacity that they have as well as their ammo count.

**Comment by X0-11** [comment]
they already do project fire onto the ground

**Comment by CdrRiley** [comment]
i like the backpack idea but not detonating bit

**Comment by PrimusOmega** [comment]
In a game that completely revolves around mobility and armor repair, the idea that a unit should be slow and prone to exploding when being shot is not a good one.  They are designed for the current meta, and as recent games display, perfectly fine in terms of balance.  As for jetpack usage, remember that whatever wears them takes increased damage as compensation for the mobility, and more recently shots even drain the flight meter to keep it from being abused in combat situations.  I would not be opposed to a backpack for carrying flamer ammo, but the idea that it should be mandatory is silly, when a backup weapon is also nearly mandatory.

**Comment by X0-11** [comment]
the increased damage point is incorrect.

**Comment by PrimusOmega** [comment]
I need to take another look at the code of the jetpack again then.   Could have sworn it did.  Point still stands though.  Risk reward tool, and it also has startup/pack up delay.  Hit the jetpackers then when they can't move or shoot them until they fall out of the air.
