### ISSUE TITLE
Other Covenant race sprites: Brutes, Grunts, Hunters, Jackals

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#284]
I believe Krautzky is working on these. Brutes should be larger than normal, probably 96x96 while hunters can probably be 128x128. Hunters are easy because they will always have the same gear so the sprites never need to change... so we can actually do shooting and moving animation sequences for them.

**Comment by Krautzy** [comment]
I got jackals and grunts done. Skirmishers will come as well after I do some polishing.

**Comment by BDpuffy420** [comment]
update on this?

**Comment by X0-11** [comment]
I believe elite, brute and jackal sprites are in the codebase. I don't think all the species are implemented though.

**Comment by BDpuffy420** [comment]
As of now I know all the base covie races we need are done, we just need to code them in.

**Comment by BDpuffy420** [comment]
Still need the rest coded in

**Comment by BDpuffy420** [comment]
#580
