### ISSUE TITLE
Different end round options for UNSC on BASE ASSAULT

### ISSUE THREAD

**Issue by thog1** [HaloSpaceStation/HaloSpaceStation13#2847]
Time and time again I see the UNSC secure the bomb off the covenant but not do anything with it which just leads to slogged out long rounds. Instead of giving the covenant back their bomb, I think it would be better if the UNSC could Perma defuse the bomb which leads to round end.

Give the covenant 10 minutes(or more) to get their bomb back before it's perma defused by the UNSC

open to suggestions about alternative timing and other ways to  end the round

**Comment by BDpuffy420** [comment]
#3220
