### ISSUE TITLE
Autobalance broke.

### ISSUE THREAD

**Issue by Glissery** [HaloSpaceStation/HaloSpaceStation13#2849]
#### Description of issue
The auto balance is straight up fucking broken.
XO says that dead people don't count toward auto balance, but yet when I die alone as unggoy deacon, covenant roles are locked to just unggoy+yanme'e minor/major.
Another round, we had 2 jiral, sang, and unggoy while there were just a few UNSC, and we obviously turned them to mush.

#### Difference between expected and actual behavior
See above.

#### Steps to reproduce 
1-play lone covenant wl role
2-die
3-respawn and see covenant is poplocked

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by bloxgate** [comment]
There have been several changes to this recently. Can you confirm if this still happens?
