### ISSUE TITLE
Covenant vehicle sprites

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#285]
We have some old sprites stashed away somewhere for Phantoms and Banshees but they might need to be updated. Some other useful vehicle sprites to have ready will be: 
- [x] Spirit dropship
- [x] Wraith tank
- [x] Ghost LSV
- [ ] Seraph space superiority fighter
- [x] Shadow APC
- [ ] Spectre LAV
- [ ] Tarrasque space superiority fighter
- [x] Banshee
- [ ] Shade turret

**Comment by BDpuffy420** [comment]
bump

**Comment by caelaislinn** [comment]
I'm removing this from the Covenant arc. We'll come back and look at ground vehicles at a later date

**Comment by BDpuffy420** [comment]
#1445 ticking off another one

**Comment by BDpuffy420** [comment]
bump

**Comment by Aroliacue** [comment]
Stale, closing
