### ISSUE TITLE
Ship elevators

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#286]
Mechanical elevator platforms for transporting vehicles and large amounts of cargo between zlevels on human ships and stations. We have sprites ready to roll (96x96 or 3 tiles by 3 tiles). 

The coding for this might be a little bit intricate because it needs to integrate with overmap multiz and handle the request/dispatch logic for elevators as well as do multi tile collision checking.

**Comment by caelaislinn** [comment]
Added in the bay12 update

**Comment by BDpuffy420** [comment]
sweet
