### ISSUE TITLE
T'voan Commando command uplink gives you UNSC equipment

### ISSUE THREAD

**Issue by Shadowtail117** [HaloSpaceStation/HaloSpaceStation13#2891]
#### Description of issue

Self-explanatory.

#### Difference between expected and actual behavior

Should be covie equipment.

#### Steps to reproduce 

Self-explnatory.

#### Length of time in which bug has been known to occur

Discovered today.

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: 138f71dfcf2cd0c09b05a7bf469977c20f04bafd - 9b05a7bf469977c20f04bafd - 
Game ID: b0U-dyv2
Current map: 111 Tauri System, UNSC Outpost

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by BDpuffy420** [comment]
#3114
