### ISSUE TITLE
cant mapvote during lobby

### ISSUE THREAD

**Issue by Anystar1** [HaloSpaceStation/HaloSpaceStation13#2894]
#### Description of issue
mapvote doesnt work during lobby saying too soon to call a mapvote

#### Difference between expected and actual behavior
you should be able to call a mapvote before round starts

#### Steps to reproduce 
do mapvote before round starts
too soon to do vote

#### Length of time in which bug has been known to occur

i think its been like this for a while

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Shadowtail117** [comment]
I believe this is intended, and the option unlocks at 7 minutes into the round.
