### ISSUE TITLE
Basic Forerunner arc sprites

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#290]
- [x] Monitor
- [x] Sentinel
- [x] Halo
- [x] Holopanel/s
- [ ] Light bridge
- [x] Wall and floor turfs

**Comment by caelaislinn** [comment]
There is some vanilla SS13 turf sprites which look nice and vaguely forerunner-y

**Comment by Delnth** [comment]
/VG/ codebase has a nice grey-ish tile, I believe it is called 'living floor' or whatever. Looks quite techy and forerunner-like, much like those in Halo 2/3. Perhaps we can fork it and work something off of it?

**Comment by caelaislinn** [comment]
https://i.gyazo.com/03178cc912625fa4c4b2e1802d6e30ef.png these are the old ones from Bay12, there's actually a good chance these are the ones VG uses

**Comment by Delnth** [comment]
Here: https://github.com/Delnth/vgstation13/blob/Bleeding-Edge/icons/turf/floors.dmi
You'll find the sprite I'm talking about, 'evilfoor' at the end of the list. But the one on your screenshot do look good too.

**Comment by BDpuffy420** [comment]
Two of these have been knocked out

**Comment by BDpuffy420** [comment]
halo was added

**Comment by caelaislinn** [comment]
With the monitors and sentinels added, I'm pretty happy with where this is at for now

**Comment by BDpuffy420** [comment]
more were added later
