### ISSUE TITLE
Autodoc Sprites

### ISSUE THREAD

**Issue by bloxgate** [HaloSpaceStation/HaloSpaceStation13#291]
We'll be needing some sprites for a UNSC auto-doc. One shows up in Midnight in the Heart of Midlothian if you need reference material. As far as I remember it's basically a surgery table with two robotic arms, one for injections and one for other surgical instruments.

Icon States:
* Idle
* Animation of the syringe arm moving onto the player
* One animated with the surgical tools moving around on the player inside it.

**Comment by Kmc2000** [comment]
doing this

**Comment by X0-11** [comment]
I believe someone has created sprites for this. Can't remember who though.

**Comment by BDpuffy420** [comment]
Cassy did, they are currently working on the map though

**Comment by bloxgate** [comment]
Yes. There are sprites for this somewhere. I'll have to make sure I have them before I go and close this issue though.

**Comment by DoctorOctopusTheOctopi** [comment]
Completed.
