### ISSUE TITLE
Apply the loadout system to heavy weapons

### ISSUE THREAD

**Issue by Sgtwok** [HaloSpaceStation/HaloSpaceStation13#2984]
#### Description of issue

Specialist weapons, the LMGs, Sniper Rifles, and Anti-tank weapons are far too common

#### Difference between expected and actual behavior

You'd think being a specialist weapon they'd be less common but the truth is, they're essentially standard issue, with 12 each, there's far too many circulating and zero incentive to play the specialists roles besides handing it off to someone, the loadout system is still in place to an extent, it should be used to limit the amount and ensure that they are overly common.

#### Steps to reproduce 
Grab a specialist weapon
Hand it to someone
Repeat

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by VoiceInYourHead** [comment]
Then let's increase specialists slots atleast to 6 from 4, or make the same with weapons like fuel rod for covies. This is not only UNSC problem probably

**Comment by X0-11** [comment]
odsts get specialist access too

**Comment by Sgtwok** [comment]
> 
> 
> Then let's increase specialists slots atleast to 6 from 4, or make the same with weapons like fuel rod for covies. This is not only UNSC problem probably

You say that like I only think it should apply to UNSC. It should apply to the covenant too.
