### ISSUE TITLE
Neural Lace Injectors Do Not Apply Right

### ISSUE THREAD

**Issue by Max-023** [HaloSpaceStation/HaloSpaceStation13#2985]
#### Description of issue
The neural laces that they inject do not provide the right accesses required.

#### Difference between expected and actual behavior
The access given should be able to suffice for all UNSC equipment.

#### Steps to reproduce 
Spawn neural lace injector, use it, cry.

#### Specific information for locating

obj/item/lace_injector/marine
obj/item/lace_injector/marine_spec
obj/item/lace_injector/odst
obj/item/lace_injector/spartan

#### Length of time in which bug has been known to occur

Unknown

#### Client version, Server revision & Game ID

Current on all accounts.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Aroliacue** [comment]
Fixed
