### ISSUE TITLE
AI unable to see player names on radio channel

### ISSUE THREAD

**Issue by MactoPerFuror** [HaloSpaceStation/HaloSpaceStation13#3004]
#### Description of issue
UNSC AI is unable to see the names of people in their radio. https://cdn.discordapp.com/attachments/912521626657112175/912529710938980392/dreamseeker_xnVkEYg6GR.png

#### Difference between expected and actual behavior
AI is supposed to be able to know who is talking on the radio. Names should appear after the radio channel name.

#### Client version, Server revision & Game ID
Client Version: NA
Game ID: ce0-ajGB
Current map: Geminus City

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Stingray540** [comment]
Duplicate to #2797

**Comment by Aroliacue** [comment]
Fixed
