### ISSUE TITLE
Undecisive map vote crashes the server

### ISSUE THREAD

**Issue by Antonio7272** [HaloSpaceStation/HaloSpaceStation13#3006]
#### Description of issue
Starting a map vote and not picking a map crashes the server, wich does not seem to startup automatically.

#### Difference between expected and actual behavior
The whole server crashes when no map is selected on map vote, shows 
>World restarting to '' map due to mapswitch vote...

And the restart crashes the server

The game should keep going on as inconclusive, as if the vote was never called

#### Steps to reproduce 
Start a map vote, let it go without voting anithing > Crash

#### Length of time in which bug has been known to occur

Maybe for a long time, since usually map votes are called to actually change the map or vote to not do so, or a git issue was not made if it happened

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by bloxgate** [comment]
This also seems to mess something up in the actual server files as well. Just had to rerun the compile script because of this.
