### ISSUE TITLE
Covenant AI starts with less access than it should

### ISSUE THREAD

**Issue by Antonio7272** [HaloSpaceStation/HaloSpaceStation13#3008]
#### Description of issue
The covenant AI (Unsure if UNSC AI too) starts with an access of 3, what does this mean?
It is unable to interact with the ship machines
It is unable to interact with doors (just open and close, as it needs more access to do that)

#### Difference between expected and actual behavior
Actual: AI spawns with 3 access level and has to hack ALL their routers to actually interact with all the ship machines and doors

Expected: The AI starts with an access level of 4 in all the ship and can interact with everything without needing to hack any router

#### Steps to reproduce 

Join Geminus city, join as covenant AI (untested if UNSC AI too)

#### Length of time in which bug has been known to occur

Not sure, but been a long time since there are a lot of complaints about AI not working

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: 5d23e2ae9b3355827ea5abbcfa7e391de34f0595 - alpha - 
Game ID: cfp-dGb2
Current map: Geminus City

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Antonio7272** [comment]
This happens to UNSC AI too, it also has access level of three in all the station

**Comment by Stingray540** [comment]
Bit late here but as far as I know, this is intended. The original intent when I assisted XO in designing these was that you'd start with 3 access everywhere in your own network, but you'd need to exert that extra bit of effort for maximum access for bolts/shocks.
