### ISSUE TITLE
URF Roles on game-mode Elmsville KS7/ODP

### ISSUE THREAD

**Issue by YourPalHolidays** [HaloSpaceStation/HaloSpaceStation13#3016]
#### Description of issue
Unable to join URF roles such as:
Insurrectionist
Insurrectionist Officer
Insurrectionist AI

On game-mode: Elmsville KS7 ODP.

They are not listed on the open job list in the respawn menu, despite being listed as roles the character can join in the character creation's occupation chart. I don't know if SOEs or any faction whitelisted URF roles work or not. 

#### Difference between expected and actual behavior
Being able to join as any basic Insurrectionist role.
Not able to join as any Insurrectionist role. ;-;

#### Steps to reproduce 
Switch to the game-mode and try to join any URF roles.

#### Specific information for locating

On the respawn menu or after you click the button: Join Game!

#### Length of time in which bug has been known to occur

Through the entire length of the round.

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: 789005f7fd0fe79239687190ebbd9cb587d88539 - alpha - 
Game ID: cfA-aQLJ
Current map: 111 Tauri System, Human Colony "Emsville"

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Stingray540** [comment]
This happens because if you vote secret as the gamemode, there's a chance of a URF game mode being selected on KS7, meaning the URF jobs are still there. This isn't a bug, though it is somewhat misleading. Going to close with that in mind.
