### ISSUE TITLE
Additional ships have unlocked slipspace cores.

### ISSUE THREAD

**Issue by Stingray540** [HaloSpaceStation/HaloSpaceStation13#3024]
#### Description of issue
When you spawn in either an additional UNSC (I assume, this I have not tested) or Covenant (Confirmed and tested) ship using the buying options IC, they come with a slipspace drive that, unlike the main drive of the Covenant ship, is able to be removed and armed as a makeshift Antimatter bomb. This is not intended.

#### Difference between expected and actual behavior
Expected - additional SS drives are locked like the one on the covenant cruiser

Actual - additional SS drives can be turned into nukes like the old days

#### Steps to reproduce 
Buy an additional ship
Remove the slipspace core
Use it as a nuke

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Aroliacue** [comment]
SS drive bombs are being reworked, as of current they cannot be armed on bomb points. Closing
