### ISSUE TITLE
Antimatter bomb can be dragged into faction-only areas

### ISSUE THREAD

**Issue by Stingray540** [HaloSpaceStation/HaloSpaceStation13#3025]
#### Description of issue
The Covenant antimatter bomb can be captured by the UNSC and taken to their planetary ONI base - this allows them to make it impossible to retrieve as covenant members cannot physically enter the base to retrieve it.

#### Difference between expected and actual behavior
Expected - something to stop the AM bomb going into the ONI base?

Actual - Nothing stops the AM bomb going into the ONI base
#### Steps to reproduce 
Take AM bomb
Drag to ONI base as UNSC

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by ilikesaying** [comment]
it can also be stored in the many vehicles the unsc has, which can be hidden or aren't usually checked because they're not used by the covenant

**Comment by Aroliacue** [comment]
Antimatter bomb can be respawned. Can be closed

**Comment by BDpuffy420** [comment]
and oni base opens after scan
