### ISSUE TITLE
UNSC Crew Montitoring does not work

### ISSUE THREAD

**Issue by Stingray540** [HaloSpaceStation/HaloSpaceStation13#3027]
#### Description of issue

The UNSC Crew monitoring console does not work. It flashes "access denied" to every rank available on the ODP, including when the AI attempts to access it. 

What's strange to me is that the vars suggest this item has no req_access, yet this still happens. The covenant one has no issues when booted by a crewmember, yet I cannot find any differences besides their icon in the code.

#### Difference between expected and actual behavior
Expected: Click console, you should be able to see a readout of UNSC players similar to how the covenant crew console works.

Actual: Access denied prompts even for the CO and AI when attempting to access. 
#### Steps to reproduce 
Click the console as a UNSC human or AI

#### Length of time in which bug has been known to occur

From what I can tell regarding general AI issues, this has been around since at least Mid 2020. I cannot personally confirm this though

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Aroliacue** [comment]
I'll probably take a look at this myself as the issue seems like a pretty easy fix and I'm finding it personally annoying

**Comment by Aroliacue** [comment]
Fixed
