### ISSUE TITLE
Some kind of grab bug

### ISSUE THREAD

**Issue by DronzTheWolf** [HaloSpaceStation/HaloSpaceStation13#3031]
#### Description of issue

I was unable to move after some shenanigans with a grab. I'm not sure what caused it, but I was pulled away from a grab and it made me unable to move.

#### Difference between expected and actual behavior

You should simply drop the grab.

#### Steps to reproduce 

After grabbing someone, I was either 
A. Stunned by a portable flasher, then pulled out of grab range
or 
B. Grabbed someone after being stunned, then got pulled out of the grab.

#### Specific information for locating

It was a portable flasher, and I was grabbing a jiralhanae captain

#### Length of time in which bug has been known to occur

I only discovered it today, during a round.

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: f8b02ddfc376f2d84a43aca83aa8f737bcc7f61d - alpha - 
Game ID: cfG-djOk
Current map: 111 Tauri System, UNSC Outpost

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Aroliacue** [comment]
Stun effect. Not a bug. Can be closed
