### ISSUE TITLE
odp MAC console walls are blocking the camera

### ISSUE THREAD

**Issue by ilikesaying** [HaloSpaceStation/HaloSpaceStation13#3039]
#### Description of issue

The MAC console walls block the camera in the MAC room on the odp, preventing the ai from accessing the routing node through cameras

#### Difference between expected and actual behavior

The ai should have a clear view of the routing node

#### Steps to reproduce 

look at the mac room and right click on the consoles.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x ] Issue could be reproduced at least once
- [ x] Issue could be reproduced by different players
- [ x] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [ x][ Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)
![unknown](https://user-images.githubusercontent.com/65475697/147845785-1b8108d1-d4de-4d21-8d09-7c875736c16e.png)

**Comment by jusa297** [comment]
As a hotfix, you can ask to be carded as AI, then get taken to the ODP room, hack the routing node then be put back into your core

**Comment by Aroliacue** [comment]
Issue fixed
