### ISSUE TITLE
UNSC Destroying CRS Slipspace Drive

### ISSUE THREAD

**Issue by Aroliacue** [HaloSpaceStation/HaloSpaceStation13#3041]
#### Description of issue
UNSC can very easily destroy the Covenant's slipspace drive by bombing in through the East side of the CRS, completely nullifying their ability to major win/evacuate. This can make tense, long matches, especially on the colony surface, quite pointless, and really has no counter aside from someone sitting in the slipspace room (As the Covenant AI cannot see CRS Atmosphere alarms).

#### Difference between expected and actual behavior
Expectation: Game not becoming impossible to win, Covenant able to escape, CRS resilient to boarders.

Reality: Covenant major unobtainable, cannot escape fleet spawn.
#### Steps to reproduce 
1) Play as any UNSC role
2) Get 4-5 C-12 charges, machete, crowbar
3) Get EVA gear
4) Get in ONI Pelican
5) Long range fly to the East side of the CRS (As it's within Spirit transport range)
6) Plant bombs on engines
7) Plant bombs on doors or machete/crowbar them open
8) Smash glass on Slipspace Drive Core
9) Plant bomb on Slipspace Drive Core

#### Specific information for locating
N/A

#### Length of time in which bug has been known to occur
N/A

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: 36974e2e20f959c94f1d29f79ccc31a8574f8770 - alpha -
Game ID: (Note this is probably the wrong one, I did not get the Game ID for the match this took place in before server restarted) cfM-chBZ

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Stingray540** [comment]
As much as I understand your annoyance with gamer marines charging into the backside of your ship and C12ing the ship - consider this.

If they had no way of destroying your slipspace drive, or the ship outright, it'd be incredibly difficult for them to win at all either. Every time I've seen the fleet arrive or the Covenant lose too hard in their first few engagements, they jump away, denying the UNSC their supreme major victory. Protect your Slipspace drive.

I decree this: 

**SKILL ISSUE**

**Comment by Sgtwok** [comment]
Given how it's the covenant ship, and we have no way to pursue them without breaching our ship, we should have some kind of method to deal with them, perhaps an airlock that rangers can use, as well as the announcement that, yes, we are being boarded, it shouldn't be as easy as it is, since we still have to engage on the ODP.

**Comment by Stingray540** [comment]
> we have no way to pursue them without breaching our ship

Use your spirits to pursue the pelicans. They can go outside the ship the same as you can go outside the ODP.

There is no clean airlock on the ODP for marines to use. There is no announcement that the ODP is being boarded. 

**Skill issue**

**Comment by rtlui** [comment]
The problem is not that they CAN destroy it, is that is TOO EASY to destroy it, the covenant ship has no defenses or protection from behind where the slipspace is specifically, everything important on the odp is heavily protected and in central areas, the slipspace isnt

**Comment by Stingray540** [comment]
>  the covenant ship has no defenses

Humanoid blocking-shields. Multiple doors/walls. The crew. The ODP does not have shields and you don't hear malding. You are both forgetting that destroying the Covenant cruiser is as much the UNSC's objective as it is the Covenant's to destroy the ODP.

> everything important on the odp is heavily protected and in central areas, the slipspace isnt

This is false. The nuke points on the ODP more often than not occur on rooms either 1 wall away from space, or 1 wall and 1 door. Not the case for the Covenant ship.

Seriously. Stop looking at it like "UNSC stopping us from winning waaa". Look at it like "We are too lazy to press humanoid blocking shields" or "The UNSC want to complete their objectives".

**SKILL ISSUE**

**Comment by Sgtwok** [comment]
No more a skill issue than marines being unable to click on yanme'e was a skill issue.

The ODP is not vital to the continuation of the round, the covenant ship is, the covenant ship shouldn't be so laughably easy to infiltrate that a single unga can just go through the back and end the round in 3 minutes.

**Comment by Stingray540** [comment]
Destroying the Slipspace drive does not end the round. It's not easy to infiltrate if you... turn on humanoid shields and guard it.

**SKILL ISSUE**

**Comment by X0-11** [comment]
please test if human-blocking shields are available before you restate this solution again

**Comment by Stingray540** [comment]
They are. I have seen them used in multiple rounds. I'm not just shitposting.
