### ISSUE TITLE
All Geminus scanning points are not shown

### ISSUE THREAD

**Issue by Antonio7272** [HaloSpaceStation/HaloSpaceStation13#3051]
#### Description of issue
When the covenant looks for scanning points with their scanning point locators on geminus, only the one inside the bar and police station is shown

#### Difference between expected and actual behavior
Expected: activating the locator after its on will cycle trough the scanner points

After turning it on or shows the bar then after using it shows the police station no matter how many times you press it

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Stingray540** [comment]
If you click on the scanning thing while it's on, it doesn't turn it off. It cycles the scanning point that it tracks. Have you tried that?

**Comment by Antonio7272** [comment]
No, I will try next time reclamation is voted

**Comment by Antonio7272** [comment]
> If you click on the scanning thing while it's on, it doesn't turn it off. It cycles the scanning point that it tracks. Have you tried that?

Tried doing so, only changed one time and it was too aún to the police station

**Comment by Stingray540** [comment]
>  too aún to the police station
What? Do you mean it toggles between the bar and police station?

**Comment by Antonio7272** [comment]
First of all, doing this on phone is hard. 

And what I meant is when I clicked the scanner like you told me it went from giving me the location of the bar which is default on all the locators to giving me the point inside the police station instead of the other points ask around the map

**Comment by Stingray540** [comment]
Okay, but what I'm asking is, does it ONLY show bar and PD, or does it go bar, PD, X, Y, Z.... etc

**Comment by Antonio7272** [comment]
It shows bar, then pd and only pd, no matter how many times you press it

**Comment by Stingray540** [comment]
> It shows bar, then pd and only pd, no matter how many times you press it

May I suggest editing the original post with this info. Therein lies the problem it seems.

**Comment by Antonio7272** [comment]
Updated it,  ready for XO to lose his mind to trying to fix

**Comment by BDpuffy420** [comment]
issue sorted
