### ISSUE TITLE
Scorpion Shell/Wraith Mortar interaction with explosive debris

### ISSUE THREAD

**Issue by Stingray540** [HaloSpaceStation/HaloSpaceStation13#3053]
The scorpion is generally thought to be worse than the wraith on current balance, despite the two having very few differences aside from the click-on-tile property of the wraith mortar. However, this interaction is another small one that mostly seems to go unnoticed but from what I have observed, can play a huge part in the vehicle effectiveness.

As soon as a wraith hits a scorpion with a mortar, all the areas around it are given the "explosion debris". This doesn't affect the wraith when the scorpion hits it nearly as badly, in fact, the wraith gets another advantage here - The wraith mortar IGNORES the debris, entirely. The scorpion shell does not, and in fact explodes on contact as if it were a bullet hitting a wall.

Essentially that means that every wraith shot on the scorpion encloses it in a bubble of soft-walls that cannot be shot over, but can be shot through by the wraith whereas when the scorpion hits the wraith and causes this effect, it's the opposite - a bubble of soft-cover that the scorpion cannot pierce, but the wraith can shoot over.

This isn't even only an issue when in a direct 1v1. As anyone will notice, explosion debris fills up the map on longer games pretty quickly. That essentially means that the Wraith has a *lot* of cover that it can shoot over, but the wraith cannot.

I'd imagine the best way to solve this would be to make the projectile ignore the debris, but I'm sure UNSC wouldn't complain if the scorpion got the same "hits clicked tile" property too. Doubt it though.

Post requested by XO.

**Comment by X0-11** [comment]
Scorp and Cobra are getting projectiles passing explosive debris.
