### ISSUE TITLE
UNSC Orion w/ SPI Jobslot for UNSC vs Covenant gamemodes

### ISSUE THREAD

**Issue by Yacobpo157** [HaloSpaceStation/HaloSpaceStation13#3055]
#### Description of suggestion: 

Due to considerations of balance, such as how the UNSC is unable to get Spartans during the first phase of Reclamation even if pop balance would normally permit it, I am suggesting that the UNSC get to have Orions. They would act like ODST+ basically, having better stats overall, and would be an improvement on the current balance situation.

#### Specific information for locating

Below are both the code for the armor and the DMI for it. Not sure how finished both are honestly but you can mess with both as needed for you to feel like things are balanced.

Armor's code, change around its benefits and negatives as how you see fit.
https://github.com/HaloSpaceStation/HaloSpaceStation13/blob/alpha/code/modules/halo/clothing/spi_armour.dm
Armor's DMI, there are no in-hand sprites and such as well as there being two different versions, so we'd have to decide on one.
https://github.com/HaloSpaceStation/HaloSpaceStation13/blob/alpha/code/modules/halo/clothing/spi_armour.dmi

**Comment by rtlui** [comment]
if this is implemented they should just be as scarce as elites, not just be "another rank of basic soldier but even stronger now", like they costing 2-3 slots for the faction

**Comment by Stingray540** [comment]
I'm strongly against this. Orions have been redundant and gone from gameplay for a while in favour of spartans (Except in the case of defectors). Spartans are already balanced to being "marine+" so we don't need this. Orions didn't even get SPI armour IIRC, those were Spartan-IIIs, which is a different thing entirely.

Adding more rolebloat isn't necessary, if anything, we should consider adding either Hellbringers or Spartans (Same poplock restrictions) to Phase 1 to balance it out.




> if this is implemented they should just be as scarce as elites, not just be "another rank of basic soldier but even stronger now", like they costing 2-3 slots for the faction

Considering elites only cost 2 poplock (Minors), they're not even that scarce. If anything this sort of deal should be aiming for the 1.5 poplock area (T-Voans) which IIRC the UNSC does not have at this time

**Comment by Aroliacue** [comment]
SPI added separately and Orions can now be made without admin intervention. Can be closed
