### ISSUE TITLE
scanning zone pinpointers sometimes are stuck on a single scanning zone

### ISSUE THREAD

**Issue by ilikesaying** [HaloSpaceStation/HaloSpaceStation13#3060]
#### Description of issue
Scanning zone pinpointers are stuck on a single scanning zone instead of switching to other scanning zones

#### Difference between expected and actual behavior
the pinpointer should switch between all avaliable scanning zones

#### Steps to reproduce 
get pinpointer after destroying odp
get scanning zone
switch to different scanning zone
try to switch to another scanning zone
be unable to

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by BDpuffy420** [comment]
#3212
