### ISSUE TITLE
Monke Sadness (Underpowered Brutes)

### ISSUE THREAD

**Issue by Stingray540** [HaloSpaceStation/HaloSpaceStation13#3065]
This is essentially just a marker for XO but:

Back in the old days brutes were immortal due to their species stats. They were clearly nerfed hard to be even WORSE than spartans and elites at one point. This should be rectified so that they are AT LEAST equal to elites, but ideally given the 5% incremental increase of pain_mod, brute_mod, and burn_mod to spartan stats. 

This is balanced by the fact they do not have access to energy shields, are heavily targeted by marines when they're spotted, and cost 1.5 pop.

you told me to do this XO

**Comment by Aroliacue** [comment]
Pretty sure this is in regards to the Brute buff that happened recently, as Brutes are now capable of undergoing monke madness. Suffice to say, issue... Resolved?
