### ISSUE TITLE
the inf rpm underbarrel shotgun

### ISSUE THREAD

**Issue by ilikesaying** [HaloSpaceStation/HaloSpaceStation13#3066]
#### Description of issue
The underbarrel shotgun has no fire delay, and click dragging will fire **ALL** the shells extremely fast, depending on how fast the cursor is moved

#### Difference between expected and actual behavior
the underbarrel shotgun should have  some fire delay

#### Steps to reproduce 
grab MA5B
attach the underbarrel shotgun
load shells into shotgun
turn on shotgun
click and drag the mouse across the screen
witness rapid fire shotgun

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

https://user-images.githubusercontent.com/65475697/149450986-dc3651a3-dc24-4ced-ad41-5823b83b9f50.mp4

**Comment by Stingray540** [comment]
This has been fixed. Closing.
