### ISSUE TITLE
M6D and M6S ammo is not interchangeable

### ISSUE THREAD

**Issue by Boltersam** [HaloSpaceStation/HaloSpaceStation13#3069]
In light of ammo exchange being intended, the M6S is unable to fit M6D magazines and vice versa, despite using the same ammunition and having the same ammo capacity. This is contrary to a similar example, where the M7 and M7(S) are able to exchange magazines with each other freely.

**Comment by Aroliacue** [comment]
PR up for making M6D and M6S mags interchangeable. Closing.
