### ISSUE TITLE
SPKR Buff

### ISSUE THREAD

**Issue by Chambers02** [HaloSpaceStation/HaloSpaceStation13#3077]
To make the Rocket Launcher a more reliable counter against Hunters and Wraiths
I say to give it a 2x scope
With changing anything it'll still be crap against infantry (unless you hit a wall) and won't put troopers into harm by needing to be close to said enemy tanks and hunters.
(Edit): Also make rockets themselves go faster

**Comment by BDpuffy420** [comment]
#3110
