### ISSUE TITLE
Remove Loading Ship-Map DEBUG message

### ISSUE THREAD

**Issue by rtlui** [HaloSpaceStation/HaloSpaceStation13#3079]
#### Description of issue
This message was made to tell players when a ship was summoned because it causes lag. But its beyond useless right now and the only purpose it serves right now is revealing all the plans a faction had related to space combat. Its a massive IC in OOC breach.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by jusa297** [comment]
Proposed alternative: instead of removing it altogether, remove what type of ship is being ordered. This still keeps an element of surprise while still notifying people that the lag is not the server box dying or from their end.

**Comment by Aroliacue** [comment]
Bumping this, pretty relevant to shifting meta as smallships are getting used more often now

**Comment by BDpuffy420** [comment]
#3127
