### ISSUE TITLE
Yanme'e can hear while being deaf...?

### ISSUE THREAD

**Issue by GLDoS** [HaloSpaceStation/HaloSpaceStation13#3080]
#### Description of issue
Yanme'e are capible of hearing everything when they're deaf, If they just swap to their 'Language', The Hive mind language.

#### Difference between expected and actual behavior
Expectation is that Yanme'e would still be deaf, albeit able to still talk in their language, And not be able to hear Battlenet, or anything else for that matter, Except they do, Including people talking right next to them.

#### Steps to reproduce 
What happened was I was playing a Yanme'e major, And A Scorpion shot at me, And I dodged the 'shell', and the explosion, but went deaf, So I changed my language to the Hivemind to tell the others that I've gone deaf, and couldn't hear, yet I was still hearing everyone talking on Battlenet, But as soon as I went back to 'Shangheili', everything was back to acting as if I was deaf, Swapped back to Hivemind and everything was normal again, Except I couldn't talk, Except in The Hivemind.

#### Length of time in which bug has been known to occur
I'm not exactly clear, but I just encountered just this round(as of making this) Which is Geminus city.

#### Client version, Server revision & Game ID
Client Version: 514
Server Revision: ac0451bd1db25d1f0793583f6e5f3e9be53ed4e9 - alpha - 
Game ID: cf3-aSi1
Current map: Geminus City

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Tupinambis** [comment]
I think that's intentional since it's a "hivemind", and thus you aren't communicating with soundwaves.
