### ISSUE TITLE
Reminder for XO: Underperforming weapons and projectiles that need some severe fixing, already tested

### ISSUE THREAD

**Issue by rtlui** [HaloSpaceStation/HaloSpaceStation13#3089]
#### Description of issue
Made this issue to remind XO of some weapons that are vastly underperforming compared to other weapons of their same factions.

**FIRST:** Slug ammo for shotguns
_This thing is absolutely disgusting, it has the damage of a m6d bullet without the AP and it basically deals less damage than PUNCHING, on top of the slow rate of fire of shotguns, even a kigyar can tank this like it is nothing._

**SECOND:** Pellet ammo for shotguns
_These are the default projectile for shotguns, these are not nearly as bad as the slugs, but compared to other UNSC weapons its a massive downgrade and its not useful most of the time. In short: it is not reliable in any way or form.
THIS PROJECTILE IS ALSO USED BY THE **MAULER**, BUT IT ACTUALLY WORKS IN THAT WEAPON BECAUSE IT IS SEMI AUTOMATIC._

**THIRD:** Concussion Rifle projectiles
_These things have such low damage, that they are almost as bad as shotgun slugs. It is worthless and i already talked with XO about this, but i just wanted to list it here so he can fix it in the future._

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by X0-11** [comment]
Conc rifle got buffed
