### ISSUE TITLE
[SUGGESTION] Add circuitry boards for mechs to the cargo console; buff some utility mechs

### ISSUE THREAD

**Issue by githubuser4141** [HaloSpaceStation/HaloSpaceStation13#3094]
#### Description of issue
Posting as I noticed combat mech circuitry couldn't be purchased from the cargo console and seemingly wasn't available from the circuit imprinter. 

Combat mechs (Durand, Gygax, HRUNTING) aren't seen, ever, due to their boards not being available to purchase from the cargo console. If their boards were available you'd still need a adv. capacitor + scanning module so their construction definitely wouldn't be free-- and the costs from the mech fab could be nerfed if necessary. In solo-game testing, the mechs didn't feel OP and most perished in a single-extended burst of a plasma rifle.

A few balance quirks, though: The mech's ultra ac 2 rifle felt OP, you could spam-click to avoid the fire delay making it shred most targets instantly, and mech punches were.. a little powerful, both stunning you and doing damage through armor. This'd make sense lore-wise but speedy mechs probably should have their punches toned down.

Furthermore a buff for non-combat mechs (Odysseys/Ripley) would be nice as both are useless in combat yet have very niche uses otherwise. E.g. A Ripley currently moves at 4 step_delay which is as slow as the Durand despite it having no offensive capability and dying in a single burst. The Odysseus is quick but has 120 health and no armor so a few shots with any weapon will kill it. It's pretty much useless except as a paper ambulance.

**Comment by X0-11** [comment]
basegame mechs aren't really intended to have a place in the balance at this point I'm afraid.
