### ISSUE TITLE
Guns are broken and need rework

### ISSUE THREAD

**Issue by BDpuffy420** [HaloSpaceStation/HaloSpaceStation13#310]
#### Description of issue

Certain guns after the update no longer fire or only shoot once and missing their projectiles such as the needler and other covies weapons 

#### Steps to reproduce 
Easy...pick up an smg and shoot it once and try again, the same can be done with the needler

#### Length of time in which bug has been known to occur

	During our testing of Team Slayer

#### Client version, Server revision & Game ID
Server Revision: b1c7bd43ef0cd8ee7bde0e2c59d2c10c45895c56 - alpha - 1970-01-01
Game ID: bQk-a3EA

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this (https://github.com/HaloSpaceStation/HaloSpaceStation13/issues/)

**Comment by X0-11** [comment]
This should be fixed now.
