### ISSUE TITLE
Experimental MAC ship has a few issues

### ISSUE THREAD

**Issue by jusa297** [HaloSpaceStation/HaloSpaceStation13#3105]
#### Description of issue
The Experimental MAC ship (In short EMAC from now on) is an unfinished mess that needs to be addressed. The Mapping is atrocious, the damage might be bugged and it's overall un-usable if you don't know how to.

#### Difference between expected and actual behavior
First: there's a console to send faxes that's in the middle of a hallway, occupying the only space to the bridge and the weapon. If you even want to pilot it, you have to wrench it and move it out of the way.

Second: The ship has a completely redundant and empty computer at the bridge with no modules installed and that isn't even completed. I believe this one is meant to be a targeting console but I have no way of knowing.

Third: I have no way to properly claim this, it might be due to the lack of a scanner but the damage value must be bugged or it's not penetrating enough into the ship. As it stands now, the EMAC can take down shields in 2-3 shots, which is amazing, it's what it's supposed to do. When it comes to actually targeting the hull of the ship, it never deals any damage apart from external superficial damage. It shouldn't be SuperMAC levels of penetration, but it shouldn't also just hit the outside either. It tested this multiple times with another player and the Combat MAC ship (CMAC now for short) penetrates far deeper and deals more damage to the hull. I mean this, you can literally hit the CRS without shields for 20 minutes with EMACs and it will never go down. I don't know if it's not supposed to, but the fact still stands. I am aware that damage decreases as the capacitors get damaged. I'm taking this into account when I make this claim.

#### Length of time in which bug has been known to occur
I'm not exactly sure, but I believe this is the case since the EMAC ship was introduced.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by jusa297** [comment]
https://imgur.com/gallery/N1HtUZS

Link with evidence to the problems

**Comment by Aroliacue** [comment]
Working on this now

**Comment by Aroliacue** [comment]
First and second issues fixed and PR'd, third issue was fixed a while ago by MAC buff.

**Comment by Aroliacue** [comment]
Issue fixed, this can be closed
