### ISSUE TITLE
Job Rework

### ISSUE THREAD

**Issue by mcalexev** [HaloSpaceStation/HaloSpaceStation13#3107]
So, this is an idea that was discussed in the Covenant chat for a good while. A solution that would both solve job bloat BUT also allow for more variety at the same time. The idea is, we'd trim down the jobs for covenant to the basic races, and then make the ranks for said races job titles that would also affect the loadout/uniform you're equipped with. It'd allow for more job variety to be added without clogging up the job menu. Could add in job titles like Sangheili Rangers or Jiralhanae Ultras, ecetera, while it'd still just be one job mechanically.

**Comment by Tupinambis** [comment]
This really should only apply to roles that aren't mechanically distinct. However I do support having more title variety for certain roles for flavor where it fits.

**Comment by X0-11** [comment]
most roles that are currently seperated are also mechanically distinct in a number of ways that aren't handled by the outfits alone.
