### ISSUE TITLE
Sniper Rifle/Beam Rifle shots don't pierce glass

### ISSUE THREAD

**Issue by Aroliacue** [HaloSpaceStation/HaloSpaceStation13#3108]
#### Description of issue
For some ungodly reason, these weapon's projectiles can pierce walls and doors, but not one-directional glass panels.

#### Difference between expected and actual behavior
Expected: Sniper rifles should pierce straight through glass.

Actual: They destroy the glass with a single shot, stopping the round.
#### Specific information for locating

Object name: One-Directional Window/One-Directional Reinforced Window

#### Length of time in which bug has been known to occur

Probably forever, but somehow nobody's noticed this before.

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: 777b48a0ca8de221288a5a4e12c3531c608b365f - alpha - 
Game ID: cgb-arCc
Current map: 111 Tauri System, Human Colony "Emsville"

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by 5crownik007** [comment]
This was a purposeful change made a while ago by @X0-11 or @caelaislinn if I recall correctly. Would like one of them to confirm.
