### ISSUE TITLE
Orion surgery

### ISSUE THREAD

**Issue by billymom2** [HaloSpaceStation/HaloSpaceStation13#3117]
#### Description of issue

Orion surgery organs are not on the map. XO said it was an oversight so I'm requesting it gets readded. Also maybe add them to oni cargo supply so we can request more. Also, the sprites for Orion gear are deleted for some reason. so they need recreated or readded if any of you have the files for them still.

#### Specific information for locating

Oni surgery rooms or Orion room for the oni base.

#### Client version, Server revision & Game ID

 4cc6d95c4877249e46ae9194b7527761ce93abcc

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ x] Issue could be reproduced at least once
- [x ] Issue could be reproduced by different players
- [ x] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [x ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Aroliacue** [comment]
This issue has been fixed and can now be closed.
