### ISSUE TITLE
[Suggestion] De-Nerf the ammo printer

### ISSUE THREAD

**Issue by DronzTheWolf** [HaloSpaceStation/HaloSpaceStation13#3120]
#### Description of issue

As of now, the ammo printer only prints four or five types of magazines. It used to print every UNSC and URF non-explosive ammo type. This nerf to the ammo printer has made the Geminus ammo factory almost obsolete, alongside the fact that all the specialty ammo for the UNSC can be vended infinitely. However, it does still have use in providing ammo to civilians, who otherwise can't get their hands on things like BR and MA3 magazines. I propose we go back to the older list of ammo which allowed you to print the URF and UNSC ammo types, instead of just the very basics you can print now.

**Comment by X0-11** [comment]
Oversight, list the commonly available ammo types that should be included and they'll likely get included next time they get a pass

**Comment by DronzTheWolf** [comment]
What is currently available:
-M6D Magazines
-M6S Magazines
-MA5B Magazines
-M7 Magazines

What should also be available:
-MA3 Magazines
-DMR Magazines
-Shotgun shells/slugs, maybe boxes
-BR55 Magazines
-SRS Magazines (Both the SRS and the innie sniper can be bought from gun dealers)

**Comment by billymom2** [comment]
Can you also add kv shotgun magazines?

**Comment by rtlui** [comment]
Isn't power weapon ammo supposed to be bought from smugglers? For the civilians obviously, i agree with adding the regular ammo tho

**Comment by X0-11** [comment]
I think you're meant to buy the ammo for these from vendors rather than print them. MA3 mags should probably be printable, though. Same for shotguns.

**Comment by X0-11** [comment]
wait i've just checked and codewise the printer is defined to print a number of magazines including a fair few you've mentioned as not being in there. is this the ONI ammo printer?

**Comment by DronzTheWolf** [comment]
Well, Mr. XO, the majority of the types mentioned here aren't available to be bought from the vendors. That's why I'm suggesting them here. And the ammo printers I'm referring to are in the Geminus ammo factory and the disco back room where the guns and armor are stored. Both of which have only what I've mentioned. It's possible that during the Geminus re-map to be more condensed, they were accidentally replaced with ONI printers?

**Comment by X0-11** [comment]
I think some changes have been made to the ammo printer. Can this be closed?
