### ISSUE TITLE
E-MAC Map issue

### ISSUE THREAD

**Issue by Chambers02** [HaloSpaceStation/HaloSpaceStation13#3130]
#### Description of issue
The Highcom console blocks you from entering the bride

#### Difference between expected and actual behavior
You are supposed to able to cross from umbie to the main room
Instead you'll get blocked

#### Steps to reproduce 
Summon E-mac
Attempt to enter the main room

#### Specific information for locating

Between the umbie room and the main room

#### Length of time in which bug has been known to occur

Indefinite

#### Client version, Server revision & Game ID

Reclamation

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ x] Issue could be reproduced at least once
- [x ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [ x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by jusa297** [comment]
#3105

Also as a temporary workaround, you can wrench the console to move it out of the way.

**Comment by Aroliacue** [comment]
This issue has been fixed and it can now be closed.
