### ISSUE TITLE
Give huragok a "DO NO HARM" message

### ISSUE THREAD

**Issue by Sgtwok** [HaloSpaceStation/HaloSpaceStation13#3133]
Suggestion is in the title, huragok are under strict obligation to do no harm to others intentionally under any obligation,  recent events have made it abundantly clear that we need a message for huragok upon spawn, preferably, in big letters.

**Comment by jusa297** [comment]
This is somewhat countered by the faction rules, but I agree that not all players would be in the discord so it only makes sense.

**Comment by Tupinambis** [comment]
If Huragoks still have a law system. That'd probably be the best way to handle it on top of a spawn message.
