### ISSUE TITLE
Suggestion: Increase SOLA amount in UNSC Vendors

### ISSUE THREAD

**Issue by Aroliacue** [HaloSpaceStation/HaloSpaceStation13#3138]
As it currently stands, The Covenant get access to multiple forms of Jetpacks, including regular vendors for each species (Jiralhanae get two per vendor) and the Yanme'e species itself, which spawn with a built-in jetpack with no repercussions for running out of fuel. My suggestion is to simply increase the SOLA jetpack numbers per vendor from 1 to 2 or 3 to bring availability more in-line between both factions and promote asymmetric tactics for UNSC forces.

It is also worth noting that the Covenant jetpack (i.e. Thruster Pack) is mechanically identical to the SOLA, however it can fit into a battle pack/backpack for some reason with little space requirement (same as a medkit).

**Comment by X0-11** [comment]
i believe this has been done
