### ISSUE TITLE
Jetpacks randomly Permastun you when landing

### ISSUE THREAD

**Issue by Aroliacue** [HaloSpaceStation/HaloSpaceStation13#3146]
#### Description of issue
Very very rarely, the Jetpack movement stun may gain significant longevity, stunning you for up to 30-40 seconds. During this time you're completely unable to do anything.

#### Difference between expected and actual behavior
Expected: Jetpack landing stun should only last 2-3 seconds

Actual: Jetpack landing stun can last up to 30 seconds
#### Steps to reproduce 
It MIGHT be from changing Z-Levels and landing immediately.
1) Use the jetpack
2) Ascend to upper z-level
3) Land
4) 1/100 chance you'll get permastunned

#### Specific information for locating
SOLA Jetpack, Thruster Pack. Unknown if items influence it. Message log in specific round:

Dante-043 starts moving downwards.
You move down.
Dante-043's S8 SOLA automatically packs up as it deactivates.
You can't dodge roll in your current state.
You can't dodge roll in your current state.
You can't dodge roll in your current state.
Your MJOLNIR Powered Assault Armor Mark IV shields fizzle and spark, losing their protective ability!
Your armor softens the blow!
Dante-043 screams in pain!
Dante-043 is hit by Fuel Rod Bolt in the chest!
Your Mjolnir boots's armor plating is damaged! 
Something feels like it shattered in your left foot!
Your MJOLNIR Powered Assault Armor Helmet Mark IV's armor plating is damaged! 
Dante-043's S8 SOLA roars as it lifts off the ground!
Your armor softens the blow!
Dante-043 is hit by Fuel Rod Bolt in the chest!
Something feels like it shattered in your left leg!
Your MJOLNIR Powered Assault Armor Helmet Mark IV's armor plating is damaged! 
Dante-043's S8 SOLA automatically packs up as it deactivates.
Dante-043's S8 SOLA roars as it lifts off the ground!

#### Length of time in which bug has been known to occur
Possibly forever. Bug has occurred only twice during my time on the server.

#### Client version, Server revision & Game ID
Client Version: 514
Server Revision: 9e7e97ac7149d0591e7f42c50e5ca95fe5ecbe3f - alpha - 
Game ID: cgq-aTml
Current map: Geminus City

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by SharkLordSatan** [comment]
Not a solution but I can confirm I've had this happen to me as Yanme'e at least once a few rounds ago.
