### ISSUE TITLE
AI are unable to see names on radio channel.

### ISSUE THREAD

**Issue by Accoint** [HaloSpaceStation/HaloSpaceStation13#3153]
#### Description of issue
All AI are unable to view the name and job of those talking on the radio.

#### Difference between expected and actual behavior
AI should see names and jobs, like all marines and covenant. Instead, they have no name or job, showing up as a blank.

#### Steps to reproduce 
Join as UNSC, Covenant, or Insurrectionist AI. Talk on radio.

#### Specific information for locating
AI radio code or something.
They ARE able to listen to those next to them without issue.

#### Length of time in which bug has been known to occur
From September 16th, at the latest. To now.

#### Client version, Server revision & Game ID
Game ID: cgv-azVV
Client Version: 514
Server Revision: fa16416a201cf3f59ffed0257d2b91f7ff7d2266 - alpha - 
This has however been going on before the revision.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)
 #3004, #2797

**Comment by Aroliacue** [comment]
This issue is well-known, however our main coder has no clue how to fix it at present. Once we've finished up some other things in the backend I'll ask XO to take another look at it
