### ISSUE TITLE
Suggestion for Rec on Geminus

### ISSUE THREAD

**Issue by CloakerJoker** [HaloSpaceStation/HaloSpaceStation13#3154]
Suggestion - Add Hell-bringers to Rec on Geminus City as a Phase 2? For Phase 1, it would obviously screw with a lotta stuff since the ODP and all but perhaps some kind of announcement can play like Spartan Deployments with something along the lines of emergency reserve troops have been pulled from cryo or something like that?

**Comment by Aroliacue** [comment]
Definitely going to look into this when we go over adding new roles to the different modes. Closing.
