### ISSUE TITLE
Syringe Gun Wont Work

### ISSUE THREAD

**Issue by nameacow** [HaloSpaceStation/HaloSpaceStation13#3157]
#### Description of issue
During a round, I tried to use the syringe gun. I picked it up in Medbay Storage on Geminus City, tried to load it with a syringe gun loader syringe, didn't work. Tried to load it with a normal syringe, didn't work. Ahelped, they said they had zero clue why it wasn't working. Here we are.

#### Difference between expected and actual behavior
- Doesn't fire
- Doesn't load Syringes or SG Capsule Syringes

#### Steps to reproduce 
- Grab syringe gun from Geminus City, and try

#### Specific information for locating
Syringe Gun

#### Length of time in which bug has been known to occur
Since 12am EST 2/15/2022

#### Client version, Server revision & Game ID
Byond 514.1575 , Don't remember server revision or Game ID

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Aroliacue** [comment]
I'll have a quick look and see if its just specifically the medbay storage one or all syringe guns, but it's likely that the gun's broken.

**Comment by nameacow** [comment]
Aighty Tighty

**Comment by Aroliacue** [comment]
You did load the syringes into the cartridges, right?

**Comment by nameacow** [comment]
Tried them with and without catridges. Neither worked

**Comment by Aroliacue** [comment]
They worked fine with cartridges for me. I'll check in-game soon.

**Comment by Aroliacue** [comment]
After a quick look and on the word of Jason, the syringe gun present in the Medbay storage room is actually a mech attachment one. Please label this a mapping issue, I'll resolve it when I go over fixes for Geminus City.

**Comment by Aroliacue** [comment]
Fixed a whole year later
