### ISSUE TITLE
Weapon Containers on Firefight/Stranded lack M6D ammo

### ISSUE THREAD

**Issue by Derpguy3** [HaloSpaceStation/HaloSpaceStation13#3197]
#### Description of issue
The weapon pods in the game modes can spawn with M6Ds, but has the incorrect ammo spawn along with it.
Instead of clips for the M6D, it spawns LMG Drums.

#### Difference between expected and actual behavior
There should be pistol magazines instead of machinegun drums.

#### Steps to reproduce 
Examine the contents of the pre-spawned weapon containers in the armory area, or one spawned as a supply drop.

#### Specific information for locating

Unknown, likely a crate object/type.

#### Length of time in which bug has been known to occur

Uncertain but its probably been like this for a few months.

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: 63b8c1d3774254aee590a35eddc359ebcae94e3f - alpha - 
Game ID: cjc-aozh
Current map: Firefight gamemode on Desert Outpost map

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Aroliacue** [comment]
M6D M225 ammo can now be dropped in by Spartans/Sergeants. Should probably be kept sparse due to the M6D's overall power. Can be closed
