### ISSUE TITLE
UNSC pod shuttle too dark

### ISSUE THREAD

**Issue by darkincarnate** [HaloSpaceStation/HaloSpaceStation13#3205]
#### Client version, Server revision & Game ID
CV - 514
Server rev - https://github.com/HaloSpaceStation/HaloSpaceStation13/commit/2adb958ef102d9053e539d1780d59362bc0bb3a9
GID - cjo-dKoY

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [x
![image_2022-08-14_010755978](https://user-images.githubusercontent.com/111207530/184517318-5824117a-ed12-4bc4-aa49-d9f67105d072.png)
 ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Aroliacue** [comment]
I'll PR the fix through on my next update, shuttle had no lights so I've just added some.

**Comment by X0-11** [comment]
It was also missing an area define, so that should be fixed too.
