### ISSUE TITLE
Pop-balance Rework Suggestion

### ISSUE THREAD

**Issue by SharkLordSatan** [HaloSpaceStation/HaloSpaceStation13#3211]
#### Description of issue
Currently as it stands, the pop-balance mechanic is rather wonky at best and _borderline non-functional_ at worst. From my understanding it's meant to prevent one team from being over-saturated with people by giving specific roles (i.e Unggoy Minor, Sangheili Major, Jiralhanae Captain, etc) "costs". So for example a Sangheili Ultra might cost 3 points, which contributes to a certain number threshold based on the number of players actively playing.

In theory, this is fine and dandy. However this frequently leads to situations where people may sometimes be vastly outnumbered by the other team because either the pop-balance mechanic doesn't kick in properly, or people choose to play as ranks that have a high cost and thus allow the other time to outnumber them. This oversaturation of pop **usually seems to occur with UNSC** as ODSTs and Marines don't have that high of a cost compared to many of the Covenant ranks/species (particularly Sangheili or Jiralhanae) and the only truly high-costing UNSC rank (Spartan-II) is limited in number anyway.

So, I propose a solution.

Currently, Mgalekgolo and Spartan-II slots are dependent on how many players are actively playing (and NOT spectating/dead/sitting at the lobby). Either 12 or 15 people are needed for a single Spartan-II and Mgalekgolo slot to open up, and more (possible double?) for the maximum of 2 slots.

So what if we applied a similar system to ALL ranks, species, etc?

Let's say there's 20 people playing on a server, divided perfectly equally; 10 people playing UNSC, and 10 people playing Covenant. Based on these numbers, there'd be 10 slots open for Marines, and 10 slots open for Unggoy Minor, Major, or Kig-Yar. Or; 5 slots open for ODST, 3 slots open for Sangheili Minor, and 2 slots open for Sangheili Major. The numbers would change **depending on how many people are playing on a specific team;** for example, if there's more UNSC than Covenant, then there would be less ODST slots open and more marine slots instead, while the Covenant would be able to have more slots of "stronger" stuff (like Elites) available than if the two teams were perfectly equal in number.

Obviously these are just meant to be examples as the actual balancing would probably look different, but personally I think this system could work better than the current "cost"-based pop balance system.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by ghost** [comment]
`then there would be less ODST slots open and more marine slots instead`
`Covenant would be able to have more slots of "stronger"`
There is a gimmick - you just forcing the game to outnumber one faction by another. Yes, Major elite is fun and all, but 10 marines to fight against - not.
Even right now there is a problem - 10 marines&odst on ODP and 3 unggoys. Even if Ultra *happen to exist*, he would be just swarmed.

**Comment by SharkLordSatan** [comment]
Yeah, the issue of 10 marines VS like 4-5 Covenant because one of them decided to go Sangheili Ultra or Unggoy Deacon is what I want to amend.

Even then, the examples I gave are just that - _examples_ of how the system could work. They aren't meant to be final numbers because they, in practice, would probably not actually be balanced at all.

**Comment by ghost** [comment]
Yes, but there is another gimmick - there were unggoys major/minor. All other details i will put in DM since offtopic.

**Comment by SharkLordSatan** [comment]
I'm not understanding what you mean by "gimmick" in this regard, could you elaborate?
