### ISSUE TITLE
Tank bugs

### ISSUE THREAD

**Issue by CapCamIII** [HaloSpaceStation/HaloSpaceStation13#3230]
#### Description of issue

Okay so wraith/scorp get blocked by explosion debris, making moving around the battlefield cancer.
and scorp's scope does zoom out, but when unscoping it puts you to a normal on-foot 7 tile camera, and you have to dismount and re-mount to get your proper vehicle camera back

#### Difference between expected and actual behavior

Wraith/scorp shouldn't be blocked by explosion debris like other vehicles
Scorp scope shouldn't break your vehicle zoom-out on use.

#### Steps to reproduce 

Shoot in a wraith/scorp and try and go past your debris.
Zoom in and out in a scorp

#### Length of time in which bug has been known to occur

Since explosion debris was added
Since scorp got its scope added.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Aroliacue** [comment]
I'll have a look at this

**Comment by X0-11** [comment]
I believe this was fixed.
