### ISSUE TITLE
Weapons  in-hand sprites fixes and wielding 

### ISSUE THREAD

**Issue by BDpuffy420** [HaloSpaceStation/HaloSpaceStation13#325]
Some weapons have temp coder sprites and need to be replaced with new updated ones, also need to implement two-hand wielding on some of the weapons as well for obvious balance,

**Comment by 5crownik007** [comment]
Sprites for wielded weapons are complete

**Comment by BDpuffy420** [comment]
Alright cool just PR them

**Comment by BDpuffy420** [comment]
#336
