### ISSUE TITLE
UNSC vehicles sprites

### ISSUE THREAD

**Issue by BDpuffy420** [HaloSpaceStation/HaloSpaceStation13#326]
We have some sprites for the mongoose  which is fine and warthog that needs to be updated. Some UNSC vehicles we need done are:
- [x] [M12 Light Reconnaissance Vehicle](http://halo.wikia.com/wiki/M12_Light_Reconnaissance_Vehicle) (Warthog)
- [X] [M831 Troop Transport](http://halo.wikia.com/wiki/M831_Troop_Transport) (Troop 'Hog) 
-  [X] [M808B Main Battle Tank](http://halo.wikia.com/wiki/M808B_Main_Battle_Tank) (Scorpion)
- [ ] [M312 Heavy Recovery Vehicle](http://halo.wikia.com/wiki/M312_Heavy_Recovery_Vehicle) (Elephant)
- [ ] [XRP12 Combat Support Vehicle](http://halo.wikia.com/wiki/XRP12_Combat_Support_Vehicle) (Gremlin)
- [ ] [M400 Artillery System](http://halo.wikia.com/wiki/M400_Artillery_System) (Kodiak)
 More to be added.

**Comment by caelaislinn** [comment]
Can we get civilian and medical variants of the troop transport hog? Also a couple of civilian vehicles for colony maps too.

**Comment by BDpuffy420** [comment]
#582

**Comment by BDpuffy420** [comment]
bump

**Comment by BDpuffy420** [comment]
Cobra has been added

**Comment by BDpuffy420** [comment]
#1452

**Comment by Aroliacue** [comment]
Stale, closing
