### ISSUE TITLE
the account uplink computer

### ISSUE THREAD

**Issue by Loldaddy5676** [HaloSpaceStation/HaloSpaceStation13#3270]
the colonists are able to access the bank accounts of every faction in the game by simply getting account id. they are also able to suspend these accounts and stop the factions from using cargo. this only affects the urf currently due to their reliance on cargo to get their equipment but once the cargo updates come and people start using cargo a lot more. they wont be able to do anything because one colonist on the ground decided to take the captains id and suspend everyone's account.

#3265

**Comment by Aroliacue** [comment]
I'll have a look at it, thanks for the heads-up

**Comment by Aroliacue** [comment]
I've removed the account uplink computer on Geminus, I haven't touched computer module code before so I'll properly fix this at some other time. For now, this can be closed

**Comment by Loldaddy5676** [comment]
right found one more account uplink terminal in the vault in gem plus the one in the bank of the urf mission, if you can get rid of those too would be cool.

**Comment by Aroliacue** [comment]
Thanks for finding these! I'll get rid of them later
