### ISSUE TITLE
The cargo stamp in the ONI cargo is stuck and unreachable

### ISSUE THREAD

**Issue by Derpguy3** [HaloSpaceStation/HaloSpaceStation13#3290]
#### Description of issue
The cargo stamp that was added into the ONI base cannot be grabbed. 
Its stuck on a table behind the cargo console and a filing cabinet.

#### Difference between expected and actual behavior
I should be able to grab the stamp for burocracy work

#### Steps to reproduce 
1. Go to the ONI base, and then the cargo room.
2. Go to the spot by the cargo console and filing cabinet
3. Attempt to grab le stamp.
4. Fail.

#### Specific information for locating

N/A

#### Length of time in which bug has been known to occur

Probably since the ONI cargo had a redesign.

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: 6a8f5ce98703d05ab56d2f909a9c866f9d063769 - alpha - 
Game ID: clS-dLUp

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Aroliacue** [comment]
Already fixed in latest PR, just needs merge

**Comment by Aroliacue** [comment]
Fixed, can be closed
