### ISSUE TITLE
cannot interact with MultiZ open space tiles

### ISSUE THREAD

**Issue by ilikesaying** [HaloSpaceStation/HaloSpaceStation13#3291]
#### Description of issue
you cannot interact with any open space tiles in the new MultiZ system

#### Difference between expected and actual behavior
should be able to interact with open space tiles
(building lattices, throwing people)

#### Steps to reproduce 
fly to the upper level on KS7/Geminus
try to build lattices on open tiles/try to throw someone off the roof
cannot

#### Length of time in which bug has been known to occur

since MultiZ view got added

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by BDpuffy420** [comment]
nades cant be thrown either or shoot
