### ISSUE TITLE
SUGGESTION: make surgery faster/make it easier to see if a person is ghosted

### ISSUE THREAD

**Issue by ilikesaying** [HaloSpaceStation/HaloSpaceStation13#3313]
currently, replacing necrotic lungs/hearts is a very tediously painfully slow process.
The process of replacing a necrotic heart/lung is so slow that if you do not biofoam the patient midway (which closes the surgical incision by the way), the patient WILL go braindead, undoing all your progress.

Even Worse, since a majority of people ghost the moment their heart stops, you might just be replacing the organs of a ghosted body, wasting all the time and effort put into the surgery.

**Comment by Aroliacue** [comment]
I'll have a look at this
