### ISSUE TITLE
Hunters can ride ghosts while crouched

### ISSUE THREAD

**Issue by Aroliacue** [HaloSpaceStation/HaloSpaceStation13#3321]
#### Description of issue
Hunters can ride ghosts (and probably another other vehicle) while in combat crouch and fire out from it.

#### Difference between expected and actual behavior
Expected: Hunters should not be able to fire their weapons out of vehicles.

Actual: Hunters can ride a ghost like a skateboard and completely ignore movement penalties.
#### Specific information for locating
N/A
#### Length of time in which bug has been known to occur
For all eternity.

#### Client version, Server revision & Game ID
Server Revision: 968fe5be38b586e99855c8c2c2f7db2105e1f00b - alpha - 
Game ID: clW-aEgR

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by X0-11** [comment]
I've put a change in that makes firing out of vehicles nonviable for hunters.
