### ISSUE TITLE
Round Early End 

### ISSUE THREAD

**Issue by UnknownMurders** [HaloSpaceStation/HaloSpaceStation13#334]
#### Description of issue
Round ends early when both factions are present. 

#### Difference between expected and actual behavior

Actual behavior is when round should not end early. You probably know this. 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by bloxgate** [comment]
Uh...

Any actual details?

**Comment by UnknownMurders** [comment]
You were present. Beyond was present. We don't know the codes behind it.

**Comment by caelaislinn** [comment]
Do you mean there was innie and ODST still alive? How often did this happen?

**Comment by X0-11** [comment]
I may have tracked down what's causing this, unsurprisingly, it's a missing word or 2.

**Comment by bloxgate** [comment]
I'm still not sure what the actual issue is supposed to be here.

**Comment by BDpuffy420** [comment]
not enough info.
