### ISSUE TITLE
[BUG?] Round ends when 4 Scanning Devices are destroyed, despite Covenant having 6 available

### ISSUE THREAD

**Issue by Aroliacue** [HaloSpaceStation/HaloSpaceStation13#3345]
#### Description of issue
Despite having six scanners total, Reclamation ends when only 4 of them are destroyed. I assume this might be intentional, but as all the scanners are grouped together, this can lead to some pretty sudden game-overs, especially if only a portion of the scanners are hidden in other parts of the ship.

#### Difference between expected and actual behavior
Expected: All scanners need to be destroyed for round to end.

Actual: 4/6 need to be destroyed for round to end.
#### Steps to reproduce 

1) Collect four scanners together. Keep two scanners safely away.
2) Blow up the four scanners.
3) Observe as the round ends.

#### Specific information for locating
invasion_scanner.dm

#### Length of time in which bug has been known to occur
Probably forever

#### Client version, Server revision & Game ID
N/A

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Loldaddy5676** [comment]
theres only 4 scanners.... unless they added more. are you not mistaking the radio jammers as scanners?

**Comment by Aroliacue** [comment]
There's six scanners. Two of them were actually being deleted due to being placed opposite to O2 lockers, so I've moved them to a better position.

**Comment by Loldaddy5676** [comment]
checked again still 4.......

**Comment by Aroliacue** [comment]
Are you checking in-game or on DMM?

**Comment by Loldaddy5676** [comment]
in game. at round start there is only 4.

**Comment by Aroliacue** [comment]
"Two of them were actually being deleted due to being placed opposite to O2 lockers, so I've moved them to a better position."

You must have missed me saying this. It's been fixed now. I've moved them to the bomb room.

**Comment by Aroliacue** [comment]
Not a bug, file edit, will talk to XO about it.
