### ISSUE TITLE
[SUGGESTION] Mauler Nerf

### ISSUE THREAD

**Issue by Aroliacue** [HaloSpaceStation/HaloSpaceStation13#3349]
Currently, the Covenant Mauler uses the exact same rounds as the UNSC Shotgun.
![image](https://user-images.githubusercontent.com/96730930/214181515-6f605420-78aa-4be6-930b-924cce374037.png)
![image](https://user-images.githubusercontent.com/96730930/214182844-b0fed10f-b10f-4cc5-b674-f7cab9a8d80a.png)

My suggestion is to simply make an alternative ammo type with 6 pellets instead of 8, and 20 damage instead of 22. This brings the maximum damage per shot down from 176 to a much more reasonable 120 for a weapon that's semi-automatic, very fast to reload and doubles as a melee weapon, compared to the pump-action mechanism of the M90 and its significantly slower reload speed.

I don't want to PR these changes as I'd rather gather thoughts on it and put up a test server to gauge its power. If the weapon does get nerfed, I'll be more than happy to add it to Covvie cargo.

**Comment by ilikesaying** [comment]
actually the UNSC Shotgun uses a different shell
![image](https://user-images.githubusercontent.com/65475697/214183449-403c7062-da45-4e30-b8e7-8aabad8280d8.png)
![image](https://user-images.githubusercontent.com/65475697/214183708-3dc5effa-77e0-4d97-a695-d3cf659b87fc.png)

**Comment by Aroliacue** [comment]
It appears I have fucked up somewhere, because I've given the supply drops the wrong one. Uh-oh.

**Comment by X0-11** [comment]
this may need to be amended, yeah
