### ISSUE TITLE
Zeal scout suits speed multplication if held

### ISSUE THREAD

**Issue by AtomicGalaxy** [HaloSpaceStation/HaloSpaceStation13#3363]
#### Description of issue

When held in hand Zeal scout suits will still give you increasingly high speed boosts (up to 3x which makes you move faster then ghosts)

#### Difference between expected and actual behavior
This is probably unintended as holding a scout suit likely shouldn't give you a speed increase

#### Steps to reproduce 
Wear scout suit. Hold two scout suits. Go mach 10

#### Length of time in which bug has been known to occur
Likely  forever

**Comment by Aroliacue** [comment]
Fixed
