### ISSUE TITLE
HUD bar for Spartan/Elite shields

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#337]
HUD work is pretty difficult for newer SS13 coders, however I'll be able to guide through anyone who wants to give this a go. Getting good looking animated shield bars may actually be the hard part.

**Comment by caelaislinn** [comment]
I have sprites for the spartan shield bar

**Comment by BDpuffy420** [comment]
@caelaislinn  do you still have it?

**Comment by caelaislinn** [comment]
Nope. I had a dig around and can't find them. I'll be able to do half decent ones myself though they might look a little blocky

**Comment by Stingray540** [comment]
This has been implemented for a while now. Closing.
