### ISSUE TITLE
An extra period is being added to every sentence including talking

### ISSUE THREAD

**Issue by Derpguy3** [HaloSpaceStation/HaloSpaceStation13#3380]
#### Description of issue
An extra period is being added to most dialog in the chat, making some sentences look weird.

#### Difference between expected and actual behavior
"Hello." is being turned into "Hello.."
or
"What was that?" into "What was that?."
#### Steps to reproduce 
Say anything in game.

#### Specific information for locating

Uncertain.

#### Length of time in which bug has been known to occur

Unknown.

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: 67b749666d84339251c5125faa1665da6eead378 - alpha - 
Game ID: cma-aaKm

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by X0-11** [comment]
Fixed.
