### ISSUE TITLE
[SUGGESTION] Forerunner Suppressor Weapon Balance

### ISSUE THREAD

**Issue by nameacow** [HaloSpaceStation/HaloSpaceStation13#3412]
# SUGGESTION, WEEP.

**This is going to break some format since there isn't much room for feedback issues as much as technical issues**

#### Description of issue
The Z-130 is overpowered, and it's **GOING** to get power gamed if not removed from Covenant cargo. It is freely available for purchase despite how powerful it can be. It's fine as a forerunner weapon for admin events (forerunners sorta expected to be overpowered), but it shouldn't be given willy-nilly to anyone who opens the cargo console.

##### Proof

Z-130 -	burst = 6 , burst_delay = 1.4   - Shoots more and faster than standard rifles.
MA5B -    burst = 5 , burst_delay = 1.8
Type-25 - burst = 5 , burst_delay = 1.8

HardlightSupressor -  damage = 25 , armor_penetration = 20 , penetrating = 1 , shield_damage = 15  - More shield damage and penetration, with damage comparable to the normal guns. Gives it insane damage to most people as AP is extremely important.
Plasmarifle              -   damage = 30
7.62                         -  damage = 30
12.7 UNSC              -   damage = 50 , shield_damage = -10 , armor_penetration = 30

The Z-130 not only SHOOTS faster, but will do more damage to  your average soldier since it penetrates through armor. There is literally no point to grabbing any other weapon as covvie BESIDES this thing, the only blockade being money (which you get already, and can grind easily)

**Comment by X0-11** [comment]
It's intended to be somewhere between an SMG and a rifle, although i think the stats have changed since I last modified it. I'll make a tweak.
