### ISSUE TITLE
Bruteshot and Brute adrenaline issues

### ISSUE THREAD

**Issue by OuterMostMonk** [HaloSpaceStation/HaloSpaceStation13#3457]
This issue is to highlight two problems brutes have, a few other players have been pointing out these issues so I am making a gitissue.

#### Bruteshot

The Bruteshot has a few issues that prevent it being useful:
1. The grenade explosions produce smoke which prevents further grenades being fired into the smoke at targets
2. Grenade shots easily get caught on debris making it dangerous to use in a chaotic battlefield (Not sure if bruteshot creates debris too)
3. The explosion radius being 3x3 means a target has to be on an adjacent tile to the grenade to take any damage at all. Faster enemies can just run out of range of the grenade before it explodes because it takes a second to explode.
4. Grenade belts cannot fit in martial belts, often requiring explosive pouches instead
5. It cannot be reloaded on the move, unlike the shotgun.

The only practical use for a bruteshot is against slow enemies, or to be used when running away from an enemy. The concussion rifle plays a similar role of displacing enemies but is far more useful and only available in elite vendors.

#### Adrenaline

Brutes needing adrenaline to reach 100u before it is converted into a strong painkiller can cause their heartrate to skyrocket. This causes damage to the heart which is not ideal, requiring inaprovaline to counteract the heartrate and probably peridaxon to heal the damage.

Getting suppressed by turrets or other fast firing weapons can cause a large spike in adrenaline.

**Comment by X0-11** [comment]
Adrenaline has been reworked to function differently, so these issues are not likely to still be present.
