### ISSUE TITLE
Armor values are messed up for bullets

### ISSUE THREAD

**Issue by bloxgate** [HaloSpaceStation/HaloSpaceStation13#371]
#### Description of issue
The bullet armor value for Marines is 95. That's the same as MJLONIR's.

Insurrectionist armor is more bullet resistant than that of ODSTs.

#### Difference between expected and actual behavior
Marines should have significantly less effective armor. ODST armor should be better than or equal to that of the insurrectionists.

I'd personally suggest 40 for innies, 45 for marines, and 50 for ODSTs for now.

**This is only for bullets not all types of armor**

#### Steps to reproduce 
Play a round of Insurrection. You'll see.

#### Specific information for locating

code/modules/halo/clothing/{marine,odst,insurrectionists}.dm

#### Length of time in which bug has been known to occur

Reported today in Discord

#### Client version, Server revision & Game ID

N/A

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by BDpuffy420** [comment]
currently working on this.

**Comment by BDpuffy420** [comment]
#372
