### ISSUE TITLE
City ATV minor "Morale" upgrade (Feature Request)

### ISSUE THREAD

**Issue by subdon** [HaloSpaceStation/HaloSpaceStation13#394]
We all love and like the new ATVs for the city map right?
Well how about a minor morale upgrade?
Ladies and gentlemen i present to you the definite upgrade:
the ability to make 4 people ride the ATV on each other's shoulders for morale boost (which i comically refer to "the clown car")

1) how would this improve morale? 
With the sound of 3 people bashing the batons against shields the morale will never run low.

2) Would not this be a huge risk for the personnel?
With a huge reward of advanced firepower

**Comment by BDpuffy420** [comment]
There would have been other vehicles but they are bugged

**Comment by caelaislinn** [comment]
Please put feature requests through a member of the dev team instead of creating issues for them directly
