### ISSUE TITLE
Can board vehicles while in crit

### ISSUE THREAD

**Issue by 5crownik007** [HaloSpaceStation/HaloSpaceStation13#395]
#### Description of issue
I was in crit and I boarded a mongoose

#### Difference between expected and actual behavior
If yer shot and unconcious
can you still board a mongoose?
:thinking:

#### Steps to reproduce 
1. get into crit, being shot with a plasma rifle is a good way, make sure you're standing next to a vehicle
2. board the vehicle with the verb
3. can't drive it
4. disembark with the same verk
5. die of your wounds

#### Specific information for locating
at any vehicle
mongeese
ghoasts

#### Length of time in which bug has been known to occur
instantaneous once you click the verb

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by DoctorOctopusTheOctopi** [comment]
I tried this and couldn't replicate the bug, Is there anything else that happened when this bug occurred?

**Comment by DoctorOctopusTheOctopi** [comment]
Fixed by @X0-11
