### ISSUE TITLE
science and robotics lack materials to start

### ISSUE THREAD

**Issue by Togopalis** [HaloSpaceStation/HaloSpaceStation13#397]
#### Description of issue

science and robotics divisions in maps normally start with several sheets of metal and glass for an early progression before needing to depend on miners. geminus' research department has been underfunded and lacks both metal and glass

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this]

**Comment by BDpuffy420** [comment]
#425
