### ISSUE TITLE
Kig-Yar movement is very slow

### ISSUE THREAD

**Issue by Nightspark43** [HaloSpaceStation/HaloSpaceStation13#398]
#### Description of issue
Kig-Yar move far too slow, they move at about the same speed as a grunt, when they should be far faster.

#### Difference between expected and actual behavior
Kig-Yar speed should be comparable, or even exceeding that of a Sangheili, they are actually far slower, making their existance as scouts pointless.

#### Specific information for locating
In the code it would be the species files, adding slowdown = -1 or -1.5 should fix the issue.

#### Length of time in which bug has been known to occur
About a week and a half.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by BDpuffy420** [comment]
#579

**Comment by DoctorOctopusTheOctopi** [comment]
Fixed
