### ISSUE TITLE
Police Roles for Geminus Colony

### ISSUE THREAD

**Issue by bloxgate** [HaloSpaceStation/HaloSpaceStation13#403]
(No need for a bug format for this, sorry)

As evidenced by a few recent rounds, vigilante justice produces way too much drama. Especially when they get the idea to use lethal weaponry against **suspected** criminals.

As such, I propose that we add a police role or possibly a full department to Geminus, with less-lethal or non-lethal weaponry available and hope that helps with the problems.

**Comment by BDpuffy420** [comment]
#424
