### ISSUE TITLE
Improve overmap flight model

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#408]
- Readd pixel based movement
- Tweak flight control model

**Comment by bloxgate** [comment]
I just want to point out that the autopilot does work now. So we probably don't want to break that again.

**Comment by caelaislinn** [comment]
The current autopilot is based off straight line pathfinding, any change to the flight model will invalidate that

**Comment by X0-11** [comment]
Changing the flight model may not be required. There's a set time between

**Comment by caelaislinn** [comment]
Duplicate #413
