### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by T-rexsuper1** [HaloSpaceStation/HaloSpaceStation13#462]
#### Description of issue
Bug with pelican

#### Difference between expected and actual behavior

So bug, I think when you leave the pelican you don't have to control it's weapons, and you must be UNABLE to do so, but you can.

#### Steps to reproduce 

You come in the pelican as gunner, leave it, but you still got gun in hand and you can aim it and fire, and pelican do so.

#### Specific information for locating

Every dropship

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by DoctorOctopusTheOctopi** [comment]
With the recent Vehicle Overhaul ( #513 ) this issue is outdated. Thanks for the report though!
