### ISSUE TITLE
Sprite Requests

### ISSUE THREAD

**Issue by DoctorOctopusTheOctopi** [HaloSpaceStation/HaloSpaceStation13#496]
- [x] UEG Friendly Sprites for the Ballistic Vests and Helmets.
- [ ] UEG Friendly hats for Peacekeeper beret, Home Guard beret, Customs and Trade beret, orbital assault beret, Government Research beret, Health Service beret, Diplomatic Security beret, Border Security beret
- [ ] Respriting all Nanotrasen clothing, hats and jumpsuits to fit Misriah Armory's Color Scheme.
- [x] ODST Armor/Weapons Vending Machine
- [x] GCPD Warthog Sprites
- [x] Custom Magnum for the USNC CO
- [x] Humbler Stun Baton held sprites, right now when someone holds it, its just invisible.
- [x] Silenced Magnum held sprites, right now when someone holds it, its just invisible.
- [x] Backsprites for guns.
- [ ] Research and Development console resprite, making it more halo-esque.
- [ ] Halo themed blast shutters.
- [x] Better nanolaminate floors/walls for covvies.
- [ ] Pirate themed kig-yar gear/armor.
- [ ] Resprite of Colonial Marshals Badge.
- [ ] Resprite of Colonial Marshals Jacket into a Windbreaker-esque version.
- [ ] A folded up version of the Colonial Marshals Windbreaker
- [ ] Combination of a windbreaker+ballistic vest for Colonial Marshals.
- [ ] Forerunner walls/floors/doors, requested by Flaksim.

I'll update the list as I crave more sprites. To any spriters who take these requests you're berry good. <3

**Comment by BDpuffy420** [comment]
Most of these have been completed

**Comment by BDpuffy420** [comment]
This is still open to whoever wants this
