### ISSUE TITLE
Unable to deconstruct power storage units

### ISSUE THREAD

**Issue by CoolfoolFTW** [HaloSpaceStation/HaloSpaceStation13#518]
#### Description of issue
You cant deconstruct power storage units.

#### Difference between expected and actual behavior
You're supposed to be able to disassemble power storage units

#### Steps to reproduce 
Try to deconstruct a power storage unit by turning the input and output off, and using a screwdriver to open the hatch.
Then you will try to use the wire cutters to deconstruct the terminal but it wont work.
If a admin uses their power to bus their way past this step the last few will work just fine.

#### Specific information for locating

Power storage unit

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by bloxgate** [comment]
Can confirm this is happening. I checked the code and as far as I can tell both he and I did all the steps correctly, something just goes odd when you try and cut the terminal.

**Comment by Flaksim** [comment]
This is still an issue, I just tested this on a buildable unit, same result as outlined above.

**Comment by Aroliacue** [comment]
Stale, closing
