### ISSUE TITLE
Unable to enter pelicans using the enter vehicle verb

### ISSUE THREAD

**Issue by nalarmg** [HaloSpaceStation/HaloSpaceStation13#519]
#### Description of issue
The enter vehicle verb does not work for pelicans.

#### Difference between expected and actual behavior
The enter vehicle verb should place the mob using the verb inside the pelican. It currently does not. No output is given either.

#### Steps to reproduce 
1. Stand next to a pelican
2. Use the "enter vehicle" verb
3. Observe results

#### Specific information for locating
D77-TC Pelican

#### Length of time in which bug has been known to occur
1-2 days

#### Client version, Server revision & Game ID
Server Revision: 4f69c3bc0838613c3299e4829da05fa1370e1614 - alpha

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by DoctorOctopusTheOctopi** [comment]
Fixed in #520 Thanks for the report!
