### ISSUE TITLE
UNSC Area Defines

### ISSUE THREAD

**Issue by Maxattacker** [HaloSpaceStation/HaloSpaceStation13#585]
#### Description of issue
UNSC area defines have been removed/overwritten, so nothing is able to be powered, specifically on deck 2

#### Length of time in which bug has been known to occur
since at least 5/19/2018

#### Client version, Server revision & Game ID
Server Revision: c322c70bda081c96272e8c4dc5fbeeb84fc313ed - alpha - 2018-05-19
Game ID: bUs-ayR4
Current map: UNSC Frigate

#### Issue bingo
![dreammaker_2018-05-19_21-02-44](https://user-images.githubusercontent.com/1341059/40275353-9f7ebfaa-5baa-11e8-834f-ee8b15973c25.png)
![dreammaker_2018-05-19_21-06-32](https://user-images.githubusercontent.com/1341059/40275354-a36b4dd6-5baa-11e8-9411-412dcd592d16.png)
![dreammaker_2018-05-19_21-08-41](https://user-images.githubusercontent.com/1341059/40275355-a60b338a-5baa-11e8-8450-51d3d13af85b.png)

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by bloxgate** [comment]
Are you sure you're including the file that defines them? I changing the gamemode can change whether those are included or not.

**Comment by Maxattacker** [comment]
okay yeah, I checked the file to include the frigate areas, but all the defines for deck 2 are not mapped in.

**Comment by bloxgate** [comment]
Do a git reset on the map just in case Dream Maker decided to save without them when the file wasn't included.

**Comment by BDpuffy420** [comment]
#584
