### ISSUE TITLE
Slots being taken by no-one on round start (FIRST CONTACT)

### ISSUE THREAD

**Issue by subdon** [HaloSpaceStation/HaloSpaceStation13#594]
#### Description of issue
On some instances of roles (ODST/Telecomms officer Confirmed at least) setting "ready" with high priority will assign you the slot but freeze on lobby screen as if "you are about to be spawned on your char role" but when reconecting will send you back to the lobby start with the role already being taken by NOBODY.

#### Difference between expected and actual behavior
Either:
A-Send you back to the lobby with the role still empty
or
B- Actually spawn you round start with the role choosed

#### Steps to reproduce 
1-ready up high on ODST/telecomms officer
2-Wait for round start
3-Get lobby image freezed but notice your character did not spawned
4-Reconnect
5-Back to lobby, but notice one of the slots was taken.

#### Client version, Server revision & Game ID
Last Test, still a persistent bug in the last versions, unknown exact IDs of affected by them.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once (happened to me at least once)
- [x] Issue could be reproduced by different players (half cross, heard in last test of the T-comms officer having trouble being returned to lobby and not being assigned)
- [ ] Issue could be reproduced in multiple rounds (Havent reproduced it since i know a way to avoid it)
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Flaksim** [comment]
This issue occures with all roles, and priority has nothing to do with it.

**Comment by Flaksim** [comment]
This issue also occures on Geminus, and is not gamemode related.

**Comment by Flaksim** [comment]
Its quite odd that such a major bug hasnt been dealt with in almost four months. This should be a priority before anything new gets added after the current sprint as its costing actual players, people who just leave after they cannot spawn in.

**Comment by caelaislinn** [comment]
I put in some potential fixes for this issue in #820

**Comment by caelaislinn** [comment]
Partially fixed. I'm going to try and fix the last part of the problem https://gyazo.com/7029bf2eef192fcdca57161efe523e36

**Comment by BDpuffy420** [comment]
Ready up has been fixed I do believe now
