### ISSUE TITLE
No way to bypass locks - (Covenant, First Contact) 

### ISSUE THREAD

**Issue by ghost** [HaloSpaceStation/HaloSpaceStation13#598]
The Covenant crew (Kig'Yar, Unggoy) don't have access to tools to force open doors (IE: A crowbar, as they can damage the doors until a crowbar can be used, but don't have a crowbar) which is rather necessary when raiding more restricted areas, damaged areas, low power areas, and so on and so forth.
_______________________________________________________________________________________________________________
___
I believe that a standalone tool for use by boarding parties (Not just the Covenant) should be made available to cut through doors and hull for the purposes of infiltration or rescue. For example, a saw (Or the plasma equivalent). If that's not possible or unnecessary, just a crowbar that the Covenant lack.
_________________________________________________________________________________________________________________
[Additional Suggestions by other people]:

Stormtrooper/1+1=: "Give Elites/Brutes the ability to rip open doors."

**Comment by Flaksim** [comment]
This is not an issue anymore, the covie ship has crowbars now.
