### ISSUE TITLE
Planetary void bug

### ISSUE THREAD

**Issue by T-rexsuper1** [HaloSpaceStation/HaloSpaceStation13#601]
#### Description of issue

Space tiles on planets

#### Difference between expected and actual behavior

Wata?

#### Steps to reproduce 

Just break some walls at icy planet, under them and under floor will be void, that sucks you inside, that sux.

#### Specific information for locating

I found it when ACCIDENTALY detonated all landmines at the cargo bay in the Deport.

#### Length of time in which bug has been known to occur

I just saw it.

#### Client version, Server revision & Game ID

IDK, must work in every game.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by DoctorOctopusTheOctopi** [comment]
Flaksim#9151 is handling this.

**Comment by Flaksim** [comment]
A coder will have to tackle this, I attempted a fix with input from XO and Octo, and it literally broke the game.

**Comment by caelaislinn** [comment]
This is a simple fix, but ironically the turf change code is complex so it needs to be handled by someone who knows the code well. 

To make sure this issue doesn't crop up again, we'll need to make sure all edge cases of turf destruction are covered. This issue obviously pegs explosions as one cause, but there could be others ie stuff like floor tiles or grass etc

**Comment by caelaislinn** [comment]
#621
