### ISSUE TITLE
Space Unggoy Suggestion

### ISSUE THREAD

**Issue by DexterDude** [HaloSpaceStation/HaloSpaceStation13#602]
#### How it will work: Basically making Unggoy space resistant as per lore, with the need of a face mask of course as their facial tissue can not withstand the pressure. Quoting;
 "Unggoy carapaces apparently can withstand the chilling cold and airless environment of EVA conditions, but they must employ sealed face masks in order to breathe, as well as presumably to protect their facial tissues. "

**Comment by Flaksim** [comment]
@X0-11  Will we do this? If so I can, it sounds like simply making their helmet a space helmet and their suit a spacesuit.
