### ISSUE TITLE
Add cryodorms to First Contact, Research facility (and possibly all ships).

### ISSUE THREAD

**Issue by subdon** [HaloSpaceStation/HaloSpaceStation13#603]
#### Description of issue
Where do we put the SSD?

#### Difference between expected and actual behavior
Expected behaviour: put SSD in cryo, slot open.
Actual Behaviour: Leave the body in a room hoping it will get better and get looted by anyone, including the feral corgis.

#### Steps to reproduce 
1- Wait for someone to SSD
2- Suffer Internally if he was a vital role

#### Specific information for locating

Mainly: Research Facility
Optionally: Ships, depot, comms outpoust.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by DoctorOctopusTheOctopi** [comment]
Flaksim#9151 is handling this.

**Comment by DoctorOctopusTheOctopi** [comment]
#606 handles cryodorms on the Research Exoplanet

**Comment by Flaksim** [comment]
I added cryodorms on listening post, research and fuel depot. After current round of merges I will add them to the corvette.
One question tho: In the code the despawn var is set to 9000. Is it milliseconds? Either way I'd halve it to a level that sets it at like a 7.5 minute despawn timer instead of 15.

**Comment by caelaislinn** [comment]
It should be standard procedure for all new maps to do this

**Comment by Flaksim** [comment]
This is finished in my current PR, all relevant planets and ships have cryodorms.
Can be closed.
