### ISSUE TITLE
reimplement cael-overmap comms

### ISSUE THREAD

**Issue by X0-11** [HaloSpaceStation/HaloSpaceStation13#607]
original functionality quoted below:
"my comms rewrite redirected all of the tcomms signals through overmap objects, passing them up then back down again
that way you could have signal spread across different areas depending on signal range
and other stuff like message decay for weak signals, and area based interference
ie a ship could block comms from another ship or planet nearby"
"it was a bit complex because i had it operate on several levels simultaneously but not duplicate internal signal processing
ie the minimum comms range of a signal was that entire overmap object ie all zlevels on a ship
whereas in default tcomms the minimum range is 1 zlevel
because in vanilla ss13 1 zlevel = an entire ship or space station or asteroid or planet etc
but if the signal had greater range than 0 (which was all the connected zlevels) then it went up to the parent object ie the ship or planet holder, then spread out to neighboring overmap tiles
the range value for signals was in overmap tiles
so it would just spread radially outward"

**Comment by caelaislinn** [comment]
#2374
