### ISSUE TITLE
Implement skirmishers

### ISSUE THREAD

**Issue by X0-11** [HaloSpaceStation/HaloSpaceStation13#609]
Sprites are present, just require species definition and stats/ species abilities to be figured out.

**Comment by ghost** [comment]
Same health as a human (As I understand it, the Ruutians have something like 75%)

Faster than Ruutians  (Personally think they should be slower but still faster than humans so they're not better in ALL ways, but there's talk of giving Skirmishers a heavier whitelist or something.)

Murmillos have better shields than Ruutians (Two smaller shields, one on each forearm, so perhaps the ability to have shields up while leaving both hands free?)

Higher pain resistance

**Comment by Nightspark43** [comment]
I think they should have normal bones and less brutemod, with it being normal, TBCH.

**Comment by DexterDude** [comment]
I thought T'vaoan were faster than the Ruutian

**Comment by Nightspark43** [comment]
Yeah, but making them a little slower would be good for balance, else, who would actually play as a Ruutian?

**Comment by X0-11** [comment]
those who aren't whitelisted

**Comment by caelaislinn** [comment]
We can balance races with different stats by restricting slots or respawn times.
