### ISSUE TITLE
Covenant Pulse Laser is underpowered and Archer Missile Pod is overpowered

### ISSUE THREAD

**Issue by Nightspark43** [HaloSpaceStation/HaloSpaceStation13#613]
#### Description of issue
Two rounds in a row, ship-to-ship combat with the Pulse Laser vs Archer Missile, several shots of the Pulse Laser did very little damage, only puncturing holes in the enemy ship hulls, meanwhile, the missile pods given to the UNSC and Insurrection have completely killed the entire Covenant Crew with one or two volleys, was told to report the issue if it happened twice.

#### Difference between expected and actual behavior
Covenant Pulse Lasers should deal more damage, capable of damaging or disabling enemy ships for boarding or escape, instead, the laser was only able to poke holes through the hull with a large amount of shots.
And Archer Missiles have the ability to completely destroy the Covenant Vessel in one to two volleys, making ship-to-ship combat a non-option for them.

#### Steps to reproduce 
Play any round of First Contact, shoot the Covenant Laser ten times, jump to the UNSC vessel, shoot the Archer Missiles once.

#### Length of time in which bug has been known to occur
Since the recent update to add both of these weapons.

#### Client version, Server revision & Game ID
Server Revision: 97e82b59e145388e73c729f03ed94d6d64fd6c8e - alpha - 2018-05-28
Game ID: bUA-aumV

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by bloxgate** [comment]
The covies really, really need shield gens mapped in. As stated in an old Halo Wars demo, Covenant stuff is basically a glass house once their shields are gone.

**Comment by Nightspark43** [comment]
Update, in straight combat, the Pulse Laser outguns the Deck Gun the Corvette has, so it's got damage potential, but it simply can't hold a candle to the explosion of the Missile.

**Comment by X0-11** [comment]
Whilst the archer missile pods may appear overpowered, the issue stems from the low-explosion resistance of covenant walls.
This is being fixed as part of PR #615
