### ISSUE TITLE
Eating Verbs Suggestion

### ISSUE THREAD

**Issue by ghost** [HaloSpaceStation/HaloSpaceStation13#616]
Due to bay wrestling, setting the variable on player mobs to allow them to eat people doesn't actually allow them to do it. Because our lives aren't complete without a Brute eating people's legs while they're still alive, here are the following suggestions for eating mechanics and text

Make a verb in, let's say the Abilities tab, for races that are able to eat (Not humans, no cannibal ODST.)
The following each take, let's say, 0.5 minutes to do, allowing them to escape.

Kig'Yar: Start text "X begins stripping the flesh from Y's bones!"
             End text "X mauls Y with their beak, ripping and tearing at their flesh!" 
             Several uses will remove the body and leave remains/bones.

Jiralhanae: Start text "X begins yanking at Y's -inserttargetedlimb-, trying to tear it off!"
                  End text "X rips off Y's -inserttargetedlimb- and begins chewing on it!"

Unggoy: Start text "X eyes Y hungrily and reaches for their -insertargettedlimb-..."
               End text "X rips off Y's -inserttargettedlimb- and puts it into their canister. There's a  brief blending noise, and X begins chewing."

Using the eating verbs will fill nutrition by half, or something like that.

**Comment by caelaislinn** [comment]
We've discussed it as staff and decided against it.

**Comment by BDpuffy420** [comment]
reopen to for re-discussion

**Comment by BDpuffy420** [comment]
re-open for discussion

**Comment by SpiderPsycho** [comment]
You can just have it so Brutes / Kig'Yar have butcher verbs. Then they can butcher dead bodies and eat them. I don't think Jiralhanae or Kig'Yar ate people alive. And if they did the victim probably died pretty damn quickly. Besides I don't think anyone really wants eating people alive. Just eating people is fine. Good for Kig'Yar morale, keeps the grunts safe.

**Comment by PantasTheDank** [comment]
Agreed.
Make sure that human meat is clearly labeled as Human Meat,and food that has human meat labels itself as such.

**Comment by caelaislinn** [comment]
Could potentially be done as a side project, but not a core feature
