### ISSUE TITLE
Pulling items up Ladders suggestion

### ISSUE THREAD

**Issue by Nightspark43** [HaloSpaceStation/HaloSpaceStation13#620]
So, around the map there are a lot of places where you go down a ladder and find a bunch of items down there, the cave on the desert, the supply depot on ice, the desert hanger, but in none of these examples is there a way for someone without a pelican to actually get any of the items without admin verbs, leaving the Covenant unable to raid the supply depot in any meaningful capacity, same with Insurrectionists, as well as leaving an artifact stuck in a cave because you can't pull them item up the ladder.

**Comment by X0-11** [comment]
Isn't the main downside of ladders the fact you can't pull things up/down them? Elevators are used for cargo-movement.

**Comment by Nightspark43** [comment]
Then, what about the artifact in the cave near the research facility, not exactly easy to install an elevator just to get that out of there.

**Comment by caelaislinn** [comment]
I agree with XO. This should be fixed by mapping, not letting players pull crates up ladders.

**Comment by Flaksim** [comment]
I concur, but stairs are no solution for this, and elevators need to get looked at before we start mapping them into other places. It also wouldnt be a solution for the "dig site".

**Comment by SpiderPsycho** [comment]
Maybe some sort of cargo tug / elevator thing which can fit one crate / cannister / item, then is sent up. Sort of like those food lift things in larger restaurants. I unno.

**Comment by X0-11** [comment]
Issue has been rectified by adding stairs instead of ladders.
