### ISSUE TITLE
Navigation consoles don't seem to work properly

### ISSUE THREAD

**Issue by Nick123q23** [HaloSpaceStation/HaloSpaceStation13#622]
#### Description of issue

Navigation consoles for spacecraft don't seem to work

#### Difference between expected and actual behavior

You press the toggle overmap mode, engage/disengage, but when engaged the overmap doesn't come up.

#### Steps to reproduce 
Press the button on any navigation console. Specifically, I was using the missionary ship's navigation console.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Maxattacker** [comment]
I think this issue can be closed. I've never had issues with nav consoles
