### ISSUE TITLE
Energy beams bypass the shield gauntlet of the kig-yars

### ISSUE THREAD

**Issue by Delnth** [HaloSpaceStation/HaloSpaceStation13#623]
#### Description of issue

I've witnessed no less than 2 stun beams bypassing the shield gauntlet of the kig-yar, when activated. Both with successfull. No message stating that it failed to block the beam or anything.

#### Difference between expected and actual behavior

It should damage the shield instead of going through it.

#### Steps to reproduce 

Stand in front of someone holding an energy based weapon with the shield gauntlet active. The stun beam should definitly bypass the shield, not sure for the laser beam.

#### Specific information for locating

Energy gun, kig-yar shield gauntlet, stun beam.

#### Length of time in which bug has been known to occur

A few minutes after this issue will be posted.

#### Client version, Server revision & Game ID
Latest (always) Stable
61161e8c15788da24d6fdf4c826673ec5cfff7c0 - alpha - 2018-05-28
I didn't get the Game ID, sadly. But the round restarted around 10-20 minutes ago, starting from the time this issue was posted.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Flaksim** [comment]
There shouldnt be energy weapons available aside from covenant weapons, which is why this eventuality wasnt accounted for. will look into this.

**Comment by DoctorOctopusTheOctopi** [comment]
Xenoarcheology/artifacts can spawn in an alien gun. It is most likely one of those.

**Comment by caelaislinn** [comment]
Covenant had beam weapons in lore, and we have carbine + beam rifle in game. I'm going to tag this as a bug for now

**Comment by ghost** [comment]
Most likely an energy gun ported over from standard SS13. I've seen them reliably spawn on civilian vessel captain's quarters.

**Comment by Flaksim** [comment]
Energy guns spawning has been resolved.
