### ISSUE TITLE
First Contact Overmap request ( New Planet with abandoned Colony on it)

### ISSUE THREAD

**Issue by Liam-Gallagher** [HaloSpaceStation/HaloSpaceStation13#626]
Currently, the Innies have no real place to call home; so as a solution, I recommend we add a planet with an abandoned facility for Innies to spawn in and use as their own kind of depot. This will not only provide them a place to hide and recuperate from any attacks and what-not, but it will add a place for the UNSC to raid and offer new RP opportunities. You can even add stuff for the innies to produce contraband and stuff (Drugs and firearms) to sell to the colony, so the civies get some love as well with that added RP opportunity.

**Comment by DoctorOctopusTheOctopi** [comment]
I may handle this after my humanitarian aid planet.

**Comment by BDpuffy420** [comment]
Or just give them the innie base Deso made

**Comment by Liam-Gallagher** [comment]
I wanted something fresh, but that's better than nothing.

**Comment by caelaislinn** [comment]
Faction bases getting raided early in the round is more of a problem with "hidden" bases being easy to find from early on. We'll need to add more mechanics for hiding away bases. In the meantime more map contributions are welcome.

**Comment by BDpuffy420** [comment]
This has been taken of due to new URF base in FC/KS7 colony
