### ISSUE TITLE
Remove Landmine Frisbee

### ISSUE THREAD

**Issue by Nightspark43** [HaloSpaceStation/HaloSpaceStation13#631]
A very common, and very annoying, habit of players, is to activate and then throw landmines at enemies like they were grenades, this upsets players when they are used that way.

So, I am suggesting, make the landmines like tanktraps, you use it in hand, it gives you a use timer of setting it up, when the timer is finished, you plant the landmine on the ground and you have five seconds to move away, also, reduce the detection range, there are complaints about it being farther than it should be, but that I do not know about.

**Comment by Liam-Gallagher** [comment]
Or make it so it can't be thrown very far, no further than its detection range.

**Comment by CoolfoolFTW** [comment]
Detection range is nine tiles I heard so that shouldn't be made a thing. Just remove throwing them.

**Comment by Liam-Gallagher** [comment]
Or take away the ridiculous nine tile detection range. A landmines effectiveness would drop off way to much at that range anyway, so it is extremely unrealistic.

**Comment by caelaislinn** [comment]
#1011
