### ISSUE TITLE
Ship weapon consoles are invincible

### ISSUE THREAD

**Issue by Nightspark43** [HaloSpaceStation/HaloSpaceStation13#637]
#### Description of issue
The only way to get rid of gun consoles on ships is to use explosions or admin delete them.

#### Difference between expected and actual behavior
Weapon consoles should be able to be disabled via tools, gunshots, and weapons fire from non-explosive ship weapons

#### Steps to reproduce 
Join any First Contact round in the Covenant Ship, light up the Thorin for a long time, jump over, and realize that not a single shot had even dented ANY of the gun consoles aboard.

#### Specific information for locating

/obj/machinery/overmap_weapon_console/deck_gun_control
--

#### Length of time in which bug has been known to occur
Since ship weapons became a thing.

#### Client version, Server revision & Game ID
Client Version: 512
Server Revision: 72ab654d8520ea1ddb90948673b46fa1752213bd - alpha - 2018-06-03
Game ID: bUG-dwaT
Current map: Outer System #1445113

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Flaksim** [comment]
This is known, @X0-11  coded them, and a suggestion was to make them lose power and become unusable in that event.

**Comment by X0-11** [comment]
Invincibility is intended, however, overmap weapon consoles should do a power-check when they fire.
Refer to #1105
