### ISSUE TITLE
Game broke during testing

### ISSUE THREAD

**Issue by GerdzC** [HaloSpaceStation/HaloSpaceStation13#645]
#### Description of issue
lost the ability to interact with objects to a certain extent. I could right click to partially interact with objects but the left click wouldn't interact with anything at all.

#### Difference between expected and actual behavior
um... I should be able to left click and pick things up, left click to change the direction of my character, left click to use ladders and such. the actual behavior was that I was unable to do anything besides walk around.

#### Steps to reproduce 
I guess you could set off the ONI base nuke and try to survive it. see if you fall from the surface level down into the underground level through an invisible hole in the ground like I did.

if that dosnt do it, I also had my camera locked onto the pelican after I took it down to the blown up UEG Hanger from the frigate and I had to relog to fix that, I don't know if that broke anything.

#### Length of time in which bug has been known to occur

as far as I know im the first one to break my game like this

#### Client version, Server revision & Game ID

the game id was bUI-al9S
it happened around 10:47p.m. Central standard time U.S.
on the date 6/4/2018
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Flaksim** [comment]
I havent run into this issue as described above yet, is this still relevant given the changes between when the tester had this issue and today? @caelaislinn I reproduced his steps above three times each and did not encounter this issue.

**Comment by caelaislinn** [comment]
Not reproducible and an old version of the code
