### ISSUE TITLE
Encumberment is way too strong

### ISSUE THREAD

**Issue by Axemeaquestion** [HaloSpaceStation/HaloSpaceStation13#646]
#### Description of issue

Currently, carrying what would be a normal combat loadout for real world soldiers slows you down to a crawl. Wearing just an empty backpack slows you to a tile a second, and makes little sense for balance. There's no combat advantage to carrying more than one rifle, and its makes handling logistics incredibly hard because anyone carrying ammo or supplies is slowed the a crawl. The weight penatly should be reworked to a more realsitic and playable value.

#### Steps to reproduce 

Carry an empty backpack, armor, and a few mags and be slowed to a crawl.

#### Length of time in which bug has been known to occur

I'm not sure how long its been like this, but it seems to be getting worse recently.

#### Client version, Server revision & Game ID

e5e3fb11a083b271dc77f0801fc4bd249838824e - alpha - 2018-06-05

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this]

**Comment by Flaksim** [comment]
The way its coded it permits 8 tiny items, 4 small items, 2 normal items or a combination of those that doesnt exceed 2 normal before it starts to give you a gradual slowdown.

I personally eun around every round with 4 small items in py pack and easily keep up with everyone else.

People dont understand the system and overload. This change was done for gameplay.

**Comment by Axemeaquestion** [comment]
That's too few, and it ends up hindering gameplay rather than enhancing it. It unrealistically caps ammo and weapon storage, "Today the average US soldier carries at least 60 pounds of gear, with an extended patrol often doubling that weight. ". This system is far too limiting, and making it more lenient and realistic wouldn't hurt balance: carrying more ammo isn't overpowered or ridiculous. If you want to cap carrying capacity of items, make the initial supply limited, and you won't have to add limits that affect every aspect of fighting from logistics to combat.

**Comment by Flaksim** [comment]
The supply IS limited. And what happened was that people scroynged the good stuff for themselves and left others with nothing.

**Comment by Axemeaquestion** [comment]
It would be better to make rules against that vs. crippling being able to carry anything whatsoever. The current system hurts all aspects of logistics and combat, and hurts more overall than people hogging good weapons. For example, if I wanted to move medicine to a forward base, I couldn't simply put it in a backpack and move it to the FOB, I would have to painstakingly carry it encumbered speeds. Another example is moving ammo, metal, and fortifications to anywhere it would be useful. None of these are limited items, and their inclusion makes gameplay more varied and interesting. However, the encumbrance system cripples this, and makes it far harder to set up a supply chain. It needs to be replaced with a better system or ruleset that specifically stops hoarding. This solution is far to broad and makes gameplay overall worse by being too broad of a solution.

**Comment by X0-11** [comment]
Enforcing limits like that adds unneeded strain on the moderators and admins. Backpacks weren't even going to be added to regular appearance, so the current system was introduced. Backpacks could be removed entirely if that's what you'd rather. Carry very little unless the situation calls for it.

**Comment by Axemeaquestion** [comment]
Carrying very little makes little sense roleplay wise, and often makes it much harder to handle situations. The encumberment system is throwing the baby out with the bath water: in getting rid of people hoarding, you also get rid of supply lines that allow for interesting situations and protracted dynamic firefights. The limits are so strict that it makes it difficult for either side to actually prepare logistically, and ends up making combat artificially short and overall worse. The idea that backpacks are overpowered makes no sense when you consider that for combat, you only need 1 weapon to be effective. However, all the logistics and supply, i.e. fortifications and meds, are crippled by this and it is near impossible to set up effective FOBs without spending ridiculous amounts of time and energy lugging around lots of items at a snail's pace or carrying a small amount over and over again. It's hostile design that sidesteps the issue by harming gameplay rather than actually fixing the underlying issues with the playerbase. By adding the idea to ROE, we would be able to easily make it clear the behavior was not okay, and as we can see with most reasonable points on the ROE, they will be followed if they are enforced. The current system just unfairly hurts people who prefer to meticulously build up a stronghold rather than run and gun.

**Comment by X0-11** [comment]
It's good to see the backpack nerf is having the intended effect then. Making combat short and lethal is the point, rather than people running away, pulling out a bunch of god-tier healing chems and getting back into the fight. Damage sustained is healed after the fight ends, or not at all.
If you're attempting to create a stronghold, then you're going against that quick-combat style.
Firefights still have the ability to dynamically evolve, but only if the human resource isn't immediately wasted.

**Comment by caelaislinn** [comment]
We're not going for realism. It's nice to have hard military scifi which is why we love the setting, but we also need to make concessions to game design and balancing.
