### ISSUE TITLE
[IDEA] Randomized pieces of clothing for the URF

### ISSUE THREAD

**Issue by hatknight** [HaloSpaceStation/HaloSpaceStation13#647]
This isn't an issue or anything and I was told to put it here so here it is, the URF base/ship should have randomized clothing like berets, civilian clothing, armor, ect randomly spawn to give it more of a "rebel" theme.  The ship already has randomized weaponry so I don't think adding clothing and whatnot would be too hard. If this doesn't belong here then excuse me for being a dummy.  
EDIT:  Another idea for the URF is stuff like crayons that can "mark" UNSC armor, that way they don't get fired upon by friendlys

**Comment by caelaislinn** [comment]
This should be done for loadouts as well. It's quite an easy change

**Comment by caelaislinn** [comment]
Innies were given colonist outfits in #1615
