### ISSUE TITLE
Add loudspeaker system for multiz ships

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#666]
As title

**Comment by Flaksim** [comment]
An intercomm system has been implemented on the UNSC Bertels. For other multi Z vessels in the same gamemode a different subtype of intercomm would have to be created. (As it works at the moment)

**Comment by Nanu308** [comment]
CM Kind of announcement for Both the LB and the Covvie main ship done from the helm would be cool to get

**Comment by Aroliacue** [comment]
Stale, closing
