### ISSUE TITLE
Ghosts + Handcuffed people can use mongooses

### ISSUE THREAD

**Issue by ghost** [HaloSpaceStation/HaloSpaceStation13#674]
#### Description of issue
Ghosts and handcuffed people can drive mongooses

#### Difference between expected and actual behavior
Ghosts shouldn't be able to interact with anything. Handcuffed people should be mostly incapacitated.

#### Steps to reproduce 
Ghosts: Ride the mongoose as a passenger, change seats to driver

Handcuffed: Unknown. Probably able to ride a mongoose by hopping on it normally, but the only case I know of is someone changing seats to driver.

#### Issue bingo
- [x] Issue could be reproduced at least once
- [] Issue could be reproduced by different players (None have tried)
- [] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this]

**Comment by BDpuffy420** [comment]
#745
