### ISSUE TITLE
CCV Slow but Steady has no gravity

### ISSUE THREAD

**Issue by Axemeaquestion** [HaloSpaceStation/HaloSpaceStation13#675]
#### Description of issue
CCV Slow but Steady has no gravity

#### Difference between expected and actual behavior
The ship should have gravity but doesn't.

#### Steps to reproduce 
Go on the CCV slow but steady

#### Client version, Server revision & Game ID
8383791d48d2f2c32a07c43a893c89ac6722036c - alpha - 2018-06-13

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ x] Issue happened in a recent (less than 7 days ago) round
- [x ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Flaksim** [comment]
This is not an issue, its how it was mapped.
