### ISSUE TITLE
Changing Gamemodes Changes Available Characters

### ISSUE THREAD

**Issue by bloxgate** [HaloSpaceStation/HaloSpaceStation13#676]
#### Description of issue
Apparently every time we change the gamemode on the server the list of characters available to players changes.

#### Difference between expected and actual behavior
You have the same characters available in the same slots without regard to gamemode. Only thing that should force change you from the previous character is playing as a race that isn't allowed in the mode, or something similar.

#### Steps to reproduce 
Save character into a slot. Recompile onto a new gamemode, check slots.

#### Specific information for locating

~~Unknown~~ Update: Affected players have a preferences_bad_000.{sav,txt} file located in their player save around when they last lost a char slot.

#### Length of time in which bug has been known to occur

People on Discord, including the moderation staff claim that this has been happening for several months.

#### Client version, Server revision & Game ID

8383791d48d2f2c32a07c43a893c89ac6722036c

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Flaksim** [comment]
edt: silly me, you mean characters not jobs: yup, always been that way.

**Comment by Flaksim** [comment]
Russle confirmed that this is intended behaviour. @bloxgate  Given that, do you wish to keep this open?

**Comment by BDpuffy420** [comment]
intended
