### ISSUE TITLE
Covenant engines

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#688]
- [x] Repulsor engines (32x32) 
- [x] Slipspace generator (96x96)

**Comment by Kmc2000** [comment]
is this taken

**Comment by caelaislinn** [comment]
These are still open.

**Comment by SpiderPsycho** [comment]
Cael, does the engine / slipspace borer have a dmi I can just use for conveniences sake? If so, just send them over to me on Discord. I should be able to get the engine done relatively quickly. The borer will take longer.

**Comment by caelaislinn** [comment]
The repulsor engine is just a 32x32 resprite of the existing thermal engine but you have freedom to muck about with it or even change the dimensions (so long as they are multiples of 32). 

We have a 64x64 sprite for a human slipspace generator located at code\modules\icons\machinery\reactor.dmi which I'm pretty happy with. It's just been unused

**Comment by SpiderPsycho** [comment]
But the Covenant Slip-space borer is going to be 96x96 right? I think I have some sort of size template for it. Its not going to have to face anywhere right?

**Comment by caelaislinn** [comment]
It can just be a stand alone machine without directional states. Either 64x64 or 96x96 will be fine

**Comment by SpiderPsycho** [comment]
![covenantengines](https://user-images.githubusercontent.com/33624371/46182965-35374b80-c301-11e8-9e13-781ac43af8ec.png)

Here's the engines. I can't upload dmi files but it has the right stuff to be opened in dream maker or whatever where you can save a copy as a dmi.

**Comment by caelaislinn** [comment]
Those look fantastic. Any chance you can do on/off states?

**Comment by SpiderPsycho** [comment]
Here's the completed one with on and off states.  I know Kozi did animated ones but they were in a different colour and he isn't on or something. Use these for the time being I suppose
![covenantenginespng](https://user-images.githubusercontent.com/33624371/46455496-e8aaaf00-c7dd-11e8-838c-838c7dc393fa.png)

**Comment by caelaislinn** [comment]
Slipspace engines   #904
