### ISSUE TITLE
Covenant doodads

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#689]
Priority:
- [ ] (BOUNTY) Gravity lift sparkle turf overlay
- [ ] (BOUNTY) Giant starsystem navigation hologram 128x128
- [ ] (BOUNTY) Pillar lift with icon states for in floor and extended to floor above
- [x] Weapon recharging rack
- [ ] Portable gas canister
- [x] Large fixed gas tank
- [x] Energy barrier for hangar bays
- [ ] Large planet navigation hologram 64x64
- [ ] Small starsystem navigation console 32x32
- [x] Double door
- [x] Triple door
- [x] Quadruple (4 tile) vehicle blast door
- [x] (BOUNTY) 1x1 circular gravlift pad (32x32)
- [x] 2x2 circular gravlift pad (64x64)
- [x] (BOUNTY) 3x3 circular gravlift pad (96x96)
- [x] 4x4 circular gravlift pad (128x128)
- [x] Ramps (to replace stairs)
- [x] Button for blast doors

Others:
- [x] Gas connector nozzle
- [x] Wall circuitry overlay
- [ ] Ornamental plant bed
- [ ] Creepy dead alien tree (64x64)
- [x] Beds, tables, chairs
- [x] Grunt food nipple
- [x] Upstanding cargo crate
- [x] Portable comms console
- [x] Portable comms antenna

**Comment by TheBimmer231** [comment]
leave the doors and atmos equipment to me.

**Comment by TheBimmer231** [comment]
airlocks:
https://drive.google.com/file/d/1fPaJrraO8vCcM9wBnQLwRA40vWHTAXLh/view?usp=sharing
https://drive.google.com/file/d/1zpdPdRMqN98h4yGS7UQrv9TQjcIhzud9/view?usp=sharing
https://drive.google.com/file/d/1a3Vyh0Ks-rZndpyM4LcJY3Eeq2hPJR1g/view?usp=sharing

**Comment by bloxgate** [comment]
All those spites require us to request access to get.

**Comment by TheBimmer231** [comment]
@bloxgate Sorry for that, i think it's fixed now.

**Comment by Delnth** [comment]
Not sure if you guys like/allow links as reference. Just in case, I put them in for the sake of having a picture of what you'd have to sprite, should you so desire.

Covenant comm node: https://www.halopedia.org/Covenant_comm_node
Plasma storage unit: https://www.halopedia.org/Plasma_storage_unit
Covenant stool: https://www.halopedia.org/Covenant_camping_stool
Covenant storage device: https://www.halopedia.org/Covenant_storage_device
Covenant supply case: https://www.halopedia.org/Covenant_supply_case
Kindler: https://www.halopedia.org/Kindler

**Comment by caelaislinn** [comment]
Still needing some work on these

**Comment by BDpuffy420** [comment]
bump

**Comment by SpiderPsycho** [comment]
I can make a button for the blast door thing, though I think we need some indicator signs for Covies as well. the OP Redflag map is a maze without signs. Maybe they can be coded to be understood / visible only to Covies but not to humans?

**Comment by SpiderPsycho** [comment]
https://drive.google.com/open?id=1yWs7LiytxVcp11excVe3tXVDyPjuOTCL button yes?

**Comment by caelaislinn** [comment]
Tagging some of these for a bounty so they get done by the end of the Covenant arc (January 2019)

**Comment by Aroliacue** [comment]
Stale, closing
