### ISSUE TITLE
Covenant turfs

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#690]
- [ ] Drone hive floor
- [ ] Drone hive wall
- [x] Alternative colour palette variants for walls and floors

**Comment by TheBimmer231** [comment]
I seen't it, i took it.

**Comment by TheBimmer231** [comment]
Will be done today if not tomorrow!

**Comment by TheBimmer231** [comment]
It's mostly done, though no color variants, will that be a problem?

**Comment by caelaislinn** [comment]
Drone hive turfs? Yeah that's the main thing. Having an expanded palette for the ships and stations would be nice too

**Comment by BDpuffy420** [comment]
bump

**Comment by caelaislinn** [comment]
Tagging this for a bounty so it gets done by the end of the Covenant arc (January 2019)

**Comment by TheBimmer231** [comment]
[https://cdn.discordapp.com/attachments/454667989128708106/516284297141813259/Covvie_newwalls.dmi](url)
Here it is, turfs should work like carpet code.

doing the rest soon
