### ISSUE TITLE
Engineer race

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#691]
- Can not wear clothing, armour or any other gear. 
- Can carry a single item
- Cute tentacle wave idle animation
- [x] Done

**Comment by Liam-Gallagher** [comment]
Osama here, dibs on the sprite job.

**Comment by TheBimmer231** [comment]
Task totally nicked from Osama, ya boy got it.

**Comment by TheBimmer231** [comment]
https://drive.google.com/open?id=1a1tuYsVyRT41nGmCXxatjKjaZNU7dPjm there we go

**Comment by TheBimmer231** [comment]
@caelaislinn cross it out

**Comment by caelaislinn** [comment]
I'll close it when it gets merged
