### ISSUE TITLE
Drone race

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#692]
- No clothing or armour. Can carry a tool belt. 
- Only small weapons (needlers, plasma pistols, tools)
- An animation for being in flight

**Comment by TheBimmer231** [comment]
Ya boy got this, any specifics you would like the sprite to have? @caelaislinn

**Comment by caelaislinn** [comment]
Just what's written there. We'll probably need a customer overlay for a tool belt but TBH we could easily make it so the toolbelt cant be removed to simplify the code. I think I can handle the weapon overlays for needlers, plasma pistols and tools in the code. 

So it just needs 32x32 directional sprites + a directional flight animation

**Comment by TheBimmer231** [comment]
https://drive.google.com/open?id=1XwSFcTjRq5ieZf89tSi0sfuKdPJh7IGW
Here is the DMI, all done with the animation.

**Comment by BDpuffy420** [comment]
Sprite done
