### ISSUE TITLE
Ice Depot bottom level is missing/gone

### ISSUE THREAD

**Issue by AlphanBlitzen** [HaloSpaceStation/HaloSpaceStation13#697]
#### Description of issue
KS7 Ice Depot for Marines the second floor/Hanger docking area is not there.

#### Steps to reproduce 
Re-put the second floor back.  Mappers

#### Specific information for locating

KS7 Ice planet.

#### Length of time in which bug has been known to occur

I've seen it today at June 20 time 10:06 pm EST

#### Client version, Server revision & Game ID

Client Version: 511
Server Revision: cbea8f7d104985cc9e3d38dce881f426b510ed01 - alpha - 2018-06-20
Game ID: bUY-aaC9
Current map: UNSC Frigate

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [x ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Flaksim** [comment]
Yes, I have noticed this issue, I will attempt to fix it, the method by which Z levels are linked needs to be looked at however, its unreliable.

**Comment by Flaksim** [comment]
Unable to fix this issue, the map is set up correctly, its just not doing what its supposed to do.

**Comment by caelaislinn** [comment]
Yeah it's a code problem. We're working on it

**Comment by Flaksim** [comment]
This is resolved in PR: #703

**Comment by AlphanBlitzen** [comment]
Thank you, and I did not expect it to give me email messages for this report.....How do I disable it so it does not send me emails.  

I figured it out.
