### ISSUE TITLE
The alert button brakes all the lights

### ISSUE THREAD

**Issue by erty80s** [HaloSpaceStation/HaloSpaceStation13#711]
#### Description of issue
When you spam the alert button inside the UNSC Thorin it brakes all the lights.

#### Difference between expected and actual behavior
It shouldn't brake all the lights

#### Steps to reproduce 
Go to the bridge and keep pressing the alert button for around 10 seconds and lights should randomly start breaking

#### Specific information for locating

It's the button on the UNSC Thorin bridge

#### Length of time in which bug has been known to occur

Around 4  days as of this post

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x ] Issue could be reproduced at least once
- [ x] Issue could be reproduced by different players
- [x ] Issue could be reproduced in multiple rounds
- [ x] Issue happened in a recent (less than 7 days ago) round
- [x ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by X0-11** [comment]
not a bug, it's part of light-code when turned on/off quickly.
