### ISSUE TITLE
Requesting coder assistance to finish up Armourspecial coding and Helmet visor switching.

### ISSUE THREAD

**Issue by Flaksim** [HaloSpaceStation/HaloSpaceStation13#724]
#### Description of issue
I got the new icon states for the ODST helmets done, but I'm struggling to give the helmets an option to switch between "Odst Helmet" and "Odst Helmet Transparent" icon states.

Got an armourspecial made that gives the armor an internal oxygen tank, this works but internals switch off again immediately, couldnt get a custom internals check for it working in life.dm.

#### Difference between expected and actual behavior
I just suck at coding and request another dev take a look at this, I think it'd only take a couple of minutes for a person who knows what they're doing to finish it up.

#### Steps to reproduce 
none, this is a feature request.

#### Specific information for locating

odst.dm
life.dm
armourspecials.dm

#### Length of time in which bug has been known to occur
no bug.

#### Client version, Server revision & Game ID
current alpha.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Flaksim** [comment]
VISR toggle for transparency has been added.

**Comment by caelaislinn** [comment]
I've setup armour specials to correctly spawn and enable breath tanks where appropriate, but haven't touched VISRs
