### ISSUE TITLE
The headset and the CH252

### ISSUE THREAD

**Issue by Max-023** [HaloSpaceStation/HaloSpaceStation13#739]
#### Description of issue
The "Radio Headset" item when equipped shows over the "CH252" and "CH252-V". The sprite is clearly visible in the same spot it hangs when no hat or helmet is equipped. It doesn't show when your sprite looks right or left.

#### Difference between expected and actual behavior
The helmet should cover it, like the others, as the helmet already covers the ears of the wearer.

#### Steps to reproduce 
Just wear a CH252 or CH252-V while also wearing the radio headset.

#### Specific information for locating

 That's a radio headset. It is a small item.
An updated, modular intercom that fits over the head. Takes encryption keys.
The radio headset can not be modified or attached!
The following channels are available:
:s - SHIPCOM, :e - EBAND

 That's CH252-V Helmet. It is a normal-sized item.
An ONI variant of the standard CH252 Helmet. Has an inbuilt VISOR for eye protection.

 That's CH252 Helmet. It is a normal-sized item.
An ONI variant of the standard CH252 Helmet

 That's CH252 Helmet. It is a normal-sized item.
The standard issue combat helmet worn by the members of the UNSC Marine Corps, UNSC Army, and UNSC Air Force.

That's CH252-V Helmet. It is a normal-sized item.
The standard issue combat helmet worn by the members of the UNSC Marine Corps, UNSC Army, and UNSC Air Force. Has an inbuilt VISOR for eye protection.

#### Length of time in which bug has been known to occur

I am not sure how long it has been occuring for.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: b0fda2f4e9bf4f6dbfaa0c20d84d36e0a234b0d2 - alpha - 2018-08-12
Game ID: bVP-cHwX

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by bloxgate** [comment]
For whoever takes this issue: my guess is we're missing a HIDE_EARS flag, or something equivalent.

**Comment by X0-11** [comment]
marine helmets have HIDE_EARS, this should be fixed.
