### ISSUE TITLE
The Marine CH252-V

### ISSUE THREAD

**Issue by Max-023** [HaloSpaceStation/HaloSpaceStation13#740]
#### Description of issue
The CH-252-V for the UNSC (not the ONI model) appears at the top edge of the slot you hold it in, might higher than the center point of the object. This can allow for you to clip the helmet into walls on tables set next to them, completely concealing them and not allowing for recovery. It's not so much an issue as it is QOL, considering how small the box is to select the thing.

#### Difference between expected and actual behavior
 All other helmets are centered, in the hand slots, in the head slot, on the tables, and on the ground. The CH252 for the UNSC and the CH252/CH252-V all are centered.

#### Steps to reproduce 
Just hold it, wear it or set it down.

#### Specific information for locating

 That's CH252-V Helmet. It is a normal-sized item.
The standard issue combat helmet worn by the members of the UNSC Marine Corps, UNSC Army, and UNSC Air Force. Has an inbuilt VISOR for eye protection.

#### Length of time in which bug has been known to occur

This has been occurring before I arrived.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: b0fda2f4e9bf4f6dbfaa0c20d84d36e0a234b0d2 - alpha - 2018-08-12
Game ID: bVP-cHwX

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by caelaislinn** [comment]
This was fixed with a marine resprite months ago... not sure which PR
