### ISSUE TITLE
Make eswords self destruct when dropped

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#746]
There have been issues with Covenant players picking up eswords from dead elites. Normally I'd suggest this be an admin and RP issue but eswords also had a failsafe to disintegrate when their bearer dies. 

Might need discussion.

**Comment by Delnth** [comment]
Never seen an energy sword disintegrate when an Elite was killed in the halo series. This sounds like a little too much to just delete something from existence because its owner died. Perhaps restrict their use to spartans/elites, as in, species restricted.

**Comment by caelaislinn** [comment]
It happened in Halo 1 and its mentioned a couple of times in the novels

**Comment by ghost** [comment]
Issue with this is that an Elite can be knocked down by, for example, an explosion, and then they've lost their sword. 

If it can be made so that it only disintegrates when the Elite is actually dead or ghosted, I support this idea.
