### ISSUE TITLE
Corgi simple_animals have no held icon state

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#756]
This probably extends to other simple_animal types as well. It borks up the entire carrier mob state

**Comment by X0-11** [comment]
Confirmed for simple_animal types in general, a drone-huragok was picked up by a player and it caused the sprite to bug out

**Comment by Stingray540** [comment]
Corgis now have held sprites. If we have other specific held issues with simple_animals we can make new issues.
