### ISSUE TITLE
[Suggestion] Covenant Energy Gauntlet

### ISSUE THREAD

**Issue by DexterDude** [HaloSpaceStation/HaloSpaceStation13#760]
Suggestion: Add Energy Gauntlet and change some loadouts.

How it will work: Add an energy gauntlet that works like a Kig-Yar energy shield. They click the button in the top right and it slides out. Give this to the Ranger, and Zealot, while also removing their swords as in Halo, Rangers do not have ESwords and I haven't seen a Zealot with an esword, except once. They only, to my understanding, have energy gauntlets, perhaps remove it from Ultra as well and only let Specops keep the sword. Perhaps make it an AdminSpawn weapon mostly? So admins give the weapon to the 'leader Sangheili' or something.

**Comment by ghost** [comment]
For reference, he means having inbuilt energy daggers in Sangheili gauntlets like in Reach, but didn't realise that they were one and the same.

**Comment by caelaislinn** [comment]
That seems redundant. Elites already have swords and everyone else has daggers

**Comment by DexterDude** [comment]
I'm saying the swords should be replaced. It's dumb to have a lot of elites wielding swords. They are too overpowered. And to my knowledge daggers don't fit in pockets. Even if they did they take up space.

**Comment by BDpuffy420** [comment]
Yeah no, since an item like that already exist and only ultra and higher ranks have the sword to begin with.

**Comment by DexterDude** [comment]
Rangers have ESwords

**Comment by caelaislinn** [comment]
I'm tagging this as energy dagger gauntlets could still be a cool feature
