### ISSUE TITLE
[Suggestion] Covenant Boots

### ISSUE THREAD

**Issue by DexterDude** [HaloSpaceStation/HaloSpaceStation13#761]
Suggestion: Give Skirmisher and Sangheili boots

How it will work: All sangheili get boots as well as Skirmisher. Perhaps make the skirmisher boots give them a speed buff, as the whole role of Skirmisher is to be fast and a flank unit. Right now they are just slow. Sangheili boots will do nothing really, maybe a special variant for Rangers that act like mag boots.

**Comment by SpiderPsycho** [comment]
There are already skirmisher greaves apparently. I'll resprite those since I've already recoloured skirmisher armor for their ranks. I don't know how github works so I'll just chuck it on the discord.

**Comment by SpiderPsycho** [comment]
![skirm_boots png](https://user-images.githubusercontent.com/33624371/45606160-56807800-ba75-11e8-9f25-0a195af612ba.png)

Here's the boots. Its saved as a sprite but I used TweakPNG to add the necessary stuff so it can be opened with dream maker. There are minor, major, murmillo, commando and champion recolours in there.
