### ISSUE TITLE
Suggestion: Covenant Ranks/Gear

### ISSUE THREAD

**Issue by mcalexev** [HaloSpaceStation/HaloSpaceStation13#771]
Alright, a small list of potential features to add as discussed in the Covenant Hall part of the Discord.

- [x] Brute Plasma Rifles (For when Brutes arrive/Great Schism mode is ready)
- [x] Sangheili/Jiralhanae Honour Guardsmen (and their respective armor/ceremonial spears)
- [x] Needle Rifles
- [x] [Type-42 Directed Energy Weapon (Plasma Turret) http://halo.wikia.com/wiki/Type-42_Directed_Energy_Support_Weapon (I can provide images for art reference if required.)

**Comment by BDpuffy420** [comment]
We have sprites for the warthogs and other  variances and we have scorpions, we just need code work

**Comment by caelaislinn** [comment]
I've added shade turret to #285. Can you please add a separate issue for the warthog and scorpion tank? Then remove warthog, scorpion and shade from this and turn each of the remaining covenant items into a markdown list

**Comment by BDpuffy420** [comment]
There already issues  open about the unsc and covenant vehicles

**Comment by caelaislinn** [comment]
Found it. In this case just remove them from this issue, then reformat it into markdown list and rename it to something like "Covenant gear"

**Comment by mcalexev** [comment]
Done! Also added the other standard Covenant infantry turret that'd be in use in the current period, with a link for reference.

**Comment by SpiderPsycho** [comment]
![final skirm armor png](https://user-images.githubusercontent.com/33624371/45606206-be36c300-ba75-11e8-952e-920a1462e27a.png)

Converted into a png but it can be opened with Dream Maker. Skirmisher Armor, without the minor armor, its got the Major, Murmillo, Commando and Champion.

Edit: Updated and tweaked version on the Discord. Ping on Discord for it

**Comment by caelaislinn** [comment]
I've got this stuff partially implemented on my hard drive but it's a low priority. If anyone wants to take up implementing the sprites that would be great

**Comment by SpiderPsycho** [comment]
Since I'm unsure which version is being implimented, I will send the FINAL FINAL versions of what I have here. https://drive.google.com/open?id=1sIX8DEm0InhnvOQB6nMUmY7MjM6klNHl
All the images dmis are in there, for the armor, gauntlets, and booties. Armor and helmets are in one dmi

**Comment by SpiderPsycho** [comment]
Item sprites for helmets and boots https://drive.google.com/open?id=1I5m_cvmiepRk0rTcB2J3g_V7CmrchR7m

**Comment by SpiderPsycho** [comment]
https://drive.google.com/open?id=1clq78ewTe3LhdcNl59m6JugbOAP3gc18 Item sprites for armor.

**Comment by caelaislinn** [comment]
Tagging this for a bounty so it gets done by the end of the Covenant arc (January 2019)

**Comment by ghost** [comment]
#1478
#1434
#1193

Completely done, issue can be closed
