### ISSUE TITLE
Make unggoy spawn with natural-boots to stop speedup-shenanigans

### ISSUE THREAD

**Issue by X0-11** [HaloSpaceStation/HaloSpaceStation13#773]
title

**Comment by DexterDude** [comment]
or just remove their ability to wear boots, because they never had boots in the games nor books

**Comment by X0-11** [comment]
That's what this is intended to do. This doesn't remove a feature of all mob inventories and instead permenantly occupies it.

**Comment by DexterDude** [comment]
can they not just take the boots off?

**Comment by X0-11** [comment]
canremove can be set to 0
