### ISSUE TITLE
[Suggestion] Civvie/Innie Anonymity

### ISSUE THREAD

**Issue by ghost** [HaloSpaceStation/HaloSpaceStation13#775]
Have the civilian and URF ships use random sprites (Either the bog standard civilian ship or CCV sprites we have right now) and random names in order to prevent meta'ing and provoke suspicion, as right now it's always very clear which ship is the innies, and which is the civilians.

**Comment by caelaislinn** [comment]
Nice idea. This was always the plan from a while back but I wasn't planning to implement it until the overmap feature arc.

**Comment by Flaksim** [comment]
Dont forget that the URF now captured a UNSC warship, the Thorin though. So anonymity there is mostly gone in exchange for proper armor and weapon systems.

**Comment by ghost** [comment]
Ya, this was made before the Thorn became the new innie ship.

**Comment by X0-11** [comment]
#1149 has a system that could be modified to allow the nav-chips to also transfer ship-name and icon.
