### ISSUE TITLE
[Suggestion] Remove/Nerf Kig-Yar Captain energy cutlass

### ISSUE THREAD

**Issue by Delnth** [HaloSpaceStation/HaloSpaceStation13#777]
#### Description of issue

The energy cutlass is way too OP. It takes less than five hits to remove a limb (and thus the ability to fight back or anything). It also knock down just as easily. I've witness a kig-yar cucking many ODSTs with just their energy cutlass, knocking them down one by one, removing their limbs and anything they needed to retaliate, thus turning them into easy preys, which is as unfair as the SRS. This can, will and is abused.

#### Difference between expected and actual behavior

The weapon is too OP, effectively removing a character from the round if aiming for the right spots with relatively little effort. It should pack a punch, yes, but removing a limb or knocking down a player in less than two hit max is unfair and unbalanced.

#### Steps to reproduce 

There is not really anything specific to do. Just go 'unga smash' with him and you will either remove the limb and / or knock down your opponent. Aiming for specific limbs might work better. It is waaaay easier to knock down someone while aiming at the mouth, too.

#### Specific information for locating

Imgur keeps hitting me failed upload errors, eugh, I'll put the screenshots once this issue is fixed. For now, text logs!

> Gik-Yan parries Jack 'Lance' Jones with the energy cutlass!
> Jack 'Lance' Jones has been slashed in the right hand with energy cutlass by Gik-Yan!
> Gik-Yan begins to cut Jack 'Lance' Jones's carpal ligament with the energy cutlass!
> Jack 'Lance' Jones has been ripped in the right hand with energy cutlass by Gik-Yan!
> Your right hand goes flying off!

> Jack 'Lance' Jones has been diced in the left arm with energy cutlass by Gik-Yan!
> Your armor has softened the blow to your left arm.
> Jack 'Lance' Jones's ODST CQB Armour's armor plating is damaged! 
> Jack 'Lance' Jones has been knocked down!

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by X0-11** [comment]
The energy cutlass does the same amount of damage as the energy daggers
