### ISSUE TITLE
[Suggestion] Skulls Tab for the admin Secret Panel

### ISSUE THREAD

**Issue by Delnth** [HaloSpaceStation/HaloSpaceStation13#778]
Skulls can be found here: https://www.halopedia.org/Skulls (In this context, this suggestion is about the collectibles that enable humorous/challenging features) I could list all the skulls I would love to see added, but there are way too many of them. Just look at the halopedia link and draw your inspiration from there, should you decide to work on this feature suggestion.

My idea is to basically add a 'skull tab' in the admin secret panel, which would contains more or less a wide range and variety of the skulls that exist in the halo series. This would allow for funnier and / or more challenging way to play a round. 

An example of a known skull with funny effects:

> Grunt Birthday Party
>
>Effect: If a Grunt is shot in the head with any headshot-capable weapon (such as the Battle Rifle, Beam Rifle, Carbine, Sniper Rifle or Magnum), a popping sound is heard, colorful confetti explodes out of it which causes minor damage to nearby enemies, and a sound clip of children cheering from the game Hurray!"can be heard in the background. When the Grunt's head explodes, their mask will usually fall off. 

And a more challenging, serious one:

> Famine
> 
> Effect: All weapons that are dropped by enemies or are scripted to spawn on the ground (e.g., near a crashed Pelican or group of dead bodies) have halved or reduced ammunition or charge. However, weapons found in cases still have the standard amount of ammo. 

Or even:

>Mythic
>
>Effect: All of the Covenant you encounter have twice the amount of health and shields. 

Those would surely help spice up the round but, perhaps only the players should decide whether or not to activate a skull and which one. Maybe through a vote, or something. This is an idea after all, insights are welcome to discuss this interesting suggestion!

**Comment by caelaislinn** [comment]
Some ideas for skulls
- Famine: Delete all magazines not in guns
- Bandanna: All players get respawning grenades
- Eye patch: Disable lock on
- Grunt Birthday Party
- Catch: NPCs throw grenades instead of firing their weapons
- Mythic: All Covenant get double health
- Black eye: Shields only recharge via melee attacks
- Blind: Disable the UI

**Comment by Aroliacue** [comment]
Stale, closing
