### ISSUE TITLE
Replace adminspawn-elite Energy Swords with energy daggers, when appropriate

### ISSUE THREAD

**Issue by X0-11** [HaloSpaceStation/HaloSpaceStation13#784]
Title. Suggestions for which ranks should keep their swords welcome.

**Comment by ghost** [comment]
Zealots and Ultras should probably still get eswords.

I'd say specops too, but they're rather overpowered.
Everything else should have edaggers.
It'd be neat if those edaggers were built into their gauntlets like the kiggie shields, but not really necessary at all.

**Comment by X0-11** [comment]
Closed as of #785
