### ISSUE TITLE
'Remove occupant' verb is broken

### ISSUE THREAD

**Issue by TitanField** [HaloSpaceStation/HaloSpaceStation13#788]
#### Description of issue
The 'Remove Occupant' verb doesn't work

#### Difference between expected and actual behavior
Expected: Occupant is removed

Actual: Nothing happens

#### Steps to reproduce 
Get someone to enter a vehicle, commonly a pelican and then use the remove occupant verb.

#### Length of time in which bug has been known to occur
A VERY long time, months?

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this]

**Comment by BDpuffy420** [comment]
#859
