### ISSUE TITLE
Duplication glitch from starting loadout

### ISSUE THREAD

**Issue by Tasald** [HaloSpaceStation/HaloSpaceStation13#790]
#### Description of issue
 Choosing a holster in the loadout menu will cause you to spawn with one on your suit, even if you already have a holster attached to it. Doing this you can holster a gun into them and boom you no have two of the same gun.

#### Difference between expected and actual behavior
Game should not be able to attach a second holster to your suit if your role spawns with one already.

#### Steps to reproduce 
What I did:
Chose hip holster in the loadout
spawn as marshal
holster revolver

#### Length of time in which bug has been known to occur
Just found it today

#### Client version, Server revision & Game ID
Client Version: 512
Server Revision: 791a26ef354ca56d7f241d0b512fb70f78abe46c - alpha - 2018-09-05
Game ID: bWe-dxJA
Current map: Outer System #1445113

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [x ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Flaksim** [comment]
Updated Issue bingo, I was able to reproduce this.
