### ISSUE TITLE
Repurpose Geminus

### ISSUE THREAD

**Issue by X0-11** [HaloSpaceStation/HaloSpaceStation13#794]
Geminus is a large but well designed map. It could be streamlined and further used for urban-combat scenarios.

**Comment by caelaislinn** [comment]
With minimal changes to the code and map, we could do this right now. I've been working on decoupling mapsets and gamemodes for the past few months and this is a good opportunity for me or someone else to go in and properly fix the slayer gamemode.

**Comment by caelaislinn** [comment]
This could be a nice side project, but probably not a main focus
