### ISSUE TITLE
Invasion Gamemode

### ISSUE THREAD

**Issue by X0-11** [HaloSpaceStation/HaloSpaceStation13#795]
Requires:
Objective time-limiting and a way to display this.
Point Capture mechanics.
Bomb Planting/defense (Payloads could be used for this)
lowered/raised respawn timers for each team
Area lockdown that is lifted when objectives are completed.

Wanted:
Tactical HUD with objective readout + objective marker.
Loadouts randomised/potentially selected, determined by team.
Optional objectives that provide assistance to completing team. (MAC bombardment/glassing beam, supply drop)

Any suggestions as to the potential features or how they could be implemented are welcome.

**Comment by BDpuffy420** [comment]
This still needs work

**Comment by caelaislinn** [comment]
As of #1783 we effectively have all this. We could split some of the features off into a Covenant vs UNSC war specific gamemode, but it would play very similarly to the current set of gamemodes

**Comment by caelaislinn** [comment]
Well done team
