### ISSUE TITLE
[Suggestion] ONI Field Agent

### ISSUE THREAD

**Issue by Nick123q23** [HaloSpaceStation/HaloSpaceStation13#796]
Add a new job to the VT9 Crescent Base, ONI Field agents from Section One, responsible for proper military intelligence. Their job would be to discover insurrectionist operations, interrogate prisoners, and assist ONI researchers in their jobs.

In terms of chain of command, they would have authority over ONI Sec guards, but be of equivalent status to ONI researchers, and work under the research director.

They would have no direct command over the main UNSC force in the Thorin, Beretels, or Heaven Above, but they should cooperate with each other to achieve the UNSC's goals.

We could whitelist this role for UNSC players if necessary.

All equipment for an agent is already ingame, although a new uniform for them might be desirable.
My proposed equipment for them would be a renamed bay expeditionary utility uniform, expeditionary service jacket, dress shoes, and a M6S pistol with a thigh holster, as well as the oni badge

**Comment by Nick123q23** [comment]
Should add that I also think there should only be about two of them per round

**Comment by Flaksim** [comment]
I personally do not think this is a good idea. It'd just lead to role proliferation with limited actual use for this specific one, as the FC mode focuses more on direct action than subterfuge.

**Comment by caelaislinn** [comment]
I've been interested in adding this as an antagonist role with a secret objective. Wouldn't be too hard.

**Comment by Aroliacue** [comment]
Added five years later
