### ISSUE TITLE
Large crates do not retain their skins

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#800]
https://cdn.discordapp.com/attachments/335526938837778443/488273149788684288/unknown.png

**Comment by BDpuffy420** [comment]
Update: This still happen

**Comment by X0-11** [comment]
This is due to improper switching of the crate icon, being manually done through the mapping variable changer interface

**Comment by Aroliacue** [comment]
Update: This is still happening, no idea how to fix
