### ISSUE TITLE
Default unggoy are majors, instead of minors.

### ISSUE THREAD

**Issue by Nick123q23** [HaloSpaceStation/HaloSpaceStation13#801]
#### Description of issue
Default unggoy spawns as majors, instead of minors.

#### Difference between expected and actual behavior
Default unggoy should spawn with the yellow minor combat harness rather than the red major harness. Instead, both unggoy majors and default unggoy spawn with the major harness.

#### Steps to reproduce 
Attempt to spawn an unggoy major next to a default unggoy, they will wear the same armor.

#### Specific information for locating

Unggoy should spawn with 

/obj/item/clothing/suit/armor/special/unggoy_combat_harness
by default, 

and only unggoy majors should spawn with

/obj/item/clothing/suit/armor/special/unggoy_combat_harness/major

#### Length of time in which bug has been known to occur
Probably a few months.

#### Client version, Server revision & Game ID
Client Version: 512
Server Revision: 0c27f38407fd44a366f77533848b6aca9299b0ef - alpha - 2018-09-08
Game ID: bWg-cgSh
Current map: Outer System #1445113

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by caelaislinn** [comment]
First Contact mode grunt crewmember

**Comment by Flaksim** [comment]
I fixed this with the addition of the covenant corvette, grunt minors and majors spawn with different armor now, according to their rank.

This issue can be closed.
