### ISSUE TITLE
[Suggestion] Add a way to get empty E-Cig cartridges.

### ISSUE THREAD

**Issue by Tasald** [HaloSpaceStation/HaloSpaceStation13#805]
#### Description of suggestion
There is no real way to get empty 'unlabeled' E-cig cartridges for making your own 'off brand' ones to sell or give out. Currently the only way to get them is to buy the E-Cig from the machine, but those are 100 - 150 each and you only have 2 each per machine. 

I recommend putting 'empty' ones in the cigarette machines and / or making it so you can make your own using some plastic or metal in the autolathe.

#### Client version, Server revision & Game ID
Client Version: 512
Server Revision: c9c0c86af10172d95284b210564457d5a7d7ed38 - alpha - 2018-09-11
Game ID: bWi-dAe7

**Comment by Flaksim** [comment]
This doesnt exist yet. Low priority to add.

**Comment by BDpuffy420** [comment]
Not really a priority at all.
