### ISSUE TITLE
[Suggestion] Lack of ways to get liquid nicotine 

### ISSUE THREAD

**Issue by Tasald** [HaloSpaceStation/HaloSpaceStation13#806]
#### Description of suggestion
None of the seed machines have tobacco seeds in them or other way of getting nicotine for that rp fluff.

Maybe put some seeds into the vendors and/or bottles of it in the cigarette machines for people to buy?

#### Client version, Server revision & Game ID
Client Version: 512
Server Revision: c9c0c86af10172d95284b210564457d5a7d7ed38 - alpha - 2018-09-11
Game ID: bWi-dAe7

**Comment by Flaksim** [comment]
Tobacco seeds were added to the seed machines
