### ISSUE TITLE
Shutter buttons don't work

### ISSUE THREAD

**Issue by Tasald** [HaloSpaceStation/HaloSpaceStation13#807]
#### Description of issue
https://gyazo.com/47c236275bb5ecf7796a8644d93e9a43

These shutter buttons do nothing despite the blast doors being there. 
Buttons are located at the ONI barracks.

#### Difference between expected and actual behavior

Clicking the buttons should closed those blast doors like all the others.

#### Steps to reproduce 
Spawn a Oni role
try to close blast doors

#### Length of time in which bug has been known to occur
At least a week now.

#### Client version, Server revision & Game ID
Client Version: 512
Server Revision: c9c0c86af10172d95284b210564457d5a7d7ed38 - alpha - 2018-09-11
Game ID: bWj-b8nj
Current map: Outer System #1445113

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Flaksim** [comment]
Fixed in my next PR.

**Comment by caelaislinn** [comment]
Please don't close until the PR is actually merged

**Comment by Flaksim** [comment]
This has been corrected and the PR has been merged.
