### ISSUE TITLE
RoE suggestion

### ISSUE THREAD

**Issue by DexterDude** [HaloSpaceStation/HaloSpaceStation13#810]
Suggestion:
My idea is to basically revamp RoE for FC Covenant so they can have fun but also have an objective at times. 

How it would work:
Make it so RoE randomly changes each round, RNG and nothing more, or perhaps RNG and a bit of 'manual' stuff. So basically RNG takes place if it's in the middle of 10-20. If it's below it is always 'you can do whatever' but if above it will be 'stealthy stuffs'. Have a notification like you get when you sign up as a clown on TG in red text saying something along the lines of 'There is no RoE this round, you are free to do as you wish' and if it's RoE basically the oppisite 'RoE is enabled, follow the Covenant RoE' or something like that.

**Comment by Max-023** [comment]
Having no sense of structure for one of the most powerful factions sounds like a horrible idea. -1

**Comment by Cynliax** [comment]
I agree with this, right now any interactions with the covenant per round is extremely limited, if any at all, with the most action you'd see is the ship driving by. I think this would benefit everyone by creating more action and interesting RP.

+1.

**Comment by DexterDude** [comment]
They didn't have a structure before, they were freeform but had to follow the server rules, and most Covenant try to roleplay even with their 'omg OP faction' and are horrid at combat.

**Comment by Max-023** [comment]
And before it got real bad because the ship would just open fire on the Thorin without any reason.

**Comment by DexterDude** [comment]
Then AHelp it. RoE doesn't actually change anything but restrict those who wish to roleplay and have fun. Again, if they randomly fire on you they are breaking rules.

**Comment by Cynliax** [comment]
UNSC often have better players and more numbers, I believe this far outweighs whatever the covvies try and do if they brute force their way against the UNSC. Especially with ODSTs capable of storming the covvie ship.

**Comment by Max-023** [comment]
You know that isn't true, right? The Insurrection does it all the time against civilains. RoE is what prevents firefights erupting out of nowhere.

**Comment by DexterDude** [comment]
I know what isn't true? Yeah it makes a guidline saying don't do this, but it restricts any fun, and Covenant are whitelist, this means hubbies have to bother applying for it and wait a day to break the rules with the Cov ship. Just because the URF do stuff doesn't mean the Covenant do.

**Comment by Nick123q23** [comment]
Not really a good idea. You should try adjusting the RoE itself instead.

**Comment by DexterDude** [comment]
What do you mean adjusting the RoE?

**Comment by BDpuffy420** [comment]
Honestly don’t think it’s a good idea

**Comment by ghost** [comment]
I disagree with this suggestion, but I do think the FC RoE needs to be reworked to account for the covvies having a corvette instead of a teeny missionary ship.

**Comment by BDpuffy420** [comment]
Due to the nature of how things changed on the server I don't think this needs to be open still, but I will leave open for the next 24 hour if anyone else has something to add.
