### ISSUE TITLE
Mounting vehicles and turrets at same time

### ISSUE THREAD

**Issue by dabbster** [HaloSpaceStation/HaloSpaceStation13#813]
#### Description of issue
Able to mount a vehicle, and a turret, then disembark the vehicle and be able to fire the turret from the vehicle's new location

#### Difference between expected and actual behavior
Expected behavior is only being able to mount a vehicle OR a turret, not both at the same time

#### Steps to reproduce 
1. Mount an ATV
2. Drive an ATV up to a turret.
3. Click on the turret to mount
4. Unmount from the ATV and mount the ATV again.
5. Drive away a few squares and unmount the ATV
6. Click around you (it will result in you shooting from the turret but from the ATV's current position

#### Length of time in which bug has been known to occur

I've just found this today (9/16/2018) but speculating that it's always been in the game.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: c9c0c86af10172d95284b210564457d5a7d7ed38 - alpha - 2018-09-11
Game ID: bWn-bDUk
Current map: Outer System #1445113

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Flaksim** [comment]
I reproduced this, Issue bingo updated.
