### ISSUE TITLE
Code doesn't compile (robot_parts.dm)

### ISSUE THREAD

**Issue by Pandolphina** [HaloSpaceStation/HaloSpaceStation13#814]
#### Description of issue
Code refuses to compile due to

code\game\objects\items\robot\robot_parts.dm:99:error: :: expected end of statement

#### Difference between expected and actual behavior
Code SHOULD compile with zero errors.

It compiles with code\game\objects\items\robot\robot_parts.dm:99:error: :: expected end of statement as an error.

#### Steps to reproduce 
1. Fork code
2. Download code
3. Attempt to compile.
4. Fail and cry

#### Specific information for locating

code\game\objects\items\robot\robot_parts.dm:99:error: :: expected end of statement

#### Client version, Server revision & Game ID

Newest code (9/16/2018)

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Delnth** [comment]
Try running the BYOND Stable version. It won't work even on stable version if you are running BYOND from a different install path than the default one, for some odd reason.

**Comment by Flaksim** [comment]
Confirmed, this is a known issue with the beta version and non standard install paths. Recompile from stable and it will function.
