### ISSUE TITLE
Destroying multitile airlocks doesn't properly clear the sight blockers

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#817]
https://i.gyazo.com/7c444936591273cb9ad055c548018505.png

Can be fixed by clearing out the sight blockers in Destroy()

**Comment by caelaislinn** [comment]
Has anyone got any info on this? I've seen it on live but can't reproduce it

**Comment by Nanu308** [comment]
I know this has happened on other Bay based servers as well, unsure why tho.
