### ISSUE TITLE
Fuel Suggestion

### ISSUE THREAD

**Issue by 2cwldys** [HaloSpaceStation/HaloSpaceStation13#823]
#### Description of suggestion
A suggestion, to replace the fuel with 'Covenant Cores' to prevent Phoron Leakage every round.
https://www.halopedia.org/Covenant_power_module

#### Difference between expected and actual behavior
When a hull breach occurs, and strikes a Phoron Tank - that's it, the end .. for the ship. (Covenant Sided)
Most players go blind and end up dying or shooting themselves, basically ship crew is incapacitated.

Perhaps we can use cores, that we start with 1-3 of, and if they are struck in combat they cause an explosion, a rather large one - instead of Phoron across the ship, all of the Huragok has to be focused to repair the ship and a new piping and layout for whatever cores that are left. This still leaves the ship dead in the water, but at least the crew can fight _back_.

#### Steps to reproduce 
This can save a lot of space, by removing most of the Phoron Tanks, Slots, and Large Tanks; using 'cores' , so more areas can be utilized, more storage and armories, overall mobility and interactivity while on a covenant carrier.

**Comment by caelaislinn** [comment]
Great idea. I wanted to do something like this for ages... we just need sprites for it though

**Comment by 2cwldys** [comment]
I purchased some spriting software known as Aesprite, I can probably do it if it is to be a rectangle sprite. Would you want that?

**Comment by caelaislinn** [comment]
See how you go, welcome to give it a try

**Comment by 2cwldys** [comment]
What are the dimensions of a 'tile' .. for like the size of a Phoron Tank per-se?

Is there some template I can obtain?

**Comment by caelaislinn** [comment]
Yeah just base it off the plasma/phoron tank. Make it perspective or 3D if you like

**Comment by Max-023** [comment]
This is an issue for Human ships as well. I would much rather have the lore fuel be used, but for now the devs have left it to be phoron engines all around.

**Comment by 2cwldys** [comment]
What can also fix the issue with phoron on covenant ships (for Unggoy) at the moment could be the goggles you see on most unggoy in halo 4-5?

To nullify the blindness from Phoron?

https://i.pinimg.com/originals/a4/9f/ac/a49fac3ceb3006b2f30c60388c1ab392.png
