### ISSUE TITLE
SDV Vindicative Infraction faxmachine is broken

### ISSUE THREAD

**Issue by Delnth** [HaloSpaceStation/HaloSpaceStation13#824]
#### Description of issue

Covenant players have been complaining the faxmachine didn't accept the ID card provided for authentification. After investigation and forcefully authentifying it through variable, it turns out that after a refresh, the faxmachine is updated into a Local Deck Gun console with an error, as quoted below:

> A variable with this name (authenticated) doesn't exist in this atom (Local Deck Gun Control)

#### Difference between expected and actual behavior

It's supposed to shoot paper through the distance, not lasers. More seriously, it doesn't work like a fax should, see above. Said update doesn't even allow for overmap view and actual use of the ship guns. The NanoUI is not updated, it's just stuck on the fax interface.

#### Steps to reproduce 

View variables of the supraluminal console on the covenant ship, look for the 'auth' variable, try to edit it. Once you get the error, clear the search bar and refresh the variable window. You'll see the update at the top, obj path.

#### Specific information for locating

> A variable with this name (authenticated) doesn't exist in this atom (Local Deck Gun Control)

#### Length of time in which bug has been known to occur

Unknown. Noticed this issue after investigating a few minutes ago. Live server.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 8da50b1baf8150fa2677841ffa637f4e1530059b - alpha - 2018-09-19
Game ID: bWt-br0R
Current map: Outer System #1445113

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Flaksim** [comment]
This should be fixed.
