### ISSUE TITLE
Increase Carbine round speed/accuracy and or allow needlers to be placed in the back slot.

### ISSUE THREAD

**Issue by SpiderPsycho** [HaloSpaceStation/HaloSpaceStation13#827]
Currently the carbine's rounds are slow enough for people to just walk out of its path. Its far too ineffective. And even on the rare occasions people don't dodge out of its way, the round just misses overall. Its pretty useless unless you're in close range, but you're at a steep disadvantage using a gun that shoots one round and misses most of the time going against someone with a gun that can shoot a multitude of rounds with one click.

The Needler is apparently a good gun compared to the carbine but it can't be put in the back slot, making you have one less item that you can carry, adding worsening the lack of storage slots for any Covenant armor.

I didn't want to make too many issues but boy I just missed like 10 shots with a carbine and all they had to do was walk back and forth whilst making their way towards me. Its pretty unusable at the moment.

**Comment by SpiderPsycho** [comment]
Okay so since the carbine is likely not going to be changed, I've had an idea that'll improve the beam rifle's usability instead, apparently well recieved by other covies I spoke to briefly about it. Turn it into a laser with no projectiles, but since that'd apparently raise the accuracy to perhaps ludicrous levels, and it still has to be fair with the SRS, cut its damage, lower the time it takes to take shots, give it a manual process to reload it instead of having it regenerate over time, and perhaps give it an overcharge shot that'd do as much damage as it does now or perhaps a little more to be effective, whilst completely depleting the charge of it and forcing a perhaps longer recharge process. And perhaps the processes are just short things that allow it to regenerate ammo till it's capped.

I'd like the beam rifle to be changed because covies aren't usually capable of beating UNSC during close quarters engagements because of the spray of bullets, so allowing covies to have a little more advantage when being long range would certainly change things.

**Comment by X0-11** [comment]
The beam rifle is now hitscan, and the covenant carbine has an extra hit of radiation damage.
