### ISSUE TITLE
[SUGG] how to make ONI Comms operator intresing 

### ISSUE THREAD

**Issue by CdrRiley** [HaloSpaceStation/HaloSpaceStation13#829]
<!-right so i have been playing as ONI comms operator for quiet some rounds now as a Comms operator you dont do anything expect sending faxes and tahts it. SO my idea would be taht if you were to add a machine / computer wich could interpect radio calls form Innis or coives but  they are Decoded with ****** like when your curmble a paper and it would be fine if it like all 5-6 radio calls it intercepts one so thaht ONI comms may assit in helping the UNSC with Intel and such/ also add a battery room and power drain and fix Tellecoms 
BTW i have Dyslexia so yhea

**Comment by Wehraboo** [comment]
Cortana mentions in Halo 1 that the Covenant battlenet was broadcasting tactical information on unencrypted channels, so you may not even have to do the entire paper thing for them at least, Maybe the ONI comms operator can also understand the language they use, and the only one on the UNSC side at that, which could make them much needed during interrogations.

**Comment by Delnth** [comment]
I'd definitely see the comms operator being some sort of highly trained multilingual nerd that spends time decoding or figuring out a language. I mean, for example, in the Halo series, the kig yar language is pretty much reversed English sentences, low-pitched and pronounced faster than average.

This job has to be useful, but not that much. For specific situations and which everyone can rely on for stuff others achieve.

**Comment by CdrRiley** [comment]
Quote: 2525 was the first time humanity and the Covenant came into contact with each other. Since then up to 2526, we see ONI has managed to put a blackout on information, but civilians do find out eventually. Luckily though, the AI Assembly had speculated on the possibility of hostile aliens threatening humanity since 2310 and manipulated events to prepare humanity in secret.  well it semms ONI knew I belive some days or such before the fall of harset taht something was happening, due unkown comms chatter, ATM im listing to Contac Harvest audio book for more info.

**Comment by CdrRiley** [comment]
when this`?

**Comment by CdrRiley** [comment]
i mean after updating the time line to ONI knows the covis exits and  waht Whrabo has commentet i would like to see something for this

**Comment by CdrRiley** [comment]
Give ONI comms operator Shangelli language maybe cuse they are nerds

**Comment by zergursh** [comment]
> Give ONI comms operator Shangelli language maybe cuse they are nerds

stop

**Comment by CdrRiley** [comment]
no.
