### ISSUE TITLE
Larger than standard mobs (elites, spartans, tvoans, sanshyuum) lying down have their gear offset incorrectly 

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#832]
Quick fix just takes a bit of code diving
https://gyazo.com/ad76b5d687b457745eb0ce350eb474f1

**Comment by BDpuffy420** [comment]
#892

**Comment by caelaislinn** [comment]
Still a problem, also affecting other mobs with larger than 32x32 dimensions (Spartans, Prophets, Skirmishers)

**Comment by caelaislinn** [comment]
#923
