### ISSUE TITLE
Let ODST armour hold oxygen tanks

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#833]
Add this to /obj/item/clothing/suit/armor/special/odst on a new line: 
```allowed = list(/obj/item/weapon/tank)```

**Comment by WitchKat** [comment]
I'll do this if we're still wanting to, but this is over a year old. Is this wanted still?

**Comment by Zergrushh** [comment]
> I'll do this if we're still wanting to, but this is over a year old. Is this wanted still?

I'll probably do it tomorrow once I'm back home, if I remember, of course. Shouldn't really be a problem for even someone as incompetent as me.
