### ISSUE TITLE
Biofoam not processing under vacuum

### ISSUE THREAD

**Issue by Lussena** [HaloSpaceStation/HaloSpaceStation13#835]
#### Description of issue
When in a sealed suit (confirmed with ODST armor 3 times) under vacuum, while using internals, biofoam(possibly other medications as well) doesn't process and builds up in your system. It doesn't seem to happen unless both criteria are met, I've tried it with an emergency suit and ODST armor with internals on and atmosphere, and it doesn't happen then.

#### Difference between expected and actual behavior
It builds up in your system and I've ODed from biofoam this way, and doesn't heal or flush from your system the way it's supposed to, ~1u per tick I believe. You can tell it's happened by the fact the "You feel a searing pain in your veins" doesn't pop up like it would any other time you inject biofoam, aka you get no indication you've just shot up. Actual behaviour expected is medication working it's way through your system as normal

#### Steps to reproduce 
1.Wear ODST armor (I suspect any vacuum rated suit works)
2.be in vacuum/need internals
3.use your internals
4. inject biofoam (or other medication possibly)

#### Client version, Server revision & Game ID
Client Version: 511
Server Revision: 6291275a818ee489f82a2a46593fc4da87012995 - alpha - 2018-09-28
Game ID: bWz-as76
Current map: Outer System #1445113

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by caelaislinn** [comment]
Is this still happening?

**Comment by BDpuffy420** [comment]
no
