### ISSUE TITLE
Kig'Yar shields need to be made more reliable.

### ISSUE THREAD

**Issue by SpiderPsycho** [HaloSpaceStation/HaloSpaceStation13#836]
Currently the Kig'Yar gauntlet shield is ludicrously unreliable. This is something that's been complained about a lot on the Discord so I'll just take the initiative to put it onto Git. It doesn't deflect bullets nearly as reliably as it should. Flat out I think it should deflect bullets from one direction. It still leaves you open to be flanked, and the shield has a limit as is to how much damage it can take. 

I've literally had both my hands gibbed off whilst facing someone with the shield on. Its too unreliable to protect oneself, let alone allow you to be in a supportive role and defend other people with it.

**Comment by BDpuffy420** [comment]
#892
