### ISSUE TITLE
[SUGG] Medical Fire base 

### ISSUE THREAD

**Issue by CdrRiley** [HaloSpaceStation/HaloSpaceStation13#842]
i had an idea basically a medical fire base,  there is one way of how it may can work basically as an elevator or shuttle to the planets and it acts as a medical base /FOB  for the UNSC  it can get recalled so that could be a other way to board the Bertel too it should contain at least Room for 1 Sleeper 1 Advanced Scanner Optional a Surgery table and it should have a bed or so for treating wounded also some medical supplies

**Comment by BDpuffy420** [comment]
seems like a cool idea

**Comment by Maxattacker** [comment]
I actually had an idea like this that I posted in discord not long ago. Adding an actual space elevator z-level to relevant planets, where it has a security checkpoint, medical area, and an actual elevator to get to the surface. On KS7, emmsville marshals could have spawn points and a role, elevator guard. Same goes for VT9, except for it would be ONI guards on the elevator. Could act as a FOB, and choke point for any forces.

**Comment by BDpuffy420** [comment]
I think @Flaksim  was working on something like that

**Comment by Flaksim** [comment]
Can confirm, am working on that elevator. Its mostly done, just need some coding assistance.

**Comment by CdrRiley** [comment]
may i can ask waht is it gonna be when its fihned for the full picture?

**Comment by Flaksim** [comment]
Exactly what is proposed. An orbital docking area with a secwing, an orbital gun and an elevator to a ground station.

The map is actually finished.

**Comment by caelaislinn** [comment]
Players can take gear from the ship down to a planet with the current mechanics
