### ISSUE TITLE
[Suggestion] replace the firing range on the Bertels with a Training room

### ISSUE THREAD

**Issue by Joe44445** [HaloSpaceStation/HaloSpaceStation13#853]
Replace the firing range on the Bertels with a training room, similar to the ones on both the Heaven above and the ONI base. This would allow for more training of the marines in round, by the platoon leader or perhaps even available ODSTs. The firing range, as it currently stands, is quite useless. Shooting your gun at a target just wastes ammo, with the Training room we could set up combat situations with varying team Compositions to prepare players for various situations they might face. Not only that, but it will also add more RP to the UNSC side, as most of the time marines end up wandering around the ship or sitting on the bridge before eventually logging out due to a lack of things happening.

The Training room would be similar in design to the other 2 rooms I mentioned, with colour coordinated teams, rifles and TTR rounds readily available in the rooms, with some basic cover/walls in there.

in the end, this would help the marines as a whole get better in fighting skill, with help from more skilled players which could teach them various team tactics, CQC skills and plenty of other areas the marines may need to work on without putting them straight in to combat with no idea what to do

**Comment by Max-023** [comment]
This is Spartan Max-023 and I approve this message.

**Comment by ghost** [comment]
I'd recommend a relatively small mockup of an apartment/general urban area. It worked very well for the covvies during our scheduled training, and it helped a lot with figuring out how to coordinate a small team and fight effectively together.

**Comment by Wehraboo** [comment]
Could the training room work like a hologram room that a few servers have? That way we could have a range of scenarios mapped out and easily changeable.

**Comment by Max-023** [comment]
Holograms could be difficult to produce.

**Comment by Flaksim** [comment]
This has been implemented. There isnt room for a large room however, this is only a Corvette afterall.
