### ISSUE TITLE
Suggestion: Give Spartans and elites the ability to force open airlocks

### ISSUE THREAD

**Issue by Maxattacker** [HaloSpaceStation/HaloSpaceStation13#854]
#### Description of issue

Spartans and elites should be able to open airlocks with their hands, similarly to the xenos forcing open doors in CM. However the airlocks would have to already be damaged to the point that you could force them open with a crowbar
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by SpiderPsycho** [comment]
I get the feeling this could easily be abused. Elites aren't really capable of doing it anyways. I think it'd be better if we just got door charges or something. Sure Chief pried open a door in 4 but I don't think I'd enjoy a single spartan just making his way through the entire ship or vice versa. It'd probably be worse for UNSC players since we'd have multiple Elites. Just restricts both roles even more if this gets added because they're capable of going wherever they please.

**Comment by Maxattacker** [comment]
For this, I was thinking more of OP redflag, where Spartan loadouts may or may not have any ability to get through any doors at all. Even if they damage them, there still is no current way to get them open, and while I realize that the game mode is still in testing phase, I think this would benefit both sides as well.

**Comment by SpiderPsycho** [comment]
Why not have breaching charges for both sides? There are plasma charges in lore for Covies. Something that deals a lot of damage in a single square so it won't break walls, just destroy whatever it's placed on. There's already C-12. Just get a weaker pack of C4 or something from vanilla bay.

**Comment by Maxattacker** [comment]
Fair point. I don't know what Cael has in mind for the game mode, but I imagine there will be a way to deploy onto that monster of a cruiser/battleship/whatever it is.

**Comment by SpiderPsycho** [comment]
There are gravity lifts. I presume once the Spartans get in through there, they keep going as far as they can. Plus it creates a sense of urgency if there are only limited charges (unless admins spawn them more). Potentially limits random breaking into places.

And yeah I think its a CCS. A CAS would be waaaaay too big.

**Comment by BDpuffy420** [comment]
Support this

**Comment by ghost** [comment]
Sounds like a cool idea. It's more thematic than an ultimately necessary change, but I think it'd be nice to have.
