### ISSUE TITLE
[Suggestion] Assault/Support hound role

### ISSUE THREAD

**Issue by Delnth** [HaloSpaceStation/HaloSpaceStation13#857]
Add an assaulthound/support. Maybe for the civilian colony or the UNSC/Innies, although it is unheard of that they employed dogs. And along that, a faction role dedicated to the well-being of the dog. Not a vet, but more like a caretaker or something along those lines.

They could have the ability to track people or an ability that lets them focus on the sounds around them, ie the direction where footsteps can be heard, etc. Additionally, maybe an ability to attack or a way for non-lethal takedown?

This is more of an idea than an actualy suggestion, because it could use some discussion beforehand.

**Comment by Liam-Gallagher** [comment]
Real life militaries have dog handlers, usually just specialized MPs or specialized infantry, who train the dogs and take care of them. The dogs should have a tackle and bite as their starting abilities and their trainers can pick from a list of abilities to specialize the dogs, like give them the ability to track, smell gunpowder and explosives, hear far off sounds, etc... This way they can have a wide range of use and be customized to meet certain criteria or situations round to round. You could also give their trainers specific abilities that provide buffs to their dogs, to simulate the bond between the two and to encourage dog players to actually RP and stick with their handler.

**Comment by Delnth** [comment]
The dog handler could also be given a whistle (or an alternative) to call the dog back to him. It could come off as a huge notice in the dog player's chatbox, with potentially a location, cardinal or not.

+1 Liam.

**Comment by ghost** [comment]
While this does sound neat, it does seem like something that would need to be restricted to specific, more 'civilian'-ish modes. Stun combat is king in SS13, and having a dog whose entire purpose is to debilitate, disarm, and stun enemies in a main mode would either end up super abused, or super underpowered due to balancing.

**Comment by Delnth** [comment]
Honestly, I wouldn't want to see a dog stunning someone. Maybe only stun unarmored targets?
Also an ability to grab limbs with their teeth, which can hurt, depending on the target's armor values. Could work similarly to the normal grab but perhaps make it impossible to resist it until the dog is dead or incapacitated? (Or if it decides to release the target for whatever reason.)

**Comment by BDpuffy420** [comment]
This was added #2047
