### ISSUE TITLE
Expanding Armor system to allow repairs

### ISSUE THREAD

**Issue by BDpuffy420** [HaloSpaceStation/HaloSpaceStation13#858]
I know this is has been requested by many on all sides, a feature to be added for armor repair after they are  damaged. If a feature was added it needs to be done in way where it isn't overpowered so you don't have people repairing on the front lines in 30 seconds, I just feel if you need to repair your armor it should at-least take a certain amount of time so you have to step back from the firefight. Maybe some one time use armor repair kit or maybe have players craft armor components that  need to be added to the set to give back some armor thickness.

**Comment by X0-11** [comment]
Fixing armour degredation is a simple feature to add, however, there's a lot of ways to do it and it's hard to really guess if they'd be balanced.

**Comment by BDpuffy420** [comment]
Yeah I feel the same way about it to be honest, but many have voiced they would really like the feature. We can always do a trial-run with with it.

**Comment by X0-11** [comment]
What method would you prefer?

**Comment by BDpuffy420** [comment]
I'm open to anything really, we should wait to get some feedback from others

**Comment by Maxattacker** [comment]
I think having a one time repair kit would be a good idea. Make the repair time as long as it takes to escape from handcuffs. While in combat, that timer will seem like an eternity and would be much more risky to use on the field, making it better to withdraw from the battle if at all possible before repairing. Those with more tactical thinking could go off somewhere secluded and dark, in order to repair armor, ie; the slums on Geminus, Caves on VT9, etc.

**Comment by X0-11** [comment]
With a timer as long as that I don't see why it wouldn't be infinite use. Single use items tend to become too easy to find.

**Comment by BDpuffy420** [comment]
That's fine by me if it has infinite uses

**Comment by Flaksim** [comment]
Why dont we just make it like a stationary workbench somewhere? Like in the prep areas, down below in a weapons lab in ONI base, on the cov corvette... That way people would have to RTB to execute repairs.

**Comment by CdrRiley** [comment]
im for the Sationry workbench as well but one player should be on the bench and "repair" the broken armor or even an automated process wich may take the double of time instaned
 when a human does it or player

**Comment by ghost** [comment]
A stationary 'workbench', or equivalent, to repair armour with would be pretty nice. I'd also suggest, in addition, "Armour patches". Single use armour repair, but the repair degrades over time. Only a temporary fix. This would make punctured suits EVA capable again for as long as the repair lasts.
