### ISSUE TITLE
Eliminate the reliance on stuncombat

### ISSUE THREAD

**Issue by X0-11** [HaloSpaceStation/HaloSpaceStation13#861]
Removal of pretty much all stun-based combat methods will allow the combat to actually feel skill-derived rather than cheesed via the use of a single stun-source.

Suggestions of things that require a rework from stunning greatly appreciated.

**Comment by ghost** [comment]
Melee weapons to the head. With a baseball bat that breaks after a few swings, it makes more sense. With a combat knife that can stunlock someone? Definitely not.

**Comment by BDpuffy420** [comment]
I know we removed stuns from the flash bangs

**Comment by ghost** [comment]
Explosive weapons cause KOs. While an explosion strong enough to KO will normally crit a normal human and therefore not matter, they can be used to easily defeat Spartans, ORIONs, Elites, etc that would otherwise only be lightly injured. (IE: KO them, then kill them while they're helpless.)

**Comment by SpiderPsycho** [comment]
Please remove stuns for flashes and batons whilst you're at it to. Going into an event and then being stunned by a marine who picked up a flash is pretty annoying.

**Comment by ghost** [comment]
I think flash powder needs to have the stun removed, but get its blindness length improved in exchange.

**Comment by caelaislinn** [comment]
There's very little to no stun related mechanics from what I've seen in active use
