### ISSUE TITLE
Antag hud/Respawn

### ISSUE THREAD

**Issue by ragnarocko** [HaloSpaceStation/HaloSpaceStation13#879]
#### Description of issue
Antag hud option still disables spawn for people.

#### Difference between expected and actual behavior
Well seeing as currently we have no way for one to become a "Tratior" or anyhting unless its trough admin intervention there should be no reason to have antag hud still disable spawn.

#### Steps to reproduce 

Just click antag hud option in ghost tab before trying to respawn.

#### Length of time in which bug has been known to occur

Not to sure.. probably has been like this for a while.

#### Client version, Server revision & Game ID

Client: 512.1448
Server revision: 892ef00e5772cc259ed71a7336300ee933f8b79f - alpha - 2018-10-09
Game ID: bWL-aoTS
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by X0-11** [comment]
A warning is provided when activating the verb and concealed antags may still be used in further development.
