### ISSUE TITLE
[Suggestion]Give ONI its own comms channel

### ISSUE THREAD

**Issue by CdrRiley** [HaloSpaceStation/HaloSpaceStation13#890]
right i often play as ONI and sometimes it gets really messy on comms with the UNSC and ONI in one channel and so i would like for ONI to get a own channel so taht they may talk about theyere scince stuff and [CLASSEFIED] stuff,   my idea was ONI gurad only get headset with ONI comms and the comms operator gets SHIPCOM and ONI comms, this is just an idea depends on how devs thing about this please leave your coment down below

**Comment by Plaguewalker** [comment]
First off, fix the grammar.
Secondly, this is a definitely needed move to it.

**Comment by CdrRiley** [comment]
First off i have Dyslexia so no grammar fixing 
secondly i agree that that should be made soon

**Comment by ghost** [comment]
Fix that grammar.

But yeah, ONI don't exactly want to be talking about the ORION project over SHIPCOM. Good idea.

**Comment by BDpuffy420** [comment]
@Plaguewalker @Boltersam  cut it out, being a dick here will lead to a git ban

**Comment by CdrRiley** [comment]
yo label it as Suggestion?

**Comment by Nick123q23** [comment]
yes please

**Comment by BDpuffy420** [comment]
#991
