### ISSUE TITLE
[Bug] Grunts don't spawn with jumpsuits

### ISSUE THREAD

**Issue by ghost** [HaloSpaceStation/HaloSpaceStation13#893]
#### Description of issue
Grunts don't spawn with unggoy jumpsuits, leading to them not being able to use their pockets or belt slots.

#### Difference between expected and actual behaviour
Grunts are supposed to spawn with jumpsuits but don't.

#### Steps to reproduce 
Spawn as a grunt, any rank.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Max-023** [comment]
Grunt Majors also need to have battlenets when spawned.

**Comment by ghost** [comment]
So do grunt minors, I believe.

**Comment by Max-023** [comment]
Minors do spawn with battlenets, oddly enough.

**Comment by caelaislinn** [comment]
#928
