### ISSUE TITLE
Grunts! English! Do you speak it?! [Suggestion]

### ISSUE THREAD

**Issue by Max-023** [HaloSpaceStation/HaloSpaceStation13#894]
Grunts of all ranks should be able to speak galactic common. Grunt Major is a role played simply because it is a Grunt Minor, but able to speak English. Grunts in Halostation are seen more in red rather than orange.

A fix would be give the Military the ability to speak common, like the Majors currently. But to make sure the Grunt Major is still higher, they get to understand all Human languages, such as Sol and Tradeband. This will make Grunt Minor more appealing while still making Majors primary comms monitors.

**Comment by Nick123q23** [comment]
agree

**Comment by caelaislinn** [comment]
I didn't let Majors speak Sol and Tradeband. I'm not sure languages are used much, and Sol will probably get disabled anyway.
