### ISSUE TITLE
Corvette repairs

### ISSUE THREAD

**Issue by Max-023** [HaloSpaceStation/HaloSpaceStation13#895]
Right now the Vindicative Infraction has no way of repairing itself. You cannot make nanomalite floors or walls nor a way to replenish atmosphere. The only tools you get are 4 crowbars, 4 screwdrivers, and 4 wrenches, That isn't even enough for fixing doors. All damage is permanent to the ship unless Koen spawns a once in a lifetime Huragok, which even then only has enough tools to repair but not fix atmos. I suggest pausing other work on the Covenant and fixing this sole issue of Huragoks and atmosphere. A breach in the hangar will eventually be the death of everything but Grunts, as Jackals and Elites have little protection and no warning of a breach. There are no air alarms. There are no warning systems for damage to the ship. Elites don't even have protection, they will just suffocate. Everything else the Covenant isn't as necessary as this. If the shields fail, the ship fails. Not even the URF gets the dick this bad.

**Comment by BDpuffy420** [comment]
>pausing other work on the Covenant and fixing this sole issue of Huragoks and atmosphere.


   I'm sorry but we will get to it when we can, you are more than welcome to make the attempt yourself though.

**Comment by Max-023** [comment]
Koen already has a functioning Huragok. Just a cyborg with the Huragok skin, but it works just fine. All it needs is to be implemented as a role rather than a custom spawn.

**Comment by BDpuffy420** [comment]
Yeah we rather not copy paste something like in that fashion, there has been slight discussion on how we will add the Huragok.

**Comment by SpiderPsycho** [comment]
Just have competent people flying the ship during combat. IE don't fly into bullets. Then have atmospheric shielding on, which makes it so the shield fills up areas which are breached. Lastly, if you can, steal metal and have the grunts repair walls. Though yes, the hull plating is really thin at vital points. iirc the medbay walls are only 2 walls thick.

**Comment by caelaislinn** [comment]
#902

**Comment by caelaislinn** [comment]
Extra nanolaminate and oxy canisters have been mapped in. There is still some stuff missing though like floor tiles, airlocks, EVA alarms, portable breach shields etc

**Comment by G0nTar** [comment]
**i'll take the whole corvette remake on my hands.**
 Since i'm now the only official mapper i guess? and this issue is the first thing that bothered me when trying out covenant, they are the less prepared and armed faction so far compared to the others.

And since they are supposed to be the most advanced one, it drives my inner nerd mad. so...
 **i'll see it done**, and even pushed further even if it's a lot of work that's not requested yet, but needed at last, and a must! indeed.

**Comment by caelaislinn** [comment]
The corvette doesn't need a remap, it's just missing a bunch of features. I'll rename this issue

**Comment by G0nTar** [comment]
-Revamp the Corvette- > Corvette Repairs.
i see what you did there, i'll do both, there's a couple of issues and QoL improvments that would make using n' navigating the ship a bit better
