### ISSUE TITLE
Make huragoks able to repair/build walls and floors

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#902]
As per title.

**Comment by SpiderPsycho** [comment]
Will they be able to repair walls that have other walls covering them?

**Comment by caelaislinn** [comment]
What do you mean? There should never be more than 1 wall on a tile

**Comment by SpiderPsycho** [comment]
But the ship's hull is multiple walls thick. And they can't survive space.

**Comment by caelaislinn** [comment]
Right. I would give the NPC huragok a basic AI that just fixes the closest tile, one by one. Player huragoks would manually target which turfs to repair.

**Comment by Delnth** [comment]
> The xenomorph code could be salvaged, if we have it. The xenomorph drone can build stuff for as long as there is plasma to supply said construct (which could be renamed biomass). Eventually do it like CM and have a way to select a type of construct and be able to build it on the mob's turf or one tile right next to it.
Also the non-CM xenomorph code grants them the ability to use mob hands, but no inventory.
While still able to throw/change intents or rest and resist.
Plus, the xeno code wouldn't require the usual human mob template with all the severed limbs etc
When a xeno is dead, it's a single sprite, unless gibbed

Just posting what I wrote in the codebus. For the posterity, so I don't forget about this idea after taking a nap. Might as well give it a shot.

**Comment by CdrRiley** [comment]
sounds like a good idea

**Comment by caelaislinn** [comment]
#985
