### ISSUE TITLE
Colony bartender job

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#903]
Add a bartender job for players. Drunk NPCs will populate a bar and ask for different drinks. If the player deliver the correctly mixed drink in time, they earn credits. Faster delivery means the player gets a tip.

**Comment by Nanu308** [comment]
Was colony jobs not removed? if so, cloze, if not, 2018 Suggestion AAAAAAAAAAA

**Comment by BDpuffy420** [comment]
This relevant to outer at this point so there no need to close
