### ISSUE TITLE
KS7 + Geminus Mapping issues

### ISSUE THREAD

**Issue by Delnth** [HaloSpaceStation/HaloSpaceStation13#907]
#### Description of issue

Geminus: Some multi_tile doors have the wrong dir set to them.
KS7: The mining area is not walled off of the space area, allowing a player to expose the sublevel colony to the vacuum.

#### Difference between expected and actual behavior

/

#### Steps to reproduce 

/

#### Specific information for locating

/

#### Length of time in which bug has been known to occur

/

#### Client version, Server revision & Game ID

/

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by caelaislinn** [comment]
We're not maintaining the Geminus map at the moment. We may decide to use it in future
