### ISSUE TITLE
Valmoric statue

### ISSUE THREAD

**Issue by SpiderPsycho** [HaloSpaceStation/HaloSpaceStation13#910]
I've made a statue to commemorate Valmoric. I know other people have made some but here's mine. Hopefully they can upload theirs here and the preffered one can be chosen and added into the game. I suggest it be placed somewhere on the Vindictive, but its up to the mappers / devs. 

https://drive.google.com/open?id=1gIQIielXLTBmkG2YvI-pADGcBVex556e

**Comment by Max-023** [comment]
Maybe it could be on KS7 in a cave?

**Comment by SpiderPsycho** [comment]
Why? Its a memorial. It should be somewhere where players can see it. Not hidden.

**Comment by Max-023** [comment]
People walk in the caves all the time. Besides, we also don't want to break immersion.

**Comment by SpiderPsycho** [comment]
How is it going to break immersion? Its a statue of an Elite. If anything, a random statue of an Elite on a human planet will break immersion.

**Comment by Max-023** [comment]
And how many Covenant planets are mapped right now? The Covie maps are just Shi at the moment.

**Comment by SpiderPsycho** [comment]
Didn't know they were even a thing yet.

**Comment by Max-023** [comment]
They aren't.
