### ISSUE TITLE
Hand held IV drip /bags [Suggestion]

### ISSUE THREAD

**Issue by CdrRiley** [HaloSpaceStation/HaloSpaceStation13#913]
-idea add in like a tube wich calld IV tube wich you could Connect to Blood bags and make them a HANDHELD IV Drip for like Medics or other wise usefull use 

needs to be in hand to work doesnt have to be in active hand, so you can have it in 1 hand and treat a patient with the other and it doesnt tranfser blood when its lying on the ground even if connect 
![images medic iv hand iv drip](https://user-images.githubusercontent.com/25209341/48224594-8aec2280-e39a-11e8-92a1-e6e7d1ef910f.jpg)

**Comment by BDpuffy420** [comment]
bump
