### ISSUE TITLE
[SUGGESTION] Back slot covenant items

### ISSUE THREAD

**Issue by Delnth** [HaloSpaceStation/HaloSpaceStation13#916]
We could dissociate Elite shield and armor abilities. Let's take the type-3 active camo for example; it would have an integrated weaker shield and allow for active-cam, obviously. However, instead of being an all-in-one thing set to the armor, it could be some sort of add-on (that can be removed), once you wear the armor, the module deploys and takes your backpack slot, allow you to use the functionalities it provides.

The module deployed cannot be removed other than by having your armor removed/stripped. Permanent removal would require a specific process that I have yet to think of.

Otherwise, we could just leave the shield as the default ability for all elite armors; thus the modules would only be dedicated to additional abilities, such as camo, and so on and so forth.

Type-3 Active Camouflage: https://www.halopedia.org/Type-3_active_camouflage
Covenant thruster pack: https://www.halopedia.org/Covenant_thruster_pack
The list: https://www.halopedia.org/Category:Armor_abilities

**Comment by caelaislinn** [comment]
We have the basic system for this in place thanks to @X0-11 although currently the only abilities are shields and active camo. 

There's a lot of abilities on that list so it would be a big job to implement them all. Some could be done quite quickly though... looking through the list a lot of them could be done quite quickly. The highlights for me are: 
- Thrusters (leap ability)
- Personal regeneration
- Jump jet (jetpack)
- Sprint
- Stun blast
- Overshield

I'd love to do holograms for the Covenant as well but that might be a bit tricky. 

Also going through the wiki I found this beauty: 

`Curiously, the cut animation for sprinting while dual wielding SMGs [in Halo 2] depicted the player raising both their middle fingers.`

**Comment by caelaislinn** [comment]
I'm going to close this when #923 merges. Strictly speaking there aren't any armour abilities for elites but that's an intentional design choice... in Operation: Red Flag, the Spartan IIs are meant to be snowflakes while the Elites are mostly expendable mooks.
