### ISSUE TITLE
Police Tape Not Spawning Correctly

### ISSUE THREAD

**Issue by ghost** [HaloSpaceStation/HaloSpaceStation13#917]
#### Description of issue
The police tape spawned in the marshall spawnroom on KS7 are deployed, rather than the item. You can't pick them up and you get the message "X lifts up the police tape to allow passage" when clicking directly on them. 

https://gyazo.com/d0d623fe7c84a3bea4cc7e648249ceb5

#### Difference between expected and actual behavior

The police tape should be an item you pick up and use to deploy tape.

#### Steps to reproduce 

Click on the police tape or right click and try to pick it up

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Max-023** [comment]
Shit. We can't police tape the armory so the innies don't raid it.

**Comment by Maxattacker** [comment]
This was fixed in #1302
