### ISSUE TITLE
Rework the AI system to function for Halostation uses

### ISSUE THREAD

**Issue by X0-11** [HaloSpaceStation/HaloSpaceStation13#925]
This is mostly for my own personal reference, but any suggestions to what features AI should have are welcome.

Personal thoughts on potential implementation:
AI implementation:
Scrap current AI code besides the camera-code.

AI's main method of interaction will be via a simple mode-switch verb. This will make the AI perform the usual attack_hand activities on machinery instead of the AI_attack.Will require a dummy mob to use for item holding, etc.

Usual AI interaction will require insertion into an AI Mainframe computer. When inserted, AI gains additional access level inherited from computer.
Add new machinery-wide variable that defines the required access level to use the AI_act features of the machinery.

AI fragmentation could be achieved by creating modified sub type of the normal AI that can only perform one of the two abilities (AI_act or holo-interact.) This would reduce a single fragment's flexibility but would provide two players access to the one AI.
If AI is in Mainframe, power draws from local grid. AI in a card/suit will assume item is providing power.

Rampant AI would be implemented as a free form antag.

AI abilities (door-hacking, etc.) could be accessed through a verb when in holo-interact mode, akin to cyborg-tools. Ideas for AI-abilities welcome.

Access Level Ideas:
Civilian
UNSC
ONI
Covenant
Forerunner

**Comment by BDpuffy420** [comment]
#2004
