### ISSUE TITLE
medical Cryo tubes for UNSC bertels and maybe URFS Thorn  [SUGGESTION]/Mapping

### ISSUE THREAD

**Issue by CdrRiley** [HaloSpaceStation/HaloSpaceStation13#927]
could the UNSC Bertels and maybe the URFS Thorn get 1 or 2 of those Medical Cryo tubes? 
i find it werid taht a Millitäry ship lacks in taht medical  equipment and a Civllian ship has those
would find good use in both side     ALSO ADD PHORON BARS TO THE CHEM LABS FOR MAKING CHEMS AND LIKE DEXALIN AND Cryoxadone

**Comment by caelaislinn** [comment]
Duplicate #932 I'm closing as the other one as it has more info

**Comment by caelaislinn** [comment]
Reopening not a duplicate
