### ISSUE TITLE
Hunter Turn Speed

### ISSUE THREAD

**Issue by SpiderPsycho** [HaloSpaceStation/HaloSpaceStation13#931]
I've said this a few times but I'll just put it here so it stays here.

People are annoyed, and with good reason, with Hunters being able to turn instantly despite the fact they can only be killed from the back. This is why I suggested they have two different stances, similar to the Durand defense mode:

- Firing Stance: The Hunter crouches and uses their shield to defend themselves. Some bullets get through but the majority don't. Like 90-95%. The Hunter is essentially stationary like this and had to do a short process to turn, like 2-5 seconds.

- Movement Stance: The Hunter is completely upright and moves at a decent speed. Firing takes 3-6 seconds longer than crouching, and only 65-70% of bullets are blocked when shot at from the front, but there's no delay on turning.

Also I think there should be a HUD button for changing these modes, as well as a HUD button for arming the fuel rod cannon. Going through tabs is pretty annoying.

**Comment by caelaislinn** [comment]
We need sprites for the crouched hunter stance. If you can rustle some up, I'll do this 100%

We also need sprites for the fuel rod explosion while we're working on hunters...

**Comment by caelaislinn** [comment]
#946
