### ISSUE TITLE
Covenant Medical Improvements

### ISSUE THREAD

**Issue by SpiderPsycho** [HaloSpaceStation/HaloSpaceStation13#932]
Currently, the Vindictive's medbay is seriously lacking. I'll list changes wanted / needed here:

- **Cryotubes:** ODing and brain damage from suffocation can be sorted with this. I don't know why advanced aliens wouldn't have this.
- **Max upgraded sleepers:** Same problems. Same reasoning.
- **Medicine dispensers:** To complement the chem dispensers. I already sprited them but I don't knnow what happened with it.
- **Advanced Brute and Burn / Combat medical kits:** Instead of standard medkits. There's brute packs in the normal ones instead of advanced brute / burn kits.
- **Reinforced / Piercing syringes:** Covies often have armor. I can't put pills into a grunt or a ranger ruutian with a mask on, and I can't syringe them either, especially grunts since they have armor on the hands and feet.
- **Medbay hull:** The hull for the medbay is dangerously thin. Its easily breached. Its a vital room and having the walls that thin is pretty iffy.
- **Printouts for Advanced Scanners:** Please. Desperately needed for surgery
- **Surgery tools:** Covies should have better surgery tools, right? If the abductor ones are still in, those would be useful. As well as incision management devices, laser scalpels and the bonefixer.
- **Autosurgeon:** SDVs and Covenant ships had automated medical stations. Could we steal the autodoc code from CM?
- **Lifeshaper Huragok:** Huragok that heal things. Resprited wisps maybe. One or two in the medbay would be a lifesaver. Wisps were things that spawned from artifacts on baycode I think, or I might be confused with TG
- **Defibs:** Please.
- EDIT **Medical Suppressors:** Apparently baymed has tables which can just knock people out for surgery. Seems useful.

I play med a lot and god damn is it a pain. Halostation medical is essentially CM medical but even less forgiving, especially without the tools, and with brain damage from minor blood loss, and with people who can't eat pills, and the scanning doesn't tell you what damage they have, and you can't bring them back from death, and you can just slap them in cryo to heal them from OD, and you can just stick them with a autoinjector or hypospray with meds. A lot of this stuff is already in baycode and just needs to be mapped in unless its been deleted.

**Comment by caelaislinn** [comment]
The main concern here is lack of sprites for Covenant machinery and gear (forgetting about potential lore conflicts). I know we've had some human sprited equipment on Covenant ships as long as we've had FC mode but I've never been happy with it

**Comment by SpiderPsycho** [comment]
I mean for the time being we should just have the stuff. Then we can work on sprites. Actually having the stuff is more important than making it look cohesive. I can work on sprites covie medical things. Should put out an open invitation to other spriters on the discord though.

**Comment by CdrRiley** [comment]
my question is will the UNSC and URF get some of the medical stuff like Cryotubes and autosugry, pretty sure they had autosurgy in lore .

**Comment by Max-023** [comment]
Cryo isn't necessary given how everything can be fixed with surgery, and autosurgery just seems lazy.

**Comment by SpiderPsycho** [comment]
How is it lazy? Most players don't even know medical. And the people know medical are overworked with a bunch of dingos who get themselves hurt.

**Comment by CdrRiley** [comment]
yep , like you get 2 or 3 wounded at the same time and your the only doc kinda stressing

**Comment by Max-023** [comment]
It's lazy because a doctor can just throw someone on an auto table and have it do the work for them. There are guides for medical so it isn't some hard thing to get down that requires 10+ years of schooling or something stupid.

**Comment by SpiderPsycho** [comment]
Just because there are guides doesn't mean everyone has them open. And again, what if there are no doctors? I literally don't see any reason for covies not to have autosurgeons. Its in lore and there's a valid reason for it to be added.

And you can't fix severe blood loss or brain damage or overdoses with surgery outright. I've had people die when they get to medical because they're just too damaged for medicine to work in time. Cryo is an instant stabilizer.

**Comment by Max-023** [comment]
It's the internet. You can easily pull up a guide.

And technically the Covies don't have doctors at all as a role. It is a VOLUNTEER role for them, so it is less necessary for them. As for the UNSC and URF, a unit that shouldn't know surgery can do it and say the table did it.



And lore fitting isn't a concern, if you couldn't tell already. The UNSC Bertels, URFS Thorin, and the Vindicative Infraction are all noncanon models. VT9 doesn't exist and wasn't involved with the Orion program. Orions don't get power ranger armor. ODST armor and Spartan armor plates are titanium and unable to be penetrated by smaller ballistics. The M6D was fitted for HE rounds and not the HP rounds the SOCOM uses, which was fitted for HP. Lore can't be a reason for inclusion.

**Comment by SpiderPsycho** [comment]
You're talking about combat balance in contest with lore, which is fine since its a game, but this isn't combat, its medical.

**Comment by Max-023** [comment]
Doesn't medical affect combat? Since, you know, 90% of injuries being treated are from firefights? If recovering from injuries is instant from autosurgery, wouldn't that effect combat as troops are coming back faster? What line is drawn for what is for combat? If a new gun is added, or if a new tool that reverses explosion damage?






And last time I checked, I said VT9 doesn't exist and had no hand in the Orion project. That is not something that would effect combat if autosurgery doesn't affect combat. Not to mention that a Corvette doesn't have a detachment of ODSTs, Marines, as well vehicles. A Corvette is just a support ship for Naval combat will Frigates and above carry land force personnel. Where do we draw the line with what lore decides what is added? Most of the lore is about a war and the conflicts within it anyway.

**Comment by SpiderPsycho** [comment]
And what if there's no one to treat your injuries? UNSC regularly has medics, but Covies don't. If a medic is shot, they die. If there is no medic, and you're shot, you die. Surgery and medical takes time. Its not it instantly fixes you and you're back on the battlefield. And coming back faster, really? You first need to drag your injured ass back across the map to the umbilical, back up the umbilical, then across the ship to the medbay. On CM there's an autosurgeon but its not like marines can just get back into the fight instantly. They need to be brought back to the ship first and then treated. I don't know where you got this idea that this would make them returning to the battlefield instant.

Also I don't know what's with this tangent about the UNSC's ships and loadouts.

**Comment by zergursh** [comment]
Cryotubes would be helpful, but probably not too great.
Max upgraded sleepers would be pretty helpful. 
AP Syringes are absolutely necessary for the unggoys, show em' some love.
Auto-Surgery would be quite interesting and balanced, so long as it isn't too overpowered. It'd be interesting watching other factions fight to get one.
How do Covvies not have defibs yet? 

That's basically all I can add, don't know too much about all the other suggestions, but they all sounds pretty good. Efficiency is clever laziness.

**Comment by SpiderPsycho** [comment]
Autosurgery still takes time to do the surgeries. It's not an A-heal. And yeah I don't know why we don't have defibs yet. Maybe they need respriting

**Comment by SpiderPsycho** [comment]
Accidentalled the close button

**Comment by BDpuffy420** [comment]
For clarification auto doctors were planned early on, we have a sprite for it just no code

**Comment by caelaislinn** [comment]
Can you post the sprite here? Wasn't it just a human version? We will need a covenant version as well

**Comment by SpiderPsycho** [comment]
https://drive.google.com/file/d/15utADHvGutxu5sXn8GWjTCqBO5jsQhZH/view?usp=drivesdk

No I made it covieish

**Comment by caelaislinn** [comment]
Some of these suggestions could still be acted on (mapping in cov surgery tools, defibs, medical suppressors, proper autosurgeons, lifeshaper huragok etc) but I'm pretty happy with where med is at.
