### ISSUE TITLE
Add Bolt Buttons to Corvette

### ISSUE THREAD

**Issue by ghost** [HaloSpaceStation/HaloSpaceStation13#937]
Add bolt buttons to the SDV Corvette's prison cells so that they can contain Covenant players that need to be imprisoned, namely due to the introduction of the law system and related punishments (Mostly timed confinement)

**Comment by BlackjackIsTired** [comment]
Covvie doors would need bolted sprites for that, currently they just go invisible when bolted.

**Comment by caelaislinn** [comment]
That's actually a very easy fix, anyone can just copy paste the sprites and add a few small red blobs a "lock" lights. It may need an animation as well. 

Alternatively just map in human blast doors.

**Comment by X0-11** [comment]
Blast doors are now present on the Kig-Yar missionary ship.

**Comment by PantasTheDank** [comment]
to add on this, I think only Elites and shipmistresses should be able to use the button
