### ISSUE TITLE
Nerf ODST armour, perhaps full armour rebalance across the board.

### ISSUE THREAD

**Issue by X0-11** [HaloSpaceStation/HaloSpaceStation13#939]
ODST armour has the exact same values as collossus armour, besides the armour thickness variable. The increased armour thickness of Collossus armour only converts to one more full bullet absorb.

Armour was originally based on the armour variable alone and did not undergo any sort of rebalancing when the armour thickness system was put into place. This appears to require a full rebalance of armour.

**Comment by Plaguewalker** [comment]
Haha, no. It's fine as is.

**Comment by CdrRiley** [comment]
leave our poor ODSTs armour alone!
