### ISSUE TITLE
URF Shotgun suggestion.

### ISSUE THREAD

**Issue by zergursh** [HaloSpaceStation/HaloSpaceStation13#941]
Observing a couple rounds, I've noticed a common pattern when it comes to Innies vs Certain factions...
UNSC: Whenever they have to engage in Close range, the M90 dominates their weapons and in Medium and Long Range, The BR and SRS are more then enough to utterly outclass their weapons.
Covenant: Murmillo's are better Zeals, and Sangheilli's do Colossus but shielded and much faster. Due to the Covenant having bad accuracy weapons at range, Their matchup is mostly balanced against Innie weapons.
### **How does this at all relate to the shotgun suggestion?**
The shotgun is intended to be an improvement to the range Innies are best at, Close range Open Spaces. This will work perfectly (and probably give a use) to the Zeal suit, since right now, it's in a sort of limbo, with none of the experienced Innie players really wanting to use it. Adding a Shotgun will turn the Zeal into a viable Hit and Run Glass Cannon, which it is intended to be. 
The colossus armor is a bit more interesting. If it was paired with a shotgun, it could possibly turn into a slow piece of shit that gets destroyed by anything that can outrun a snail, or it could be a situation of "You're facing a wall and I am the fucking wall!" being literally unstoppable to anyone who dares challenge it. Probably the former, but fragile classes like kiggies or Marines will probably not want to go anywhere close to it. Shotgun colossus vs Hunter, unstoppable force vs immovable object.

**Comment by frontline03** [comment]
OY, WHAT YOU TALKIN' 'BOUT NO SHOTTYS, WE GOT DA SAWED OFF.WE GOT LOTZ OF DAKKA, YA GROT.
