### ISSUE TITLE
FIX The medical Items weight please [suggestion/bug/idk]

### ISSUE THREAD

**Issue by CdrRiley** [HaloSpaceStation/HaloSpaceStation13#942]
medical items weight like a half a ton you cant carry more then 1 UNSC medkit as combat medic cuse it will slow you down really fucking fast and its just stupid, yes it should slow down a bit BUT not like you are wearing a fucking backpack filled with a HMG and a ODST drop pod 

how to find this bug try to walk around with more then 1 UNSC medkit

**Comment by CdrRiley** [comment]
fix this.

**Comment by caelaislinn** [comment]
fixed #943
