### ISSUE TITLE
Make ship v ship combat damage visible to the firer of the weapon

### ISSUE THREAD

**Issue by X0-11** [HaloSpaceStation/HaloSpaceStation13#945]
Currently, Ship V Ship combat has no visual identifier for the damage dealt during combat. Whilst this could be accomplished with vague overlays, I believe a toggleable option of a camera that follows the course of an overmap projectile would be the best way to show players the damage their attacks deal whilst also limiting potential metagaming.
The camera could also move slightly ahead of the projectile, showing the players the area before and after impact. A small delay would be present so players can glimpse the effect their shot had before moving back to the firing console.

**Comment by SpiderPsycho** [comment]
Oh, additional idea, an overmap shield for the Vindictive which flares up when shot?

**Comment by Max-023** [comment]
This might be very hard to do due to the size of the ships, but maybe some pops of color or something to signify a hit rather than the bullet looking missiles and autocannon fire disappearing?

**Comment by Maxattacker** [comment]
It could be pretty easy to sprite that, as well as a tiny explosion(?) animation for an actual hit, ie; when a mac slug hits.
