### ISSUE TITLE
Autodoc/autosurgeon

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#947]
With human and covenant variants racelocked to their faction races. Also have a smart variant which auto diagnoses the problem, and a dumb variant which has to be manually choose what you want it to do. Pick the wrong thing and it may do terrible terrible damage. 

- [ ] Animated human autodoc sprite (dumb and smart)
- [ ] Animated Covenant autodoc sprite (dumb and smart)

**Comment by BDpuffy420** [comment]
https://cdn.discordapp.com/attachments/454667989128708106/516089249217642496/autosurgeon.dmi

**Comment by SpiderPsycho** [comment]
I'll give the covie ones a go. I won't be able to animate them though. I can do an occupied / unoccupied state though.

**Comment by caelaislinn** [comment]
Closed #952 

But if anyone wants to resprite them that's fine :+1:
