### ISSUE TITLE
Noises of the Void

### ISSUE THREAD

**Issue by Max-023** [HaloSpaceStation/HaloSpaceStation13#956]
This would basically coincide with the overmap additions to space combat to help gauge how a space battle is going. The current feel of space battles is more like a non-immersive, click-the-enemy-ship-until-you-think-it-is-dead experience that has led to clunky fights and then a janked aftermath. After beating the left button of your mouse until your finger is numb, you must exit the artillery terminal and proceed to judge how fucked you are. This can be very dangerous as entire sections of the ship might be gone and you have no idea. You need to grab a orange soft suit, discard any armor you had, and proceed to poke around the ship and hope that the next yellow door you open doesn't space you. Since you grabbed a soft suit, that means you are UNSC or URF. Not only will the hull damage be a problem, but you also have to worry about power. Since damage to power is irreversible (an issue for another time) you have to worry about large sections of the ship where you have to pry open the yellow doors without any air alarm warnings, potentially spacing the hallway or room permanently too. The best way to prevent this sort of damage is to at least have a grasp of how much of a beating you are taking without having to have others screaming over comms that X room was hit and now they have lung damage.

Or worse, you are the Covenant. If you thought having to grab soft suits and air tanks to walk around quiet hallways with flashing alarms notifying you that there is a problem nearby is bad, then being a Covenant player while fighting another ship is a nightmare. You have zero idea if the shields of the ship have given out until you visit the umbilical room, which has the only window on the ship. You might be fighting a ship and pull out just to realize you almost got cut in half and only a narrow bridge is what keeps the ship together. Knowing you can't repair the damages (again, another separate issue) now you have to sit there and think about what you would have done knowing things would end like this.

A good way to know is by noises. When things happen, a noise goes to associate with it. Was your ship just hit with a MAC cannon? Well now you hear the violent, muffled tearing of steel as well as an impact sound comparable to a airburst firework going off right next to you. Archer missile strike the power room? Well now not only do you hear a muffled boom like that of the artillery in CM going off, but also the wirring of unseen electronics shutting off. Alien laser beams putting holes in your hull, now you got a BING sound to match each hit. You just heard a BWOOM, signifying that your shield just took a big hit. Boy are you glad to know it is still working. This way you know that you are taking hits and better judge your next step. Just ate a MAC round? Might consider leaving then. Seem to only be taking 1 or 2 covie lasers per barrage? Keep up the heat then. Shields failed and now you are taking damage? Leg it.

This would drastically increase the amount of retreats and decrease the suicide charges from ships who have no idea how bad things are getting. It could also be a wake up call for those not on a terminal. You suddenly hear the tacking sound of autocannon fire razing the hull, better get to a turret terminal and return the favor.

**Comment by X0-11** [comment]
Whilst #1040 should provide a step towards this, audio feedback is still needed.
