### ISSUE TITLE
Magazine and Ammo Boxes

### ISSUE THREAD

**Issue by saltprjak** [HaloSpaceStation/HaloSpaceStation13#962]
Code and map in CM-esque deployable bullet and magazine boxes, with the ability to refill mags or take new ones. 

Will help marines with establishing well-defended spots without juggling three backpacks and a previously engineering crate stacked with mags that crash your game on right click once someone drops a biofoam syringe in there.

Relevant commit? https://github.com/ColonialMarines-Mirror/ColonialMarines-2018/commit/d85f2b785df3b6e94f5ae957ccb4d25b3ea9ce91

**Comment by X0-11** [comment]
Ability to refill magazines from ammo boxes has been added, just requires coding of subtypes and integration with the map
