### ISSUE TITLE
Covenant drop pod

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#973]
https://s1.megabrandsmedia.com/products/covenant-drop-pod-elite-ultra-96928-346.jpg
http://halofanforlife.com/wp-content/uploads/2012/08/McF-Micro-Ops-s2-Elite-Drop-Pod.jpg
http://legacy.the-junkyard.net/images/vehicles/halo2/CovDropPod_Full.jpg

**Comment by daPotato** [comment]
Going to take this. Location for the SOEIV sprite would speed things up. Will start work on it tomorrow.
