### ISSUE TITLE
Variety in commandos

### ISSUE THREAD

**Issue by frontline03** [HaloSpaceStation/HaloSpaceStation13#974]
Make it so Commandos are split in two. One side is what it is currently. Traditionalist guerilla force.
The other side, A terror squad which are more heavy armoured and carry more heavy hitting weaponry. They are sent to places like the colony or germinus to, To put it bluntly,  Destroy any hostile anti urf resistance to the urf.

**Comment by caelaislinn** [comment]
This is effectively what they already are... Geminus Innies are geurilla rebels with very little starting gear while the URFC/SOE start with better gear and a ship
