### ISSUE TITLE
Role Abilities

### ISSUE THREAD

**Issue by Liam-Gallagher** [HaloSpaceStation/HaloSpaceStation13#978]
Basically, I think the base ss13 spell system would be a great base for creating role/species based abilities. They'd kind of be like armor abilities from reach but they'd be tied to the role you spawn with and your species (also admemes). This would add more options for players to use in fights and will make a bit of forethought, into how players will approach a fight, necessary. They'd also give use to certain roles like squad leads, who outside of RP, are no different from your bog standard marine. Overall, I feel they'd increase player cooperation, raise the skill ceiling, and change the stale meta. 
**Reasons this system should be implemented:** 
- You can have ODSTs/Commandos acting like real special forces, moving in quietly, taking out unsuspecting foes. (Also: ODST Tackle™)
- You can have SLs, providing buffs to nearby allies and actually giving players a reason to follow them.
- Species like Elites can dodge out of the way and Brutes can enter their primal rage.
- You can have Spartans sprinting at blistering speeds and performing other feats that they do in lore.
- Many, many more possibilities.

**Potential Abilities**
_Note: In keeping with the general theme of the two factions in the halo universe, the human abilities I list will be mostly based on training and doctrine (learned skills and strategy) while the covenant will be more focused on their alien nature (physical differences in their species and their advanced tech). Of course, any recommendations that are to the contrary are welcome._

**UNSC**
Marine --- _Sprint_ (Short-Medium burst of speed followed by a small slowdown and medium cool down.)
MG Marine --- _Suppressing Fire_ (Fire rate increase, medium cool down.)
Scout Sniper Marine --- _AP rounds_ (High Increase to Penetration with weapons, very long cool down.)
Assault Recon Marine --- _Adrenaline Rush_ (Increase in damage and pain resistance, long cool down.)
EVA Marine --- _Void Training_ (Decreased slip resistance and better void survivabilty, for those moments when you get caught in a hull breach with no suit, very long cool down.)
Marine Medic --- _Basic First Aid_ (Provides a small amount of brute healing to a target, medium cool down.)
Designated Marksman Marine --- _Bipod_ (Slightly Increased accuracy, as long as they are still, short cool down.)
Marine SL --- _Coordinated Fire_ (Increases accuracy of allies in a 2-3 tile radius, medium cool down.) _Sprint_
Platoon Leader --- _Marching Pace_ (Slightly increased speed for a 7 tile radius, long duration, long cool down.) _Moral Boost_ (Slightly lowers pain damage, short cool down.)
ODST --- _Door Kicker mode or Breach_ (Accuracy, damage, and fire rate slightly increased for a short duration, long cool down)=.) _Tackle_ (Provides a chance to stun a target and the user, with the chance dictated by the targets species, medium cool down.)
CQB ODST --- _Krav Maga_ (Provides a chance to stun an enemy, higher than the tackle and that does not stun user, with the chance dictated by the targets species, medium cool down.)
Sniper ODST --- _Precise Aim_ (Extreme-increases to limb hit chance, very long cool down.)
ODST Medic --- _Trauma Kit_ (Provides a medium amount of healing to a target, medium cool down.)
ODST Engineer --- _Firefight Fortification_ (Immediately lays out a deploy-able barricade, about equal to a sandbag, long cool down.)
ODST Squad Lead --- _Full Squad Cohesion_ (Increased Accuracy in a 5 tile radius, long cool down.)

**Spartan**
(W.I.P.)

**Covenant**
(W.I.P.)

**URF**
(W.I.P.)

**Civilian/Aux**
(W.I.P.)

**Species Specific**
(W.I.P.)

**Comment by caelaislinn** [comment]
I actually did something similar for the player navigation system for Operation: Red Flag. There are various simple mechanical differences between the species such as hitpoints, organs, kigyar take extra brute damage, sangheili selfheal and lunge, tvoan speed etc. 

It's something we could put more time into though. Can you move this justification/discussion to a forum thread and rewrite this issue to have a specific list of species and role abilities?

**Comment by Liam-Gallagher** [comment]
Sure thing, I'll move it over shortly.

**Comment by caelaislinn** [comment]
This is an important sub project for refactoring our species code and I actually considered doing it several times during the Covenant arc but it fell too far down the priority list. Part of this issue should include rewriting the current species abilities to be generic. Once you rewrite the issue I'll tag it

**Comment by Liam-Gallagher** [comment]
I'll have the list finished tomorrow.

**Comment by BDpuffy420** [comment]
We actually added some of these things

**Comment by Nanu308** [comment]
> 
> 
> I'll have the list finished tomorrow.

Hmmmmmmmm

**Comment by ghost** [comment]
Grunts can set their fuel tank to explode when
