### ISSUE TITLE
Maxattacker donor armour bug

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#984]
When the visor is toggled, the entire helmet overlay disappears. This is probably just a misnamed or missing icon state. 

Mjolnir variant: navy gungnir

**Comment by Maxattacker** [comment]
Just to clear it up, my odst gear, should be odst/donor/maxattacker is the one with the broken visr.
On My Spartan donor gear, navy gungnir, the helmet completely disappears when worn.

**Comment by Maxattacker** [comment]
this was fixed
