### ISSUE TITLE
Colony rock mining causes random atmospheric oopsies

### ISSUE THREAD

**Issue by daPotato** [HaloSpaceStation/HaloSpaceStation13#993]
You mine a rock on KS7, and the atmosphere might just not fucking exist where that rock was.
Lasts for about two seconds, causes massive atmos issues after mining large areas.

Repeatable, just mine a bunch of rocks.

**Comment by caelaislinn** [comment]
var/default_type of turf/simulated/asteroid is set to an airless floor type. It should be pulling from the default_turf of that map data but I'm not sure it's possible to set. 

Either way this is an easy ish fix and one I've already got half done in another branch. If anyone wants to have a go at this on the alpha branch, go for it

**Comment by daPotato** [comment]
Update : It Happens when you empty the satchel on the ground, when you pick up a large amount of ore at once with the satchel, and occasionally when you sell out of your satchel, as well as when previously stated.

**Comment by caelaislinn** [comment]
#1011
